### PR TITLE
[Core] Downloading MMG precompiled in nightly build

### LINKED ISSUE #2787: [MeshingApplication] MMG process is not working
This is an auto reminder:

imagen

@loumalouomega, please fix this

### PR DESCRIPTION
**Pull request by loumalouomega**
Fixes  #2787

### CODE REVIEW

File: scripts/build/nightly_build.sh [hunk 1]
```diff
@@ -20,11 +20,15 @@ while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
   echo "Waiting for apt-get to finish"
 done
 
+# Download additional dependencies
+cd ${HOME}
+wget https://github.com/loumalouomega/MMGPrecompiled/archive/master.zip -O mmg.zip
```
Comment (philbucher) [inline scripts/build/nightly_build.sh]: wait, wouldn't it make more sense to add the libs to the KratosMultiphysics git account rather than yours?
There we could also put Metis, Trilinos, ...
@roigcarlo is this possible?

Comment (loumalouomega) [reply scripts/build/nightly_build.sh]: @roigcarlo told me to do it this way

Comment (roigcarlo) [reply scripts/build/nightly_build.sh]: I was not specifically implying that it had to be in @loumalouomega account. Personally I don't want to turn kratos into a repo of compiled software to avoid problems (mainly because then we can be considered as software distributors). Of course sames goes for your @loumalouomega's github account.

My initial thoughts were more in the lines of a FTP server or something like that. Sorry If I did not explain myself clearly. Seeing that this is a problem what the others members of the @KratosMultiphysics/technical-committee think?

Comment (loumalouomega) [reply scripts/build/nightly_build.sh]: If you know any place where we can store it for free....

Comment (RiccardoRossi) [reply scripts/build/nightly_build.sh]: Guys, i think we should get in contact with people at MMG to ask (in writing) if they agree about us doing this... you have the contact of Algiane, Heloise and Mario, why don't you try to write them and ask?

Comment (loumalouomega) [reply scripts/build/nightly_build.sh]: I added a direct link, in any case there is no problem to  have a precompiled version of a LGPL program

**Comment by loumalouomega** [comment]
@roigcarlo How can we test this?

**Comment by roigcarlo** [comment]
We have to test it in my office, come by this afternoon

**Review by roigcarlo — APPROVED** [review]
I have tested it and it works :+1:

**Comment by loumalouomega** [comment]
@philbucher you can use this very same technique to compile the EigenApplication for nightly compilations

**Comment by philbucher** [comment]
Hm cool
where did you save it in the end?

**Comment by loumalouomega** [comment]
In the Kratos drive

**Comment by loumalouomega** [comment]
Send me via mail and I will upload it

**Comment by philbucher** [comment]
can be retrieved from the Eigen-Website directly: bitbucket.org/eigen/eigen/get/3.3.5.tar.bz2 (source: http://eigen.tuxfamily.org/index.php?title=Main_Page)

**Comment by philbucher** [comment]
It is described in the [EigenSolversApp-README](https://github.com/KratosMultiphysics/Kratos/tree/master/applications/EigenSolversApplication#build-instructions) how to install/configure it => super easy!

**Comment by loumalouomega** [comment]
OK

**Comment by loumalouomega** [comment]
The link is wget https://drive.google.com/uc\?export\=download\&id\=15dTI6xoJE024qh2UjfdQa85nuEAdsab- -O eigen.tar.gz

**Comment by loumalouomega** [comment]
We will added after this merge

**Comment by loumalouomega** [comment]
In the drive account of the account that sends the emails nightly
