### PR TITLE
[Core][ModelPart] fix GetParentModelPart signature

### LINKED ISSUE #7436: fix ModelPart::GetParentModelPart fct
=> const is messed up, and why does it give back a pointer and not a reference

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
Fixes #7436 

Also added some tests for this
Apps were updated

### CODE REVIEW

**Comment by rubenzorrilla** [comment]
Didn't we agree on creating a `pGetParentModelPart` too?

**Comment by philbucher** [comment]
> Didn't we agree on creating a `pGetParentModelPart` too?

Don't remember :sweat_smile: 

I would add it only if there is a need for it (and seeing how it is used I would say there isn't at the moment). The `ModelPart` interface is already huge. Furthermore `GetRootModelPart` doesn't have the `pGetRootModelPart` version

**Comment by rubenzorrilla** [comment]
> > Didn't we agree on creating a `pGetParentModelPart` too?
> 
> Don't remember sweat_smile
> 
> I would add it only if there is a need for it (and seeing how it is used I would say there isn't at the moment). The `ModelPart` interface is already huge. Furthermore `GetRootModelPart` doesn't have the `pGetRootModelPart` version

I think that we at some point comment about the possibility of creating the `pGetParentModelPart` too. In any case, I think it makes sense to keep the consistency with the `GetRootModelPart`.

File: kratos/sources/model_part.cpp [hunk 1]
```diff
@@ -1758,12 +1758,21 @@ void ModelPart::RemoveSubModelPart(ModelPart& ThisSubModelPart)
 }
 
 
-ModelPart* ModelPart::GetParentModelPart() const
+ModelPart& ModelPart::GetParentModelPart()
+{
+    if (IsSubModelPart()) {
+        return *mpParentModelPart;
```
Comment (rubenzorrilla) [inline kratos/sources/model_part.cpp:1764]: Maybe makes sense to take the chance and modify the `ModelPart* mpParentModelPart = NULL` to `ModelPart& mrModelPart`.
By doing so the parent model part member variable will be consistent with the model one and we will avoid the dereference operators in here.

**Review by rubenzorrilla — APPROVED** [review]
The changes are correct.

File: kratos/sources/model_part.cpp (hunk 1 above)
Comment (philbucher) [reply kratos/sources/model_part.cpp:1764]: sounds ok to me but this should be a separate PR just to be sure

Comment (rubenzorrilla) [reply kratos/sources/model_part.cpp:1764]: For the record. I've just realized that doing this would imply changing the way we implement the `IsSubModelPart` function (now we check the pointer is not null). Considering that checking empty references is a weird issue, I'd keep it as it is.

Comment (philbucher) [reply kratos/sources/model_part.cpp:1764]: I think an empty reference is undefined behavior no?
I mean dangling references is a bad thing :D

Comment (rubenzorrilla) [reply kratos/sources/model_part.cpp:1764]: Genau. We'd better keep the pointer :smile:
