### PR TITLE
Core/hotfix issue 1997

### LINKED ISSUE #1997: Bug on multiple cuts
Hi! 
I'm trying to set more than one cut plane for a CFD and having an error

```
Traceback (most recent call last):
  File "MainKratos.py", line 58, in <module>
    gid_output.ExecuteInitialize()
  File "E:\GiD\GiD 14.0-rc1\problemtypes\kratos.gid\exec\kratos\kratos\python_scripts\gid_output_process.py", line 129, in ExecuteInitialize
    self.__initialize_cut_output(plane_output_configuration)
  File "E:\GiD\GiD 14.0-rc1\problemtypes\kratos.gid\exec\kratos\kratos\python_scripts\gid_output_process.py", line 361, in __initialize_cut_output
    self.__define_output_plane(cut_data)
  File "E:\GiD\GiD 14.0-rc1\problemtypes\kratos.gid\exec\kratos\kratos\python_scripts\gid_output_process.py", line 455, in __define_output_plane
    0.01)
RuntimeError: Error: attempting to add the variable: FATHER_NODES to the model part with name: CutPart which is not empty


in kratos/includes/model_part.h:472:ModelPart::AddNodalSolutionStepVariable
   kratos/utilities/cutting_utility.h:184:CuttingUtility::GenerateCut
```

[Example case attached](https://we.tl/H0hnNYPj1P)

### PR DESCRIPTION
**Pull request by jcotela**
The cut plane generation utility was adding variables to the nodal solution step variable list of its output model part every time a cut was defined. This is no longer allowed to prevent memory errors, so an error was thrown.

A new function was implemented to define the solution step variables of the cut model part, which must be called before defining the cuts. The functions that were modifying the solution step variable list previously will now only check that the required variables have been added and throw an error otherwise (the error message instructs users to call the new function).

The change has been ported to the trilinos version of the utility, and a separate bug (missing function in python wrapper utility) has been fixed there.

Finally, the change has been propagated by adding calls to the new function to other python modules that also use the cut utility.

This fixes #1997 @jginternational

### CODE REVIEW

File: applications/trilinos_application/custom_utilities/trilinos_cutting_app.h [hunk 1]
```diff
@@ -257,13 +257,13 @@ class TrilinosCuttingApplication
 
         int ierr = -1;
         ierr = aux_non_overlapping_graph->GlobalAssemble(Insert,true); //Epetra_CombineMode mode=Add);
-        if (ierr < 0) KRATOS_THROW_ERROR(std::logic_error, "epetra failure --> ln 249", "");
+        KRATOS_ERROR_IF(ierr < 0) << "epetra failure --> " << __LINE__ << std::endl;
```
Comment (pooyan-dadvand) [inline applications/trilinos_application/custom_utilities/trilinos_cutting_app.h]: KRATOS ERROR macro has the __line__ incorporated so there are no need to re report it

File: applications/trilinos_application/custom_utilities/trilinos_cutting_app.h [hunk 2]
```diff
@@ -257,13 +257,13 @@ class TrilinosCuttingApplication
...
         //now in our local graph we have also the nodes that are required by other processors
 
 
         double* local_non_ov = new double  [nlocal_nodes]; //a human readeable copy of the FEvector
         ierr = aux_non_overlapping_graph->ExtractCopy(local_non_ov,nlocal_nodes);
-        if (ierr < 0) KRATOS_THROW_ERROR(std::logic_error, "epetra failure", "");
+        KRATOS_ERROR_IF(ierr < 0) << "epetra failure --> " << __LINE__ << std::endl;
```
Comment (pooyan-dadvand) [inline applications/trilinos_application/custom_utilities/trilinos_cutting_app.h]: Same

**Review by pooyan-dadvand — COMMENTED** [review]
👍

File: applications/trilinos_application/custom_utilities/trilinos_cutting_app.h (hunk 1 above)
Comment (jcotela) [reply applications/trilinos_application/custom_utilities/trilinos_cutting_app.h]: I was fixing the old macro, did not think about that...

**Comment by jcotela** [comment]
@mpentek @msandre I believe this should also solve the issue with the cut output in MPI we discussed last week.

**Review by msandre — APPROVED** [review]
