### PR TITLE
Making operator<< visible.

### LINKED ISSUE #3410: Compilation error in logger_message.h with Linux, Clang++
When trying to compile kratos, with the following options for CMake,
```
-DCMAKE_BUILD_TYPE=Debug
-DCMAKE_C_COMPILER=/usr/bin/clang-6.0
-DCMAKE_CXX_COMPILER=/usr/bin/clang++-6.0
-DCMAKE_CXX_FLAGS= -msse3 -std=c++11
```

I get the following error:
```
In file included from /home/mraschi/Projects/Kratos/applications/StructuralMechanicsApplication/custom_processes/spr_error_process.cpp:18:
In file included from /home/mraschi/Projects/Kratos/kratos/processes/find_nodal_neighbours_process.h:29:
In file included from /home/mraschi/Projects/Kratos/kratos/processes/process.h:29:
In file included from /home/mraschi/Projects/Kratos/kratos/includes/kratos_flags.h:26:
In file included from /home/mraschi/Projects/Kratos/kratos/containers/flags.h:30:
In file included from /home/mraschi/Projects/Kratos/kratos/includes/serializer.h:34:
In file included from /home/mraschi/Projects/Kratos/kratos/input_output/logger.h:23:
/home/mraschi/Projects/Kratos/kratos/input_output/logger_message.h:195:12: error: call to function 'operator<<' that is neither visible in the template definition nor found by argument-dependent lookup
                                buffer << rValue;
                                       ^
/home/mraschi/Projects/Kratos/kratos/input_output/logger.h:151:21: note: in instantiation of function template specialization 'Kratos::LoggerMessage::operator<<<std::vector<double, std::allocator<double> > >' requested here
                  mCurrentMessage << rValue;
                                  ^
/home/mraschi/Projects/Kratos/applications/StructuralMechanicsApplication/custom_processes/spr_error_process.cpp:158:74: note: in instantiation of function template specialization 'Kratos::Logger::operator<<<std::vector<double, std::allocator<double> > >' requested here
        KRATOS_INFO_IF("SPRErrorProcess", mEchoLevel > 2) << "Error GP:" << error_integration_point << std::endl;
                                                                         ^
/home/mraschi/Projects/Kratos/kratos/utilities/stl_io.h:27:15: note: 'operator<<' should be declared prior to the call site
std::ostream& operator<<(std::ostream& rOStream, const std::vector<T>& rVec) {
```

### PR DESCRIPTION
**Pull request by jcotela**
@rubenzorrilla see if it fixes your issue.

Fixes #3410

### CODE REVIEW

**Comment by rubenzorrilla** [comment]
Same error :confused:

File: kratos/includes/exception.h [hunk 1]
```diff
@@ -24,6 +24,7 @@
 // Project includes
 #include "includes/kratos_export_api.h"
 #include "includes/code_location.h"
+#include "utilities/stl_io.h" // Defines operator<< for several stl types, needed to print such types in error messages using Exception::operator<<
```
Comment (philbucher) [inline kratos/includes/exception.h]: Doing this will basically include many stl-containers everywhere (through „define.h“)

**Review by philbucher — CHANGES_REQUESTED** [review]

File: kratos/includes/exception.h (hunk 1 above)
Comment (jcotela) [reply kratos/includes/exception.h]: Note that you are already including `<vector>` and `<iostream>` in the include block just above  and shared_pointers (also in `define.h`) includes `<memory>` (so we are only adding `<set>` to the list of headers)

**Review by rubenzorrilla — DISMISSED** [review]
Now it works with Clang. Thanks for the fix.

File: kratos/includes/exception.h (hunk 1 above)
Comment (rubenzorrilla) [reply kratos/includes/exception.h]: Just to say that I agree with @jcotela . There is not so much difference and right now the compilation with Clang is broken. I'd merge this as it is. We can always find a more efficient solution afterwards.

Comment (philbucher) [reply kratos/includes/exception.h]: Have you tried including the stl io in the test where the compilation fails?

(Brief answer, don’t have much time)
To be discussed next week

Comment (rubenzorrilla) [reply kratos/includes/exception.h]: The compilation fails in a test... This would imply to include it in every place we use the macro. Am I wrong?

Comment (philbucher) [reply kratos/includes/exception.h]: Yes exactly

Comment (rubenzorrilla) [reply kratos/includes/exception.h]: Taking into account that It only crashes with Clang, I found this not so robust...

**Comment by philbucher** [comment]
More elaborate comment:
`define.h` includes `exception.h` => we should very carefully evaluate adding dependencies there IMO

In general I really like the idea of having the stl-io included there, bcs then you can natively use it (e.g. for `KRATOS_WATCH`, `KRATOS_EXCEPTION` etc) and most probably we would not have problems like the current one any more

HOWEVER:
If we do this, then we will most likely have the stl-containers included everywhere (vector, array, set, map (some of them not yet implemented) etc)
=> **QUESTION**: do we want this?

BTW this would most probably also solve #3410

File: kratos/includes/exception.h (hunk 1 above)
Comment (jcotela) [reply kratos/includes/exception.h]: > Have you tried including the stl io in the test where the compilation fails?

Yes. Getting the `operator<<` of `Exception` to accept stl containers is not a problem, it does already. The problem is that the generic implementation of `Exception::operator<<` contains a call to to `operator<<` for streams and the argument type, which requires the definitions in `stl_io` for stl containers.

>  The compilation fails in a test... This would imply to include it in every place we use the macro. Am I wrong?

Only if using std::vector (the macro should work fine for array_1d, ublas types, etc.)

**Comment by jcotela** [comment]
@philbucher I'm just checking now, but #3410 should require including `std_io.h` from `logger_message.h` (for the same reasons I need to include it from `exception.h`). If this PR is not wanted, a compromise solution would be to add `std_io.h` to `logger_message` and use a `LoggerMessage` to build the error message in my macro. I wonder if logger is included in less places than exception, though...

**Comment by jcotela** [comment]
Pushing some more changes after discussing with @philbucher. Current form also fixes #3410

**Review by philbucher — APPROVED** [review]
looks good to me, as discussed
