### PR TITLE
Fixing race condition in FluidBioApp

### LINKED ISSUE #10115: [Biomedical] Test Case Randomly Failing
I've seen ```testUnitParabolaString2D``` randomly fail in the CI with the same message a couple of times now. It failed on Windows most recently, but it might not be limited to that platform. Here's the traceback from the CI:
```
 FAIL: testUnitParabolaString2D (apply_parabolic_inlet_process_test.ApplyParabolicInletProcessTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\Kratos\Kratos\bin\Custom\applications\FluidDynamicsBiomedicalApplication\tests\apply_parabolic_inlet_process_test.py", line 180, in testUnitParabolaString2D
    self.assertVectorAlmostEqual(test_node.GetSolutionStepValue(KratosMultiphysics.VELOCITY), [0.0,2.0,0.0])
  File "D:\a\Kratos\Kratos\bin\Custom\KratosMultiphysics\KratosUnittest.py", line 92, in assertVectorAlmostEqual
    self.assertAlmostEqual(v1, v2, places, LazyErrMsg(i, msg), delta)
AssertionError: 0.0 != 2.0 within 7 places (2.0 difference) : 
Check failed because vector arguments are not equal in component 1
Vector 1:
[3](-0,0,-0)
Vector 2:
[0.0, 2.0, 0.0]
```

@rubenzorrilla can you please look into it?

### PR DESCRIPTION
**Pull request by roigcarlo**
**📝 Description**
See #10115

**🆕 Changelog**
Fixing race condition in GenericFunction inside ParabolicProfileUtilities

### CODE REVIEW

File: applications/FluidDynamicsBiomedicalApplication/custom_utilities/parabolic_profile_utilities.cpp [hunk 1]
```diff
@@ -199,15 +199,18 @@ void ParabolicProfileUtilities::ImposeParabolicInlet(
...
     // Impose the parabolic inlet profile
-    ImposeParabolicProfile(rModelPart, MaxParabolaValue, MaxValueFactor);
+    ImposeParabolicProfile(rModelPart, *MaxParabolaValue, MaxValueFactor);
 }
 
 template<class TInputType>
 void ParabolicProfileUtilities::ImposeParabolicProfile(
     ModelPart &rModelPart,
-    const TInputType& rMaxParabolaValue,
+    const TInputType & rMaxParabolaValue,
```
Comment (rubenzorrilla) [inline applications/FluidDynamicsBiomedicalApplication/custom_utilities/parabolic_profile_utilities.cpp]:
```suggestion
    const TInputType& rMaxParabolaValue,
```
I think this is a debugging left over.

File: applications/FluidDynamicsBiomedicalApplication/custom_utilities/parabolic_profile_utilities.cpp [hunk 2]
```diff
@@ -199,15 +199,18 @@ void ParabolicProfileUtilities::ImposeParabolicInlet(
...
     const double MaxValueFactor)
 {
+    // STOP
+    std::cout << "\nPROCESS BEGIN\n" << std::endl;
+
```
Comment (rubenzorrilla) [inline applications/FluidDynamicsBiomedicalApplication/custom_utilities/parabolic_profile_utilities.cpp]:
```suggestion
```
Same.

File: applications/FluidDynamicsBiomedicalApplication/custom_utilities/parabolic_profile_utilities.cpp [hunk 3]
```diff
@@ -219,28 +222,38 @@ void ParabolicProfileUtilities::ImposeParabolicProfile(
...
 
+    // TLS with the Inlet normal and the rMaxParabolaValue (to prevent race conditions if its a function)
+    struct TLSType{
+        array_1d<double,3> mInlet;
+        TInputType mParabolaValue;
+
+        TLSType(const TInputType & parabolaValue) : mInlet(array_1d<double,3>()), mParabolaValue(parabolaValue) {};
+    };
+
+    TLSType tsl(rMaxParabolaValue);
```
Comment (rubenzorrilla) [inline applications/FluidDynamicsBiomedicalApplication/custom_utilities/parabolic_profile_utilities.cpp]:
```suggestion
    TLSType tls(rMaxParabolaValue);
```

File: applications/FluidDynamicsBiomedicalApplication/custom_utilities/parabolic_profile_utilities.cpp [hunk 4]
```diff
@@ -219,28 +222,38 @@ void ParabolicProfileUtilities::ImposeParabolicProfile(
...
+
     // Impose the parabolic profile values
-    block_for_each(rModelPart.Nodes(), array_1d<double,3>(), [time, max_dist, MaxValueFactor, &rMaxParabolaValue](NodeType& rNode, array_1d<double,3>& rTLSValue){
+    block_for_each(rModelPart.Nodes(), tsl, [time, max_dist, MaxValueFactor](NodeType& rNode, TLSType& rTLSValue){
```
Comment (rubenzorrilla) [inline applications/FluidDynamicsBiomedicalApplication/custom_utilities/parabolic_profile_utilities.cpp]:
```suggestion
    block_for_each(rModelPart.Nodes(), tls, [time, max_dist, MaxValueFactor](NodeType& rNode, TLSType& rTLSValue){
```

File: applications/FluidDynamicsBiomedicalApplication/tests/test_FluidDynamicsBiomedicalApplication.py [hunk 5]
```diff
@@ -48,7 +48,7 @@ def AssembleTestSuites():
     KratosMultiphysics.Logger.GetDefaultOutput().SetSeverity(KratosMultiphysics.Logger.Severity.WARNING)
     KratosMultiphysics.Logger.PrintInfo("Unittests", "\nRunning cpp unit tests ...")
     KratosMultiphysics.Tester.SetVerbosity(KratosMultiphysics.Tester.Verbosity.PROGRESS) # TESTS_OUTPUTS
-    KratosMultiphysics.Tester.RunTestSuite("FluidDynamicsBiomedicalApplicationFastSuite")
+    # KratosMultiphysics.Tester.RunTestSuite("FluidDynamicsBiomedicalApplicationFastSuite")
```
Comment (rubenzorrilla) [inline applications/FluidDynamicsBiomedicalApplication/tests/test_FluidDynamicsBiomedicalApplication.py:51]:
```suggestion
    KratosMultiphysics.Tester.RunTestSuite("FluidDynamicsBiomedicalApplicationFastSuite")
```
I think this is another leftover.

File: applications/FluidDynamicsBiomedicalApplication/custom_utilities/parabolic_profile_utilities.cpp (hunk 1 above)
Comment (roigcarlo) [reply applications/FluidDynamicsBiomedicalApplication/custom_utilities/parabolic_profile_utilities.cpp]: Nop, this is needed, is the function or the value in the input :S

File: applications/FluidDynamicsBiomedicalApplication/custom_utilities/parabolic_profile_utilities.cpp (hunk 2 above)
Comment (roigcarlo) [reply applications/FluidDynamicsBiomedicalApplication/custom_utilities/parabolic_profile_utilities.cpp]: ups.

File: applications/FluidDynamicsBiomedicalApplication/tests/test_FluidDynamicsBiomedicalApplication.py (hunk 5 above)
Comment (roigcarlo) [reply applications/FluidDynamicsBiomedicalApplication/tests/test_FluidDynamicsBiomedicalApplication.py:51]: Mm I am not sure, this assumes that there is a existing test suite with that name, and if its not the case it crashes (for example because the cpp tests are not compiled). If we want to leave this enabled we have to control when is executed.

File: applications/FluidDynamicsBiomedicalApplication/custom_utilities/parabolic_profile_utilities.cpp (hunk 1 above)
Comment (rubenzorrilla) [reply applications/FluidDynamicsBiomedicalApplication/custom_utilities/parabolic_profile_utilities.cpp]: But isn't it the same?

Comment (roigcarlo) [reply applications/FluidDynamicsBiomedicalApplication/custom_utilities/parabolic_profile_utilities.cpp]: aaa you mean the space, yes.

File: applications/FluidDynamicsBiomedicalApplication/tests/test_FluidDynamicsBiomedicalApplication.py (hunk 5 above)
Comment (rubenzorrilla) [reply applications/FluidDynamicsBiomedicalApplication/tests/test_FluidDynamicsBiomedicalApplication.py:51]: But the CI always compiles the cpp tests right?

Comment (roigcarlo) [reply applications/FluidDynamicsBiomedicalApplication/tests/test_FluidDynamicsBiomedicalApplication.py:51]: But its different, the CI runs the cpp tests though the runner scripts. You don't specify which test to run, you check the ones that are available and you run them all. With this you are explicitly asking to run the tests in a suit that may not exists.

It should be at least warded with a try/catch

Comment (rubenzorrilla) [reply applications/FluidDynamicsBiomedicalApplication/tests/test_FluidDynamicsBiomedicalApplication.py:51]: Understood. Lets keep it commented then.

**Review by rubenzorrilla — APPROVED** [review]
