### PR TITLE
[GeoMechanicsApplication] Partially saturated flow does not work as expected

### LINKED ISSUE #12842: [GeoMechanicsApplication] INVESTIGATION - Partially saturated flow does not work as expected
### This issue is time-boxed to 10 developer days.

**22/10/2024 - JDN - Comment**
I need more information to able to prioritize this for this sprint or beyond. i.e. whats the urgency ? who is it for ? also needs refinement ? I wasn't aware we were using partial saturation anywhere and we are currently awaiting for 2025 to do so, but do I interpret correctly that the mechanism also fails when the zone above the phreatic line is **fully unsaturated** 

### Description

The Partially saturated flow is implemented but it has been never tested. Moreover, instability arrised when we tried to apply it. 

The equation for partially saturated flow is:

$$\left[ (\alpha + n \beta) \rho^w S + n \rho^w \frac{d S}{dp} \right] \frac{\partial p}{\partial t} = \frac{\partial}{\partial x_i} \left[ \frac{\rho^w k_r K_{ij}}{\mu}  \left( \frac{\partial p}{\partial x_j} - \rho^w g_j \right) \right]$$

where 

$$k_r = S_e^{g_l} \left[ 1 - \left( 1 -S_e^{1/g_m} \right)^{g_m} \right]$$
$$S_e = \frac{S - S_r}{S_s - S_r}$$

Here we start from a simple test case, with saturated flow below the phreatic line:
In the case of $S_r = 0$, the pressure above the phreatic line needs to be zero. However, from this equation, the left hand side includes the saturation $S$ which is zero. It leads to a zero $C$ matrix. Morover, $k_r = 0$ too, which leads to a zero $K$ matrix. Therefore, a zero matrix is added which makes the diagonal of the generic matrix partly to be zero, and it lead to a singular matrix.
This can be probably avoided to adding "BIOT_COEFFICIENT" to the material parameters to set the $C$ matrix manually as a user defined parameter. 

In the case of $S_r > 0$, then $K_r =0$`but the left hand side gets a nonzero value. it means $\frac{dp}{dt} = 0$. This is proposed to lead to unchanged pressure above the phreatic line. 

However, here we see a change in pressure. It indicates there is driving force, which leads the water pressure goes up. Which is an unexpected behaviour,

### LINKED ISSUE #12929: [GeoMechanicsApplication] Fix Partially saturated flow for Pw element
The partially saturated flow, specifically with the retention law of "saturated_below_phreatic_level" is unstable and does not even converge because it gets divided by zero.

- Fix the problem
- Add test case(s): for triangular (3 & 6 noded)
- Documentation for test cases

### LINKED ISSUE #12930: [GeoMechanicsApplication] Fix Partially saturated flow for U-Pw small strain element
The partially saturated flow, specifically with the retention law of "saturated_below_phreatic_level" is unstable and does not even converge because it gets divided by zero.

- Fix the problem
- Add test case(s): for triangular (3 & 6 noded)
- Documentation for test cases

### LINKED ISSUE #12931: [GeoMechanicsApplication] Fix Partially saturated flow for triangular U-Pw diff order element
The Partially saturated flow, especifically with retention law of "saturated_below_phreatic_level" is instable and does not even converge because it gets divided by zero.

- Fix the problem
- Add test case: Column of soil
- Documentation for test case

The solution to the problem was found in this issue: [INVESTIGATION - Partially saturated flow does not work as expected](https://github.com/KratosMultiphysics/Kratos/issues/12842)

### PR DESCRIPTION
**Pull request by mnabideltares**
### This issue is time-boxed to 10 developer days.

**22/10/2024 - JDN - Comment**
I need more information to able to prioritize this for this sprint or beyond. i.e. whats the urgency ? who is it for ? also needs refinement ? I wasn't aware we were using partial saturation anywhere and we are currently awaiting for 2025 to do so, but do I interpret correctly that the mechanism also fails when the zone above the phreatic line is **fully unsaturated** 

### Description

The Partially saturated flow is implemented but it has been never tested. Moreover, instability arrised when we tried to apply it. 

The equation for partially saturated flow is:

$$\left[ (\alpha + n \beta) \rho^w S + n \rho^w \frac{d S}{dp} \right] \frac{\partial p}{\partial t} = \frac{\partial}{\partial x_i} \left[ \frac{\rho^w k_r K_{ij}}{\mu}  \left( \frac{\partial p}{\partial x_j} - \rho^w g_j \right) \right]$$

where 

$$k_r = S_e^{g_l} \left[ 1 - \left( 1 -S_e^{1/g_m} \right)^{g_m} \right]$$
$$S_e = \frac{S - S_r}{S_s - S_r}$$

Here we start from a simple test case, with saturated flow below the phreatic line:
In the case of $S_r = 0$, the pressure above the phreatic line needs to be zero. However, from this equation, the left hand side includes the saturation $S$ which is zero. It leads to a zero $C$ matrix. Morover, $k_r = 0$ too, which leads to a zero $K$ matrix. Therefore, a zero matrix is added which makes the diagonal of the generic matrix partly to be zero, and it lead to a singular matrix.
This can be probably avoided to adding "BIOT_COEFFICIENT" to the material parameters to set the $C$ matrix manually as a user defined parameter. 

In the case of $S_r > 0$, then $K_r =0$`but the left hand side gets a nonzero value. it means $\frac{dp}{dt} = 0$. This is proposed to lead to unchanged pressure above the phreatic line. 

However, here we see a change in pressure. It indicates there is driving force, which leads the water pressure goes up. Which is an unexpected behaviour,

### CODE REVIEW

File: applications/GeoMechanicsApplication/custom_elements/U_Pw_small_strain_element.cpp [hunk 1]
```diff
@@ -283,8 +283,6 @@ void UPwSmallStrainElement<TDim, TNumNodes>::InitializeSolutionStep(const Proces
         noalias(Variables.StressVector) = mStressVector[GPoint];
         ConstitutiveParameters.SetStressVector(Variables.StressVector);
         mConstitutiveLawVector[GPoint]->InitializeMaterialResponseCauchy(ConstitutiveParameters);
-
-        mRetentionLawVector[GPoint]->InitializeSolutionStep(RetentionParameters);
```
Comment (markelov208) [inline applications/GeoMechanicsApplication/custom_elements/U_Pw_small_strain_element.cpp:287]: RetentionParameters is not used any longer.

File: applications/GeoMechanicsApplication/custom_elements/U_Pw_base_element.cpp [hunk 2]
```diff
@@ -135,10 +135,8 @@ void UPwBaseElement::Initialize(const ProcessInfo& rCurrentProcessInfo)
     }
 
     mRetentionLawVector.resize(number_of_integration_points);
-    for (unsigned int i = 0; i < mRetentionLawVector.size(); ++i) {
-        mRetentionLawVector[i] = RetentionLawFactory::Clone(r_properties);
-        mRetentionLawVector[i]->InitializeMaterial(
```
Comment (markelov208) [inline applications/GeoMechanicsApplication/custom_elements/U_Pw_base_element.cpp:140]: As far as I  understand, InitializeMaterial and other retention law functions were doing nothing after certain changes. Nice to remove them finally.

File: applications/GeoMechanicsApplication/custom_elements/U_Pw_small_strain_interface_element.cpp [hunk 3]
```diff
@@ -206,9 +206,6 @@ void UPwSmallStrainInterfaceElement<TDim, TNumNodes>::InitializeSolutionStep(con
         noalias(StressVector) = mStressVector[GPoint];
         ConstitutiveParameters.SetStressVector(StressVector);
         mConstitutiveLawVector[GPoint]->InitializeMaterialResponseCauchy(ConstitutiveParameters);
-
-        // Initialize retention law
-        mRetentionLawVector[GPoint]->InitializeSolutionStep(RetentionParameters);
```
Comment (markelov208) [inline applications/GeoMechanicsApplication/custom_elements/U_Pw_small_strain_interface_element.cpp:211]: RetentionParameters should be removed as well.

File: applications/GeoMechanicsApplication/custom_elements/U_Pw_small_strain_interface_element.cpp [hunk 4]
```diff
@@ -279,9 +276,6 @@ void UPwSmallStrainInterfaceElement<TDim, TNumNodes>::FinalizeSolutionStep(const
 
         mStateVariablesFinalized[GPoint] =
             mConstitutiveLawVector[GPoint]->GetValue(STATE_VARIABLES, mStateVariablesFinalized[GPoint]);
-
-        // retention law
-        mRetentionLawVector[GPoint]->FinalizeSolutionStep(RetentionParameters);
```
Comment (markelov208) [inline applications/GeoMechanicsApplication/custom_elements/U_Pw_small_strain_interface_element.cpp:284]: Sorry, again about RetentionParameters

File: applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.cpp [hunk 5]
```diff
@@ -296,177 +284,177 @@ void SmallStrainUPwDiffOrderElement::AssignPressureToIntermediateNodes()
...
     {
-        const double p0 = rGeom[0].FastGetSolutionStepValue(WATER_PRESSURE);
-        const double p1 = rGeom[1].FastGetSolutionStepValue(WATER_PRESSURE);
-        const double p2 = rGeom[2].FastGetSolutionStepValue(WATER_PRESSURE);
-        ThreadSafeNodeWrite(rGeom[3], WATER_PRESSURE, 0.5 * (p0 + p1));
-        ThreadSafeNodeWrite(rGeom[4], WATER_PRESSURE, 0.5 * (p1 + p2));
-        ThreadSafeNodeWrite(rGeom[5], WATER_PRESSURE, 0.5 * (p2 + p0));
+        const double p0 = r_geom[0].FastGetSolutionStepValue(WATER_PRESSURE);
+        const double p1 = r_geom[1].FastGetSolutionStepValue(WATER_PRESSURE);
+        const double p2 = r_geom[2].FastGetSolutionStepValue(WATER_PRESSURE);
```
Comment (markelov208) [inline applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.cpp]: There are many assignments for pressure values. What do you think on using 
Vector pressure(3);
        std::transform(r_geom.begin(), r_geom.begin()+3, pressure.begin(), [](const auto& node) {
            return node.FastGetSolutionStepValue(WATER_PRESSURE);
        });
It can be a separate function that returns pressure vector of given size.

File: applications/GeoMechanicsApplication/custom_retention/saturated_below_phreatic_level_law.cpp [hunk 6]
```diff
@@ -11,155 +11,98 @@
...
-        return rValue;
     } else if (rThisVariable == DERIVATIVE_OF_SATURATION) {
         rValue = this->CalculateDerivativeOfSaturation(rParameterValues);
-        return rValue;
     } else if (rThisVariable == RELATIVE_PERMEABILITY) {
         rValue = this->CalculateRelativePermeability(rParameterValues);
-        return rValue;
     }
-
     return rValue;
```
Comment (markelov208) [inline applications/GeoMechanicsApplication/custom_retention/saturated_below_phreatic_level_law.cpp:72]: Would it be nicer to use `switch`?

File: applications/GeoMechanicsApplication/custom_retention/saturated_law.cpp [hunk 7]
```diff
@@ -63,59 +45,25 @@ double& SaturatedLaw::CalculateValue(RetentionLaw::Parameters& rParameterValues,
...
-        return rValue;
     } else if (rThisVariable == DERIVATIVE_OF_SATURATION) {
         rValue = this->CalculateDerivativeOfSaturation(rParameterValues);
-        return rValue;
     } else if (rThisVariable == RELATIVE_PERMEABILITY) {
         rValue = this->CalculateRelativePermeability(rParameterValues);
-        return rValue;
     }
-
     return rValue;
```
Comment (markelov208) [inline applications/GeoMechanicsApplication/custom_retention/saturated_law.cpp:57]: I would use `switch` but this is subjective. ;)

File: applications/GeoMechanicsApplication/custom_retention/van_genuchten_law.cpp [hunk 8]
```diff
@@ -63,18 +60,18 @@ double VanGenuchtenLaw::CalculateEffectiveSaturation(Parameters& rParameters) co
...
-        const double  gc                  = (1.0 - gn) / gn;
-
-        return (satMax - satMin) * gc * pow((1.0 + pow(p / pb, gn)), gc - 1.0) * gn * pow(pb, -gn) *
-               pow(p, gn - 1.0);
+        const auto& rMaterialProperties = rParameters.GetMaterialProperties();
+        const auto  sat_max             = rMaterialProperties[SATURATED_SATURATION];
+        const auto  sat_min             = rMaterialProperties[RESIDUAL_SATURATION];
+        const auto  pb                  = rMaterialProperties[VAN_GENUCHTEN_AIR_ENTRY_PRESSURE];
+        const auto  gn                  = rMaterialProperties[VAN_GENUCHTEN_GN];
+        const auto  gc                  = (1.0 - gn) / gn;
```
Comment (markelov208) [inline applications/GeoMechanicsApplication/custom_retention/van_genuchten_law.cpp]: this is a copy of lines 33-37 above. Would it be better to extract them as a function to reduce duplication?

File: applications/GeoMechanicsApplication/custom_retention/van_genuchten_law.cpp [hunk 9]
```diff
@@ -102,92 +99,73 @@ double VanGenuchtenLaw::CalculateRelativePermeability(Parameters& rParameters) c
...
-        return rValue;
     } else if (rThisVariable == BISHOP_COEFFICIENT) {
         rValue = this->CalculateBishopCoefficient(rParameterValues);
-        return rValue;
     } else if (rThisVariable == DERIVATIVE_OF_SATURATION) {
         rValue = this->CalculateDerivativeOfSaturation(rParameterValues);
-        return rValue;
     } else if (rThisVariable == RELATIVE_PERMEABILITY) {
         rValue = this->CalculateRelativePermeability(rParameterValues);
-        return rValue;
```
Comment (markelov208) [inline applications/GeoMechanicsApplication/custom_retention/van_genuchten_law.cpp:130]: `switch`? ;)

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/MaterialParameters_stage1.json [hunk 10]
```diff
@@ -0,0 +1,34 @@
...
+          "PERMEABILITY_XX": 1.157E-05,
+          "PERMEABILITY_YY": 1.157E-05,
+          "PERMEABILITY_XY": 0.0,
+          "DYNAMIC_VISCOSITY": 0.001,
+          "RETENTION_LAW": "SaturatedBelowPhreaticLevelLaw",
+          "RESIDUAL_SATURATION": 0.001,
+          "SATURATED_SATURATION": 1.0,
+          "MINIMUM_RELATIVE_PERMEABILITY": 0.001,
+          "K0_MAIN_DIRECTION": 1,
+          "K0_NC": 0.6,
```
Comment (markelov208) [inline applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/MaterialParameters_stage1.json]: I do not see a call for K0. Are these K0 data needed?

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/MaterialParameters_stage2.json [hunk 11]
```diff
@@ -0,0 +1,34 @@
...
+          "PERMEABILITY_XX": 1.157E-05,
+          "PERMEABILITY_YY": 1.157E-05,
+          "PERMEABILITY_XY": 0.0,
+          "DYNAMIC_VISCOSITY": 0.001,
+          "RETENTION_LAW": "SaturatedBelowPhreaticLevelLaw",
+          "RESIDUAL_SATURATION": 0.001,
+          "SATURATED_SATURATION": 1.0,
+          "MINIMUM_RELATIVE_PERMEABILITY": 0.001,
+          "K0_MAIN_DIRECTION": 1,
+          "K0_NC": 0.6,
```
Comment (markelov208) [inline applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/MaterialParameters_stage2.json]: I do not see a call for K0. Are these K0 data needed?

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage1.json [hunk 12]
```diff
@@ -0,0 +1,191 @@
...
+    "parallel_type"                    : "OpenMP",
+    "number_of_threads"                : 1
+  },
+  "solver_settings": {
+    "solver_type"                      : "Pw",
+    "model_part_name"                  : "PorousDomain",
+    "domain_size"                      : 2,
+    "model_import_settings": {
+      "input_type"                     : "mdpa",
+      "input_filename"                 : "kolom"
```
Comment (markelov208) [inline applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage1.json]: Should the file name be `column`?

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage2.json [hunk 13]
```diff
@@ -0,0 +1,173 @@
...
+    "parallel_type"                    : "OpenMP",
+    "number_of_threads"                : 1
+  },
+  "solver_settings": {
+    "solver_type"                      : "Pw",
+    "model_part_name"                  : "PorousDomain",
+    "domain_size"                      : 2,
+    "model_import_settings": {
+      "input_type"                     : "mdpa",
+      "input_filename"                 : "kolom"
```
Comment (markelov208) [inline applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage2.json]: Should the file name be `column`?

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle6N/MaterialParameters_stage1.json [hunk 14]
```diff
@@ -0,0 +1,34 @@
...
+          "PERMEABILITY_XX": 1.157E-05,
+          "PERMEABILITY_YY": 1.157E-05,
+          "PERMEABILITY_XY": 0.0,
+          "DYNAMIC_VISCOSITY": 0.001,
+          "RETENTION_LAW": "SaturatedBelowPhreaticLevelLaw",
+          "RESIDUAL_SATURATION": 0.001,
+          "SATURATED_SATURATION": 1.0,
+          "MINIMUM_RELATIVE_PERMEABILITY": 0.001,
+          "K0_MAIN_DIRECTION": 1,
+          "K0_NC": 0.6,
```
Comment (markelov208) [inline applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle6N/MaterialParameters_stage1.json]: As above

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle6N/MaterialParameters_stage2.json [hunk 15]
```diff
@@ -0,0 +1,34 @@
...
+          "PERMEABILITY_XX": 1.157E-05,
+          "PERMEABILITY_YY": 1.157E-05,
+          "PERMEABILITY_XY": 0.0,
+          "DYNAMIC_VISCOSITY": 0.001,
+          "RETENTION_LAW": "SaturatedBelowPhreaticLevelLaw",
+          "RESIDUAL_SATURATION": 0.001,
+          "SATURATED_SATURATION": 1.0,
+          "MINIMUM_RELATIVE_PERMEABILITY": 0.001,
+          "K0_MAIN_DIRECTION": 1,
+          "K0_NC": 0.6,
```
Comment (markelov208) [inline applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle6N/MaterialParameters_stage2.json]: As above

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle6N/ProjectParameters_stage1.json [hunk 16]
```diff
@@ -0,0 +1,191 @@
...
+    "parallel_type"                    : "OpenMP",
+    "number_of_threads"                : 1
+  },
+  "solver_settings": {
+    "solver_type"                      : "Pw",
+    "model_part_name"                  : "PorousDomain",
+    "domain_size"                      : 2,
+    "model_import_settings": {
+      "input_type"                     : "mdpa",
+      "input_filename"                 : "kolom"
```
Comment (markelov208) [inline applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle6N/ProjectParameters_stage1.json]: `column`?

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle6N/ProjectParameters_stage2.json [hunk 17]
```diff
@@ -0,0 +1,173 @@
...
+    "parallel_type"                    : "OpenMP",
+    "number_of_threads"                : 1
+  },
+  "solver_settings": {
+    "solver_type"                      : "Pw",
+    "model_part_name"                  : "PorousDomain",
+    "domain_size"                      : 2,
+    "model_import_settings": {
+      "input_type"                     : "mdpa",
+      "input_filename"                 : "kolom"
```
Comment (markelov208) [inline applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle6N/ProjectParameters_stage2.json]: `column`?

**Review by markelov208 — CHANGES_REQUESTED** [review]
Hi Mohamed and Wijtze-Pieter, the code looks very professional! Sorry I missed what was done to fix the problem. Based on the recent discussion, a higher order shall be used; however, I do not see it here. Does it mean that this PR's goal is to make the code professional? Many thanks.

File: applications/GeoMechanicsApplication/custom_elements/U_Pw_small_strain_element.cpp [hunk 18]
```diff
@@ -622,19 +612,7 @@ void UPwSmallStrainElement<TDim, TNumNodes>::CalculateOnIntegrationPoints(const
...
-                rOutput[GPoint] = mRetentionLawVector[GPoint]->CalculateEffectiveSaturation(RetentionParameters);
-            else if (rVariable == BISHOP_COEFFICIENT)
-                rOutput[GPoint] = mRetentionLawVector[GPoint]->CalculateBishopCoefficient(RetentionParameters);
-            else if (rVariable == DERIVATIVE_OF_SATURATION)
-                rOutput[GPoint] =
-                    mRetentionLawVector[GPoint]->CalculateDerivativeOfSaturation(RetentionParameters);
-            else if (rVariable == RELATIVE_PERMEABILITY)
-                rOutput[GPoint] =
-                    mRetentionLawVector[GPoint]->CalculateRelativePermeability(RetentionParameters);
+            rOutput[GPoint] = mRetentionLawVector[GPoint]->CalculateValue(RetentionParameters, rVariable, rOutput[GPoint]);
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_elements/U_Pw_small_strain_element.cpp]: I have noticed that the switch that has been taken out here, is repeated for each retention law (in their overrides of `CalculateValue`). We shouldn't try to address that in this PR, but I think it would be nice to pick that up soon after merging this one. I would propose to implement the switch in class `RetentionLaw` and to not make `CalculateValue` virtual. In that way, the switch is implemented only once, in a place where you would expect it to be.

File: applications/GeoMechanicsApplication/custom_elements/U_Pw_small_strain_element.cpp [hunk 19]
```diff
@@ -1280,17 +1261,18 @@ void UPwSmallStrainElement<TDim, TNumNodes>::CalculateAndAddCouplingMatrix(Matri
 {
     KRATOS_TRY
 
-    const auto coupling_matrix = GeoTransportEquationUtilities::CalculateCouplingMatrix(
-        rVariables.B, this->GetStressStatePolicy().GetVoigtVector(), rVariables.Np,
+    const Matrix coupling_matrix_up = GeoTransportEquationUtilities::CalculateCouplingMatrix(
+        rVariables.B, GetStressStatePolicy().GetVoigtVector(), rVariables.Np,
         rVariables.BiotCoefficient, rVariables.BishopCoefficient, rVariables.IntegrationCoefficient);
-    GeoElementUtilities::AssembleUPBlockMatrix(rLeftHandSideMatrix, coupling_matrix);
+    GeoElementUtilities::AssembleUPBlockMatrix(rLeftHandSideMatrix, coupling_matrix_up);
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_elements/U_Pw_small_strain_element.cpp:1267]: I am confused here: I had expected a minus sign in front of the coupling matrix, but I haven't found it yet... Perhaps @WPK4FEM can shed some light here, please?

File: applications/GeoMechanicsApplication/custom_elements/U_Pw_small_strain_element.cpp (hunk 1 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_elements/U_Pw_small_strain_element.cpp:287]: Removed

File: applications/GeoMechanicsApplication/custom_elements/U_Pw_base_element.cpp (hunk 2 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_elements/U_Pw_base_element.cpp:140]: Thank you.

File: applications/GeoMechanicsApplication/custom_elements/U_Pw_small_strain_interface_element.cpp (hunk 3 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_elements/U_Pw_small_strain_interface_element.cpp:211]: Removed.

File: applications/GeoMechanicsApplication/custom_elements/U_Pw_small_strain_interface_element.cpp (hunk 4 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_elements/U_Pw_small_strain_interface_element.cpp:284]: Removed.

File: applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.cpp (hunk 5 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.cpp]: Tried, see the version on github now.
Eventually, I would like to replace the whole summation below with shapefunctions of the pressure geometry multiplied by the p gotten from this pressure geometry. That is what it should be, there is no real need to write out this interpolation in the way it is done here. ( This is only very error prone )

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage2.json (hunk 13 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage2.json]: Changed.

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle6N/MaterialParameters_stage1.json (hunk 14 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle6N/MaterialParameters_stage1.json]: removed.

File: applications/GeoMechanicsApplication/custom_retention/saturated_below_phreatic_level_law.cpp (hunk 6 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_retention/saturated_below_phreatic_level_law.cpp:72]: Spoke with Anne. We will eventually place this in the retention law base class ( because all derived classes do exactly the same ) and clean it there.

File: applications/GeoMechanicsApplication/custom_retention/saturated_law.cpp (hunk 7 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_retention/saturated_law.cpp:57]: See previous reply.

File: applications/GeoMechanicsApplication/custom_retention/van_genuchten_law.cpp (hunk 9 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_retention/van_genuchten_law.cpp:130]: See previous reply.

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/MaterialParameters_stage1.json (hunk 10 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/MaterialParameters_stage1.json]: Removed.

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/MaterialParameters_stage2.json (hunk 11 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/MaterialParameters_stage2.json]: Removed.

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage1.json (hunk 12 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage1.json]: Changed.

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle6N/MaterialParameters_stage2.json (hunk 15 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle6N/MaterialParameters_stage2.json]: Removed.

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle6N/ProjectParameters_stage1.json (hunk 16 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle6N/ProjectParameters_stage1.json]: Changed.

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle6N/ProjectParameters_stage2.json (hunk 17 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle6N/ProjectParameters_stage2.json]: Changed.

File: applications/GeoMechanicsApplication/custom_retention/retention_law.h
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_retention/retention_law.h:1]: Perhaps we can try to apply the Rule of zero here?

File: applications/GeoMechanicsApplication/custom_retention/saturated_below_phreatic_level_law.h
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_retention/saturated_below_phreatic_level_law.h:1]: Perhaps we can try to apply the Rule of zero here?

File: applications/GeoMechanicsApplication/custom_retention/saturated_below_phreatic_level_law.cpp [hunk 20]
```diff
@@ -11,155 +11,98 @@
...
 
 namespace Kratos
 {
 SaturatedBelowPhreaticLevelLaw::SaturatedBelowPhreaticLevelLaw() : RetentionLaw() {}
 
-SaturatedBelowPhreaticLevelLaw::SaturatedBelowPhreaticLevelLaw(const SaturatedBelowPhreaticLevelLaw& rOther)
-    : RetentionLaw(rOther)
-{
-}
+SaturatedBelowPhreaticLevelLaw::SaturatedBelowPhreaticLevelLaw(const SaturatedBelowPhreaticLevelLaw& rOther) = default;
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_retention/saturated_below_phreatic_level_law.cpp]: We should be able to remove these when we apply the Rule of zero.

File: applications/GeoMechanicsApplication/custom_retention/saturated_below_phreatic_level_law.cpp [hunk 21]
```diff
@@ -11,155 +11,98 @@
...
 
 RetentionLaw::Pointer SaturatedBelowPhreaticLevelLaw::Clone() const
 {
     return Kratos::make_shared<SaturatedBelowPhreaticLevelLaw>(*this);
 }
 
-SaturatedBelowPhreaticLevelLaw::~SaturatedBelowPhreaticLevelLaw() {}
+SaturatedBelowPhreaticLevelLaw::~SaturatedBelowPhreaticLevelLaw() = default;
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_retention/saturated_below_phreatic_level_law.cpp]: We can probably do without explicitly defining the (default) destructor.

File: applications/GeoMechanicsApplication/custom_retention/van_genuchten_law.cpp [hunk 22]
```diff
@@ -29,17 +26,17 @@ double VanGenuchtenLaw::CalculateSaturation(Parameters& rParameters) const
...
-        const double& gn     = rMaterialProperties[VAN_GENUCHTEN_GN];
-        const double  gc     = (1.0 - gn) / gn;
+        const auto sat_max = rMaterialProperties[SATURATED_SATURATION];
+        const auto sat_min = rMaterialProperties[RESIDUAL_SATURATION];
+        const auto pb      = rMaterialProperties[VAN_GENUCHTEN_AIR_ENTRY_PRESSURE];
+        const auto gn      = rMaterialProperties[VAN_GENUCHTEN_GN];
+        const auto gc      = (1.0 - gn) / gn;
 
-        return satMin + (satMax - satMin) * pow(1.0 + pow(p / pb, gn), gc);
+        return sat_min + (sat_max - sat_min) * pow(1.0 + pow(p / pb, gn), gc);
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_retention/van_genuchten_law.cpp]: I would suggest to use `std::pow` here:
```suggestion
        return sat_min + (sat_max - sat_min) * std::pow(1.0 + std::pow(p / pb, gn), gc);
```

There are more occurrences of `pow` in this file that you may want to replace by `std::pow`.

File: applications/GeoMechanicsApplication/custom_retention/van_genuchten_law.cpp [hunk 23]
```diff
@@ -29,17 +26,17 @@ double VanGenuchtenLaw::CalculateSaturation(Parameters& rParameters) const
 {
     KRATOS_TRY
 
-    const double&     p                   = rParameters.GetFluidPressure();
-    const Properties& rMaterialProperties = rParameters.GetMaterialProperties();
+    const auto  p                   = rParameters.GetFluidPressure();
+    const auto& rMaterialProperties = rParameters.GetMaterialProperties();
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_retention/van_genuchten_law.cpp]: To be in line with the Kratos Style Guide:
```suggestion
    const auto& r_material_properties = rParameters.GetMaterialProperties();
```

File: applications/GeoMechanicsApplication/custom_retention/van_genuchten_law.cpp [hunk 24]
```diff
@@ -51,9 +48,9 @@ double VanGenuchtenLaw::CalculateEffectiveSaturation(Parameters& rParameters) co
 {
     KRATOS_TRY
 
-    const auto&   rMaterialProperties = rParameters.GetMaterialProperties();
-    const double& satMax              = rMaterialProperties[SATURATED_SATURATION];
-    const double& satMin              = rMaterialProperties[RESIDUAL_SATURATION];
+    const auto& rMaterialProperties = rParameters.GetMaterialProperties();
+    const auto  satMax              = rMaterialProperties[SATURATED_SATURATION];
+    const auto  satMin              = rMaterialProperties[RESIDUAL_SATURATION];
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_retention/van_genuchten_law.cpp]: Just to be consistent with your other changes:
```suggestion
    const auto& r_material_properties = rParameters.GetMaterialProperties();
    const auto  sat_max               = rMaterialProperties[SATURATED_SATURATION];
    const auto  sat_min               = rMaterialProperties[RESIDUAL_SATURATION];
```

File: applications/GeoMechanicsApplication/custom_retention/van_genuchten_law.cpp [hunk 25]
```diff
@@ -86,13 +83,13 @@ double VanGenuchtenLaw::CalculateRelativePermeability(Parameters& rParameters) c
 {
     KRATOS_TRY
 
-    const double effSat = CalculateEffectiveSaturation(rParameters);
+    const auto effSat = CalculateEffectiveSaturation(rParameters);
 
-    const auto&   rMaterialProperties = rParameters.GetMaterialProperties();
-    const double& gl                  = rMaterialProperties[VAN_GENUCHTEN_GL];
-    const double& gn                  = rMaterialProperties[VAN_GENUCHTEN_GN];
+    const auto& rMaterialProperties = rParameters.GetMaterialProperties();
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_retention/van_genuchten_law.cpp]: To comply with the Kratos Style Guide: `effSat` => `eff_sat`, `rMaterialPropererties` => `r_material_properties`, and `relPerm` => `rel_perm`.

File: applications/GeoMechanicsApplication/custom_retention/van_genuchten_law.cpp [hunk 26]
```diff
@@ -102,92 +99,73 @@ double VanGenuchtenLaw::CalculateRelativePermeability(Parameters& rParameters) c
...
+    KRATOS_ERROR_IF_NOT((rMaterialProperties[VAN_GENUCHTEN_GN] > 0.0))
+        << "VAN_GENUCHTEN_GN (" << rMaterialProperties[VAN_GENUCHTEN_GN] << ") must be greater than 0 "
+        << "for material " << rMaterialProperties.Id() << "." << std::endl;
+
+    KRATOS_ERROR_IF_NOT(rMaterialProperties.Has(VAN_GENUCHTEN_GL))
+        << "VAN_GENUCHTEN_GL is not available in the parameters of material "
+        << rMaterialProperties.Id() << "." << std::endl;
+    KRATOS_ERROR_IF_NOT((rMaterialProperties[VAN_GENUCHTEN_GL] >= 0.0))
+        << "VAN_GENUCHTEN_GL (" << rMaterialProperties[VAN_GENUCHTEN_GL]
+        << ") must be greater than 0 for material " << rMaterialProperties.Id() << "." << std::endl;
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_retention/van_genuchten_law.cpp]: I've spotted a minor inconsistency between the check (value must be >= 0.0) and the reported error (must be > 0.0). Can we please make it consistent (i.e. handle the case where value == 0.0 properly)?

File: applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.hpp [hunk 27]
```diff
@@ -224,7 +224,8 @@ class KRATOS_API(GEO_MECHANICS_APPLICATION) SmallStrainUPwDiffOrderElement : pub
     std::vector<Matrix> CalculateBMatrices(const GeometryType::ShapeFunctionsGradientsType& rDN_DXContainer,
                                            const Matrix& rNContainer) const;
 
-    void AssignPressureToIntermediateNodes();
+    Vector GetPressures(size_t n_nodes);
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.hpp]: I believe we can make this member function `const`.

File: applications/GeoMechanicsApplication/custom_elements/U_Pw_small_strain_element.cpp [hunk 28]
```diff
@@ -1493,7 +1478,7 @@ array_1d<double, TNumNodes> UPwSmallStrainElement<TDim, TNumNodes>::CalculateFlu
     const BoundedMatrix<double, TNumNodes, TDim> temp_matrix =
         prod(rVariables.GradNpT, rVariables.PermeabilityMatrix) * rVariables.IntegrationCoefficient;
 
-    return rVariables.DynamicViscosityInverse * this->GetProperties()[DENSITY_WATER] *
+    return rVariables.DynamicViscosityInverse * this->GetProperties()[DENSITY_WATER] * rVariables.BishopCoefficient *
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_elements/U_Pw_small_strain_element.cpp:1481]: I don't know how I can verify that this change is correct... Perhaps you could try to explain it to me in-person? Thanks.

File: applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.cpp [hunk 29]
```diff
@@ -56,112 +55,109 @@ int SmallStrainUPwDiffOrderElement::Check(const ProcessInfo& rCurrentProcessInfo
...
-            << "Wrong constitutive law used. This is a 2D element! expected "
-               "strain size is "
+            << "Wrong constitutive law used. This is a 2D element! expected strain size is "
             << VOIGT_SIZE_2D_PLANE_STRAIN << " But received: " << strainSize
             << " in element id: " << this->Id() << std::endl;
     }
 
+    // Check retention law
+    if (!mRetentionLawVector.empty()) {
+        return mRetentionLawVector[0]->Check(r_prop, rCurrentProcessInfo);
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.cpp:157]: Why is it sufficient to only check the retention law of the first integration point? Wouldn't it be better to check them all?

File: applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.cpp [hunk 30]
```diff
@@ -291,182 +279,151 @@ void SmallStrainUPwDiffOrderElement::FinalizeSolutionStep(const ProcessInfo& rCu
...
-        const double p0 = rGeom[0].FastGetSolutionStepValue(WATER_PRESSURE);
-        const double p1 = rGeom[1].FastGetSolutionStepValue(WATER_PRESSURE);
-        const double p2 = rGeom[2].FastGetSolutionStepValue(WATER_PRESSURE);
-        ThreadSafeNodeWrite(rGeom[3], WATER_PRESSURE, 0.5 * (p0 + p1));
-        ThreadSafeNodeWrite(rGeom[4], WATER_PRESSURE, 0.5 * (p1 + p2));
-        ThreadSafeNodeWrite(rGeom[5], WATER_PRESSURE, 0.5 * (p2 + p0));
+        const Vector p = GetPressures(3);
+        ThreadSafeNodeWrite(r_geom[3], WATER_PRESSURE, 0.5 * (p[0] + p[1]));
+        ThreadSafeNodeWrite(r_geom[4], WATER_PRESSURE, 0.5 * (p[1] + p[2]));
+        ThreadSafeNodeWrite(r_geom[5], WATER_PRESSURE, 0.5 * (p[2] + p[0]));
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.cpp:305]: This is already a nice improvement. I guess that at some later point in time we'd like to take this one step further by explicitly using the shape functions for interpolating the water pressure values?

File: applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.cpp [hunk 31]
```diff
@@ -589,55 +546,45 @@ void SmallStrainUPwDiffOrderElement::CalculateOnIntegrationPoints(const Variable
...
-            else if (rVariable == RELATIVE_PERMEABILITY)
-                rOutput[GPoint] =
-                    mRetentionLawVector[GPoint]->CalculateRelativePermeability(RetentionParameters);
+            rOutput[GPoint] = mRetentionLawVector[GPoint]->CalculateValue(
+                RetentionParameters, rVariable, rOutput[GPoint]);
         }
     } else if (rVariable == HYDRAULIC_HEAD) {
-        const double          NumericalLimit = std::numeric_limits<double>::epsilon();
-        const PropertiesType& rProp          = this->GetProperties();
+        constexpr double      NumericalLimit = std::numeric_limits<double>::epsilon();
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.cpp]: To comply with the Kratos Style Guide and to use `auto`:
```suggestion
        constexpr auto numerical_limit = std::numeric_limits<double>::epsilon();
```

File: applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.cpp [hunk 32]
```diff
@@ -589,55 +546,45 @@ void SmallStrainUPwDiffOrderElement::CalculateOnIntegrationPoints(const Variable
...
+        for (unsigned int node = 0; node < num_u_nodes; ++node) {
             Vector NodeVolumeAcceleration(3);
-            noalias(NodeVolumeAcceleration) = rGeom[node].FastGetSolutionStepValue(VOLUME_ACCELERATION, 0);
+            noalias(NodeVolumeAcceleration) = r_geom[node].FastGetSolutionStepValue(VOLUME_ACCELERATION, 0);
             const double g = norm_2(NodeVolumeAcceleration);
             if (g > NumericalLimit) {
-                const double FluidWeight = g * rProp[DENSITY_WATER];
+                const auto fluid_weight = g * r_prop[DENSITY_WATER];
 
                 Vector NodeCoordinates(3);
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.cpp]:
```suggestion
                Vector node_coordinates(3);
```

File: applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.cpp [hunk 33]
```diff
@@ -589,55 +546,45 @@ void SmallStrainUPwDiffOrderElement::CalculateOnIntegrationPoints(const Variable
...
-                noalias(NodeCoordinates) = rGeom[node].Coordinates();
+                noalias(NodeCoordinates) = r_geom[node].Coordinates();
                 Vector NodeVolumeAccelerationUnitVector(3);
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.cpp]:
```suggestion
                Vector node_volume_acceleration_unit_vector(3);
```

File: applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.cpp [hunk 34]
```diff
@@ -1452,14 +1400,14 @@ void SmallStrainUPwDiffOrderElement::CalculateAndAddFluidBodyFlow(VectorType& rR
 {
     KRATOS_TRY
 
-    const Matrix grad_Np_T_perm =
-        rVariables.DynamicViscosityInverse * GetProperties()[DENSITY_WATER] * rVariables.RelativePermeability *
-        prod(rVariables.DNp_DX, rVariables.IntrinsicPermeability) * rVariables.IntegrationCoefficient;
+    const Matrix grad_Np_T_perm = rVariables.DynamicViscosityInverse * rVariables.BishopCoefficient *
+                                  GetProperties()[DENSITY_WATER] * rVariables.RelativePermeability *
+                                  prod(rVariables.DNp_DX, rVariables.IntrinsicPermeability) *
+                                  rVariables.IntegrationCoefficient;
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.cpp:1406]: I'm not sure how I should review this change.

File: applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.cpp [hunk 35]
```diff
@@ -1471,10 +1419,8 @@ void SmallStrainUPwDiffOrderElement::CalculateAndAddFluidBodyFlow(VectorType& rR
         }
     }
 
-    for (SizeType i = 0; i < num_P_nodes; ++i) {
-        rRightHandSideVector[num_U_nodes * dimension + i] +=
-            inner_prod(row(grad_Np_T_perm, i), body_acceleration);
-    }
+    const Vector fluid_body_flow = prod(grad_Np_T_perm, body_acceleration);
+    GeoElementUtilities::AssemblePBlockVector(rRightHandSideVector, fluid_body_flow);
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.cpp:1423]: Nice! This is much easier to read. Thank you.

File: applications/GeoMechanicsApplication/tests/Interface/interface_on_beam/MaterialParameters.json
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/Interface/interface_on_beam/MaterialParameters.json:1]: I'm sorry, it's not obvious to me why the `IGNORE_UNDRAINED` flag needs to be toggled.

File: applications/GeoMechanicsApplication/tests/Interface/weak_interface_on_beam/MaterialParameters.json
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/Interface/weak_interface_on_beam/MaterialParameters.json:1]: I'm sorry, it's not obvious to me why the `IGNORE_UNDRAINED` flag needs to be toggled.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_retention/test_saturated_below_phreatic_level_law.cpp [hunk 36]
```diff
@@ -0,0 +1,113 @@
...
+
+namespace
+{
+
+using namespace Kratos;
+
+SaturatedBelowPhreaticLevelLaw CreateSaturatedBelowPhreaticLevelLaw()
+{
+    return SaturatedBelowPhreaticLevelLaw{};
+}
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_retention/test_saturated_below_phreatic_level_law.cpp]: Perhaps this helper function is overkill. If we would inline this function, I think the readability of the test code would be just as good as without this helper.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_retention/test_saturated_below_phreatic_level_law.cpp [hunk 37]
```diff
@@ -0,0 +1,113 @@
...
+
+} // namespace
+
+namespace Kratos::Testing
+{
+
+KRATOS_TEST_CASE_IN_SUITE(SaturatedBelowPhreaticLevelLawReturnsCloneOfCorrectType, KratosGeoMechanicsFastSuiteWithoutKernel)
+{
+    const auto law         = CreateSaturatedBelowPhreaticLevelLaw();
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_retention/test_saturated_below_phreatic_level_law.cpp]: So, for instance here I would have written:
```suggestion
    const auto law         = SaturatedBelowPhreaticLevelLaw{};
```

I think we can do the same thing in other places.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_retention/test_saturated_law.cpp [hunk 38]
```diff
@@ -0,0 +1,78 @@
...
+#include "custom_retention/saturated_law.h"
+#include "geo_mechanics_application_variables.h"
+#include "tests/cpp_tests/geo_mechanics_fast_suite.h"
+
+namespace
+{
+
+using namespace Kratos;
+
+SaturatedLaw CreateSaturatedLaw() { return SaturatedLaw{}; }
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_retention/test_saturated_law.cpp]: Also here, I'm not sure about the added value of this helper function.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_retention/test_van_genuchten_law.cpp [hunk 39]
```diff
@@ -0,0 +1,146 @@
...
+#include "custom_retention/van_genuchten_law.h"
+#include "geo_mechanics_application_variables.h"
+#include "tests/cpp_tests/geo_mechanics_fast_suite.h"
+
+namespace
+{
+
+using namespace Kratos;
+
+VanGenuchtenLaw CreateVanGenuchtenLaw() { return VanGenuchtenLaw{}; }
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_retention/test_van_genuchten_law.cpp]: Same doubt here...

File: applications/GeoMechanicsApplication/tests/test_partial_saturation.py [hunk 40]
```diff
@@ -0,0 +1,87 @@
...
+    This class contains benchmark tests which are checked with the analytical solution
+    """
+
+    def setUp(self):
+        # Code here will be placed BEFORE every test in this TestCase.
+        pass
+
+    def tearDown(self):
+        # Code here will be placed AFTER every test in this TestCase.
+        pass
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/test_partial_saturation.py]: I would leave both of these out, since `KratosUnittest.TestCase` doesn't define these and thus inherits them from Python's `TestCase`. The default implementations of `setUp` and `tearDown` of Python's `TestCase` also [do nothing](https://docs.python.org/3/library/unittest.html#unittest.TestCase.setUp).

File: applications/GeoMechanicsApplication/tests/test_partial_saturation.py [hunk 41]
```diff
@@ -0,0 +1,87 @@
...
+
+    def __test_saturated_below_phreatic_level_pw(self, test_name):
+        n_stages = 2
+
+        # get the parameter file names for all stages
+        file_path = test_helper.get_file_path(os.path.join('.', 'test_partially_saturated', test_name))
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/test_partial_saturation.py]: No need to explicitly include `.` here, since it is a relative path anyway.
```suggestion
        file_path = test_helper.get_file_path(os.path.join('test_partially_saturated', test_name))
```

File: applications/GeoMechanicsApplication/tests/test_partial_saturation.py [hunk 42]
```diff
@@ -0,0 +1,87 @@
...
+        parameter_file_names = [os.path.join(file_path, 'ProjectParameters_stage' + str(i + 1) + '.json') for i in
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/test_partial_saturation.py]: Python f-strings are the modern way to dynamically build strings:
```suggestion
        parameter_file_names = [os.path.join(file_path, f'ProjectParameters_stage{i+1}.json') for i in
```

File: applications/GeoMechanicsApplication/tests/test_partial_saturation.py [hunk 43]
```diff
@@ -0,0 +1,87 @@
...
+                                range(n_stages)]
+
+        # set stage parameters
+        parameters_stages = [None] * n_stages
+        os.chdir(file_path)
+        for idx, parameter_file_name in enumerate(parameter_file_names):
+            with open(parameter_file_name, 'r') as parameter_file:
+                parameters_stages[idx] = Kratos.Parameters(parameter_file.read())
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/test_partial_saturation.py]: There is no need to use a loop counter here:
```suggestion
        parameters_stages = []
        os.chdir(file_path)
        for parameter_file_name in parameter_file_names:
            with open(parameter_file_name, 'r') as parameter_file:
                parameters_stages.append(Kratos.Parameters(parameter_file.read()))
```

File: applications/GeoMechanicsApplication/tests/test_partial_saturation.py [hunk 44]
```diff
@@ -0,0 +1,87 @@
...
+
+        model = Kratos.Model()
+        stages = [analysis.GeoMechanicsAnalysis(model, stage_parameters) for stage_parameters in parameters_stages]
+
+        # run stages and get water pressure/displacement results per stage
+        stage_water_pressure = [None] * n_stages
+        for idx, stage in enumerate(stages):
+            stage.Run()
+            stage_water_pressure[idx] = test_helper.get_water_pressure(stage)
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/test_partial_saturation.py]: We have experienced in the past that creating all analysis stages upfront, may cause problems. Therefore, I'd suggest to create the analysis stage as we iterate over the stages:
```suggestion
        model = Kratos.Model()

        # run stages and get water pressure/displacement results per stage
        stage_water_pressure = []
        for stage_parameters in parameters_stages:
            stage = analysis.GeoMechanicsAnalysis(model, stage_parameters)
            stage.Run()
            stage_water_pressure.append(test_helper.get_water_pressure(stage))
```

File: applications/GeoMechanicsApplication/tests/test_partial_saturation.py [hunk 45]
```diff
@@ -0,0 +1,87 @@
...
+
+        # get y coords of all the nodes
+        coords = test_helper.get_nodal_coordinates(stages[1])
+        y_coords = [coord[1] for coord in coords]
+
+        # calculate water pressure analytical solution for all stages and calculate the error
+        rel_p_stage  = [self.__calculate_column_saturated_under_phreatic_level(y_coord) for y_coord in y_coords]
+        print(rel_p_stage)
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/test_partial_saturation.py]: This is nice for debugging, but we shouldn't print results during a test run. So please, remove this `print` statement.

File: applications/GeoMechanicsApplication/tests/test_partial_saturation.py [hunk 46]
```diff
@@ -0,0 +1,87 @@
...
+        
+        errors_stage = [stage_water_pressure[1][node_idx] - rel_p for node_idx, rel_p in
+                         enumerate(rel_p_stage)]
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/test_partial_saturation.py]: It seems like you'd like to iterate two sequences at the same time. Python's built-in function `zip` is intended to do just that:
```suggestion
        errors_stage = [actual_pressure - expected_pressure for actual_pressure, expected_pressure in
                         zip(stage_water_pressure[1], rel_p_stage)]
```

File: applications/GeoMechanicsApplication/tests/test_partial_saturation.py [hunk 47]
```diff
@@ -0,0 +1,87 @@
...
+        rmse_stages = (sum([error ** 2 for error in errors_stage]) / len(errors_stage)) ** 0.5
+
+        # assert if average error in all stages is below 1 percent
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/test_partial_saturation.py]: I'm sorry, but I don't understand this comment. How does 1% relate to an accuracy of 1.0e-7?

File: applications/GeoMechanicsApplication/tests/test_partial_saturation.py [hunk 48]
```diff
@@ -0,0 +1,87 @@
...
+    def test_saturated_below_phreatic_level_upw_difforder_triangle6n(self):
+        self.__test_saturated_below_phreatic_level_pw('test_saturated_below_phreatic_level_upw_difforder_triangle6n')
+        
+    def test_saturated_below_phreatic_level_upw_smallstrain_triangle3n(self):
+        self.__test_saturated_below_phreatic_level_pw('test_saturated_below_phreatic_level_upw_smallstrain_triangle3n')
+        
+    def test_saturated_below_phreatic_level_upw_smallstrain_triangle6n(self):
+        self.__test_saturated_below_phreatic_level_pw('test_saturated_below_phreatic_level_upw_smallstrain_triangle6n')
+
+    def __calculate_column_saturated_under_phreatic_level(self, y_coord):
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/test_partial_saturation.py]: This function computes the hydrostatic water pressure at the given depth (i.e. $`y`$). Perhaps we can reflect that in the function's name, e.g. `compute_hydrostatic_water_pressure`?

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/README.md [hunk 49]
```diff
@@ -0,0 +1,21 @@
+# Test Cases for partially saturated flow
+## Saturated below phreatic level
+
+**Author:** [Mohamed Nabi](https://github.com/mnabideltares)
+
+**Source files:** [Partially saturated flow](https://github.com/KratosMultiphysics/Kratos/tree/master/applications/GeoMechanicsApplication/tests/test_partially_saturated)
+
+## Case Specification
+In this test case, a column of 1 x 5 m soil is considered (set between -5 m and 0 m). A phreatic line is set at the level of $y = -2$ m. The water pore pressure field is then calculated.
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/test_partially_saturated/README.md]:
```suggestion
In this test case, a column of 1 x 5 m soil is considered (set between $`y = -5 \mathrm{m}`$ and $`y = 0 \mathrm{m}`$). A phreatic line is set at the level of $y = -2$ m. The water pore pressure field is then calculated.
```

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/README.md [hunk 50]
```diff
@@ -0,0 +1,21 @@
...
+The simulation is done on a double stage process, and steady state Pw and U-Pw elements are considered. This test is conducted for various configurations, including
+
+- 2D3N: for Pw and U-Pw small strain elements
+- 2D6N: for Pw and U-Pw small strain and U-Pw different order elements.
+
+The pressure distribution along the column is then evaluated with its alalytical result.
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/test_partially_saturated/README.md]: A typo (and perhaps use "compare" rather than "evaluate"?):
```suggestion
The pressure distribution along the column is then compared with its analytical result.
```

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage1.json [hunk 51]
```diff
@@ -0,0 +1,191 @@
...
+    "max_radius_factor"                : 10.0,
+    "min_radius_factor"                : 0.1,
+    "calculate_reactions"              : true,
+    "max_line_search_iterations"       : 5,
+    "first_alpha_value"                : 0.5,
+    "second_alpha_value"               : 1.0,
+    "min_alpha"                        : 0.1,
+    "max_alpha"                        : 2.0,
+    "line_search_tolerance"            : 0.5,
+    "rotation_dofs"                    : true,
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage1.json]: I don't think you want to have rotational DoFs in this analysis (it should be water pressure DoFs only, I think)...
```suggestion
    "rotation_dofs"                    : false,
```

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage1.json [hunk 52]
```diff
@@ -0,0 +1,191 @@
...
+              "output_control_type"    : "step",
+              "output_interval"        : 1,
+              "body_output"            : true,
+              "node_output"            : false,
+              "skin_output"            : false,
+              "plane_output"           : [],
+              "nodal_results"          : ["DISPLACEMENT", "TOTAL_DISPLACEMENT", "WATER_PRESSURE", "VOLUME_ACCELERATION",
+			                              "LINE_LOAD_Y", "TOTAL_STRESS_TENSOR", "CAUCHY_STRESS_TENSOR"],
+              "gauss_point_results"    : ["GREEN_LAGRANGE_STRAIN_TENSOR", "ENGINEERING_STRAIN_TENSOR", "VON_MISES_STRESS",
+                                          "FLUID_FLUX_VECTOR", "HYDRAULIC_HEAD", "DEGREE_OF_SATURATION"]
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage1.json]: Please limit the requested output to what you actually want to check. This is particularly relevant for code coverage, as it may suggest that some output items are covered by tests, which in fact aren't.

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage1.json [hunk 53]
```diff
@@ -0,0 +1,191 @@
...
+      {
+        "python_module"                : "apply_scalar_constraint_table_process",
+        "kratos_module"                : "KratosMultiphysics.GeoMechanicsApplication",
+        "process_name"                 : "ApplyScalarConstraintTableProcess",
+        "Parameters": {
+          "model_part_name"            : "PorousDomain.WATER_PRESSURE_Initial",
+          "variable_name"              : "WATER_PRESSURE",
+          "is_fixed"                   : false,
+          "table"                      : 0,
+          "fluid_pressure_type"        : "Phreatic_Multi_Line",
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage1.json:117]: This type aims at phreatic lines that consist of multiple line segments. This type works, but there is a simpler one that is targeted at your situation, where the phreatic line has a uniform $`y`$ coordinate.

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage1.json [hunk 54]
```diff
@@ -0,0 +1,191 @@
...
+    ],
+    "auxiliar_process_list": [
+     {
+        "python_module"                : "geo_extrapolate_integration_point_values_to_nodes_process",
+        "kratos_module"                : "KratosMultiphysics.GeoMechanicsApplication",
+        "process_name"                 : "GeoExtrapolateIntegrationPointValuesToNodesProcess",
+        "Parameters": {
+          "model_part_name"            : "PorousDomain",
+          "list_of_variables"          : ["TOTAL_STRESS_TENSOR", "CAUCHY_STRESS_TENSOR"]
+        }
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage1.json]: We aren't checking the values produced by this process, are we? If that is correct, I would suggest to remove this process from the test, to keep it as simple as possible.

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage2.json [hunk 55]
```diff
@@ -0,0 +1,173 @@
...
+    "domain_size"                      : 2,
+    "model_import_settings": {
+      "input_type"                     : "mdpa",
+      "input_filename"                 : "column"
+    },
+    "material_import_settings": {
+      "materials_filename"             : "../Common/MaterialParameters_stage2.json"
+    },
+    "time_stepping": {
+      "time_step"                      : 0.1,
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage2.json:22]: Can you please explain why we would need to carry out ten time steps, since the elements used are steady-state Pw elements? There shouldn't be any time effects, or am I overlooking something?

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage2.json [hunk 56]
```diff
@@ -0,0 +1,173 @@
...
+    "nodal_smoothing"                  : false,
+    "block_builder"                    : true,
+    "solution_type"                    : "Steady_State_Groundwater_Flow",
+    "scheme_type"                      : "Backward_Euler",
+    "reset_displacements"              : false,
+    "strategy_type"                    : "newton_raphson",
+    "convergence_criterion"            : "water_pressure_criterion",
+    "water_pressure_relative_tolerance": 0.0001,
+    "water_pressure_absolute_tolerance": 1E-09,
+    "displacement_relative_tolerance"  : 0.0001,
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage2.json:39]: This value is ten times smaller than what was used in stage 1. But there are no displacement DoFs here... So I would suggest to use the same value as in stage 1, since it is irrelevant anyway.

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/column.mdpa [hunk 57]
```diff
@@ -0,0 +1,206 @@
...
+           22
+    End SubModelPartNodes
+End SubModelPart
+
+Begin SubModelPart DISPLACEMENT_Bottom // Group Bottom // Subtree DISPLACEMENT
+    Begin SubModelPartNodes
+            1
+            2
+    End SubModelPartNodes
+End SubModelPart
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/column.mdpa]: This sub-model part is not being used in this simulation, so I would take it out.

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle6N/column.mdpa [hunk 58]
```diff
@@ -0,0 +1,393 @@
...
+    End SubModelPartNodes
+End SubModelPart
+
+Begin SubModelPart DISPLACEMENT_Bottom // Group Bottom // Subtree DISPLACEMENT
+    Begin SubModelPartNodes
+            1
+            2
+           43
+    End SubModelPartNodes
+End SubModelPart
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle6N/column.mdpa]: This is an unused sub-model part.

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle6N/column.mdpa [hunk 59]
```diff
@@ -0,0 +1,393 @@
...
+
+Begin SubModelPart DISPLACEMENT_Sides // Group Sides // Subtree DISPLACEMENT
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle6N/column.mdpa]: And also this sub-model part is not being used.

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/column.mdpa [hunk 60]
```diff
@@ -0,0 +1,206 @@
...
+
+Begin SubModelPart DISPLACEMENT_Sides // Group Sides // Subtree DISPLACEMENT
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/column.mdpa]: Also this sub-model part is not being used...

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_upw_difforder_triangle6n/ProjectParameters_stage1.json
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_upw_difforder_triangle6n/ProjectParameters_stage1.json:1]: I am missing displacement boundary conditions here. I had expected to see that the bottom edge would be fixed, and sliders along the sides of the column. Shouldn't we better add these?

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_upw_difforder_triangle6n/column.mdpa [hunk 61]
```diff
@@ -0,0 +1,393 @@
...
+           58
+           59
+           60
+           61
+           62
+           63
+    End SubModelPartNodes
+End SubModelPart
+
+Begin SubModelPart DISPLACEMENT_Bottom // Group Bottom // Subtree DISPLACEMENT
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_upw_difforder_triangle6n/column.mdpa:256]: This sub-model part should be referenced from the `ProjectParameters.json` files to fix the displacements at the bottom, but that is currently not being done.

UPDATE: Now I see that you fix _all_ displacement DOFs, by prescribing zeroes for them. In that case, we don't need this sub-model part.

**Review by avdg81 — COMMENTED** [review]
Gentlemen, you two have done a lot of work to clean up the code and to fix a few issues. I'm very satisfied with the result. It's yet another step towards code that is easier to understand and more maintainable.

I do have quite a few suggestions and some questions, but none of them is blocking in my opinion.

File: applications/GeoMechanicsApplication/custom_elements/U_Pw_small_strain_element.cpp (hunk 19 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_elements/U_Pw_small_strain_element.cpp:1267]: As we discussed, I have the same doubt and have been looking for the same. Trying to change it leads at least to some tests failing. We need to sort this out building up a really validated test suite.

File: applications/GeoMechanicsApplication/custom_retention/retention_law.h
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_retention/retention_law.h:1]: Tried with some help.

File: applications/GeoMechanicsApplication/custom_retention/saturated_below_phreatic_level_law.h
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_retention/saturated_below_phreatic_level_law.h:1]: Tried.

File: applications/GeoMechanicsApplication/custom_retention/saturated_below_phreatic_level_law.cpp (hunk 20 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_retention/saturated_below_phreatic_level_law.cpp]: tried.

File: applications/GeoMechanicsApplication/custom_retention/saturated_below_phreatic_level_law.cpp (hunk 21 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_retention/saturated_below_phreatic_level_law.cpp]: tried.

File: applications/GeoMechanicsApplication/custom_retention/van_genuchten_law.cpp (hunk 23 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_retention/van_genuchten_law.cpp]: done trhoughout.

File: applications/GeoMechanicsApplication/custom_retention/van_genuchten_law.cpp (hunk 24 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_retention/van_genuchten_law.cpp]: done.

File: applications/GeoMechanicsApplication/custom_retention/van_genuchten_law.cpp (hunk 25 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_retention/van_genuchten_law.cpp]: done

File: applications/GeoMechanicsApplication/custom_retention/van_genuchten_law.cpp (hunk 26 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_retention/van_genuchten_law.cpp]: Good find, originates from an existing test. Should now be consistent, thank you.

File: applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.cpp (hunk 29 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.cpp:157]: They are all clones of the same thing. Is it necessary to do all of them?

File: applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.hpp (hunk 27 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.hpp]: done.

File: applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.cpp (hunk 30 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.cpp:305]: Yes indeed

File: applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.cpp (hunk 31 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.cpp]: done

File: applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.cpp (hunk 32 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.cpp]: done.

File: applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.cpp (hunk 33 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_elements/small_strain_U_Pw_diff_order_element.cpp]: done.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_retention/test_saturated_below_phreatic_level_law.cpp (hunk 36 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_retention/test_saturated_below_phreatic_level_law.cpp]: removed it.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_retention/test_saturated_below_phreatic_level_law.cpp (hunk 37 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_retention/test_saturated_below_phreatic_level_law.cpp]: done

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_retention/test_saturated_law.cpp (hunk 38 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_retention/test_saturated_law.cpp]: removed.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_retention/test_van_genuchten_law.cpp (hunk 39 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_retention/test_van_genuchten_law.cpp]: removed

File: applications/GeoMechanicsApplication/tests/test_partial_saturation.py (hunk 40 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/test_partial_saturation.py]: Reomoved

File: applications/GeoMechanicsApplication/tests/test_partial_saturation.py (hunk 41 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/test_partial_saturation.py]: done.

File: applications/GeoMechanicsApplication/tests/test_partial_saturation.py (hunk 42 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/test_partial_saturation.py]: done.

File: applications/GeoMechanicsApplication/tests/test_partial_saturation.py (hunk 48 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/test_partial_saturation.py]: done.

File: applications/GeoMechanicsApplication/tests/test_partial_saturation.py (hunk 47 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/test_partial_saturation.py]: changed the descriptive text.

File: applications/GeoMechanicsApplication/tests/test_partial_saturation.py (hunk 46 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/test_partial_saturation.py]: tried.

File: applications/GeoMechanicsApplication/tests/test_partial_saturation.py (hunk 45 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/test_partial_saturation.py]: removed.

File: applications/GeoMechanicsApplication/tests/test_partial_saturation.py (hunk 44 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/test_partial_saturation.py]: done.

File: applications/GeoMechanicsApplication/tests/test_partial_saturation.py (hunk 43 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/test_partial_saturation.py]: tried

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/README.md (hunk 50 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/test_partially_saturated/README.md]: done.

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/README.md (hunk 49 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/test_partially_saturated/README.md]: done.

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage1.json (hunk 52 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage1.json]: Removed most items. I would like to do without output process, but the test helper looks at it to determine the node numbers.

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage1.json (hunk 54 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage1.json]: Removed.

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/column.mdpa (hunk 57 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/column.mdpa]: Done

File: applications/GeoMechanicsApplication/custom_retention/saturated_below_phreatic_level_law.cpp (hunk 20 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_retention/saturated_below_phreatic_level_law.cpp]: tried.

File: applications/GeoMechanicsApplication/custom_retention/van_genuchten_law.cpp (hunk 22 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_retention/van_genuchten_law.cpp]: replaced all.

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle6N/column.mdpa (hunk 58 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle6N/column.mdpa]: Done

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_upw_difforder_triangle6n/column.mdpa (hunk 61 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_upw_difforder_triangle6n/column.mdpa:256]: Removed

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_upw_difforder_triangle6n/ProjectParameters_stage1.json
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_upw_difforder_triangle6n/ProjectParameters_stage1.json:1]: Removed the bottom boundary, as it is not necessary

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/column.mdpa (hunk 60 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/column.mdpa]: Removed

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle6N/column.mdpa (hunk 59 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle6N/column.mdpa]: Removed

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle6N/column.mdpa (hunk 58 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle6N/column.mdpa]: Removed

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage2.json (hunk 56 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage2.json:39]: To be consistent with other parts, in stage 1, it is changed to 0.0001

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage2.json (hunk 55 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage2.json:22]: Changed to 1.0

File: applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage1.json (hunk 53 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage1.json:117]: I think one of the goals of of these test cases is to prove that multi-line phreatic line works correctly. 
What do you think @WPK4FEM ?

Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/test_partially_saturated/test_saturated_below_phreatic_level_pw_triangle3N/ProjectParameters_stage1.json:117]: The objective of the tests is to show that the correct equilibrium is found and stays stable. The method used for providing the pressure boundary condition can be any, preferably the simplest.

**Review by avdg81 — DISMISSED** [review]
Thanks for all the hard work. I believe this PR is ready to be merged.

**Review by markelov208 — DISMISSED** [review]

**Review by avdg81 — APPROVED** [review]
Let me approve it once more :-)
