### PR TITLE
[GeoMechanicsApplication] Fix arrays passed to UDSM

### LINKED ISSUE #13426: [GeoMechanicsApplication] Check inputs we provide to our UDSMs
The UDSM interface is detailed in the manual "PLAXIS 2D 2024.2" starting from page 181.

### PR DESCRIPTION
**Pull request by avdg81**
**📝 Description**
The sizes of three arrays (i.e. `Sig0`, `dEps`, and `Props`) did not match the expected sizes as written down in the UDSM documentation. With these changes, we now ensure that the arrays have the correct sizes. See Section 16.2 "Implementation of User Defined (UD) soil Models in calculations program" of the Plaxis documentation.

Note that data member `mStressVectorFinalized` has been replaced by data member `mSig0` (which matches the function parameter name adopted by the UDSM), since it contains more than just the stress vector.

**🆕 Changelog**
Other changes include:
- Use subscript operator `[]` rather than `()` to access vector elements.
- Removed an `override` that did effectively the same thing as the base class version.
- Replaced a few raw `for` loops by STL algorithms.
- Changed a few names to comply with the Kratos Style Guide.
- Replaced some explicit type names by `auto`.
- Removed some redundant size checks (member function `resize` already checks whether the new size differs from the current one).
- Removed some `KRATOS_TRY` and `KRATOS_CATCH` constructs.

### CODE REVIEW

File: applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_2D_plane_strain_law.cpp [hunk 1]
```diff
@@ -25,15 +25,6 @@ ConstitutiveLaw::Pointer SmallStrainUDSM2DPlaneStrainLaw::Clone() const
...
 }
 
-void SmallStrainUDSM2DPlaneStrainLaw::UpdateInternalDeltaStrainVector(ConstitutiveLaw::Parameters& rValues)
-{
-    const Vector& rStrainVector = rValues.GetStrainVector();
-
-    for (unsigned int i = 0; i < VoigtSize; ++i) {
-        mDeltaStrainVector[i] = rStrainVector(i) - mStrainVectorFinalized[i];
-    }
-}
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_2D_plane_strain_law.cpp:35]: Note that this `override` is essentially doing the same thing as the base class version, except for `VoigtSize` having a different value (it differs per class). We have fixed that by using the overridable `GetStrainSize` member in the base class version.

File: applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_2D_interface_law.cpp [hunk 2]
```diff
@@ -40,12 +42,12 @@ void SmallStrainUDSM2DInterfaceLaw::SetExternalStressVector(Vector& rStressVecto
...
 void SmallStrainUDSM2DInterfaceLaw::SetInternalStressVector(const Vector& rStressVector)
 {
-    KRATOS_TRY
-    std::fill(mStressVectorFinalized.begin(), mStressVectorFinalized.end(), 0.0);
+    auto& r_sig0 = GetSig0();
 
-    mStressVectorFinalized[INDEX_3D_ZZ] = rStressVector(INDEX_2D_INTERFACE_ZZ);
-    mStressVectorFinalized[INDEX_3D_XZ] = rStressVector(INDEX_2D_INTERFACE_XZ);
-    KRATOS_CATCH("")
+    std::fill_n(r_sig0.begin(), StressVectorSize, 0.0);
```
Comment (rfaasse) [inline applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_2D_interface_law.cpp:47]: I see StressVectorSize is defined in the 3D law, should it be the same for 2D vs 3D?

File: applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_2D_plane_strain_law.cpp [hunk 3]
```diff
@@ -43,15 +34,6 @@ void SmallStrainUDSM2DPlaneStrainLaw::SetExternalStressVector(Vector& rStressVec
...
 }
 
-void SmallStrainUDSM2DPlaneStrainLaw::SetInternalStressVector(const Vector& rStressVector)
-{
-    KRATOS_TRY
-    for (unsigned int i = 0; i < VoigtSize; ++i) {
-        mStressVectorFinalized[i] = rStressVector(i);
-    }
-    KRATOS_CATCH("")
-}
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_2D_plane_strain_law.cpp:53]: Same story here.

File: applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_3D_law.cpp [hunk 4]
```diff
@@ -24,6 +24,24 @@
...
 #endif
 
+namespace
+{
+
+using namespace Kratos;
+
+constexpr auto props_size = SizeType{50};
+
+array_1d<double, props_size> MakePropsVector(const Vector& rUMatParameters)
```
Comment (rfaasse) [inline applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_3D_law.cpp:34]: I think it might be nice to add a comment here why it's hardcoded 50 (i.e. it's expected by the interface)

File: applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_2D_interface_law.cpp [hunk 5]
```diff
@@ -95,10 +97,11 @@ Vector& SmallStrainUDSM2DInterfaceLaw::GetValue(const Variable<Vector>& rThisVar
...
+        rValue.resize(VoigtSize);
 
-        rValue[INDEX_2D_INTERFACE_ZZ] = mStressVectorFinalized[INDEX_3D_ZZ];
-        rValue[INDEX_2D_INTERFACE_XZ] = mStressVectorFinalized[INDEX_3D_XZ];
+        auto& r_sig0                  = GetSig0();
+        rValue[INDEX_2D_INTERFACE_ZZ] = r_sig0[INDEX_3D_ZZ];
+        rValue[INDEX_2D_INTERFACE_XZ] = r_sig0[INDEX_3D_XZ];
     }
     return rValue;
 }
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_2D_interface_law.cpp:107]: Elsewhere we seem to prefer rVariable i.s.o. rThisVariable.
the VoigtSize can be retrieved through GetStrainSize(), but the specific indices will not permit only having an implementation in the baseclass.

File: applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_2D_plane_strain_law.cpp [hunk 6]
```diff
@@ -89,10 +71,8 @@ Vector& SmallStrainUDSM2DPlaneStrainLaw::GetValue(const Variable<Vector>& rThisV
...
     } else if (rThisVariable == CAUCHY_STRESS_VECTOR) {
-        if (rValue.size() != VoigtSize) rValue.resize(VoigtSize);
-        for (unsigned int i = 0; i < VoigtSize; ++i) {
-            rValue[i] = mStressVectorFinalized[i];
-        }
+        rValue.resize(VoigtSize);
+        std::copy_n(GetSig0().begin(), VoigtSize, rValue.begin());
     }
     return rValue;
 }
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_2D_plane_strain_law.cpp:78]: See earlier comment on rThisVariable and GetStrainSize. For the latter it does not involve specific indices here, so this may be done in the base class. ( which could be out of scope for this PR )

File: applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_3D_interface_law.cpp [hunk 7]
```diff
@@ -30,11 +30,14 @@ ConstitutiveLaw::Pointer SmallStrainUDSM3DInterfaceLaw::Clone() const
...
-    mDeltaStrainVector[INDEX_3D_YZ] = rStrainVector(INDEX_3D_INTERFACE_YZ) - mStrainVectorFinalized[INDEX_3D_YZ];
-    mDeltaStrainVector[INDEX_3D_XZ] = rStrainVector(INDEX_3D_INTERFACE_XZ) - mStrainVectorFinalized[INDEX_3D_XZ];
+    const auto& r_strain_vector = rValues.GetStrainVector();
+
+    mDeltaStrainVector[INDEX_3D_ZZ] =
+        r_strain_vector[INDEX_3D_INTERFACE_ZZ] - mStrainVectorFinalized[INDEX_3D_ZZ];
+    mDeltaStrainVector[INDEX_3D_YZ] =
+        r_strain_vector[INDEX_3D_INTERFACE_YZ] - mStrainVectorFinalized[INDEX_3D_YZ];
+    mDeltaStrainVector[INDEX_3D_XZ] =
+        r_strain_vector[INDEX_3D_INTERFACE_XZ] - mStrainVectorFinalized[INDEX_3D_XZ];
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_3D_interface_law.cpp:40]: most likely the component by component approach can be avoided. mDeltaStrainVector is defined as the difference between the other two vectors.

File: applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_3D_law.cpp [hunk 8]
```diff
@@ -611,13 +630,11 @@ void SmallStrainUDSM3DLaw::CalculateMaterialResponseCauchy(ConstitutiveLaw::Para
...
 {
-    KRATOS_TRY
-    const Vector& r_strain_vector = rValues.GetStrainVector();
+    const auto& r_strain_vector = rValues.GetStrainVector();
 
-    for (unsigned int i = 0; i < mDeltaStrainVector.size(); ++i) {
-        mDeltaStrainVector[i] = r_strain_vector(i) - mStrainVectorFinalized[i];
+    for (unsigned int i = 0; i < GetStrainSize(); ++i) {
+        mDeltaStrainVector[i] = r_strain_vector[i] - mStrainVectorFinalized[i];
     }
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_3D_law.cpp:637]: can this be a vector subtraction i.s.o. a component by component approach?

**Review by WPK4FEM — APPROVED** [review]
Probably my comments about vector i.s.o. component by component operations can be done later to avoid scope creep on this issue. I'm happy that this PR solves potential issues with passing to short allocations to the UDSM.

File: applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_3D_law.hpp [hunk 9]
```diff
@@ -115,6 +115,10 @@ class KRATOS_API(GEO_MECHANICS_APPLICATION) SmallStrainUDSM3DLaw : public Consti
     /// Static definition of the VoigtSize
     static constexpr SizeType VoigtSize = VOIGT_SIZE_3D;
 
+    static constexpr SizeType Sig0Size                  = 20;
+    static constexpr SizeType StressVectorSize          = 6;
+    static constexpr SizeType StrainIncrementVectorSize = 12;
```
Comment (rfaasse) [inline applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_3D_law.hpp:120]: As mentioned in an earlier comment, might be nice to add a comment that these sizes are prescribed by the UDSM interface

**Review by rfaasse — APPROVED** [review]
To me this is good to go. I have a minor suggestion about adding some clarifying comments, but I leave it up to you if you want to do it.

File: applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_3D_law.hpp (hunk 9 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_3D_law.hpp:120]: Thanks for the suggestion. Done.

File: applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_3D_law.cpp (hunk 4 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_3D_law.cpp:34]: Thanks for the suggestion. Done.

File: applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_2D_interface_law.cpp (hunk 2 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_2D_interface_law.cpp:47]: Yes, the Plaxis documentation (see section 16.2 "Implementation of User Defined (UD) soil Models in calculations program") states that `Sig0` must have an array size of 20, where the first six entries are reserved for the effective stress components of the current integration point (regardless of the actual stress state, i.e. plane strain or 3D).

File: applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_3D_law.cpp (hunk 8 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_3D_law.cpp:637]: It uses `std::transform` to perform the subtraction.

File: applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_2D_plane_strain_law.cpp (hunk 6 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_2D_plane_strain_law.cpp:78]: This class has now been removed, so the duplication is no longer there.

File: applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_2D_interface_law.cpp (hunk 5 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_2D_interface_law.cpp:107]: `rThisVariable` has now been replaced by `rVariable` for all UDSM-related constitutive laws. Also `VoigtSize` has been replaced by a call to `GetStrainSize`.

File: applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_3D_interface_law.cpp (hunk 7 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/custom_constitutive/small_strain_udsm_3D_interface_law.cpp:40]: No, unfortunately this is not possible since we only subtract a few noncontiguous elements. If they were contiguous then I'd agree with your suggestion.
