### PR TITLE
Feature fix quality metrics

### LINKED ISSUE #85: failure in the c++ tests
in kratos/sources/model_part_io.cpp:1651:void ModelPartIO::ReadNodalDataBlock(ModelPart&)
   kratos/sources/model_part_io.cpp:1691:void ModelPartIO::ReadNodalDataBlock(ModelPart&)
   kratos/sources/model_part_io.cpp:553:virtual void ModelPartIO::ReadModelPart(ModelPart&)

    TestTetrahedra3D4RegualrityQuiality Failed with message: 
        Error: Method 'RegualrityQuiality' is not yet implemented for Tetrahedra3D4

in kratos/geometries/tetrahedra_3d_4.h:646:double Tetrahedra3D4<TPointType>::RegualrityQuiality() const [with TPointType = Node<3ul>]

    TestTetrahedra3D4VolumeToAverageEdgeLength Failed with message: 
        Error: Check failed becuase geomTriRect->Quality(criteria) = 0.585786 is not near to -1.0 = -1 within the tolerance 1e-06
in kratos/tests/geometries/test_tetrahedra_3d_4.cpp:276:virtual void Testing::TestTetrahedra3D4VolumeToAverageEdgeLength::TestFunction()

    TestTetrahedra3D4VolumeToEdgeLengthQuality Failed with message: 
        Error: Check failed becuase geomTriRect->Quality(criteria) = 0.839947 is not near to -1.0 = -1 within the tolerance 1e-06
in kratos/tests/geometries/test_tetrahedra_3d_4.cpp:261:virtual void Testing::TestTetrahedra3D4VolumeToEdgeLengthQuality::TestFunction()

    TestTetrahedra3D4VolumeToRMSEdgeLength Failed with message: 
        Error: Check failed becuase geomTriRect->Quality(criteria) = 0.839947 is not near to -1.0 = -1 within the tolerance 1e-06
in kratos/tests/geometries/test_tetrahedra_3d_4.cpp:291:virtual void Testing::TestTetrahedra3D4VolumeToRMSEdgeLength::TestFunction()

    TestTetrahedra3D4VolumeToSurfaceAreaQuality Failed with message: 
        Error: Method 'VolumeToSurfaceAreaQuality' is not yet implemented for Tetrahedra3D4

in kratos/geometries/tetrahedra_3d_4.h:660:double Tetrahedra3D4<TPointType>::VolumeToSurfaceAreaQuality() const [with TPointType = Node<3ul>]

### LINKED ISSUE #94: Some quality functions not working properly with non-unitary geometries
Creating this issue to track the bug that @pooyan-dadvand found regarding some quality functions (the ones relating magnitudes with different dimensions) not returning normalized results between 0 and 1.

### PR DESCRIPTION
**Pull request by roigcarlo**
This should fix #94 and fix #85. 

As a resume this PR:
* Corrects the problem with the `VolumeToAverageEdgeLength` quality function for tetrahedras
* Fixed a bug that was causing an error if tests were compiled with clang
* Completed the missing tests
* Extended the tests for tetrahedras so a non-unitary geometry is also tested
* Non implemented functions (regualrity and surface area) are now check that the excpetion is trown rather than the correct value.
* Fixed KRATOS_CHECK_EXCEPTION while being called multiple times inside the same test

### CODE REVIEW

**Comment by loumalouomega** [comment]
NICE WORK

File: kratos/testing/tester.cpp [hunk 1]
```diff
@@ -228,8 +228,7 @@ namespace Kratos
 		{
 			// creating the regex pattern replacing * with ".*"
 
-#if defined(__GNUC__) &&( __GNUC__ < 4 || \
-              (__GNUC__ == 4 && (__GNUC_MINOR__ < 9))) 
+#if __cplusplus <= 199711L
```
Comment (pooyan-dadvand) [inline kratos/testing/tester.cpp]: Is this also visual studio compatible?

File: kratos/tests/geometries/test_geometry.h [hunk 2]
```diff
@@ -28,14 +28,15 @@
 namespace Kratos {
 namespace Testing {
 
+    static std::ofstream out("/dev/null");
```
Comment (pooyan-dadvand) [inline kratos/tests/geometries/test_geometry.h]: Is this windows compatible?

**Review by pooyan-dadvand — COMMENTED** [review]
I think there are some compatibility issues for windows to be checked

File: kratos/testing/tester.cpp (hunk 1 above)
Comment (roigcarlo) [reply kratos/testing/tester.cpp]: There was a problem in VS 2012 with this but since we already use 2015 it should be fine. I will test it again to be sure.

File: kratos/tests/geometries/test_geometry.h (hunk 2 above)
Comment (roigcarlo) [reply kratos/tests/geometries/test_geometry.h]: Probably not. 
As we spoke, maybe I should just remove that ?

File: kratos/testing/tester.cpp (hunk 1 above)
Comment (roigcarlo) [reply kratos/testing/tester.cpp]: Looks like they still define this as 199711L.

The question is, since we now have C+11 as a requisite can't we just compile the regex code as is?

File: kratos/tests/geometries/test_geometry.h (hunk 2 above)
Comment (roigcarlo) [reply kratos/tests/geometries/test_geometry.h]: At the end it was working because `std::cout.rdbuf(out.rdbuf());` was evaluated as `NULL`, which is an accepted buffer which has the same effect as `/dev/null` in linux. As it happens to be what we want im just making `std::cout.rdbuf(nullptr);`

According to [this](http://stackoverflow.com/questions/14845446/how-redirect-stdostream-to-a-file-or-dev-null-in-c-and-linux) it also sets the `std::ios::badbit` which should prevent conversions in the output in case we eventually have any.

File: kratos/testing/tester.cpp (hunk 1 above)
Comment (RiccardoRossi) [reply kratos/testing/tester.cpp]: I think that this particular feature (regex) was still broken on relatively recent gccs, anyway Pooyan will remember more about this

Comment (pooyan-dadvand) [reply kratos/testing/tester.cpp]: Exactly as @RiccardoRossi saying, gcc 4.8 which is one of the popular old one does not support it and for me this function wasn't enough for drop it

File: kratos/tests/geometries/test_geometry.h (hunk 2 above)
Comment (pooyan-dadvand) [reply kratos/tests/geometries/test_geometry.h]: Seems ok, but in long term I would like to know why the same mechanism is not working in the [tester](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/testing/tester.cpp#L259)

**Comment by roigcarlo** [comment]
@pooyan-dadvand I've made some changes since the last time:
* The tester macro should now test the clang case apart
* Fixed the length returning `-nan` from #126. Notice that it uses the norm of the volume so it will be always positive
* I've corrected a problem in the determinants while calculating the circumsphere
* I added an inverted tetrahedra to the tests and extended the tests so it is checked as well, returning negative values in those who use volume as a metric (which was already working btw).

However, none of the quality functions were using the `Length()` method from the geometry, so the problems in #126 may still persist...

File: kratos/geometries/tetrahedra_3d_4.h [hunk 3]
```diff
@@ -506,9 +500,9 @@ template<class TPointType> class Tetrahedra3D4 : public Geometry<TPointType>
       double y30 = rP2[1] - rP3[1];
       double z30 = rP2[2] - rP3[2];
 
-      double detJMX = s10 * y20 * z30 + y10 * z20 * s30 + z10 * s20 * y30 - s30 * y20 * z30 - y30 * z20 * s10 - z30 * s20 * y10;
-      double detJMY = s10 * x20 * z30 + x10 * z20 * s30 + z10 * s20 * x30 - s30 * x20 * z30 - x30 * z20 * s10 - z30 * s20 * x10;
-      double detJMZ = s10 * x20 * y30 + x10 * y20 * s30 + y10 * s20 * x30 - s30 * x20 * y30 - x30 * y20 * s10 - y30 * s20 * x10;
+      double detJMX = s10 * y20 * z30 + y10 * z20 * s30 + z10 * s20 * y30 - s30 * y20 * z10 - y30 * z20 * s10 - z30 * s20 * y10;
```
Comment (pooyan-dadvand) [inline kratos/geometries/tetrahedra_3d_4.h:503]: I should not change this! The volume results to be correct after my issue. Why you want to change it?

**Review by pooyan-dadvand — CHANGES_REQUESTED** [review]
I would not let change the Volume method unless you have a very strong reason because it will break a lot of code.

File: kratos/geometries/tetrahedra_3d_4.h (hunk 3 above)
Comment (roigcarlo) [reply kratos/geometries/tetrahedra_3d_4.h:503]: This is not the volume function. This calculates the circumradius of the tetrahedron for the quality function that need them. It had an error in one of the components of a diagonal that calculates another determinant. See ac707a565561248d556e0121634d586fe669350b. 

But I can rewrite the whole matrix so it looks like the volume if you want.

**Comment by roigcarlo** [comment]
Can we merge?

File: kratos/geometries/tetrahedra_3d_4.h (hunk 3 above)
Comment (pooyan-dadvand) [reply kratos/geometries/tetrahedra_3d_4.h:503]: Now I see. So I aree with changes.

**Review by pooyan-dadvand — APPROVED** [review]
