### PR TITLE
Fix local point coordinate

### LINKED ISSUE #987: method PointLocalCoordinates of base geometry fails in 2D
as can be seen in 
https://github.com/KratosMultiphysics/Kratos/blame/master/kratos/geometries/geometry.h#L880

the method fails for a type mismatch in 2D.

@roigcarlo @iiaconeta, @RiccardoRossi tells that he thinks that you corrected this locally. Can u verify?

### PR DESCRIPTION
**Pull request by roigcarlo**
This fixes #987

This is an incomplete PR and needs:
- [ ] Add checks to the tests

In general the code is fixed and it does not break for 2D anymore. Also corrected an error that was making recursive stack trace if the base geometry chrased.

Honestly I don't understand what the code does so I cannot check if the results are correct or not. But I would expect that the quadrilateral defined by the points: `(0,0)(1,0)(0,1)(1,1)` and the global coordinate `(1,1)` would result into `(1,1)` as local coordinates. But the result is `(0.833333 0.818182)`. At least I would expect both coordinates to be the same...

If this is Ok, or someone gives me an example with the expected results I'll finish the missing checks and we can merge.

### CODE REVIEW

File: kratos/geometries/geometry.h [hunk 1]
```diff
@@ -901,29 +906,38 @@ class Geometry : public PointerVector<TPointType>
...
+                    break;
+                }
             }
+        }
 
-//            if ( MathUtils<double>::Norm3( DeltaXi ) < tol )
-            if ( norm_2( DeltaXi ) < tol )
-            {
-                break;
+        if(LocalSpaceDimension() == 3) {
```
Comment (loumalouomega) [inline kratos/geometries/geometry.h]: else if?

**Comment by pooyan-dadvand** [comment]
@roigcarlo you should create the Quadrilateral with [ordered](http://www-opale.inrialpes.fr/Aerochina/info/en/html-version/gid_11.html#SEC187) points. In your case the points are creating an hourglass shape....

**Comment by roigcarlo** [comment]
Ups, thx @pooyan-dadvand!

**Comment by roigcarlo** [comment]
```C++
GeneratePoint<TPointType>( 0.0, 0.0, 0.0),
GeneratePoint<TPointType>( 1.0, 0.0, 0.0),
GeneratePoint<TPointType>( 1.1, 1.1, 0.0),
GeneratePoint<TPointType>( 0.0, 1.1, 0.0)
```

Shouldn't this be a normal quadrialteral¿?

**Comment by roigcarlo** [comment]
Found the error.  Code works good and the results are correct. The probem is thatr coordinates for the cube are not `1` but `1.1`. Since it does not affect the existing tests I am gonna change the coords so the tests can be understood more easily

File: kratos/geometries/geometry.h [hunk 2]
```diff
@@ -901,29 +906,38 @@ class Geometry : public PointerVector<TPointType>
...
-            if ( norm_2( DeltaXi ) > 30 )
-            {
-                break;
+        if(LocalSpaceDimension() == 2) {
+            for ( unsigned int k = 0; k < maxiter; k++ ) {
+                CurrentGlobalCoords = ZeroVector( 3 );
+                GlobalCoordinates( CurrentGlobalCoords, rResult );
+                noalias( CurrentGlobalCoords ) = rPoint - CurrentGlobalCoords;
+                InverseOfJacobian( J, rResult );
+                DeltaXi[0] = J(0,0) * CurrentGlobalCoords(0) + J(0,1) * CurrentGlobalCoords(1);
```
Comment (RiccardoRossi) [inline kratos/geometries/geometry.h]: now this only works in 2D but not in 3D... 

i would do this as

    DeltaXi.clear();
     for(unsigned int i=0; i<WorkingSpaceDimension(); ++i
           for(unsigned int j=0; k<WorkingSpaceDimension(); ++j)
                DeltaXi[i] += J(i,j)*CurrentGlobalCoords[j];

**Review by RiccardoRossi — CHANGES_REQUESTED** [review]

File: kratos/geometries/geometry.h (hunk 2 above)
Comment (roigcarlo) [reply kratos/geometries/geometry.h]: It does work in 3d because doesn't use that code, I just separated the cases. I assume the prod from boost had some kind of in-built optimization for matrices and I didn't wanted to touch it. If is not the case I can implement what you said.

**Comment by roigcarlo** [comment]
@RiccardoRossi Implemented your suggestions

**Comment by roigcarlo** [comment]
Ping someone?

**Review by RiccardoRossi — APPROVED** [review]
