### PR TITLE
[GeoMechanicsApplication] Fixed the bug related to shape-function-gradients for thermal line el…

### LINKED ISSUE #12344: [GeoMechanicsApplication] Fix bug in calculation of shape-function-gradients in thermal element.
### Description

There is a bug detected in the calculation of shape function gradients for line thermal element. The shape fuction gradient is calculated based on the local coordinates. Later it has to be multiplied by the inverse of the Jacobian in order to be projected to the global coordinates. However, a such multiplication is missing.

### PR DESCRIPTION
**Pull request by mnabideltares**
📝 Description
There is a bug detected in the calculation of shape function gradients for line thermal element. The shape fuction gradient is calculated based on the local coordinates. Later it has to be multiplied by the inverse of the Jacobian in order to be projected to the global coordinates. However, a such multiplication is missing.

🆕 Changelog

Added a statement to divide the shape-function-gradients to the determinant of Jacobian. In 1D, this is equvalent to multiplication with inverse Jacobian

### CODE REVIEW

File: applications/GeoMechanicsApplication/custom_elements/transient_thermal_element.h [hunk 1]
```diff
@@ -74,6 +74,8 @@ class KRATOS_API(GEO_MECHANICS_APPLICATION) TransientThermalElement : public Ele
         if (GetGeometry().LocalSpaceDimension() == 1) {
             GetGeometry().DeterminantOfJacobian(det_J_container, this->GetIntegrationMethod());
             dN_dX_container = GetGeometry().ShapeFunctionsLocalGradients(this->GetIntegrationMethod());
+            std::transform(dN_dX_container.begin(), dN_dX_container.end(), det_J_container.begin(),
```
Comment (rfaasse) [inline applications/GeoMechanicsApplication/custom_elements/transient_thermal_element.h:80]: Is there a way to test this bug without having point fluxes? If not, I'm okay to only have the tests in that PR.

**Review by rfaasse — COMMENTED** [review]
Thanks for splitting this out of the other PR, a very easy to review PR like this! I was just wondering if we can illustrate this bug already without point source flux, but I don't have any other comments, so if that's unnecessarily hard to do without the other PR, this is good to go from my point of view

File: applications/GeoMechanicsApplication/custom_elements/transient_thermal_element.h (hunk 1 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_elements/transient_thermal_element.h:80]: @rfaasse Thank you for the review.
I used to test it without flux, but it was converging to correct steady state. It seems the cases with Dirichlet conditions were not affected much. This problem appeared when added test cases with flux.
There is maybe possible to follow the unsteady path. But as we don't have an accurate unsteady development, a such test may or may not give an accurate indication.

**Review by WPK4FEM — COMMENTED** [review]
Dear Mohammed,
After spending some effort on rewriting the if else structure for the computation of the dN_dX container, the result of that is not better than what you have shown here.
After consulting with Anne and Richard we would appreciate if you ad a comment before line 74 e.g.
// ShapeFunctionsIntegrationsPointsGradients does not allow for the line element in 2D/3D configuration and will produce errors. To circumvent this, the dN_dX_container is separately computed with correct dimensions for the line element.
Regards, Wijtze Pieter

**Review by WPK4FEM — APPROVED** [review]
Thank you.
