### PR TITLE
[Hdf5] Fix windows compilation

### LINKED ISSUE #14089: [HDF5Application] HDF5Application compilation in Windows with Master branch
**Description**
The compilation of HDF5Application fails when building on Windows 11. The issue appears to be an ambiguous call to DataCommunicator::SumAll and a type conversion error involving std::vector in the HDF5 custom IO files.

**Scope**
- Compilation
- HDF5Application

**To Reproduce**
1. First, I succesfully compiled the HDF5 library using the script below. I am using version 1.12.2, (I got the source from https://hdf-wordpress-1.s3.amazonaws.com/wp-content/uploads/manual/HDF5/HDF5_1_12_2/source/hdf5-1.12.2.zip) since it is the one used in for the docker file here https://github.com/KratosMultiphysics/Kratos/blob/master/scripts/docker_files/docker_file_wheelbuilder_windows/Dockerfile#L139-L143

```batch
@echo off
SET SOURCE_PATH=D:\hdf5\source\hdf5-1.12.2
SET BUILD_PATH=D:\hdf5\build
SET INSTALL_PATH=D:\hdf5\bin
SET CMAKE_EXE="C:\Program Files\CMake\bin\cmake.exe"

echo Starting HDF5 Configuration...
%CMAKE_EXE% -S %SOURCE_PATH% -B %BUILD_PATH% ^
            -DCMAKE_INSTALL_PREFIX=%INSTALL_PATH% ^
            -DBUILD_TESTING=OFF ^
            -DBUILD_SHARED_LIBS=ON
if %ERRORLEVEL% NEQ 0 (
    echo Configuration failed!
    pause
    exit /b %ERRORLEVEL%
)

echo.
echo Starting HDF5 Build and Install...
%CMAKE_EXE% --build %BUILD_PATH% --target install -- /property:configuration=Release

if %ERRORLEVEL% EQU 0 (
    echo.
    echo ========================================
    echo SUCCESS: HDF5 installed to %INSTALL_PATH%
    echo ========================================
) else (
    echo Build failed!
)

pause
```

2.  Then, I added the HDF5 path to my Kratos configure script as shown:

```batch
@echo off
rem Please do not modify this script

rem For any question please contact with us in:
rem  - https://github.com/KratosMultiphysics/Kratos

rem Optional parameters:
rem You can find a list will all the compiation options in INSTALL.md or here:
rem  - https://github.com/KratosMultiphysics/Kratos/wiki/Compilation-options

rem Set compiler
set CC=cl.exe
set CXX=cl.exe

rem Set variables
if not defined KRATOS_SOURCE set KRATOS_SOURCE=%~dp0..
if not defined KRATOS_BUILD set KRATOS_BUILD=%KRATOS_SOURCE%/build

rem Warning: In windows this option only works if you run through a terminal with admin privileges
rem set KRATOS_INSTALL_PYTHON_USING_LINKS=ON

rem Set basic configuration
if not defined KRATOS_BUILD_TYPE set KRATOS_BUILD_TYPE=Release
if not defined BOOST_ROOT set BOOST_ROOT=D:\Boost
if not defined PYTHON_EXECUTABLE set PYTHON_EXECUTABLE=C:\Program Files\Python310\python.exe



rem Set applications to compile
set KRATOS_APP_DIR=applications
set KRATOS_APPLICATIONS=
CALL :add_app %KRATOS_APP_DIR%\LinearSolversApplication;
CALL :add_app %KRATOS_APP_DIR%\FluidDynamicsApplication;
CALL :add_app %KRATOS_APP_DIR%\RomApplication;
CALL :add_app %KRATOS_APP_DIR%\ConvectionDiffusionApplication;
CALL :add_app %KRATOS_APP_DIR%\HDF5Application;

rem Clean
del /F /Q "%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%\cmake_install.cmake"
del /F /Q "%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%\CMakeCache.txt"
del /F /Q "%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%\CMakeFiles"

rem Enable this if your build is slow and you have a multi-core machine
rem set KRATOS_PARALLEL_BUILD_FLAG=/MP4

rem Configure
@echo on
cmake -G"Visual Studio 16 2019" -H"%KRATOS_SOURCE%" -B"%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%"          ^
-DCMAKE_CXX_FLAGS=" %KRATOS_PARALLEL_BUILD_FLAG% "                                                  ^
-DCMAKE_POLICY_VERSION_MINIMUM=3.5                                                                  ^
-DUSE_EIGEN_MKL=OFF                                                                                 ^
-DHDF5_ROOT="D:\hdf5\bin"                                                                           ^
-DKRATOS_GENERATE_PYTHON_STUBS=ON

rem Build
cmake --build "%KRATOS_BUILD%/%KRATOS_BUILD_TYPE%" --target install -- /property:configuration=%KRATOS_BUILD_TYPE% /p:Platform=x64
goto:eof

rem Function to add apps
:add_app
set KRATOS_APPLICATIONS=%KRATOS_APPLICATIONS%%1;
goto:eof

pause
```

3. The build fails during the compilation of KratosHDF5Core with the following log

```log
Windows PowerShell
Copyright (C) Microsoft Corporation. Todos los derechos reservados.

Instale la versión más reciente de PowerShell para obtener nuevas características y mejoras. https://aka.ms/PSWindows

PS D:\Kratos\scripts> .\configure.bat

D:\Kratos\scripts>cmake -G"Visual Studio 16 2019" -H"D:\Kratos\scripts\.." -B"D:\Kratos\scripts\../build\Release"          -DCMAKE_CXX_FLAGS="  "                                                  -DCMAKE_POLICY_VERSION_MINIMUM=3.5                                                                  -DUSE_EIGEN_MKL=OFF                                                                                 -DHDF5_ROOT="D:\hdf5\bin"                                                                           -DKRATOS_GENERATE_PYTHON_STUBS=ON
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.26200.
-- The C compiler identification is MSVC 19.29.30159.0
-- The CXX compiler identification is MSVC 19.29.30159.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No KRATOS_SOURCE_DIR is defined, using: D:/Kratos
-- No KRATOS_BINARY_DIR is defined, using: D:/Kratos/build/Release
-- No KRATOS_INSTALL_PYTHON_USING_LINKS is defined, setting to OFF
-- No CMAKE_INSTALL_MESSAGE is defined. Setting to NEVER
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.52.0.windows.1")
-- CMAKE_SYSTEM_NAME = Windows
-- CMAKE_CXX_COMPILER_ID = MSVC
-- CMAKE_CXX_FLAGS =
-- CMAKE_C_FLAGS = /DWIN32 /D_WINDOWS
-- Detected compiler as MSVC
CMake Deprecation Warning at build/Release/_deps/googletest-src/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.


CMake Deprecation Warning at build/Release/_deps/googletest-src/googlemock/CMakeLists.txt:39 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.


CMake Deprecation Warning at build/Release/_deps/googletest-src/googletest/CMakeLists.txt:49 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.


-- Found Python: C:/Program Files/Python310/python.exe (found version "3.10.11") found components: Interpreter
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
CMake Deprecation Warning at cmake_modules/pybind11Tools.cmake:8 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.
Call Stack (most recent call first):
  CMakeLists.txt:407 (include)


-- Found PythonInterp: C:\Program Files\Python310\python.exe (found suitable version "3.10.11", minimum required is "3.6")
-- Found PythonLibs: C:/Program Files/Python310/libs/python310.lib
-- LTO is Disabled
-- AR VERSION: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/lib.exe
-- Python version used for the interface will be 3.10
-- Standard install dir D:/Kratos/bin/Release
-- "KRATOS_SHARED_MEMORY_PARALLELIZATION" not defined, defaulting to "OpenMP"
-- Found OpenMP_C: -openmp (found version "2.0")
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Found OpenMP: TRUE (found version "2.0")
-- Using OpenMP for shared memory parallelization
-- Found Boost: D:/Boost/lib/cmake/Boost-1.89.0/BoostConfig.cmake (found version "1.89.0")
-- Boost include directory found with find_package
-- Boost library deduced from root directory
-- Boost include directory: D:/Boost/include/boost-1_89
-- Boost library directory: D:\Boost/lib
-- Could NOT find ZLIB (missing: ZLIB_INCLUDE_DIR)
-- Preparing local ZLIB compilation.
CMake Deprecation Warning at external_libraries/zlib/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.


-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - failed
-- Looking for fseeko
-- Looking for fseeko - not found
-- Looking for unistd.h
-- Looking for unistd.h - not found

-- CMAKE_BUILD_TYPE ........ Release

-- Found ZLIB by find_package():
-- * Configuring gidpost library
-- Configuring applications (ENV):
        Adding application 'applications\LinearSolversApplication'
**** configuring KratosLinearSolversApplication ****
CMake Deprecation Warning at cmake_modules/pybind11Tools.cmake:8 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.
Call Stack (most recent call first):
  applications/LinearSolversApplication/CMakeLists.txt:28 (include)


        Adding application 'applications\FluidDynamicsApplication'
**** configuring KratosFluidDynamicsApplication ****
        Adding application 'applications\RomApplication'
**** configuring KratosRomApplication ****
CMake Deprecation Warning at cmake_modules/pybind11Tools.cmake:8 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.
Call Stack (most recent call first):
  applications/RomApplication/CMakeLists.txt:6 (include)


        Adding application 'applications\ConvectionDiffusionApplication'
**** configuring KratosConvectionDiffusionApplication ****
        Adding application 'applications\HDF5Application'
**** configuring KratosHDF5Application ****
-- Searching for serial HDF5 libraries.
-- Found HDF5: hdf5-shared (found version "1.12.2") found components: C
-- Using serial HDF5 libraries.

***********************************************************************

        LIST OF APPLICATIONS THAT ARE GOING TO BE COMPILED:

        LinearSolversApplication
        FluidDynamicsApplication
        RomApplication
        ConvectionDiffusionApplication
        HDF5Application

        APPLICATIONS ADDED TO COMPILATION THROUGH DEPENDENCIES:


***********************************************************************


List of upcoming API-breaking and behavior changes:
         Behavior change of Testing. Please ensure you use KRATOS_EXPECT for testing instead of KRATOS_CHECK
         Removal of misused EXTENDED_GAUSS integration rules and unification across geometries: https://github.com/KratosMultiphysics/Kratos/pull/13444
-- clipper : D:/Kratos/external_libraries/clipper
-- tinyexpr : D:/Kratos/external_libraries/tinyexpr/tinyexpr/
-- Configuring done (15.1s)
CMake Error in applications/HDF5Application/CMakeLists.txt:
  IMPORTED_IMPLIB not set for imported target "hdf5-shared" configuration
  "FullDebug".


CMake Error in applications/HDF5Application/CMakeLists.txt:
  IMPORTED_IMPLIB not set for imported target "hdf5-shared" configuration
  "FullDebug".


CMake Error in applications/HDF5Application/CMakeLists.txt:
  IMPORTED_LOCATION or IMPORTED_IMPLIB not set for imported target
  "hdf5-shared" configuration "FullDebug".


CMake Error in applications/HDF5Application/CMakeLists.txt:
  IMPORTED_IMPLIB not set for imported target "hdf5-shared" configuration
  "FullDebug".


-- Generating done (0.5s)
CMake Generate step failed.  Build files cannot be regenerated correctly.

D:\Kratos\scripts>rem Build

D:\Kratos\scripts>cmake --build "D:\Kratos\scripts\../build/Release" --target install -- /property:configuration=Release /p:Platform=x64
Microsoft (R) Build Engine versión 16.11.6+a918ceb31 para .NET Framework
Copyright (C) Microsoft Corporation. Todos los derechos reservados.

  KratosVersion.vcxproj -> D:\Kratos\build\Release\kratos\KratosVersion.dir\Release\KratosVersion.lib
  clipper.vcxproj -> D:\Kratos\build\Release\external_libraries\clipper\Release\clipper.lib
  zlib.vcxproj -> D:\Kratos\build\Release\external_libraries\zlib\Release\zlib.dll
  gidpost.vcxproj -> D:\Kratos\build\Release\external_libraries\gidpost\source\Release\gidpost.lib
  tinyexpr.vcxproj -> D:\Kratos\build\Release\external_libraries\tinyexpr\Release\tinyexpr.lib
  KratosCore.vcxproj -> D:\Kratos\build\Release\kratos\Release\KratosCore.dll
  Kratos.vcxproj -> D:\Kratos\build\Release\kratos\Release\Kratos.cp310-win_amd64.pyd
  KratosConvectionDiffusionCore.vcxproj -> D:\Kratos\build\Release\applications\ConvectionDiffusionApplication\Release\KratosConvectionDiffusionCore.dll
  KratosConvectionDiffusionApplication.vcxproj -> D:\Kratos\build\Release\applications\ConvectionDiffusionApplication\Release\KratosConvectionDiffusionApplication.pyd
  KratosFluidDynamicsCore.vcxproj -> D:\Kratos\build\Release\applications\FluidDynamicsApplication\Release\KratosFluidDynamicsCore.dll
  KratosFluidDynamicsApplication.vcxproj -> D:\Kratos\build\Release\applications\FluidDynamicsApplication\Release\KratosFluidDynamicsApplication.pyd
  hdf5_connectivities_data.cpp
D:\Kratos\applications\HDF5Application\custom_io\hdf5_connectivities_data.cpp(112,1): error C2668: 'Kratos::DataCommunicator::SumAll': llamada ambigua a una función sobrecargada [D:\Kratos\build\Release\appli
cations\HDF5Application\KratosHDF5Core.vcxproj]
D:\Kratos\kratos\includes/data_communicator.h(394,5): message : puede ser 'double Kratos::DataCommunicator::SumAll(const double &) const' [D:\Kratos\build\Release\applications\HDF5Application\KratosHDF5Core.v
cxproj]
D:\Kratos\kratos\includes/data_communicator.h(393,5): message : o       'unsigned long Kratos::DataCommunicator::SumAll(const unsigned long &) const' [D:\Kratos\build\Release\applications\HDF5Application\Krat
osHDF5Core.vcxproj]
D:\Kratos\kratos\includes/data_communicator.h(392,5): message : o       'unsigned int Kratos::DataCommunicator::SumAll(const unsigned int &) const' [D:\Kratos\build\Release\applications\HDF5Application\Kratos
HDF5Core.vcxproj]
D:\Kratos\kratos\includes/data_communicator.h(391,5): message : o       'int Kratos::DataCommunicator::SumAll(const int &) const' [D:\Kratos\build\Release\applications\HDF5Application\KratosHDF5Core.vcxproj]
D:\Kratos\kratos\includes/data_communicator.h(390,5): message : o       'char Kratos::DataCommunicator::SumAll(const char &) const' [D:\Kratos\build\Release\applications\HDF5Application\KratosHDF5Core.vcxproj
]
D:\Kratos\applications\HDF5Application\custom_io\hdf5_connectivities_data.cpp(112,1): message : al hacer coincidir la lista de argumentos '(unsigned __int64)' [D:\Kratos\build\Release\applications\HDF5Applica
tion\KratosHDF5Core.vcxproj]
D:\Kratos\applications\HDF5Application\custom_io\hdf5_connectivities_data.cpp(109): message : al compilar la función del miembro clase plantilla "void Kratos::HDF5::Internals::ConnectivitiesData<Kratos::Model
Part::ConditionsContainerType>::Write(const TContainerType &,const bool)" [D:\Kratos\build\Release\applications\HDF5Application\KratosHDF5Core.vcxproj]
          with
          [
              TContainerType=Kratos::ModelPart::ConditionsContainerType
          ]
D:\Kratos\applications\HDF5Application\custom_io\hdf5_connectivities_data.cpp(210): message : Vea la referencia a la creación de una instancia de clase plantilla "Kratos::HDF5::Internals::ConnectivitiesData<K
ratos::ModelPart::ConditionsContainerType>" que se está compilando [D:\Kratos\build\Release\applications\HDF5Application\KratosHDF5Core.vcxproj]
  hdf5_container_component_io.cpp
D:\Kratos\applications\HDF5Application\custom_io\hdf5_container_component_io.cpp(267,88): error C2664: 'char Kratos::DataCommunicator::SumAll(const char &) const': el argumento 1 no puede convertirse de 'std:
:vector<Kratos::VariablesList::IndexType,std::allocator<T>>' a 'const char &' [D:\Kratos\build\Release\applications\HDF5Application\KratosHDF5Core.vcxproj]
          with
          [
              T=size_t
          ]
D:\Kratos\applications\HDF5Application\custom_io\hdf5_container_component_io.cpp(235,1): message : Razón: no se puede realizar la conversión de 'std::vector<Kratos::VariablesList::IndexType,std::allocator<T>>
' a 'const char' [D:\Kratos\build\Release\applications\HDF5Application\KratosHDF5Core.vcxproj]
          with
          [
              T=size_t
          ]
D:\Kratos\applications\HDF5Application\custom_io\hdf5_container_component_io.cpp(267,118): message : No hay disponible ningún operador de conversión definido por el usuario que pueda realizar esta conversión,
 o bien no se puede llamar al operador [D:\Kratos\build\Release\applications\HDF5Application\KratosHDF5Core.vcxproj]
D:\Kratos\kratos\includes/data_communicator.h(390,5): message : vea la declaración de 'Kratos::DataCommunicator::SumAll' [D:\Kratos\build\Release\applications\HDF5Application\KratosHDF5Core.vcxproj]
D:\Kratos\applications\HDF5Application\custom_io\hdf5_container_component_io.cpp(194): message : Vea la referencia a la creación de una instancia de la función plantilla "bool Kratos::HDF5::ContainerComponent
IO<Kratos::ModelPart::PropertiesContainerType,Kratos::HDF5::Internals::NonHistoricalIO,Kratos::Variable<int>,Kratos::Variable<double>,Kratos::Variable<Kratos::array_1d<double,3>>,Kratos::Variable<Kratos::arra
y_1d<double,4>>,Kratos::Variable<Kratos::array_1d<double,6>>,Kratos::Variable<Kratos::array_1d<double,9>>,Kratos::Variable<Kratos::Vector>,Kratos::Variable<Kratos::Matrix>>::WriteComponents<Kratos::Variable<i
nt>>(const std::string &,const TContainerDataIO &,const TContainerType &,Kratos::Parameters,Kratos::HDF5::WriteInfo &)" que se está compilando [D:\Kratos\build\Release\applications\HDF5Application\KratosHDF5C
ore.vcxproj]
          with
          [
              TContainerDataIO=Kratos::HDF5::Internals::NonHistoricalIO,
              TContainerType=Kratos::ModelPart::PropertiesContainerType
          ]
D:\Kratos\applications\HDF5Application\custom_io\hdf5_container_component_io.cpp(184): message : Vea la referencia a la creación de una instancia de la función plantilla "bool Kratos::HDF5::ContainerComponent
IO<Kratos::ModelPart::PropertiesContainerType,Kratos::HDF5::Internals::NonHistoricalIO,Kratos::Variable<int>,Kratos::Variable<double>,Kratos::Variable<Kratos::array_1d<double,3>>,Kratos::Variable<Kratos::arra
y_1d<double,4>>,Kratos::Variable<Kratos::array_1d<double,6>>,Kratos::Variable<Kratos::array_1d<double,9>>,Kratos::Variable<Kratos::Vector>,Kratos::Variable<Kratos::Matrix>>::WriteComponents<Kratos::Variable<i
nt>>(const std::string &,const TContainerDataIO &,const TContainerType &,Kratos::Parameters,Kratos::HDF5::WriteInfo &)" que se está compilando [D:\Kratos\build\Release\applications\HDF5Application\KratosHDF5C
ore.vcxproj]
          with
          [
              TContainerDataIO=Kratos::HDF5::Internals::NonHistoricalIO,
              TContainerType=Kratos::ModelPart::PropertiesContainerType
          ]
D:\Kratos\applications\HDF5Application\custom_io\hdf5_container_component_io.cpp(173): message : al compilar la función del miembro clase plantilla "void Kratos::HDF5::ContainerComponentIO<Kratos::ModelPart::
PropertiesContainerType,Kratos::HDF5::Internals::NonHistoricalIO,Kratos::Variable<int>,Kratos::Variable<double>,Kratos::Variable<Kratos::array_1d<double,3>>,Kratos::Variable<Kratos::array_1d<double,4>>,Kratos
::Variable<Kratos::array_1d<double,6>>,Kratos::Variable<Kratos::array_1d<double,9>>,Kratos::Variable<Kratos::Vector>,Kratos::Variable<Kratos::Matrix>>::Write(const TContainerType &,const TContainerIO &,const
Kratos::Parameters)" [D:\Kratos\build\Release\applications\HDF5Application\KratosHDF5Core.vcxproj]
          with
          [
              TContainerType=Kratos::ModelPart::PropertiesContainerType,
              TContainerIO=Kratos::HDF5::Internals::NonHistoricalIO
          ]
D:\Kratos\applications\HDF5Application\custom_io\hdf5_container_component_io.cpp(487): message : Vea la referencia a la creación de una instancia de clase plantilla "Kratos::HDF5::ContainerComponentIO<Kratos:
:ModelPart::PropertiesContainerType,Kratos::HDF5::Internals::NonHistoricalIO,Kratos::Variable<int>,Kratos::Variable<double>,Kratos::Variable<Kratos::array_1d<double,3>>,Kratos::Variable<Kratos::array_1d<doubl
e,4>>,Kratos::Variable<Kratos::array_1d<double,6>>,Kratos::Variable<Kratos::array_1d<double,9>>,Kratos::Variable<Kratos::Vector>,Kratos::Variable<Kratos::Matrix>>" que se está compilando [D:\Kratos\build\Rele
ase\applications\HDF5Application\KratosHDF5Core.vcxproj]
D:\Kratos\applications\HDF5Application\custom_io\hdf5_container_component_io.cpp(267,57): error C2530: 'availability_global_counts_pair': se deben inicializar las referencias [D:\Kratos\build\Release\applicat
ions\HDF5Application\KratosHDF5Core.vcxproj]
D:\Kratos\applications\HDF5Application\custom_io\hdf5_container_component_io.cpp(235,1): error C3536: 'availability_global_counts_pair': no se puede usar antes de inicializarse [D:\Kratos\build\Release\applic
ations\HDF5Application\KratosHDF5Core.vcxproj]
D:\Kratos\applications\HDF5Application\custom_io\hdf5_container_component_io.cpp(235,1): error C2109: el subíndice requiere una matriz o tipo de puntero [D:\Kratos\build\Release\applications\HDF5Application\K
ratosHDF5Core.vcxproj]
  Generando código...
  KratosLinearSolversCore.vcxproj -> D:\Kratos\build\Release\applications\LinearSolversApplication\Release\KratosLinearSolversCore.pyd
  KratosLinearSolversApplication.vcxproj -> D:\Kratos\build\Release\applications\LinearSolversApplication\Release\KratosLinearSolversApplication.pyd
  KratosRomCore.vcxproj -> D:\Kratos\build\Release\applications\RomApplication\Release\KratosRomCore.dll
  KratosRomApplication.vcxproj -> D:\Kratos\build\Release\applications\RomApplication\Release\KratosRomApplication.pyd

D:\Kratos\scripts>goto:eof
```

**Environment**
- HDF5 Version: 1.12.2
- Branch: master
- Python 3.10.11
- OS: Windows 11 Pro (10.0.26200) 64-bit
- CPU: AMD Ryzen 9 8945HS
- Visual Studio 2019

### PR DESCRIPTION
**Pull request by roigcarlo**
**📝 Description**
@Rbravo555  this Fixes #14089 (or should, can't test exaustively). If you can try it and give feedback I'd appreaciate.

@sunethwarna There is big change in hdf5_points_data. I've merged the source and header in one file. I am afraid that there is no other solution for this class in particular, because `VertexContainerCoordinateIO` is derived from `PointsData<VertexIO>` which causes the later to be partialy defined until the compiler sees the definition of `PointsData<VertexIO>`, which triggers the error and the explicit instantiation cannot be moved before the definition of `VertexContainer` because its base class needs to come before...

Rest of the problems were most warnings because stf::vector<bool> especializations which causes functions not being able to resolve overloads correctly.

### CODE REVIEW

**Comment by Rbravo555** [comment]
I'm compiling this branch, will let you know

**Comment by Rbravo555** [comment]
I am getting an `LNK2019: unresolved external symbol "public: std::string Kratos::Parameters::Get<std::string>` error, 

<details>

<summary> Here's the log: </summary>

```log
Windows PowerShell
Copyright (C) Microsoft Corporation. Todos los derechos reservados.

Instale la versión más reciente de PowerShell para obtener nuevas características y mejoras. https://aka.ms/PSWindows

PS D:\Kratos\scripts> git status
On branch hdf5/fix-win
Your branch is up to date with 'origin/hdf5/fix-win'.

nothing to commit, working tree clean
PS D:\Kratos\scripts> .\configure.bat

D:\Kratos\scripts>cmake -G"Visual Studio 16 2019" -H"D:\Kratos\scripts\.." -B"D:\Kratos\scripts\../build\Release"          -DCMAKE_CXX_FLAGS="  "                                                  -DCMAKE_POLICY_VERSION_MINIMUM=3.5                                                                  -DUSE_EIGEN_MKL=OFF                                                                                 -DHDF5_ROOT="D:\hdf5\bin"                                                                           -DKRATOS_GENERATE_PYTHON_STUBS=ON
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.26200.
-- The C compiler identification is MSVC 19.29.30159.0
-- The CXX compiler identification is MSVC 19.29.30159.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No KRATOS_SOURCE_DIR is defined, using: D:/Kratos
-- No KRATOS_BINARY_DIR is defined, using: D:/Kratos/build/Release
-- No KRATOS_INSTALL_PYTHON_USING_LINKS is defined, setting to OFF
-- No CMAKE_INSTALL_MESSAGE is defined. Setting to NEVER
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.52.0.windows.1")
-- CMAKE_SYSTEM_NAME = Windows
-- CMAKE_CXX_COMPILER_ID = MSVC
-- CMAKE_CXX_FLAGS =
-- CMAKE_C_FLAGS = /DWIN32 /D_WINDOWS
-- Detected compiler as MSVC
CMake Deprecation Warning at build/Release/_deps/googletest-src/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.


CMake Deprecation Warning at build/Release/_deps/googletest-src/googlemock/CMakeLists.txt:39 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.


CMake Deprecation Warning at build/Release/_deps/googletest-src/googletest/CMakeLists.txt:49 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.


-- Found Python: C:/Program Files/Python310/python.exe (found version "3.10.11") found components: Interpreter
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
CMake Deprecation Warning at cmake_modules/pybind11Tools.cmake:8 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.
Call Stack (most recent call first):
  CMakeLists.txt:407 (include)


-- Found PythonInterp: C:\Program Files\Python310\python.exe (found suitable version "3.10.11", minimum required is "3.6")
-- Found PythonLibs: C:/Program Files/Python310/libs/python310.lib
-- LTO is Disabled
-- AR VERSION: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/lib.exe
-- Python version used for the interface will be 3.10
-- Standard install dir D:/Kratos/bin/Release
-- "KRATOS_SHARED_MEMORY_PARALLELIZATION" not defined, defaulting to "OpenMP"
-- Found OpenMP_C: -openmp (found version "2.0")
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Found OpenMP: TRUE (found version "2.0")
-- Using OpenMP for shared memory parallelization
-- Found Boost: D:/Boost/lib/cmake/Boost-1.89.0/BoostConfig.cmake (found version "1.89.0")
-- Boost include directory found with find_package
-- Boost library deduced from root directory
-- Boost include directory: D:/Boost/include/boost-1_89
-- Boost library directory: D:\Boost/lib
-- Could NOT find ZLIB (missing: ZLIB_INCLUDE_DIR)
-- Preparing local ZLIB compilation.
CMake Deprecation Warning at external_libraries/zlib/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.


-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - failed
-- Looking for fseeko
-- Looking for fseeko - not found
-- Looking for unistd.h
-- Looking for unistd.h - not found

-- CMAKE_BUILD_TYPE ........ Release

-- Found ZLIB by find_package():
-- * Configuring gidpost library
-- Configuring applications (ENV):
        Adding application 'applications\LinearSolversApplication'
**** configuring KratosLinearSolversApplication ****
CMake Deprecation Warning at cmake_modules/pybind11Tools.cmake:8 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.
Call Stack (most recent call first):
  applications/LinearSolversApplication/CMakeLists.txt:28 (include)


        Adding application 'applications\FluidDynamicsApplication'
**** configuring KratosFluidDynamicsApplication ****
        Adding application 'applications\RomApplication'
**** configuring KratosRomApplication ****
CMake Deprecation Warning at cmake_modules/pybind11Tools.cmake:8 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.
Call Stack (most recent call first):
  applications/RomApplication/CMakeLists.txt:6 (include)


        Adding application 'applications\ConvectionDiffusionApplication'
**** configuring KratosConvectionDiffusionApplication ****
        Adding application 'applications\HDF5Application'
**** configuring KratosHDF5Application ****
-- Searching for serial HDF5 libraries.
-- Found HDF5: hdf5-shared (found version "1.12.2") found components: C
-- Using serial HDF5 libraries.

***********************************************************************

        LIST OF APPLICATIONS THAT ARE GOING TO BE COMPILED:

        LinearSolversApplication
        FluidDynamicsApplication
        RomApplication
        ConvectionDiffusionApplication
        HDF5Application

        APPLICATIONS ADDED TO COMPILATION THROUGH DEPENDENCIES:


***********************************************************************


List of upcoming API-breaking and behavior changes:
         Behavior change of Testing. Please ensure you use KRATOS_EXPECT for testing instead of KRATOS_CHECK
         Removal of misused EXTENDED_GAUSS integration rules and unification across geometries: https://github.com/KratosMultiphysics/Kratos/pull/13444
-- clipper : D:/Kratos/external_libraries/clipper
-- tinyexpr : D:/Kratos/external_libraries/tinyexpr/tinyexpr/
-- Configuring done (14.8s)
CMake Error in applications/HDF5Application/CMakeLists.txt:
  IMPORTED_IMPLIB not set for imported target "hdf5-shared" configuration
  "FullDebug".


CMake Error in applications/HDF5Application/CMakeLists.txt:
  IMPORTED_IMPLIB not set for imported target "hdf5-shared" configuration
  "FullDebug".


CMake Error in applications/HDF5Application/CMakeLists.txt:
  IMPORTED_LOCATION or IMPORTED_IMPLIB not set for imported target
  "hdf5-shared" configuration "FullDebug".


CMake Error in applications/HDF5Application/CMakeLists.txt:
  IMPORTED_IMPLIB not set for imported target "hdf5-shared" configuration
  "FullDebug".


-- Generating done (0.5s)
CMake Generate step failed.  Build files cannot be regenerated correctly.

D:\Kratos\scripts>rem Build

D:\Kratos\scripts>cmake --build "D:\Kratos\scripts\../build/Release" --target install -- /property:configuration=Release /p:Platform=x64
Microsoft (R) Build Engine versión 16.11.6+a918ceb31 para .NET Framework
Copyright (C) Microsoft Corporation. Todos los derechos reservados.

  1>Checking Build System
  KratosVersion.vcxproj -> D:\Kratos\build\Release\kratos\KratosVersion.dir\Release\KratosVersion.lib
  clipper.vcxproj -> D:\Kratos\build\Release\external_libraries\clipper\Release\clipper.lib
  zlib.vcxproj -> D:\Kratos\build\Release\external_libraries\zlib\Release\zlib.dll
  gidpost.vcxproj -> D:\Kratos\build\Release\external_libraries\gidpost\source\Release\gidpost.lib
  tinyexpr.vcxproj -> D:\Kratos\build\Release\external_libraries\tinyexpr\Release\tinyexpr.lib
  KratosCore.vcxproj -> D:\Kratos\build\Release\kratos\Release\KratosCore.dll
  Kratos.vcxproj -> D:\Kratos\build\Release\kratos\Release\Kratos.cp310-win_amd64.pyd
  KratosConvectionDiffusionCore.vcxproj -> D:\Kratos\build\Release\applications\ConvectionDiffusionApplication\Release\KratosConvectionDiffusionCore.dll
  KratosConvectionDiffusionApplication.vcxproj -> D:\Kratos\build\Release\applications\ConvectionDiffusionApplication\Release\KratosConvectionDiffusionApplication.pyd
  KratosFluidDynamicsCore.vcxproj -> D:\Kratos\build\Release\applications\FluidDynamicsApplication\Release\KratosFluidDynamicsCore.dll
  KratosFluidDynamicsApplication.vcxproj -> D:\Kratos\build\Release\applications\FluidDynamicsApplication\Release\KratosFluidDynamicsApplication.pyd
     Creando biblioteca D:/Kratos/build/Release/applications/HDF5Application/Release/KratosHDF5Core.lib y objeto D:/Kratos/build/Release/applications/HDF5Application/Release/KratosHDF5Core.exp
hdf5_vertex_container_io.obj : error LNK2019: símbolo externo "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl Kratos::Parameters::Get<class std::basic_
string<char,struct std::char_traits<char>,class std::allocator<char> > >(void)const " (??$Get@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Parameters@Kratos@@QEBA?AV?$basic_string@DU?$char_t
raits@D@std@@V?$allocator@D@2@@std@@XZ) sin resolver al que se hace referencia en la función "public: __cdecl Kratos::HDF5::VertexContainerCoordinateIO::VertexContainerCoordinateIO(class Kratos::Parameters,cl
ass std::shared_ptr<class Kratos::HDF5::File>)" (??0VertexContainerCoordinateIO@HDF5@Kratos@@QEAA@VParameters@2@V?$shared_ptr@VFile@HDF5@Kratos@@@std@@@Z) [D:\Kratos\build\Release\applications\HDF5Application
\KratosHDF5Core.vcxproj]
D:\Kratos\build\Release\applications\HDF5Application\Release\KratosHDF5Core.dll : fatal error LNK1120: 1 externos sin resolver [D:\Kratos\build\Release\applications\HDF5Application\KratosHDF5Core.vcxproj]
  KratosLinearSolversCore.vcxproj -> D:\Kratos\build\Release\applications\LinearSolversApplication\Release\KratosLinearSolversCore.pyd
  KratosLinearSolversApplication.vcxproj -> D:\Kratos\build\Release\applications\LinearSolversApplication\Release\KratosLinearSolversApplication.pyd
  KratosRomCore.vcxproj -> D:\Kratos\build\Release\applications\RomApplication\Release\KratosRomCore.dll
  KratosRomApplication.vcxproj -> D:\Kratos\build\Release\applications\RomApplication\Release\KratosRomApplication.pyd

D:\Kratos\scripts>goto:eof
PS D:\Kratos\scripts>
```
</details>

**Comment by roigcarlo** [comment]
Ok, compilation errors should be solved, but not sure about the CI testes failing, I suspect there is some mismatch with the overload of the cheks in the function `WriteComponents`, but I am not familiar with the details of this piece of code in particular and my filesystem seems that does not support the executions of the tests that are failing, so patience with those.

**Comment by Rbravo555** [comment]
I am still getting some  `error LNK2019`

<details>

<summary> Here's the log: </summary>

```log
Windows PowerShell
Copyright (C) Microsoft Corporation. Todos los derechos reservados.

Instale la versión más reciente de PowerShell para obtener nuevas características y mejoras. https://aka.ms/PSWindows

PS D:\Kratos\scripts> git pull
Already up to date.
PS D:\Kratos\scripts> git status
On branch hdf5/fix-win
Your branch is up to date with 'origin/hdf5/fix-win'.

nothing to commit, working tree clean
PS D:\Kratos\scripts> .\configure.bat

D:\Kratos\scripts>cmake -G"Visual Studio 16 2019" -H"D:\Kratos\scripts\.." -B"D:\Kratos\scripts\../build\Release"          -DCMAKE_CXX_FLAGS="  "                                                  -DCMAKE_POLICY_VERSION_MINIMUM=3.5                                                                  -DUSE_EIGEN_MKL=OFF                                                                                 -DHDF5_ROOT="D:\hdf5\bin"                                                                           -DKRATOS_GENERATE_PYTHON_STUBS=ON
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.26200.
-- The C compiler identification is MSVC 19.29.30159.0
-- The CXX compiler identification is MSVC 19.29.30159.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No KRATOS_SOURCE_DIR is defined, using: D:/Kratos
-- No KRATOS_BINARY_DIR is defined, using: D:/Kratos/build/Release
-- No KRATOS_INSTALL_PYTHON_USING_LINKS is defined, setting to OFF
-- No CMAKE_INSTALL_MESSAGE is defined. Setting to NEVER
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.52.0.windows.1")
-- CMAKE_SYSTEM_NAME = Windows
-- CMAKE_CXX_COMPILER_ID = MSVC
-- CMAKE_CXX_FLAGS =
-- CMAKE_C_FLAGS = /DWIN32 /D_WINDOWS
-- Detected compiler as MSVC
CMake Deprecation Warning at build/Release/_deps/googletest-src/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.


CMake Deprecation Warning at build/Release/_deps/googletest-src/googlemock/CMakeLists.txt:39 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.


CMake Deprecation Warning at build/Release/_deps/googletest-src/googletest/CMakeLists.txt:49 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.


-- Found Python: C:/Program Files/Python310/python.exe (found version "3.10.11") found components: Interpreter
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
CMake Deprecation Warning at cmake_modules/pybind11Tools.cmake:8 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.
Call Stack (most recent call first):
  CMakeLists.txt:407 (include)


-- Found PythonInterp: C:\Program Files\Python310\python.exe (found suitable version "3.10.11", minimum required is "3.6")
-- Found PythonLibs: C:/Program Files/Python310/libs/python310.lib
-- LTO is Disabled
-- AR VERSION: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/lib.exe
-- Python version used for the interface will be 3.10
-- Standard install dir D:/Kratos/bin/Release
-- "KRATOS_SHARED_MEMORY_PARALLELIZATION" not defined, defaulting to "OpenMP"
-- Found OpenMP_C: -openmp (found version "2.0")
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Found OpenMP: TRUE (found version "2.0")
-- Using OpenMP for shared memory parallelization
-- Found Boost: D:/Boost/lib/cmake/Boost-1.89.0/BoostConfig.cmake (found version "1.89.0")
-- Boost include directory found with find_package
-- Boost library deduced from root directory
-- Boost include directory: D:/Boost/include/boost-1_89
-- Boost library directory: D:\Boost/lib
-- Could NOT find ZLIB (missing: ZLIB_INCLUDE_DIR)
-- Preparing local ZLIB compilation.
CMake Deprecation Warning at external_libraries/zlib/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.


-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - failed
-- Looking for fseeko
-- Looking for fseeko - not found
-- Looking for unistd.h
-- Looking for unistd.h - not found

-- CMAKE_BUILD_TYPE ........ Release

-- Found ZLIB by find_package():
-- * Configuring gidpost library
-- Configuring applications (ENV):
        Adding application 'applications\LinearSolversApplication'
**** configuring KratosLinearSolversApplication ****
CMake Deprecation Warning at cmake_modules/pybind11Tools.cmake:8 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.
Call Stack (most recent call first):
  applications/LinearSolversApplication/CMakeLists.txt:28 (include)


        Adding application 'applications\FluidDynamicsApplication'
**** configuring KratosFluidDynamicsApplication ****
        Adding application 'applications\RomApplication'
**** configuring KratosRomApplication ****
CMake Deprecation Warning at cmake_modules/pybind11Tools.cmake:8 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.
Call Stack (most recent call first):
  applications/RomApplication/CMakeLists.txt:6 (include)


        Adding application 'applications\ConvectionDiffusionApplication'
**** configuring KratosConvectionDiffusionApplication ****
        Adding application 'applications\HDF5Application'
**** configuring KratosHDF5Application ****
-- Searching for serial HDF5 libraries.
-- Found HDF5: hdf5-shared (found version "1.12.2") found components: C
-- Using serial HDF5 libraries.

***********************************************************************

        LIST OF APPLICATIONS THAT ARE GOING TO BE COMPILED:

        LinearSolversApplication
        FluidDynamicsApplication
        RomApplication
        ConvectionDiffusionApplication
        HDF5Application

        APPLICATIONS ADDED TO COMPILATION THROUGH DEPENDENCIES:


***********************************************************************


List of upcoming API-breaking and behavior changes:
         Behavior change of Testing. Please ensure you use KRATOS_EXPECT for testing instead of KRATOS_CHECK
         Removal of misused EXTENDED_GAUSS integration rules and unification across geometries: https://github.com/KratosMultiphysics/Kratos/pull/13444
-- clipper : D:/Kratos/external_libraries/clipper
-- tinyexpr : D:/Kratos/external_libraries/tinyexpr/tinyexpr/
-- Configuring done (18.2s)
CMake Error in applications/HDF5Application/CMakeLists.txt:
  IMPORTED_IMPLIB not set for imported target "hdf5-shared" configuration
  "FullDebug".


CMake Error in applications/HDF5Application/CMakeLists.txt:
  IMPORTED_IMPLIB not set for imported target "hdf5-shared" configuration
  "FullDebug".


CMake Error in applications/HDF5Application/CMakeLists.txt:
  IMPORTED_LOCATION or IMPORTED_IMPLIB not set for imported target
  "hdf5-shared" configuration "FullDebug".


CMake Error in applications/HDF5Application/CMakeLists.txt:
  IMPORTED_IMPLIB not set for imported target "hdf5-shared" configuration
  "FullDebug".


-- Generating done (0.6s)
CMake Generate step failed.  Build files cannot be regenerated correctly.

D:\Kratos\scripts>rem Build

D:\Kratos\scripts>cmake --build "D:\Kratos\scripts\../build/Release" --target install -- /property:configuration=Release /p:Platform=x64
Microsoft (R) Build Engine versión 16.11.6+a918ceb31 para .NET Framework
Copyright (C) Microsoft Corporation. Todos los derechos reservados.

  KratosVersion.vcxproj -> D:\Kratos\build\Release\kratos\KratosVersion.dir\Release\KratosVersion.lib
  clipper.vcxproj -> D:\Kratos\build\Release\external_libraries\clipper\Release\clipper.lib
  zlib.vcxproj -> D:\Kratos\build\Release\external_libraries\zlib\Release\zlib.dll
  gidpost.vcxproj -> D:\Kratos\build\Release\external_libraries\gidpost\source\Release\gidpost.lib
  tinyexpr.vcxproj -> D:\Kratos\build\Release\external_libraries\tinyexpr\Release\tinyexpr.lib
  KratosCore.vcxproj -> D:\Kratos\build\Release\kratos\Release\KratosCore.dll
  Kratos.vcxproj -> D:\Kratos\build\Release\kratos\Release\Kratos.cp310-win_amd64.pyd
  KratosConvectionDiffusionCore.vcxproj -> D:\Kratos\build\Release\applications\ConvectionDiffusionApplication\Release\
  KratosConvectionDiffusionCore.dll
  KratosConvectionDiffusionApplication.vcxproj -> D:\Kratos\build\Release\applications\ConvectionDiffusionApplication\R
  elease\KratosConvectionDiffusionApplication.pyd
  KratosFluidDynamicsCore.vcxproj -> D:\Kratos\build\Release\applications\FluidDynamicsApplication\Release\KratosFluidD
  ynamicsCore.dll
  KratosFluidDynamicsApplication.vcxproj -> D:\Kratos\build\Release\applications\FluidDynamicsApplication\Release\Krato
  sFluidDynamicsApplication.pyd
  KratosHDF5Core.vcxproj -> D:\Kratos\build\Release\applications\HDF5Application\Release\KratosHDF5Core.dll
  KratosHDF5Application.vcxproj -> D:\Kratos\build\Release\applications\HDF5Application\Release\KratosHDF5Application.p
  yd
  KratosLinearSolversCore.vcxproj -> D:\Kratos\build\Release\applications\LinearSolversApplication\Release\KratosLinear
  SolversCore.pyd
  KratosLinearSolversApplication.vcxproj -> D:\Kratos\build\Release\applications\LinearSolversApplication\Release\Krato
  sLinearSolversApplication.pyd
  KratosRomCore.vcxproj -> D:\Kratos\build\Release\applications\RomApplication\Release\KratosRomCore.dll
  KratosRomApplication.vcxproj -> D:\Kratos\build\Release\applications\RomApplication\Release\KratosRomApplication.pyd
  gmock.vcxproj -> D:\Kratos\build\Release\bin\Release\gmock.dll
  gtest.vcxproj -> D:\Kratos\build\Release\bin\Release\gtest.dll
  KratosCoreTestUtilities.vcxproj -> D:\Kratos\build\Release\kratos\Release\KratosCoreTestUtilities.dll
  gmock_main.vcxproj -> D:\Kratos\build\Release\bin\Release\gmock_main.dll
  KratosConvectionDiffusionCoreTest.vcxproj -> D:\Kratos\build\Release\applications\ConvectionDiffusionApplication\Rele
  ase\KratosConvectionDiffusionCoreTest.exe
  KratosCoreTest.vcxproj -> D:\Kratos\build\Release\kratos\Release\KratosCoreTest.exe
  KratosFluidDynamicsCoreTest.vcxproj -> D:\Kratos\build\Release\applications\FluidDynamicsApplication\Release\KratosFl
  uidDynamicsCoreTest.exe
test_hdf5_connectivities_data.obj : error LNK2019: símbolo externo "class std::vector<class Kratos::PointerVectorSet<cl
ass Kratos::Element,class Kratos::IndexedObject,struct std::less<unsigned __int64>,struct std::equal_to<unsigned __int6
4>,class Kratos::intrusive_ptr<class Kratos::Element>,class std::vector<class Kratos::intrusive_ptr<class Kratos::Eleme
nt>,class std::allocator<class Kratos::intrusive_ptr<class Kratos::Element> > > >,class std::allocator<class Kratos::Po
interVectorSet<class Kratos::Element,class Kratos::IndexedObject,struct std::less<unsigned __int64>,struct std::equal_t
o<unsigned __int64>,class Kratos::intrusive_ptr<class Kratos::Element>,class std::vector<class Kratos::intrusive_ptr<cl
ass Kratos::Element>,class std::allocator<class Kratos::intrusive_ptr<class Kratos::Element> > > > > > __cdecl Kratos::
FactorElements(class Kratos::PointerVectorSet<class Kratos::Element,class Kratos::IndexedObject,struct std::less<unsign
ed __int64>,struct std::equal_to<unsigned __int64>,class Kratos::intrusive_ptr<class Kratos::Element>,class std::vector
<class Kratos::intrusive_ptr<class Kratos::Element>,class std::allocator<class Kratos::intrusive_ptr<class Kratos::Elem
ent> > > > const &)" (?FactorElements@Kratos@@YA?AV?$vector@V?$PointerVectorSet@VElement@Kratos@@VIndexedObject@2@U?$le
ss@_K@std@@U?$equal_to@_K@5@V?$intrusive_ptr@VElement@Kratos@@@2@V?$vector@V?$intrusive_ptr@VElement@Kratos@@@Kratos@@V
?$allocator@V?$intrusive_ptr@VElement@Kratos@@@Kratos@@@std@@@5@@Kratos@@V?$allocator@V?$PointerVectorSet@VElement@Krat
os@@VIndexedObject@2@U?$less@_K@std@@U?$equal_to@_K@5@V?$intrusive_ptr@VElement@Kratos@@@2@V?$vector@V?$intrusive_ptr@V
Element@Kratos@@@Kratos@@V?$allocator@V?$intrusive_ptr@VElement@Kratos@@@Kratos@@@std@@@5@@Kratos@@@std@@@std@@AEBV?$Po
interVectorSet@VElement@Kratos@@VIndexedObject@2@U?$less@_K@std@@U?$equal_to@_K@5@V?$intrusive_ptr@VElement@Kratos@@@2@
V?$vector@V?$intrusive_ptr@VElement@Kratos@@@Kratos@@V?$allocator@V?$intrusive_ptr@VElement@Kratos@@@Kratos@@@std@@@5@@
1@@Z) sin resolver al que se hace referencia en la función "private: virtual void __cdecl Kratos::Testing::KratosHDF5Te
stSuite_HDF5_Internals_ConnectivitiesData1_Test::TestBody(void)" (?TestBody@KratosHDF5TestSuite_HDF5_Internals_Connecti
vitiesData1_Test@Testing@Kratos@@EEAAXXZ) [D:\Kratos\build\Release\applications\HDF5Application\KratosHDF5CoreTest.vcxp
roj]
test_hdf5_connectivities_data.obj : error LNK2019: símbolo externo "class std::vector<class Kratos::PointerVectorSet<cl
ass Kratos::Condition,class Kratos::IndexedObject,struct std::less<unsigned __int64>,struct std::equal_to<unsigned __in
t64>,class Kratos::intrusive_ptr<class Kratos::Condition>,class std::vector<class Kratos::intrusive_ptr<class Kratos::C
ondition>,class std::allocator<class Kratos::intrusive_ptr<class Kratos::Condition> > > >,class std::allocator<class Kr
atos::PointerVectorSet<class Kratos::Condition,class Kratos::IndexedObject,struct std::less<unsigned __int64>,struct st
d::equal_to<unsigned __int64>,class Kratos::intrusive_ptr<class Kratos::Condition>,class std::vector<class Kratos::intr
usive_ptr<class Kratos::Condition>,class std::allocator<class Kratos::intrusive_ptr<class Kratos::Condition> > > > > >
__cdecl Kratos::FactorConditions(class Kratos::PointerVectorSet<class Kratos::Condition,class Kratos::IndexedObject,str
uct std::less<unsigned __int64>,struct std::equal_to<unsigned __int64>,class Kratos::intrusive_ptr<class Kratos::Condit
ion>,class std::vector<class Kratos::intrusive_ptr<class Kratos::Condition>,class std::allocator<class Kratos::intrusiv
e_ptr<class Kratos::Condition> > > > const &)" (?FactorConditions@Kratos@@YA?AV?$vector@V?$PointerVectorSet@VCondition@
Kratos@@VIndexedObject@2@U?$less@_K@std@@U?$equal_to@_K@5@V?$intrusive_ptr@VCondition@Kratos@@@2@V?$vector@V?$intrusive
_ptr@VCondition@Kratos@@@Kratos@@V?$allocator@V?$intrusive_ptr@VCondition@Kratos@@@Kratos@@@std@@@5@@Kratos@@V?$allocat
or@V?$PointerVectorSet@VCondition@Kratos@@VIndexedObject@2@U?$less@_K@std@@U?$equal_to@_K@5@V?$intrusive_ptr@VCondition
@Kratos@@@2@V?$vector@V?$intrusive_ptr@VCondition@Kratos@@@Kratos@@V?$allocator@V?$intrusive_ptr@VCondition@Kratos@@@Kr
atos@@@std@@@5@@Kratos@@@std@@@std@@AEBV?$PointerVectorSet@VCondition@Kratos@@VIndexedObject@2@U?$less@_K@std@@U?$equal
_to@_K@5@V?$intrusive_ptr@VCondition@Kratos@@@2@V?$vector@V?$intrusive_ptr@VCondition@Kratos@@@Kratos@@V?$allocator@V?$
intrusive_ptr@VCondition@Kratos@@@Kratos@@@std@@@5@@1@@Z) sin resolver al que se hace referencia en la función "private
: virtual void __cdecl Kratos::Testing::KratosHDF5TestSuite_HDF5_Internals_ConnectivitiesData2_Test::TestBody(void)" (?
TestBody@KratosHDF5TestSuite_HDF5_Internals_ConnectivitiesData2_Test@Testing@Kratos@@EEAAXXZ) [D:\Kratos\build\Release\
applications\HDF5Application\KratosHDF5CoreTest.vcxproj]
test_hdf5_points_data.obj : error LNK2019: símbolo externo "void __cdecl Kratos::HDF5::WritePartitionTable(class Kratos
::HDF5::File &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,struct K
ratos::HDF5::WriteInfo const &)" (?WritePartitionTable@HDF5@Kratos@@YAXAEAVFile@12@AEBV?$basic_string@DU?$char_traits@D
@std@@V?$allocator@D@2@@std@@AEBUWriteInfo@12@@Z) sin resolver al que se hace referencia en la función "public: void __
cdecl Kratos::HDF5::Internals::PointsData<class Kratos::HDF5::Internals::NodesIO>::Write(class Kratos::PointerVectorSet
<class Kratos::Node,class Kratos::IndexedObject,struct std::less<unsigned __int64>,struct std::equal_to<unsigned __int6
4>,class Kratos::intrusive_ptr<class Kratos::Node>,class std::vector<class Kratos::intrusive_ptr<class Kratos::Node>,cl
ass std::allocator<class Kratos::intrusive_ptr<class Kratos::Node> > > > const &,class Kratos::HDF5::Internals::NodesIO
 const &,class Kratos::Parameters)" (?Write@?$PointsData@VNodesIO@Internals@HDF5@Kratos@@@Internals@HDF5@Kratos@@QEAAXA
EBV?$PointerVectorSet@VNode@Kratos@@VIndexedObject@2@U?$less@_K@std@@U?$equal_to@_K@5@V?$intrusive_ptr@VNode@Kratos@@@2
@V?$vector@V?$intrusive_ptr@VNode@Kratos@@@Kratos@@V?$allocator@V?$intrusive_ptr@VNode@Kratos@@@Kratos@@@std@@@5@@4@AEB
VNodesIO@234@VParameters@4@@Z) [D:\Kratos\build\Release\applications\HDF5Application\KratosHDF5CoreTest.vcxproj]
test_hdf5_points_data.obj : error LNK2019: símbolo externo "class std::tuple<unsigned int,unsigned int> __cdecl Kratos:
:HDF5::StartIndexAndBlockSize(class Kratos::HDF5::File &,class std::basic_string<char,struct std::char_traits<char>,cla
ss std::allocator<char> > const &)" (?StartIndexAndBlockSize@HDF5@Kratos@@YA?AV?$tuple@II@std@@AEAVFile@12@AEBV?$basic_
string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@@Z) sin resolver al que se hace referencia en la función "public: cla
ss Kratos::Parameters __cdecl Kratos::HDF5::Internals::PointsData<class Kratos::HDF5::Internals::NodesIO>::Read(class K
ratos::PointerVectorSet<class Kratos::Node,class Kratos::IndexedObject,struct std::less<unsigned __int64>,struct std::e
qual_to<unsigned __int64>,class Kratos::intrusive_ptr<class Kratos::Node>,class std::vector<class Kratos::intrusive_ptr
<class Kratos::Node>,class std::allocator<class Kratos::intrusive_ptr<class Kratos::Node> > > > &,class Kratos::HDF5::I
nternals::NodesIO const &)" (?Read@?$PointsData@VNodesIO@Internals@HDF5@Kratos@@@Internals@HDF5@Kratos@@QEAA?AVParamete
rs@4@AEAV?$PointerVectorSet@VNode@Kratos@@VIndexedObject@2@U?$less@_K@std@@U?$equal_to@_K@5@V?$intrusive_ptr@VNode@Krat
os@@@2@V?$vector@V?$intrusive_ptr@VNode@Kratos@@@Kratos@@V?$allocator@V?$intrusive_ptr@VNode@Kratos@@@Kratos@@@std@@@5@
@4@AEBVNodesIO@234@@Z) [D:\Kratos\build\Release\applications\HDF5Application\KratosHDF5CoreTest.vcxproj]
D:\Kratos\build\Release\applications\HDF5Application\Release\KratosHDF5CoreTest.exe : fatal error LNK1120: 4 externos s
in resolver [D:\Kratos\build\Release\applications\HDF5Application\KratosHDF5CoreTest.vcxproj]
  KratosRomCoreTest.vcxproj -> D:\Kratos\build\Release\applications\RomApplication\Release\KratosRomCoreTest.exe
  gtest_main.vcxproj -> D:\Kratos\build\Release\bin\Release\gtest_main.dll
  zlibstatic.vcxproj -> D:\Kratos\build\Release\external_libraries\zlib\Release\zlibstatic.lib

D:\Kratos\scripts>goto:eof
PS D:\Kratos\scripts>

```

</details>

File: applications/HDF5Application/custom_io/hdf5_vertex_container_io.cpp [hunk 1]
```diff
@@ -25,7 +25,7 @@ namespace HDF5
 
 namespace Internals
 {
-std::string AddMissingAndGetPrefix(Parameters Settings)
+std::string AddMissingAndGetPrefix(Parameters & Settings)
```
Comment (sunethwarna) [inline applications/HDF5Application/custom_io/hdf5_vertex_container_io.cpp:28]: Is this necessary?

File: applications/HDF5Application/custom_io/hdf5_vertex_container_io.cpp [hunk 2]
```diff
@@ -44,7 +44,7 @@ VertexContainerCoordinateIO::VertexContainerCoordinateIO(
 {
     KRATOS_TRY
 
-    const std::string prefix = Settings["prefix"].Get<std::string>();
+    const std::string prefix = Settings["prefix"].GetString();
```
Comment (sunethwarna) [inline applications/HDF5Application/custom_io/hdf5_vertex_container_io.cpp:47]: Curious: Was the previous causing problems?

**Review by sunethwarna — COMMENTED** [review]
Thanks @roigcarlo , and sorry for being late....

File: applications/HDF5Application/custom_io/hdf5_vertex_container_io.cpp (hunk 2 above)
Comment (roigcarlo) [reply applications/HDF5Application/custom_io/hdf5_vertex_container_io.cpp:47]: Get<std::string> is not exposed, hence cannot be called.

File: applications/HDF5Application/custom_io/hdf5_vertex_container_io.cpp (hunk 1 above)
Comment (roigcarlo) [reply applications/HDF5Application/custom_io/hdf5_vertex_container_io.cpp:28]: Yep, otherwise the copy contructor implicitly calls `Get<>`

**Comment by roigcarlo** [comment]
Sadly I cannot find the errors, so I reverted the changes to hdf5 so it keeps using unsigned char and added it to the data communicator interface.

@Rbravo555 This should make the tests ok again, if it works I will extend the API interface for win to accommodate the lasts errors you sent.

**Comment by roigcarlo** [comment]
@sunethwarna I've added a set of changes to the app:
1 - I've removed all the warnings of calls using the old `Write/Read[Container]` interface in favor of the new `Write/Read` that deduces the container from the `HDF5ContainerIO`.
2 - I've removed all the warnings from the `HDF5File` constructor (including the one from the mocks in `file_io` stub)
3 - I've changed the construction of the mdpa of the `test_hdf5_model_part_io` modelpart as it has a nasty bug that could cause any of the 4 sets of tri_elems, tri_conds, quad_elemes or quad_conds to be empty causing the write function to fail in the check because there is no active element of that type (but others exist).

This can be the cause of other tests randomly failing with extremely low fail rates that we have been seeing if they follow a similar mechanism while creating the modelparts. We should keep an eye on them.

Lastly, there seems to be still a deadlock while running in mpi under some scenarios. For now it eludes me why, if you could take a look could be super helpful :pray:

**Comment by Rbravo555** [comment]
> Sadly I cannot find the errors, so I reverted the changes to hdf5 so it keeps using unsigned char and added it to the data communicator interface.
> 
> @Rbravo555 This should make the tests ok again, if it works I will extend the API interface for win to accommodate the lasts errors you sent.

<details>

<summary>I have attemped the compile just now with the latest changes with the following error log:</summary>


```
PS D:\Kratos\scripts> .\configure.bat

D:\Kratos\scripts>cmake -G"Visual Studio 16 2019" -H"D:\Kratos\scripts\.." -B"D:\Kratos\scripts\../build\Release"          -DCMAKE_CXX_FLAGS="  "                                                  -DCMAKE_POLICY_VERSION_MINIMUM=3.5                                                                  -DUSE_EIGEN_MKL=OFF                                                                                 -DHDF5_ROOT="D:\hdf5\bin"                                                                           -DKRATOS_GENERATE_PYTHON_STUBS=ON
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.26200.
-- The C compiler identification is MSVC 19.29.30159.0
-- The CXX compiler identification is MSVC 19.29.30159.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No KRATOS_SOURCE_DIR is defined, using: D:/Kratos
-- No KRATOS_BINARY_DIR is defined, using: D:/Kratos/build/Release
-- No KRATOS_INSTALL_PYTHON_USING_LINKS is defined, setting to OFF
-- No CMAKE_INSTALL_MESSAGE is defined. Setting to NEVER
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.52.0.windows.1")
-- CMAKE_SYSTEM_NAME = Windows
-- CMAKE_CXX_COMPILER_ID = MSVC
-- CMAKE_CXX_FLAGS =
-- CMAKE_C_FLAGS = /DWIN32 /D_WINDOWS
-- Detected compiler as MSVC
CMake Deprecation Warning at build/Release/_deps/googletest-src/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.


CMake Deprecation Warning at build/Release/_deps/googletest-src/googlemock/CMakeLists.txt:39 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.


CMake Deprecation Warning at build/Release/_deps/googletest-src/googletest/CMakeLists.txt:49 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.


-- Found Python: C:/Program Files/Python310/python.exe (found version "3.10.11") found components: Interpreter
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
CMake Deprecation Warning at cmake_modules/pybind11Tools.cmake:8 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.
Call Stack (most recent call first):
  CMakeLists.txt:407 (include)


-- Found PythonInterp: C:\Program Files\Python310\python.exe (found suitable version "3.10.11", minimum required is "3.6")
-- Found PythonLibs: C:/Program Files/Python310/libs/python310.lib
-- LTO is Disabled
-- AR VERSION: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/lib.exe
-- Python version used for the interface will be 3.10
-- Standard install dir D:/Kratos/bin/Release
-- "KRATOS_SHARED_MEMORY_PARALLELIZATION" not defined, defaulting to "OpenMP"
-- Found OpenMP_C: -openmp (found version "2.0")
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Found OpenMP: TRUE (found version "2.0")
-- Using OpenMP for shared memory parallelization
-- Found Boost: D:/Boost/lib/cmake/Boost-1.89.0/BoostConfig.cmake (found version "1.89.0")
-- Boost include directory found with find_package
-- Boost library deduced from root directory
-- Boost include directory: D:/Boost/include/boost-1_89
-- Boost library directory: D:\Boost/lib
-- Could NOT find ZLIB (missing: ZLIB_INCLUDE_DIR)
-- Preparing local ZLIB compilation.
CMake Deprecation Warning at external_libraries/zlib/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.


-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - failed
-- Looking for fseeko
-- Looking for fseeko - not found
-- Looking for unistd.h
-- Looking for unistd.h - not found

-- CMAKE_BUILD_TYPE ........ Release

-- Found ZLIB by find_package():
-- * Configuring gidpost library
-- Configuring applications (ENV):
        Adding application 'applications\LinearSolversApplication'
**** configuring KratosLinearSolversApplication ****
CMake Deprecation Warning at cmake_modules/pybind11Tools.cmake:8 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.
Call Stack (most recent call first):
  applications/LinearSolversApplication/CMakeLists.txt:28 (include)


        Adding application 'applications\FluidDynamicsApplication'
**** configuring KratosFluidDynamicsApplication ****
        Adding application 'applications\RomApplication'
**** configuring KratosRomApplication ****
CMake Deprecation Warning at cmake_modules/pybind11Tools.cmake:8 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.
Call Stack (most recent call first):
  applications/RomApplication/CMakeLists.txt:6 (include)


        Adding application 'applications\ConvectionDiffusionApplication'
**** configuring KratosConvectionDiffusionApplication ****
        Adding application 'applications\StructuralMechanicsApplication'
**** configuring KratosStructuralMechanicsApplication ****
CMake Deprecation Warning at cmake_modules/pybind11Tools.cmake:8 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.
Call Stack (most recent call first):
  applications/StructuralMechanicsApplication/CMakeLists.txt:6 (include)


        Adding application 'applications\ConstitutiveLawsApplication'
**** configuring KratosConstitutiveLawsApplication ****
CMake Deprecation Warning at cmake_modules/pybind11Tools.cmake:8 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.
Call Stack (most recent call first):
  applications/ConstitutiveLawsApplication/CMakeLists.txt:6 (include)


        Adding application 'applications\HDF5Application'
**** configuring KratosHDF5Application ****
-- Searching for serial HDF5 libraries.
-- Found HDF5: hdf5-shared (found version "1.12.2") found components: C
-- Using serial HDF5 libraries.

***********************************************************************

        LIST OF APPLICATIONS THAT ARE GOING TO BE COMPILED:

        LinearSolversApplication
        FluidDynamicsApplication
        RomApplication
        ConvectionDiffusionApplication
        StructuralMechanicsApplication
        ConstitutiveLawsApplication
        HDF5Application

        APPLICATIONS ADDED TO COMPILATION THROUGH DEPENDENCIES:


***********************************************************************


List of upcoming API-breaking and behavior changes:
         Behavior change of Testing. Please ensure you use KRATOS_EXPECT for testing instead of KRATOS_CHECK
         Removal of misused EXTENDED_GAUSS integration rules and unification across geometries: https://github.com/KratosMultiphysics/Kratos/pull/13444
-- clipper : D:/Kratos/external_libraries/clipper
-- tinyexpr : D:/Kratos/external_libraries/tinyexpr/tinyexpr/
-- Configuring done (16.8s)
CMake Error in applications/HDF5Application/CMakeLists.txt:
  IMPORTED_IMPLIB not set for imported target "hdf5-shared" configuration
  "FullDebug".


CMake Error in applications/HDF5Application/CMakeLists.txt:
  IMPORTED_IMPLIB not set for imported target "hdf5-shared" configuration
  "FullDebug".


CMake Error in applications/HDF5Application/CMakeLists.txt:
  IMPORTED_LOCATION or IMPORTED_IMPLIB not set for imported target
  "hdf5-shared" configuration "FullDebug".


CMake Error in applications/HDF5Application/CMakeLists.txt:
  IMPORTED_IMPLIB not set for imported target "hdf5-shared" configuration
  "FullDebug".


-- Generating done (0.7s)
CMake Generate step failed.  Build files cannot be regenerated correctly.

D:\Kratos\scripts>rem Build

D:\Kratos\scripts>cmake --build "D:\Kratos\scripts\../build/Release" --target install -- /property:configuration=Release /p:Platform=x64
Microsoft (R) Build Engine versión 16.11.6+a918ceb31 para .NET Framework
Copyright (C) Microsoft Corporation. Todos los derechos reservados.

  KratosVersion.vcxproj -> D:\Kratos\build\Release\kratos\KratosVersion.dir\Release\KratosVersion.lib
  clipper.vcxproj -> D:\Kratos\build\Release\external_libraries\clipper\Release\clipper.lib
  zlib.vcxproj -> D:\Kratos\build\Release\external_libraries\zlib\Release\zlib.dll
  gidpost.vcxproj -> D:\Kratos\build\Release\external_libraries\gidpost\source\Release\gidpost.lib
  tinyexpr.vcxproj -> D:\Kratos\build\Release\external_libraries\tinyexpr\Release\tinyexpr.lib
  KratosCore.vcxproj -> D:\Kratos\build\Release\kratos\Release\KratosCore.dll
  Kratos.vcxproj -> D:\Kratos\build\Release\kratos\Release\Kratos.cp310-win_amd64.pyd
  KratosStructuralMechanicsCore.vcxproj -> D:\Kratos\build\Release\applications\StructuralMechanicsApplication\Release\KratosStructuralMechanicsCore.dll
  KratosConstitutiveLawsCore.vcxproj -> D:\Kratos\build\Release\applications\ConstitutiveLawsApplication\Release\KratosConstitutiveLawsCore.dll
  KratosConstitutiveLawsApplication.vcxproj -> D:\Kratos\build\Release\applications\ConstitutiveLawsApplication\Release\KratosConstitutiveLawsApplication.pyd
  KratosConvectionDiffusionCore.vcxproj -> D:\Kratos\build\Release\applications\ConvectionDiffusionApplication\Release\KratosConvectionDiffusionCore.dll
  KratosConvectionDiffusionApplication.vcxproj -> D:\Kratos\build\Release\applications\ConvectionDiffusionApplication\Release\KratosConvectionDiffusionApplication.pyd
  KratosFluidDynamicsCore.vcxproj -> D:\Kratos\build\Release\applications\FluidDynamicsApplication\Release\KratosFluidDynamicsCore.dll
  KratosFluidDynamicsApplication.vcxproj -> D:\Kratos\build\Release\applications\FluidDynamicsApplication\Release\KratosFluidDynamicsApplication.pyd
  KratosHDF5Core.vcxproj -> D:\Kratos\build\Release\applications\HDF5Application\Release\KratosHDF5Core.dll
  KratosHDF5Application.vcxproj -> D:\Kratos\build\Release\applications\HDF5Application\Release\KratosHDF5Application.pyd
  KratosLinearSolversCore.vcxproj -> D:\Kratos\build\Release\applications\LinearSolversApplication\Release\KratosLinearSolversCore.pyd
  KratosLinearSolversApplication.vcxproj -> D:\Kratos\build\Release\applications\LinearSolversApplication\Release\KratosLinearSolversApplication.pyd
  KratosRomCore.vcxproj -> D:\Kratos\build\Release\applications\RomApplication\Release\KratosRomCore.dll
  KratosRomApplication.vcxproj -> D:\Kratos\build\Release\applications\RomApplication\Release\KratosRomApplication.pyd
  KratosStructuralMechanicsApplication.vcxproj -> D:\Kratos\build\Release\applications\StructuralMechanicsApplication\Release\KratosStructuralMechanicsApplication.pyd
  gmock.vcxproj -> D:\Kratos\build\Release\bin\Release\gmock.dll
  gtest.vcxproj -> D:\Kratos\build\Release\bin\Release\gtest.dll
  KratosCoreTestUtilities.vcxproj -> D:\Kratos\build\Release\kratos\Release\KratosCoreTestUtilities.dll
  gmock_main.vcxproj -> D:\Kratos\build\Release\bin\Release\gmock_main.dll
  KratosConstitutiveLawsCoreTest.vcxproj -> D:\Kratos\build\Release\applications\ConstitutiveLawsApplication\Release\KratosConstitutiveLawsCoreTest.exe
  KratosConvectionDiffusionCoreTest.vcxproj -> D:\Kratos\build\Release\applications\ConvectionDiffusionApplication\Release\KratosConvectionDiffusionCoreTest.exe
  KratosCoreTest.vcxproj -> D:\Kratos\build\Release\kratos\Release\KratosCoreTest.exe
  KratosFluidDynamicsCoreTest.vcxproj -> D:\Kratos\build\Release\applications\FluidDynamicsApplication\Release\KratosFluidDynamicsCoreTest.exe
test_hdf5_connectivities_data.obj : error LNK2019: símbolo externo "class std::vector<class Kratos::PointerVectorSet<class Kratos::Element,class Kratos::IndexedObject,struct std:
:less<unsigned __int64>,struct std::equal_to<unsigned __int64>,class Kratos::intrusive_ptr<class Kratos::Element>,class std::vector<class Kratos::intrusive_ptr<class Kratos::Elem
ent>,class std::allocator<class Kratos::intrusive_ptr<class Kratos::Element> > > >,class std::allocator<class Kratos::PointerVectorSet<class Kratos::Element,class Kratos::Indexed
Object,struct std::less<unsigned __int64>,struct std::equal_to<unsigned __int64>,class Kratos::intrusive_ptr<class Kratos::Element>,class std::vector<class Kratos::intrusive_ptr<
class Kratos::Element>,class std::allocator<class Kratos::intrusive_ptr<class Kratos::Element> > > > > > __cdecl Kratos::FactorElements(class Kratos::PointerVectorSet<class Krato
s::Element,class Kratos::IndexedObject,struct std::less<unsigned __int64>,struct std::equal_to<unsigned __int64>,class Kratos::intrusive_ptr<class Kratos::Element>,class std::vec
tor<class Kratos::intrusive_ptr<class Kratos::Element>,class std::allocator<class Kratos::intrusive_ptr<class Kratos::Element> > > > const &)" (?FactorElements@Kratos@@YA?AV?$vec
tor@V?$PointerVectorSet@VElement@Kratos@@VIndexedObject@2@U?$less@_K@std@@U?$equal_to@_K@5@V?$intrusive_ptr@VElement@Kratos@@@2@V?$vector@V?$intrusive_ptr@VElement@Kratos@@@Krato
s@@V?$allocator@V?$intrusive_ptr@VElement@Kratos@@@Kratos@@@std@@@5@@Kratos@@V?$allocator@V?$PointerVectorSet@VElement@Kratos@@VIndexedObject@2@U?$less@_K@std@@U?$equal_to@_K@5@V
?$intrusive_ptr@VElement@Kratos@@@2@V?$vector@V?$intrusive_ptr@VElement@Kratos@@@Kratos@@V?$allocator@V?$intrusive_ptr@VElement@Kratos@@@Kratos@@@std@@@5@@Kratos@@@std@@@std@@AEB
V?$PointerVectorSet@VElement@Kratos@@VIndexedObject@2@U?$less@_K@std@@U?$equal_to@_K@5@V?$intrusive_ptr@VElement@Kratos@@@2@V?$vector@V?$intrusive_ptr@VElement@Kratos@@@Kratos@@V
?$allocator@V?$intrusive_ptr@VElement@Kratos@@@Kratos@@@std@@@5@@1@@Z) sin resolver al que se hace referencia en la función "private: virtual void __cdecl Kratos::Testing::Kratos
HDF5TestSuite_HDF5_Internals_ConnectivitiesData1_Test::TestBody(void)" (?TestBody@KratosHDF5TestSuite_HDF5_Internals_ConnectivitiesData1_Test@Testing@Kratos@@EEAAXXZ) [D:\Kratos\
build\Release\applications\HDF5Application\KratosHDF5CoreTest.vcxproj]
test_hdf5_connectivities_data.obj : error LNK2019: símbolo externo "class std::vector<class Kratos::PointerVectorSet<class Kratos::Condition,class Kratos::IndexedObject,struct st
d::less<unsigned __int64>,struct std::equal_to<unsigned __int64>,class Kratos::intrusive_ptr<class Kratos::Condition>,class std::vector<class Kratos::intrusive_ptr<class Kratos::
Condition>,class std::allocator<class Kratos::intrusive_ptr<class Kratos::Condition> > > >,class std::allocator<class Kratos::PointerVectorSet<class Kratos::Condition,class Krato
s::IndexedObject,struct std::less<unsigned __int64>,struct std::equal_to<unsigned __int64>,class Kratos::intrusive_ptr<class Kratos::Condition>,class std::vector<class Kratos::in
trusive_ptr<class Kratos::Condition>,class std::allocator<class Kratos::intrusive_ptr<class Kratos::Condition> > > > > > __cdecl Kratos::FactorConditions(class Kratos::PointerVec
torSet<class Kratos::Condition,class Kratos::IndexedObject,struct std::less<unsigned __int64>,struct std::equal_to<unsigned __int64>,class Kratos::intrusive_ptr<class Kratos::Con
dition>,class std::vector<class Kratos::intrusive_ptr<class Kratos::Condition>,class std::allocator<class Kratos::intrusive_ptr<class Kratos::Condition> > > > const &)" (?FactorC
onditions@Kratos@@YA?AV?$vector@V?$PointerVectorSet@VCondition@Kratos@@VIndexedObject@2@U?$less@_K@std@@U?$equal_to@_K@5@V?$intrusive_ptr@VCondition@Kratos@@@2@V?$vector@V?$intru
sive_ptr@VCondition@Kratos@@@Kratos@@V?$allocator@V?$intrusive_ptr@VCondition@Kratos@@@Kratos@@@std@@@5@@Kratos@@V?$allocator@V?$PointerVectorSet@VCondition@Kratos@@VIndexedObjec
t@2@U?$less@_K@std@@U?$equal_to@_K@5@V?$intrusive_ptr@VCondition@Kratos@@@2@V?$vector@V?$intrusive_ptr@VCondition@Kratos@@@Kratos@@V?$allocator@V?$intrusive_ptr@VCondition@Kratos
@@@Kratos@@@std@@@5@@Kratos@@@std@@@std@@AEBV?$PointerVectorSet@VCondition@Kratos@@VIndexedObject@2@U?$less@_K@std@@U?$equal_to@_K@5@V?$intrusive_ptr@VCondition@Kratos@@@2@V?$vec
tor@V?$intrusive_ptr@VCondition@Kratos@@@Kratos@@V?$allocator@V?$intrusive_ptr@VCondition@Kratos@@@Kratos@@@std@@@5@@1@@Z) sin resolver al que se hace referencia en la función "p
rivate: virtual void __cdecl Kratos::Testing::KratosHDF5TestSuite_HDF5_Internals_ConnectivitiesData2_Test::TestBody(void)" (?TestBody@KratosHDF5TestSuite_HDF5_Internals_Connectiv
itiesData2_Test@Testing@Kratos@@EEAAXXZ) [D:\Kratos\build\Release\applications\HDF5Application\KratosHDF5CoreTest.vcxproj]
test_hdf5_points_data.obj : error LNK2019: símbolo externo "void __cdecl Kratos::HDF5::WritePartitionTable(class Kratos::HDF5::File &,class std::basic_string<char,struct std::cha
r_traits<char>,class std::allocator<char> > const &,struct Kratos::HDF5::WriteInfo const &)" (?WritePartitionTable@HDF5@Kratos@@YAXAEAVFile@12@AEBV?$basic_string@DU?$char_traits@
D@std@@V?$allocator@D@2@@std@@AEBUWriteInfo@12@@Z) sin resolver al que se hace referencia en la función "public: void __cdecl Kratos::HDF5::Internals::PointsData<class Kratos::HD
F5::Internals::NodesIO>::Write(class Kratos::PointerVectorSet<class Kratos::Node,class Kratos::IndexedObject,struct std::less<unsigned __int64>,struct std::equal_to<unsigned __in
t64>,class Kratos::intrusive_ptr<class Kratos::Node>,class std::vector<class Kratos::intrusive_ptr<class Kratos::Node>,class std::allocator<class Kratos::intrusive_ptr<class Krat
os::Node> > > > const &,class Kratos::HDF5::Internals::NodesIO const &,class Kratos::Parameters)" (?Write@?$PointsData@VNodesIO@Internals@HDF5@Kratos@@@Internals@HDF5@Kratos@@QEA
AXAEBV?$PointerVectorSet@VNode@Kratos@@VIndexedObject@2@U?$less@_K@std@@U?$equal_to@_K@5@V?$intrusive_ptr@VNode@Kratos@@@2@V?$vector@V?$intrusive_ptr@VNode@Kratos@@@Kratos@@V?$al
locator@V?$intrusive_ptr@VNode@Kratos@@@Kratos@@@std@@@5@@4@AEBVNodesIO@234@VParameters@4@@Z) [D:\Kratos\build\Release\applications\HDF5Application\KratosHDF5CoreTest.vcxproj]
test_hdf5_points_data.obj : error LNK2019: símbolo externo "class std::tuple<unsigned int,unsigned int> __cdecl Kratos::HDF5::StartIndexAndBlockSize(class Kratos::HDF5::File &,cl
ass std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?StartIndexAndBlockSize@HDF5@Kratos@@YA?AV?$tuple@II@std@@AEAVFile@12@AEBV?$basic
_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@@Z) sin resolver al que se hace referencia en la función "public: class Kratos::Parameters __cdecl Kratos::HDF5::Internals::Poi
ntsData<class Kratos::HDF5::Internals::NodesIO>::Read(class Kratos::PointerVectorSet<class Kratos::Node,class Kratos::IndexedObject,struct std::less<unsigned __int64>,struct std:
:equal_to<unsigned __int64>,class Kratos::intrusive_ptr<class Kratos::Node>,class std::vector<class Kratos::intrusive_ptr<class Kratos::Node>,class std::allocator<class Kratos::i
ntrusive_ptr<class Kratos::Node> > > > &,class Kratos::HDF5::Internals::NodesIO const &)" (?Read@?$PointsData@VNodesIO@Internals@HDF5@Kratos@@@Internals@HDF5@Kratos@@QEAA?AVParam
eters@4@AEAV?$PointerVectorSet@VNode@Kratos@@VIndexedObject@2@U?$less@_K@std@@U?$equal_to@_K@5@V?$intrusive_ptr@VNode@Kratos@@@2@V?$vector@V?$intrusive_ptr@VNode@Kratos@@@Kratos@
@V?$allocator@V?$intrusive_ptr@VNode@Kratos@@@Kratos@@@std@@@5@@4@AEBVNodesIO@234@@Z) [D:\Kratos\build\Release\applications\HDF5Application\KratosHDF5CoreTest.vcxproj]
D:\Kratos\build\Release\applications\HDF5Application\Release\KratosHDF5CoreTest.exe : fatal error LNK1120: 4 externos sin resolver [D:\Kratos\build\Release\applications\HDF5Appli
cation\KratosHDF5CoreTest.vcxproj]
  KratosRomCoreTest.vcxproj -> D:\Kratos\build\Release\applications\RomApplication\Release\KratosRomCoreTest.exe
  KratosStructuralMechanicsCoreTest.vcxproj -> D:\Kratos\build\Release\applications\StructuralMechanicsApplication\Release\KratosStructuralMechanicsCoreTest.exe
  gtest_main.vcxproj -> D:\Kratos\build\Release\bin\Release\gtest_main.dll
  zlibstatic.vcxproj -> D:\Kratos\build\Release\external_libraries\zlib\Release\zlibstatic.lib

D:\Kratos\scripts>goto:eof
```
</details>

File: kratos/includes/data_communicator.h [hunk 3]
```diff
@@ -388,6 +388,7 @@ class KRATOS_API(KRATOS_CORE) DataCommunicator
     // Complete interface for basic types
 
     KRATOS_BASE_DATA_COMMUNICATOR_DECLARE_PUBLIC_INTERFACE_FOR_TYPE(char)
+    KRATOS_BASE_DATA_COMMUNICATOR_DECLARE_PUBLIC_INTERFACE_FOR_TYPE(unsigned char)
```
Comment (roigcarlo) [inline kratos/includes/data_communicator.h:391]: Please @roigcarlo remove this because the DataCommunicator interface does not support unsigned char reductions as it should be used with `MPI_BYTE` or `MPI_UNSIGNED_CHAR`

Comment (roigcarlo) [reply kratos/includes/data_communicator.h:391]: Ok will do once test pass

File: applications/HDF5Application/custom_io/hdf5_container_component_io.cpp [hunk 4]
```diff
@@ -260,16 +260,19 @@ bool ContainerComponentIO<TContainerType, TContainerDataIO, TComponents...>::Wri
...
-            KRATOS_ERROR_IF(availability_global_counts_pair[1] == availability_global_counts_pair[2])
+            const auto& availability_global_counts_pair = mpFile->GetDataCommunicator().SumAll(std::vector<int>{std::get<0>(availability_local_counts_pair), std::get<1>(availability_local_counts_pair)});
+            const auto& available_count = availability_global_counts_pair[0];
+            const auto& non_available_count = availability_global_counts_pair[1];
+
+            KRATOS_ERROR_IF(available_count == 0)
                 << "None of the entities in the container have \"" << rComponentName << "\" defined.";
 
-            if (availability_global_counts_pair[0] == availability_global_counts_pair[2]) {
+            if (non_available_count == 0) {
```
Comment (roigcarlo) [inline applications/HDF5Application/custom_io/hdf5_container_component_io.cpp]: @sunethwarna I am pretty sure this was the problems with the testing, because it was accessing `[2]` of the `availability` vector. Also, if the interface failed to do the casting from unsigned char to a type supported by the DataCommmunicator it did not calculate well the global values and failed while assigning `container_data_availability` (it also was checking a `[2]`).

This should fix all. I opted to change <unsigned char> to <unsigned int> because apparently the `DataCommunicator` interface fails with this type specifically (Probably this is why it wasn't there in the first place).

**Comment by roigcarlo** [comment]
Ping @sunethwarna

File: applications/HDF5Application/custom_io/hdf5_container_component_io.cpp (hunk 4 above)
Comment (sunethwarna) [reply applications/HDF5Application/custom_io/hdf5_container_component_io.cpp]: I am ok with the change, but I still don't understand why calling `[2]` was problematic, because in the following line, it should always have 3 components, last one being number of total components.
```c++
const auto& availability_global_counts_pair = mpFile->GetDataCommunicator().SumAll(std::vector<IndexType>{std::get<0>(availability_local_counts_pair), std::get<1>(availability_local_counts_pair), rLocalContainer.size()});
```

File: applications/HDF5Application/custom_io/hdf5_container_component_io.cpp [hunk 5]
```diff
@@ -247,10 +247,10 @@ bool ContainerComponentIO<TContainerType, TContainerDataIO, TComponents...>::Wri
         const auto& r_data_set_path = mComponentPrefix + rComponentName;
         const auto& r_component = KratosComponents<TComponentType>::Get(rComponentName);
 
-        std::vector<int> shape(value_type_traits::Dimension);
+        std::vector<unsigned int> shape(value_type_traits::Dimension);
 
         // first we have to check the availability
-        Vector<unsigned char> availability(rLocalContainer.size(), 1);
+        Vector<int> availability(rLocalContainer.size(), 1);
```
Comment (sunethwarna) [inline applications/HDF5Application/custom_io/hdf5_container_component_io.cpp]: This change will add an additional space cost when writing to H5 file, is this necessary?

File: applications/HDF5Application/custom_io/hdf5_container_component_io.cpp [hunk 6]
```diff
@@ -385,8 +388,8 @@ bool ContainerComponentIO<TContainerType, TContainerDataIO, TComponents...>::Rea
         const auto data_availability = attributes["__data_availability"].GetString();
 
         // there is no need to read data sets which cannot be set, hence can ignore the whole block
-        Vector<unsigned char> availability(BlockSize, 1);
-        if (data_availability != "CONSISTENTLY_UNAVAILABLE ") {
+        Vector<int> availability(BlockSize, 1);
```
Comment (sunethwarna) [inline applications/HDF5Application/custom_io/hdf5_container_component_io.cpp]: Same comment as before, if it is written as `int`, then it takes more space on the hard drive, which was the intention of using `unsigned char`.

File: applications/HDF5Application/custom_utilities/container_io_utils.h [hunk 7]
```diff
@@ -681,7 +681,7 @@ void CopyFromContiguousDataArray(
     const TContainerDataIO& rContainerDataIO,
     TDataType const* pBegin,
     const std::vector<unsigned int>& rShape,
-    const Vector<unsigned char>& rAvailability)
+    const Vector<int>& rAvailability)
```
Comment (sunethwarna) [inline applications/HDF5Application/custom_utilities/container_io_utils.h]: Same problem.

File: applications/HDF5Application/tests/test_hdf5_processes.py [hunk 8]
```diff
@@ -123,18 +123,18 @@ def test_SingleMeshTemporalOutputProcess(self):
...
         self.assertEqual(
-            self.HDF5File.call_args[0][0]['file_name'].GetString(), 'test_model_part.h5')
+            self.HDF5File.call_args[0][1]['file_name'].GetString(), 'test_model_part.h5')
         for time in [0.09999999, 0.19999998]:
             self.model_part.CloneTimeStep(time)
             self.model_part.ProcessInfo[KratosMultiphysics.STEP] += 1
             process.ExecuteFinalizeSolutionStep()
         self.assertEqual(self.HDF5File.call_count, 2)
-        self.assertEqual(self.HDF5File.call_args[0][0]['file_name'].GetString(
+        self.assertEqual(self.HDF5File.call_args[0][1]['file_name'].GetString(
```
Comment (sunethwarna) [inline applications/HDF5Application/tests/test_hdf5_processes.py:132]: Curious: Why the index changed?

Comment (roigcarlo) [reply applications/HDF5Application/tests/test_hdf5_processes.py:132]: This is because the self.HDF5File.call_args checks for the index of the argument in the `mock`. The deprecated version had the arguments in a different order, just that.

File: applications/HDF5Application/python_scripts/core/file_io.py [hunk 9]
```diff
@@ -28,13 +28,15 @@ def _FileSettings(self, model_part):
 class _HDF5SerialFileIO(_FileIO):
 
     def Get(self, model_part=None):
-        return KratosHDF5.HDF5File(self._FileSettings(model_part).Get())
+        # return KratosHDF5.HDF5File(self._FileSettings(model_part).Get())
+        return KratosHDF5.HDF5File(KratosMultiphysics.ParallelEnvironment.GetDefaultDataCommunicator(), self._FileSettings(model_part).Get())
```
Comment (roigcarlo) [inline applications/HDF5Application/python_scripts/core/file_io.py:32]: This is the reason for the change if index @sunethwarna

File: applications/HDF5Application/custom_io/hdf5_container_component_io.cpp (hunk 5 above)
Comment (roigcarlo) [reply applications/HDF5Application/custom_io/hdf5_container_component_io.cpp]: Ok, I think this is the problem, I must have changed this to `std::tuple<unsigned char, unsigned char>` to solve the windows type deduction error with the `auto` in line 263 and after seeing it was not working in the mpi communicator I just changed all `availability` references to `int` not only the comm one because I assumed the global and local vectors where of the same type.

Should work if the local is `unsigned char`. sorry 🙏

**Review by sunethwarna — APPROVED** [review]
Thanks @roigcarlo
