### PR TITLE
Mpi/bugfix strategy finalization

### LINKED ISSUE #3751: MPI crashes on exit
I get the following errors in almost every mpi-run (standard fluid simulation, nothing special), after the simulation finished succesfully
~~~
*** The MPI_Comm_free() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[(null):4883] Local abort after MPI_FINALIZE completed successfully; not able to aggregate error messages, and not able to guarantee that all other processes were killed!
~~~

@jcotela did you notice sth similar?
could be related to #77 I think
also FYI @roigcarlo

### PR DESCRIPTION
**Pull request by jcotela**
Fixes #3751 

Several epetra objects are deallocated within the `Finalize()` method of the python solver to ensure that they do not exist once `MPI_Finalize` is called (they hold pointers to MPI objects or perform MPI calls during destruction, so we need to be sure that they are freed in advance). This is again related to #77, since we have little control of destruction order in Python.

Unfortunately I could not find a way to completely skip having to call Strategy::Clear explicitly, since the situation is further complicated by lifetime dependencies between the trilinos ML solver (in fact its preconditioners) and the system matrix (they hold a reference to the system matrix and seem to use them somehow it during destruction, which was originally detected and solved by @msandre).

For now I have only fixed the issue for the classes used in the trilinos monolithic fluid solver (the one were this was originally reported). I'd ask for a review and, if this is considered to be the way forward, I will extend it to other classes and solvers.

### CODE REVIEW

**Comment by philbucher** [comment]
I tested this and it works for me
Unfortunately I could not reproduce the errors on my work-PC, I will try later with my laptop where I originally had the problems

File: kratos/solving_strategies/strategies/residualbased_newton_raphson_strategy.h [hunk 1]
```diff
@@ -247,6 +247,26 @@ class ResidualBasedNewtonRaphsonStrategy
      */
     ~ResidualBasedNewtonRaphsonStrategy() override
     {
+        // If the linear solver has not been deallocated, clean it before
+        // deallocating mpA. This prevents a memory error with the the ML
+        // solver (which holds a reference to it).
+        auto p_linear_solver = GetBuilderAndSolver()->GetLinearSystemSolver();
```
Comment (msandre) [inline kratos/solving_strategies/strategies/residualbased_newton_raphson_strategy.h:253]: Some of these lines are repeated in `Clear()`

```suggestion
        Clear();
        mpA.reset();
        mpDx.reset();
        mpb.reset();
```

**Review by msandre — DISMISSED** [review]

File: kratos/solving_strategies/strategies/residualbased_newton_raphson_strategy.h (hunk 1 above)
Comment (jcotela) [reply kratos/solving_strategies/strategies/residualbased_newton_raphson_strategy.h:253]: I know my solution is not the most elegant, but I need to reset the pointers before calling `Clear()`. Essentially, the point is that `TrilinosSpace::Clear()` does things that are not allowed after calling `MPI_Finalize` (which I have no way to control has not happened before this point).

**Comment by philbucher** [comment]
I still get the error message on my laptop:
~~~
[philipp-Aspire-VN7-592G:16773] Local abort after MPI_FINALIZE started completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
*** The MPI_Comm_free() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
~~~

I will bring it tmr such that we can see if I am doing sth wrong

EDIT: It did solve the problem, I was running a different case

**Comment by jcotela** [comment]
@philbucher the fractional step solver should finish cleanly now too.

File: kratos/solving_strategies/builder_and_solvers/builder_and_solver.h [hunk 2]
```diff
@@ -523,7 +523,7 @@ class BuilderAndSolver
     virtual void Clear()
     {
         this->mDofSet = DofsArrayType();
-        if (this->mpReactionsVector != nullptr) TSparseSpace::Clear(this->mpReactionsVector);
+        if (this->mpReactionsVector != nullptr) this->mpReactionsVector.reset();
```
Comment (philbucher) [inline kratos/solving_strategies/builder_and_solvers/builder_and_solver.h]: I think now you no longer need the `if`-check

File: kratos/solving_strategies/strategies/residualbased_linear_strategy.h [hunk 3]
```diff
@@ -221,6 +221,26 @@ class ResidualBasedLinearStrategy
...
+        // way Python garbage collection works, this may happen after
+        // MPI_Finalize has already been called and is an error. Resetting
+        // the pointers here prevents Clear from operating with the
+        // (now deallocated) vectors.
+        if (mpA != nullptr)
+            mpA.reset();
+        if (mpDx != nullptr)
+            mpDx.reset();
+        if (mpb != nullptr)
+            mpb.reset();
```
Comment (philbucher) [inline kratos/solving_strategies/strategies/residualbased_linear_strategy.h]: same

File: kratos/solving_strategies/strategies/residualbased_newton_raphson_strategy.h [hunk 4]
```diff
@@ -247,6 +247,26 @@ class ResidualBasedNewtonRaphsonStrategy
...
+        // way Python garbage collection works, this may happen after
+        // MPI_Finalize has already been called and is an error. Resetting
+        // the pointers here prevents Clear from operating with the
+        // (now deallocated) vectors.
+        if (mpA != nullptr)
+            mpA.reset();
+        if (mpDx != nullptr)
+            mpDx.reset();
+        if (mpb != nullptr)
+            mpb.reset();
```
Comment (philbucher) [inline kratos/solving_strategies/strategies/residualbased_newton_raphson_strategy.h]: same

File: applications/trilinos_application/custom_strategies/builder_and_solvers/trilinos_block_builder_and_solver.h [hunk 5]
```diff
@@ -830,6 +830,11 @@ class TrilinosBlockBuilderAndSolver
             }
             delete [] temp;
         }
+        else if (BaseType::mpReactionsVector == nullptr && this->mCalculateReactionsFlag)
+        {
+            TSystemVectorPointerType pNewReactionsVector = TSystemVectorPointerType(new TSystemVectorType(pDx->Map()) );
+            BaseType::mpReactionsVector.swap(pNewReactionsVector);
+        }
```
Comment (philbucher) [inline applications/trilinos_application/custom_strategies/builder_and_solvers/trilinos_block_builder_and_solver.h:837]: does the elimination-based-version also need this?

File: applications/FluidDynamicsApplication/python_scripts/trilinos_navier_stokes_solver_vmsmonolithic.py [hunk 6]
```diff
@@ -201,3 +201,6 @@ def Initialize(self):
         if self._IsPrintingRank():
             #TODO: CHANGE THIS ONCE THE MPI LOGGER IS IMPLEMENTED
             KratosMultiphysics.Logger.Print("Monolithic MPI solver initialization finished.")
+
+    def Finalize(self):
+        self.solver.Clear()
```
Comment (philbucher) [inline applications/FluidDynamicsApplication/python_scripts/trilinos_navier_stokes_solver_vmsmonolithic.py:206]: I think you should add a comment why this is necessary for the trilinos-version

**Review by philbucher — COMMENTED** [review]
looks ok to me, I will try it again

The `Clear` that is called in the destructor of the Strategy does not automatically solve this I assume?

File: kratos/solving_strategies/strategies/residualbased_newton_raphson_strategy.h (hunk 1 above)
Comment (msandre) [reply kratos/solving_strategies/strategies/residualbased_newton_raphson_strategy.h:253]: ok, then I think you don't need to call `Clear` in the destructor for the ML problem since you anyway clear the linear solver.

**Comment by msandre** [comment]
I'm find with it. @philbucher still has some comments so I will leave it to him to approve.

**Comment by philbucher** [comment]
I am running some final tests but this should be fine now

@KratosMultiphysics/technical-committee how about we add a call to solver.Clear() in the finalization of the analysis-stage? (in a separate PR ofc)
This would have two benefits:
1. If `Clear` is properly implemented in the solvers then the fix from this PR will automatically be applied too
2. In a multi-stage-analysis it might be good to clear the previous stages to free some memory.

What do you think?

**Review by philbucher — APPROVED** [review]
for me this works now for Monolithic and for FractionalStep

I will open a separate discussion abt calling the Clear of the solver in the finalize of the AnalysisStage

thanks for fixing @jcotela

**Comment by philbucher** [comment]
btw @jcotela you do have access to the strategy in the fluid_solver, so probably you should call the clear from there

**Comment by jcotela** [comment]
@philbucher regarding who calls the Clear, for me it is a problem of who owns and manages the strategy. Right now, in the fluid solvers it is the derived class who does it, so I prefer to keep the clear there too. I agree that it would be wiser to move this "ownership" to the base class, but I'd rather address this on a separate PR, probably during the next release cycle.

**Comment by philbucher** [comment]
@jcotela I know we discussed this, sorry for the confusion
I was looking at the base-solver, and also there are some calls to the strategy:
https://github.com/KratosMultiphysics/Kratos/blob/master/applications/FluidDynamicsApplication/python_scripts/fluid_solver.py#L118-L122

Thats why I thought you could put it there after all

Either way, #3972 should solve this on a global level

**Comment by jcotela** [comment]
@philbucher you are completely right, and this is why I believe that the ownership should be passed to the base class (otherwise the base class is calling members it does not have by itself). For now, I only added the clear to the classes that need it, since changing ownership would be a much more intrusive change.
