### PR TITLE
[GeoMechanicsApplication] Improve the error message for "GEO_SHEAR_CAPACITY" output

### LINKED ISSUE #13572: [GeoMechanicsApplication] Improve the error message for "GEO_SHEAR_CAPACITY" output
**Issue Description**
When using the linear version of the Quay Wall model, an error occurs due to the inclusion of the "GEO_SHEAR_CAPACITY" variable in the GiD output configuration. This variable depends on UMAT parameters, which are not defined in the context of a linear material. As a result, the calculation fails.

Currently, the error message is unclear and does not indicate the actual cause, namely, the incompatibility between the selected output and the material type. This can be misleading for users who are not aware of the internal dependency of "GEO_SHEAR_CAPACITY" on UMAT-based models.

**Suggested Improvement**
The error handling should be improved to explicitly state that "GEO_SHEAR_CAPACITY" requires a non-linear (UMAT-based) material, and that it cannot be evaluated when a linear material is used. This would help users more easily identify and correct the issue in their output configuration.

_A screenshot of the current error message is attached below for reference:_

Image

### PR DESCRIPTION
**Pull request by markelov208**
**📝 Description**
A brief description of the PR.

- Added try/catch in GetCohesion and GetFrictionAngleInDegrees
- Updated error messages

### CODE REVIEW

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_utilities/test_constitutive_law_utilities.cpp [hunk 1]
```diff
@@ -72,13 +72,17 @@ KRATOS_TEST_CASE_IN_SUITE(CohesionCanBeFetchedFromUMatParameters, KratosGeoMecha
     KRATOS_EXPECT_DOUBLE_EQ(ConstitutiveLawUtilities::GetCohesion(properties), 2.0);
 
     properties.Erase(INDEX_OF_UMAT_C_PARAMETER);
-    KRATOS_EXPECT_EXCEPTION_IS_THROWN(ConstitutiveLawUtilities::GetCohesion(properties),
-                                      "Material 0 does not have INDEX_OF_UMAT_C_PARAMETER");
+    KRATOS_EXPECT_EXCEPTION_IS_THROWN(
+        ConstitutiveLawUtilities::GetCohesion(properties),
+        "ConstitutiveLawUtilities::GetCohesion failed. There are no GEO_COHESION and underlying "
+        "UMAT Error: There is no INDEX_OF_UMAT_C_PARAMETER for material 0.");
```
Comment (rfaasse) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_utilities/test_constitutive_law_utilities.cpp]: This is already way clearer than it was before, thanks for picking this up! 

Nitpicking, but I would rephrase the error message slightly (and similar for the friction angle):
```suggestion
        "ConstitutiveLawUtilities::GetCohesion failed. There is no GEO_COHESION available and
        "attempting to get the cohesion from UMAT parameters resulted in the following error: "
        "There is no INDEX_OF_UMAT_C_PARAMETER for material 0.");
```
Curious what you think!

**Review by rfaasse — COMMENTED** [review]
Thanks for picking this up, good to see you found a way to fix it more easily than we thought! I have a minor suggestion for the message, curious what you think!

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_utilities/test_constitutive_law_utilities.cpp (hunk 1 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_utilities/test_constitutive_law_utilities.cpp]: @WPK4FEM and myself agree with this suggestion.

Comment (markelov208) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_utilities/test_constitutive_law_utilities.cpp]: Richard, thank you for the detailed message. Used it.

**Review by WPK4FEM — APPROVED** [review]
Thank you for picking up Richards suggestion. Looking at the overal state now, its possible to refactor a bit as the contents of GetCohesion and GetFrictionAngleInDegrees are very similar. I'm happy with its current state already.
