### PR TITLE
[Core] Tinyexpr wrapper Depends on space bug

### LINKED ISSUE #9681: Wrong parsing of functions in .json
**Description**
This piece of code is in charge of detecting if a function depends on space.

https://github.com/KratosMultiphysics/Kratos/blob/39cc4fcff426d57bb6d19e859dd3c3be05e6837e/kratos/utilities/function_parser_utility.cpp#L39-L46

this fails for something as simple as `exp(t)`, because it contains an `x`.

**Scope**
When a function is passed e.g. for a boundary condition

**To Reproduce**
Check out https://github.com/KratosMultiphysics/Kratos/pull/9679
This branch contains two unit tests showing the problem
```
(1.0)*(50*(cos(t)-2)) -> DependsOnSpace() : false
(1.0)*(50*(exp(t)-2)) -> DependsOnSpace() : true
```

**Expected behavior**
The tests should pass

**Environment**
- OS: Ubuntu Ubuntu 21.10
- Branch: bug-assign-vector-direction-condition
- Python 3.9.7

### PR DESCRIPTION
**Pull request by EduardGomezEscandell**
**📝 Description**
This PR is to exemplify issue https://github.com/KratosMultiphysics/Kratos/issues/9681

**🆕 Changelog**
- Added tests so show problem

### CODE REVIEW

**Comment by loumalouomega** [comment]
What's the problem?

**Comment by loumalouomega** [comment]
I implemented this BTW

**Comment by EduardGomezEscandell** [comment]
> What's the problem?

Sorry I forgot to link the issue
See here https://github.com/KratosMultiphysics/Kratos/issues/9681

**Review by loumalouomega — DISMISSED** [review]

File: kratos/utilities/function_parser_utility.cpp [hunk 1]
```diff
@@ -36,7 +60,7 @@ BasicGenericFunctionUtility::BasicGenericFunctionUtility(const std::string& rFun
     InitializeParser();
 
     // Check if it depends on space
-    if (mFunctionBody.find(std::string("x")) == std::string::npos &&
+    if (CheckThereIsNotx(mFunctionBody)                           &&
         mFunctionBody.find(std::string("y")) == std::string::npos &&
         mFunctionBody.find(std::string("z")) == std::string::npos &&
         mFunctionBody.find(std::string("X")) == std::string::npos &&
```
Comment (philbucher) [inline kratos/utilities/function_parser_utility.cpp:71]: wouldn't it be safer to check if the character are by themselves? I.e. not surrounded by other characters

Comment (loumalouomega) [reply kratos/utilities/function_parser_utility.cpp:71]: How do you check that is only x?, it is the same as saying not surrounded by other characters. If you find a character, you don't know if it is part of a keyword

Comment (philbucher) [reply kratos/utilities/function_parser_utility.cpp:71]: Depends if we allow e.g. `xy` or enforce `x*y`
not saying I am correct, just giving my thoughts

Comment (loumalouomega) [reply kratos/utilities/function_parser_utility.cpp:71]: IMO this is the easiest way with the least corner cases

File: kratos/utilities/function_parser_utility.cpp [hunk 2]
```diff
@@ -23,6 +23,30 @@
 namespace Kratos
 {
 
+// A check only to check that the x is not part of exp
+inline bool CheckThereIsNotx(const std::string& rString)
```
Comment (philbucher) [inline kratos/utilities/function_parser_utility.cpp:28]: as it is, it seems to only check for the first x

what abt sth like `exp(2)*x`?

=> maybe you could improve the algorithm by removing all occurrences of `exp` and then checking again
You could even implement it in a way that it removes all fct names before checking (and the fct names to be removed could be extended if necessary)

Comment (philbucher) [reply kratos/utilities/function_parser_utility.cpp:28]: i.e. 
~~~c++
for (const auto& r_keyword : {"exp"}) {
    StringUtilities::ReplaceAllSubstrings(r_keyword, rString, "");
}

~~~

Comment (loumalouomega) [reply kratos/utilities/function_parser_utility.cpp:28]: My code checks all x, see again, the first line only check if thee is at least one x

Comment (loumalouomega) [reply kratos/utilities/function_parser_utility.cpp:28]: > i.e.
> 
> ```c++
> for (const auto& r_keyword : {"exp"}) {
>     StringUtilities::ReplaceAllSubstrings(r_keyword, rString, "");
> }
> ```

I don't want to do that, I have bad experience in the past

Comment (loumalouomega) [reply kratos/utilities/function_parser_utility.cpp:28]: > as it is, it seems to only check for the first x
> 
> what abt sth like `exp(2)*x`?

That will work, check yourself

**Comment by loumalouomega** [comment]
> I could translate it to C++ if necessary. Thoughts?

The problem is from our side, I rather prefer the suggestion from @philbucher

**Comment by loumalouomega** [comment]
> > I could translate it to C++ if necessary. Thoughts?
> 
> The problem is from our side, I rather prefer the suggestion from @philbucher

But I prefer my proposal

**Comment by miguelmaso** [comment]
`sqrt` -> depends on time
I don't know if it's relevant

File: kratos/utilities/function_parser_utility.cpp (hunk 1 above)
Comment (oberbichler) [reply kratos/utilities/function_parser_utility.cpp:71]: `std::regex_search(expr, std::regex("\\b[xyz]\\b"))`?

Comment (loumalouomega) [reply kratos/utilities/function_parser_utility.cpp:71]: Good idea but does not work, I am not experienced in regex enough to do the correct reguar expression

Comment (loumalouomega) [reply kratos/utilities/function_parser_utility.cpp:71]: image

Comment (loumalouomega) [reply kratos/utilities/function_parser_utility.cpp:71]: Fixed with  regex like a pro, thanks @oberbichler 

image

Today I learned regex

**Review by loumalouomega — DISMISSED** [review]

File: kratos/utilities/function_parser_utility.cpp (hunk 1 above)
Comment (oberbichler) [reply kratos/utilities/function_parser_utility.cpp:71]: `\b...\b` is similar to "Match Whole Word" in VS Code search function. `[xyz]` matches any of the chars. There is also an option for case-insensitivity. Just wondering why [`\b[xyzXYZ]\b` is not equivalent to "depends on space"](https://regex101.com/r/SzNK98/1) and [`\bt\b` to "depends on time"](https://regex101.com/r/T9TIny/1). The xy=x*y thing?

[...and keep in mind ;)](http://regex.info/blog/2006-09-15/247)

Comment (loumalouomega) [reply kratos/utilities/function_parser_utility.cpp:71]: With the regex looks like it fails, do not know why

Comment (loumalouomega) [reply kratos/utilities/function_parser_utility.cpp:71]: I reverted the regex, I am unable to translate to C++ a proper regex code to work:  https://regex101.com/r/YYDMKo/1 , this works, but once I translate to C++ it does not work

Comment (EduardGomezEscandell) [reply kratos/utilities/function_parser_utility.cpp:71]: This is quite strange because the same code seems to compile and run just fine in isolation:

https://godbolt.org/z/r993dbqxe

Comment (loumalouomega) [reply kratos/utilities/function_parser_utility.cpp:71]: The problem is not that, the problem is that "x" and "2*x" does not work, so you need an additional check, that in C++ fails, but in JS not

Comment (oberbichler) [reply kratos/utilities/function_parser_utility.cpp:71]: I thought that it might be enough to search for `xyz` or `t` (instead of checking for non-"exp"/non-"sqrt")

https://godbolt.org/z/hc41PYr7P

but I am probably missing some corner cases(?)

Comment (loumalouomega) [reply kratos/utilities/function_parser_utility.cpp:71]: I tried that the other day, and it didn't work, I will try again

Comment (loumalouomega) [reply kratos/utilities/function_parser_utility.cpp:71]: According to this should work now: https://regex101.com/r/upucEk/1

**Review by loumalouomega — DISMISSED** [review]

**Comment by oberbichler** [comment]
I'm not sure but Centos probably doesn't work because of gcc 4.8. regex support was introduced in 2014 with gcc 4.9. Too bad for the one-liner 🤷

Maybe revert to the working solution and add a comment for future development. The AST solution is also very nice but I guess more work.

**Comment by loumalouomega** [comment]
> I'm not sure but Centos probably doesn't work because of gcc 4.8. regex support was introduced in 2014 with gcc 4.9. Too bad for the one-liner shrug
> 
> Maybe revert to the working solution and add a comment for future development. The AST solution is also very nice but I guess more work.

Effectively...

**Review by loumalouomega — DISMISSED** [review]
Ready to merge

File: kratos/utilities/function_parser_utility.cpp [hunk 3]
```diff
@@ -12,6 +12,9 @@
 //
 
 // System includes
+#ifdef KRATOS_MODERN_REGEX
+    #include <regex>
+#endif
```
Comment (philbucher) [inline kratos/utilities/function_parser_utility.cpp]: why is this needed?

Comment (loumalouomega) [reply kratos/utilities/function_parser_utility.cpp]: Because centos... (minimal version of gcc required for regex is 4.9, centos uses 4.8)

Comment (philbucher) [inline kratos/utilities/function_parser_utility.cpp]:
```suggestion
#if defined __has_include
    if __has_include(<regex>)
        #define KRATOS_MODERN_REGEX
    #endif
#endif

#ifdef KRATOS_MODERN_REGEX
    #include <regex>
#endif
```

this way would be more modern and automatic
or sth in that direction

Comment (philbucher) [reply kratos/utilities/function_parser_utility.cpp]: `__has_include` is officially C++17, but already supported by most compilers afaik
https://en.cppreference.com/w/cpp/preprocessor/include

Comment (loumalouomega) [reply kratos/utilities/function_parser_utility.cpp]: Is not a problem of compilation, is a problem of full support (apparently in 4.8, the regex support is partial)

Comment (philbucher) [reply kratos/utilities/function_parser_utility.cpp]: ah ok
hm maybe then the following:
```suggestion
#if !(defined(__GNUC__) && !defined(__clang__) && (__GNUC__ < 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ < 9))))
    #include <regex>
#endif
```

from here:
https://github.com/KratosMultiphysics/Kratos/blob/9ea10775243e921f8caaa115eaca4a235ab9cb4d/applications/HDF5Application/custom_io/hdf5_file.cpp#L22

Comment (loumalouomega) [reply kratos/utilities/function_parser_utility.cpp]: So, you want to avoid the KRATOS_MODERN_REGEX macro?

Comment (philbucher) [reply kratos/utilities/function_parser_utility.cpp]: yes

Comment (loumalouomega) [reply kratos/utilities/function_parser_utility.cpp]: Do I also remove it?

File: kratos/utilities/function_parser_utility.cpp [hunk 4]
```diff
@@ -36,14 +67,19 @@ BasicGenericFunctionUtility::BasicGenericFunctionUtility(const std::string& rFun
     InitializeParser();
 
     // Check if it depends on space
-    if (mFunctionBody.find(std::string("x")) == std::string::npos &&
+#ifdef KRATOS_MODERN_REGEX
```
Comment (loumalouomega) [inline kratos/utilities/function_parser_utility.cpp]:
```suggestion
#if !(defined(__GNUC__) && !defined(__clang__) && (__GNUC__ < 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ < 9))))
```

**Review by loumalouomega — DISMISSED** [review]

**Review by loumalouomega — APPROVED** [review]

**Review by philbucher — APPROVED** [review]

**Comment by loumalouomega** [comment]
@EduardGomezEscandell feel free to merge
