### PR TITLE
Geo/13720 has function umat constitutive law

### LINKED ISSUE #13720: [GeoMechanicsApplication] Persistence of State Parameters across stages does not work for UMAT materials
Just like for UDSM materials the Has function is not implemented.

- implement Has function
- provide unit tests for functionality of Has function

### PR DESCRIPTION
**Pull request by WPK4FEM**
**📝 Description**
Add missing Has function to UMAT constitutive laws.

**🆕 Changelog**
- Has added to .hpp and .cpp for umat constitutive law
- Added unit test.

### CODE REVIEW

File: applications/GeoMechanicsApplication/custom_constitutive/small_strain_umat_law.cpp [hunk 1]
```diff
@@ -776,6 +776,12 @@ void SmallStrainUMATLaw<TVoigtSize>::SetValue(const Variable<Vector>& rVariable,
     }
 }
 
+template <SizeType TVoigtSize>
+bool SmallStrainUMATLaw<TVoigtSize>::Has(const Variable<Vector>& rThisVariable)
```
Comment (markelov208) [inline applications/GeoMechanicsApplication/custom_constitutive/small_strain_umat_law.cpp]: Recently, Anne has changed `rThisVariable `on `rVariable`. Please could you do it for this file. There is a  mixture of these names right now.

File: applications/GeoMechanicsApplication/custom_constitutive/small_strain_umat_law.hpp [hunk 2]
```diff
@@ -297,9 +297,11 @@ class KRATOS_API(GEO_MECHANICS_APPLICATION) SmallStrainUMATLaw : public Constitu
 
     using ConstitutiveLaw::SetValue;
     void SetValue(const Variable<double>& rVariable, const double& rValue, const ProcessInfo& rCurrentProcessInfo) override;
-
     void SetValue(const Variable<Vector>& rVariable, const Vector& rValue, const ProcessInfo& rCurrentProcessInfo) override;
 
+    using ConstitutiveLaw::Has;
+    bool Has(const Variable<Vector>& rThisVariable) override;
```
Comment (markelov208) [inline applications/GeoMechanicsApplication/custom_constitutive/small_strain_umat_law.hpp]: Here is `rThisVariable`. If you are going to change it on `rVariable` in cpp file, please do it as well.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_small_strain_umat_law.cpp [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+//  Main authors:    Wijtze Pieter Kikstra
+//
+
+#include "custom_constitutive/small_strain_umat_2D_plane_strain_law.hpp"
+#include "custom_constitutive/three_dimensional.h"
+#include "tests/cpp_tests/geo_mechanics_fast_suite.h"
+
+#include <string>
+
+using namespace std::string_literals;
```
Comment (markelov208) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_small_strain_umat_law.cpp]: There is no need in these two lines.

**Review by markelov208 — COMMENTED** [review]
Dear Wijtze Pieter, thank you very much for this nice small PR. I've made a few short comments.

File: applications/GeoMechanicsApplication/custom_constitutive/small_strain_umat_law.cpp (hunk 1 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_constitutive/small_strain_umat_law.cpp]: Done

File: applications/GeoMechanicsApplication/custom_constitutive/small_strain_umat_law.hpp (hunk 2 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_constitutive/small_strain_umat_law.hpp]: Done

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_small_strain_umat_law.cpp (hunk 3 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_small_strain_umat_law.cpp]: Removed

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_small_strain_umat_law.cpp [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+#include "custom_constitutive/three_dimensional.h"
+#include "tests/cpp_tests/geo_mechanics_fast_suite.h"
+
+namespace Kratos::Testing
+{
+
+KRATOS_TEST_CASE_IN_SUITE(SmallStrainUMATLaw_HasReturnsTrueForCauchyStress, KratosGeoMechanicsFastSuiteWithoutKernel)
+{
+    // Arrange
+    auto umat_law = SmallStrainUMAT2DPlaneStrainLaw{std::make_unique<ThreeDimensional>()};
```
Comment (rfaasse) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_small_strain_umat_law.cpp:28]: Doesn't matter for the test, but since the law is 2d plane strain, I'd use the PlaneStrain ConstitutiveLawDimension to avoid confusion
```suggestion
    auto umat_law = SmallStrainUMAT2DPlaneStrainLaw{std::make_unique<PlaneStrain>()};
```

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_small_strain_umat_law.cpp [hunk 5]
```diff
@@ -0,0 +1,31 @@
...
+//
+
+#include "custom_constitutive/small_strain_umat_2D_plane_strain_law.hpp"
+#include "custom_constitutive/three_dimensional.h"
+#include "tests/cpp_tests/geo_mechanics_fast_suite.h"
+
+namespace Kratos::Testing
+{
+
+KRATOS_TEST_CASE_IN_SUITE(SmallStrainUMATLaw_HasReturnsTrueForCauchyStress, KratosGeoMechanicsFastSuiteWithoutKernel)
```
Comment (rfaasse) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_small_strain_umat_law.cpp]: For completeness you could add:
```suggestion
KRATOS_TEST_CASE_IN_SUITE(SmallStrainUMATLaw_HasReturnsTrueForCauchyStressAndStateVariables, KratosGeoMechanicsFastSuiteWithoutKernel)
```

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_small_strain_umat_law.cpp [hunk 6]
```diff
@@ -0,0 +1,31 @@
...
+{
+    // Arrange
+    auto umat_law = SmallStrainUMAT2DPlaneStrainLaw{std::make_unique<ThreeDimensional>()};
+
+    // Act & Assert
+    KRATOS_EXPECT_TRUE(umat_law.Has(STATE_VARIABLES));
+    KRATOS_EXPECT_TRUE(umat_law.Has(CAUCHY_STRESS_VECTOR));
+    KRATOS_EXPECT_FALSE(umat_law.Has(TOTAL_STRESS_VECTOR));
```
Comment (rfaasse) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_small_strain_umat_law.cpp]: Instead of three asserts in one test, we could use a parametrized test, which Variable<Vector> and bool as input and expected output. An example can be found [here](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/GeoMechanicsApplication/tests/cpp_tests/custom_elements/test_integration_schemes.cpp#L111-L132) (or of course let me or Anne know, then we can help out)

File: applications/GeoMechanicsApplication/custom_constitutive/small_strain_umat_law.cpp [hunk 7]
```diff
@@ -770,12 +768,18 @@ void SmallStrainUMATLaw<TVoigtSize>::SetValue(const Variable<Vector>& rVariable,
                                               const ProcessInfo&      rCurrentProcessInfo)
 {
     if ((rVariable == STATE_VARIABLES) && (rValue.size() == mStateVariablesFinalized.size())) {
-        std::copy(rValue.begin(), rValue.end(), mStateVariablesFinalized.begin());
+        std::ranges::copy(rValue, mStateVariablesFinalized.begin());
```
Comment (rfaasse) [inline applications/GeoMechanicsApplication/custom_constitutive/small_strain_umat_law.cpp:771]: Nice!

File: applications/GeoMechanicsApplication/custom_constitutive/small_strain_umat_law.cpp [hunk 8]
```diff
@@ -205,7 +203,7 @@ int SmallStrainUMATLaw<TVoigtSize>::Check(const Properties&   rMaterialPropertie
                                           const ProcessInfo&  rCurrentProcessInfo) const
 {
     // Verify Properties variables
-    if (!rMaterialProperties.Has(UDSM_NAME) || rMaterialProperties[UDSM_NAME] == "")
+    if (!rMaterialProperties.Has(UDSM_NAME) || rMaterialProperties[UDSM_NAME].empty())
```
Comment (rfaasse) [inline applications/GeoMechanicsApplication/custom_constitutive/small_strain_umat_law.cpp:206]: This might clash with Gennady's PR, but it won't be a big clash I think, so we could still do it.

**Review by rfaasse — DISMISSED** [review]
Looks good, thanks for adding this! I have some non-blocking suggestions for improvements (mainly in the test), but this is close to ready to go!

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_small_strain_umat_law.cpp (hunk 4 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_small_strain_umat_law.cpp:28]: After looking together: No this needs to be ThreeDimensional.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_small_strain_umat_law.cpp (hunk 5 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_small_strain_umat_law.cpp]: After refactoring to a parameterized test, we have choosen another name together.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_small_strain_umat_law.cpp (hunk 6 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_small_strain_umat_law.cpp]: With you help done.

File: applications/GeoMechanicsApplication/custom_constitutive/small_strain_umat_law.cpp (hunk 7 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_constitutive/small_strain_umat_law.cpp:771]: Thank you, but with inspiration from another file.

File: applications/GeoMechanicsApplication/custom_constitutive/small_strain_umat_law.cpp (hunk 8 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_constitutive/small_strain_umat_law.cpp:206]: We'll see.

**Review by rfaasse — APPROVED** [review]
Thanks for processing the review comments, to me this is good to go!
