### PR TITLE
[Core] improve AtomicUtilities

### LINKED ISSUE #8125: [Core][OpenMP] AtomicAdd template argument deduction issue
**Description**
Take these two functions (or any other feasible use case for the `AtomicAdd`)
```c++
template<>
void VariableRedistributionUtility::ThreadsafeAdd<double>(
    double& rLHS,
    const double& rRHS)
{
    AtomicAdd(rLHS,rRHS);
}

template<>
void VariableRedistributionUtility::ThreadsafeAdd< array_1d<double,3> >(
    array_1d<double,3>& rLHS,
    const array_1d<double,3>& rRHS)
{
    AtomicAdd(rLHS, rRHS);
}
```
This should be possible to be done. However, since the two vector types are the same in the second function (`array_1d<double,3>`), the compiler tries to access the second function in the `AtomicUtilitites`
```c++
template<class TDataType>
inline void AtomicAdd(TDataType& target, const TDataType& value ) {
    #pragma omp atomic
    target += value;
}
```
which of course leads to a compiler error in the addition.

**Scope**
- KratosCore

**To Reproduce**
(see above)

**Expected behavior**
This is obviously solved by specifying the types as
```c++
template<>
void VariableRedistributionUtility::ThreadsafeAdd<double>(
    double& rLHS,
    const double& rRHS)
{
    AtomicAdd<double>(rLHS,rRHS);
}

template<>
void VariableRedistributionUtility::ThreadsafeAdd< array_1d<double,3> >(
    array_1d<double,3>& rLHS,
    const array_1d<double,3>& rRHS)
{
    AtomicAdd<array_1d<double,3>, array_1d<double,3>>(rLHS, rRHS);
}
```
In my opinion, this limits the usability and brings the question if we should try to figure out an alternative implementation of this. Maybe this is the best we can do and we need to live with that.

**Environment**
(any environment)

### PR DESCRIPTION
**Pull request by philbucher**
**Description**
This PR improves the AtomicUtilities by solving the template deduction issues, see #8125 
Also adds a missing method

Closes #8125

### CODE REVIEW

File: kratos/utilities/variable_redistribution_utility.cpp [hunk 1]
```diff
@@ -604,7 +604,7 @@ void VariableRedistributionUtility::UpdateDistributionRHS(
             for (unsigned int k = 0; k < TNumNodes; k++) {
                 rhs_j -= size * rMassMatrix(j,k) * AuxiliaryGet<TIsHistorical>(rDistributedVariable, r_geometry[k]);
             }
-            ThreadsafeAdd(r_geometry[j].GetValue(rhs_variable), rhs_j);
```
Comment (philbucher) [inline kratos/utilities/variable_redistribution_utility.cpp:607]: @rubenzorrilla now it works properly even without those helpers!

**Comment by philbucher** [comment]
@RiccardoRossi I think this works quite nicely now
The specialization with `array_1d<double, 3>` will also come in handy in other places!
Now e.g. `SumReduction` will work out of the box also for `array_1d<double, 3>`!

FYI @ashishdarekar I already fixed the issue you found today, you can remove the hack with the `Array3Reduction` after this is merged

**Review by RiccardoRossi — DISMISSED** [review]

**Comment by philbucher** [comment]
@RiccardoRossi I had to make a minor fix can you reapprove please?

**Review by RiccardoRossi — APPROVED** [review]
