### PR TITLE
Fix memory tests

### LINKED ISSUE #7743: Thread safety issue in test_chunk.cpp
**Description**
I have been running kratos tests and I noticed that test_chunk is failing from time to time for different num threads. I get this error message:
Error: Error: Check failed because the_vector[i] is equal to nullptr for i = 98 and repeat = 21
   in: kratos/tests/cpp_tests/sources/test_chunk.cpp:137:virtual void Testing::TestChunkParallelAllocateDeallocate::TestFunction()Exception

**Scope**
- cpp tests

**To Reproduce**
I am running run_tests.py and run_cpp_tests.py. Specially it fails when I set OMP_NUM_THREADS=16. 

**Environment**
- OS: Fedora 7.7
- Branch: master
- Python 3.6

### PR DESCRIPTION
**Pull request by roigcarlo**
**Description**
Fixes chunk tests.

Probably the confusion was because `LockObject::GetNumberOfThreads` is translated to `OpenMPUtils::GetNumThreads` instead of `OpenMPUtils::GetCurrentNumberOfThreads` which was causing that `max_threads` in the tests to be evaluated always to 1.

I've also extended the chunk tests so it checks initialization both for the single thread case and with OpenMp. This should give a hint on what the value of max_threads should be if it happens again.

@RezaNajian could you confirm you no longer get the error? I've tried up to 128 and seems to be ok.

@pooyan-dadvand I suspect something similar could happen to the memory pool tests (the disabled one to be precise), but I do not fully understand them, maybe its worth to take a look.

Fixes #7743

**Changelog**
- Fix chunk tests.

### CODE REVIEW

File: kratos/tests/cpp_tests/sources/test_chunk.cpp [hunk 1]
```diff
@@ -30,25 +30,76 @@ namespace Kratos {
...
+			chunk.Initialize();
+
+			std::size_t block_size_after_alignment = 8;
+			std::size_t available_blocks_should_be = (chunk_size_in_bytes - 2* max_threads * sizeof(Chunk::SizeType)) / block_size_after_alignment;
+			KRATOS_CHECK_EQUAL(chunk.GetNumberOfAvailableBlocks(), available_blocks_should_be) << " Available block :" << chunk.GetNumberOfAvailableBlocks() << " vs " << available_blocks_should_be;
+		}
+
+		KRATOS_TEST_CASE_IN_SUITE(ChunkInitializeSmallBlock, KratosCoreFastSuite)
+		{
+			int max_threads = OpenMPUtils::GetCurrentNumberOfThreads();
```
Comment (philbucher) [inline kratos/tests/cpp_tests/sources/test_chunk.cpp:47]: shouldn't this also be `GetNumThreads`?

**Review by philbucher — COMMENTED** [review]
I confirm that this fixes the errors (which I could reproduce now with 16 threads, but not with 2 like the CI has)

File: kratos/tests/cpp_tests/sources/test_chunk.cpp (hunk 1 above)
Comment (roigcarlo) [reply kratos/tests/cpp_tests/sources/test_chunk.cpp:47]: Not for this case. This is a bit misleading, that's why I split into `Initialize` and `InitializeParallel`. In this case the chunk is being called by a single thread context, so the max_threads will be one, which is consistent with the definition of `GetCurrentNumberOfThreads()`. We could use one, but this is better if a user copy/pastes this piece of code, as internally the chunk uses the same call.

Comment (philbucher) [reply kratos/tests/cpp_tests/sources/test_chunk.cpp:47]: ok!

**Review by philbucher — APPROVED** [review]
approving as this fixes some nasty failures and @pooyan-dadvand anyway wants to refactor/take a closer look

thx @roigcarlo
