### PR TITLE
[Core] SVD utils throwing error with no rectangular matrices

### LINKED ISSUE #8535: [Core] SVD utils not working with rectangular matrices
**Description**
I tried the SVD decomposition in the `svd_utils` with a rectangular matrix (m>n) and, as far as I understand, it is not working properly as the product of SVD doesn't give the original matrix. This is not happening with square matrices.

Aside of this, we should throw an error to inform the user that m must be larger than n. Right now it is only documented in the code meaning that the utility just segfaults without any information.

### PR DESCRIPTION
**Pull request by loumalouomega**
**Description**
Fixes #8535. "Fixes"

**Changelog**
- SVD utils throwing error with no rectangular matrices

### CODE REVIEW

File: kratos/utilities/svd_utils.h [hunk 1]
```diff
@@ -186,6 +177,7 @@ class SVDUtils
     {
         const SizeType m = InputMatrix.size1();
         const SizeType n = InputMatrix.size2();
+    	KRATOS_ERROR_IF(m != n) << "Current Jacobi implementation only works with square matrices" << std::endl;
```
Comment (rubenzorrilla) [inline kratos/utilities/svd_utils.h]:
```suggestion
        KRATOS_ERROR_IF(m != n) << "Current Jacobi implementation only works with square matrices. Use \'LinearSolversApplication\' decompositions instead." << std::endl;
```

**Review by rubenzorrilla — APPROVED** [review]
Thanks!
