### PR TITLE
Fixing print macros

### LINKED ISSUE #2800: [Logger] KRATOS_WARNING_ONCE does not compile
Using `KRATOS_WARNING_ONCE` results in the following compiler error (GCC 5.4)
~~~
/home/philippb/software/Kratos_Master/kratos/input_output/logger.h:253:108: error: ‘__COUNT__’ was not declared in this scope
 #define KRATOS_WARNING_ONCE(label) static int KRATOS_LOG_OCCURRENCES = -1; if (++KRATOS_LOG_OCCURRENCES == __COUNT__) Logger(label) << KRATOS_CODE_LOCATION << Logger::Severity::WARNING

~~~

### PR DESCRIPTION
**Pull request by roigcarlo**
Fixes #2800, the tests for warning level, the detail and future trace macros and adds tests for the detail level.

### CODE REVIEW

File: kratos/tests/input_output/test_logger.cpp [hunk 1]
```diff
@@ -142,34 +142,34 @@ namespace Kratos {
...
         {
             static std::stringstream buffer;
-			LoggerOutput::Pointer p_output(new LoggerOutput(buffer));
-			Logger::AddOutput(p_output);
+            LoggerOutput::Pointer p_output(new LoggerOutput(buffer));
+            Logger::AddOutput(p_output);
 
-            KRATOS_INFO_IF("TestWarning", true) << "Test warning message";
-            KRATOS_INFO_IF("TestWarning", false) << "This should not appear";
+            KRATOS_WARNING_IF("TestWarning", true) << "Test warning message";
```
Comment (philbucher) [inline kratos/tests/input_output/test_logger.cpp:159]: Shouldn't both variants be tested?
Or is that handled internally through the level?

**Review by philbucher — APPROVED** [review]
Thanks @roigcarlo 
works, see #2813

File: kratos/tests/input_output/test_logger.cpp (hunk 1 above)
Comment (roigcarlo) [reply kratos/tests/input_output/test_logger.cpp:159]: Mm not sure what you mean. Which variant is not tested? I may have missed a test :S

Comment (philbucher) [reply kratos/tests/input_output/test_logger.cpp:159]: You change `KRATOS_INFO_IF` to `KRATOS_WARNING_IF`
Are they both using the same implementation with the only difference that they internally use another severity lvl?

Comment (roigcarlo) [reply kratos/tests/input_output/test_logger.cpp:159]: Yes

Comment (roigcarlo) [reply kratos/tests/input_output/test_logger.cpp:159]: For example, if you look at the tests for the "detail" level, I had to specify explicitly the output level, otherwise it wouldn't have printed anything. 

I can make the same for the warning and info levels if it is clearer.

**Comment by roigcarlo** [comment]
I'll merge if its ok since its blocking the other PR

**Comment by philbucher** [comment]
thx
