### PR TITLE
[GeoMechanicsApplication] Avoid division by zero when calculating Lode angle

### LINKED ISSUE #13164: [GeoMechanicsApplication] Investigate unbalance /convergence in the null step
Look into how Plaxis does it.
Also look at if our new Mohr-Coulomb has the same issue.
Need to check the soil model (Mostly failing with Mohr-Coulomb).

Link to the Gravity wall issue:
[Investigate and improve the Gravity Wall Reliability Benchmark](https://github.com/Deltares/FEA-Tools/issues/132)

### LINKED ISSUE #13166: [GeoMechanicsApplication] Fix issue in Lode's angle calculation
In `StressStrainUtilities::CalculateLodeAngle`, when the argument passed to `std::asin` (i.e. `(-27. / 2.) * numerator / (q * q * q)`) is close to either 1 or -1, it returns a `NaN` value. We can fix it by testing for values close to 1 and -1, and return the expected value (i.e. $`\frac{\pi}{6}`$ when the argument is close to 1, and $`-\frac{\pi}{6}`$ when the argument is close to -1).

### PR DESCRIPTION
**Pull request by avdg81**
**📝 Description**
When calculating Lode angle, avoid division by zero. When the Von Mises stress equals (nearly) zero, Lode angle should be zero, too.

**🆕 Changelog**
Other changes include:
- No special handling is needed when the `numerator` equals (nearly) zero.
- The calculation of Lode angle first checks for the special case where the Von Mises stress equals (nearly) zero. Only calculate the principal stresses and eigenvectors when they are needed, rather than upfront.
- Avoid a domain error raised by `std::asin` by clamping the input value to [-1, +1].
- Reuse a vector instance in the unit test for the calculation of Lode angle.
- Added some comments to the unit test to make clear that all relevant cases (i.e. triaxial extension [TXE], triaxial compression [TXC], and shear [SHR]) have been covered.

### CODE REVIEW

File: applications/GeoMechanicsApplication/custom_utilities/stress_strain_utilities.cpp [hunk 1]
```diff
@@ -64,14 +64,16 @@ double StressStrainUtilities::CalculateLodeAngle(const Vector& rStressVector)
...
-    const double p                   = CalculateMeanStress(rStressVector);
-    const double q                   = CalculateVonMisesStress(rStressVector);
-    const Matrix local_stress_tensor = MathUtils<double>::StressVectorToTensor(rStressVector);
-    Matrix       sigma_princi;
-    Matrix       eigen_vectors;
-    MathUtils<double>::GaussSeidelEigenSystem(local_stress_tensor, eigen_vectors, sigma_princi, 1.0e-16, 20);
-    const double numerator = (sigma_princi(0, 0) - p) * (sigma_princi(1, 1) - p) * (sigma_princi(2, 2) - p);
-    if (std::abs(numerator) < 1.0E-12) return 0.;
+    const auto q = CalculateVonMisesStress(rStressVector);
+    if (constexpr auto tolerance = 1.0E-12; q < tolerance) return 0.0;
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/custom_utilities/stress_strain_utilities.cpp:68]: Shouldn't we use something like Defaults::absolute_tolerance?
The 1.0e-16 that I managed to put on line 72 is equally bad.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_utilities/test_stress_strain_utitlities.cpp [hunk 2]
```diff
@@ -58,15 +58,17 @@ KRATOS_TEST_CASE_IN_SUITE(CheckCalculateVonMisesStressPureShear, KratosGeoMechan
...
     stress_vector <<= 0.5, -1.0, 0.5, 0.0;
     KRATOS_EXPECT_DOUBLE_EQ(MathUtils<>::DegreesToRadians(30.),
                             StressStrainUtilities::CalculateLodeAngle(stress_vector));
+    // Validate Triaxial Compression (TXC)
     KRATOS_EXPECT_DOUBLE_EQ(MathUtils<>::DegreesToRadians(-30.),
                             StressStrainUtilities::CalculateLodeAngle(-1. * stress_vector));
-    Vector stress_vector2(4);
-    stress_vector2 <<= -1.0, 0.0, 1.0, 0.0;
+    // Validate Shear (SHR)
+    stress_vector <<= -1.0, 0.0, 1.0, 0.0;
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_utilities/test_stress_strain_utitlities.cpp:69]: No clue why I introduced an extra variable before. This is clearer.

File: applications/GeoMechanicsApplication/custom_utilities/stress_strain_utilities.cpp [hunk 3]
```diff
@@ -64,14 +64,16 @@ double StressStrainUtilities::CalculateLodeAngle(const Vector& rStressVector)
...
+
+    Matrix sigma_princi;
+    Matrix eigen_vectors;
+    MathUtils<>::GaussSeidelEigenSystem(MathUtils<>::StressVectorToTensor(rStressVector),
+                                        eigen_vectors, sigma_princi, 1.0e-16, 20);
+    const auto p = CalculateMeanStress(rStressVector);
+    const auto numerator = (sigma_princi(0, 0) - p) * (sigma_princi(1, 1) - p) * (sigma_princi(2, 2) - p);
+
     return std::asin((-27. / 2.) * numerator / (q * q * q)) / 3.0;
```
Comment (rfaasse) [inline applications/GeoMechanicsApplication/custom_utilities/stress_strain_utilities.cpp]: As a first fix we also used to test the argument of the asin (`(-27. / 2.) * numerator / (q * q * q)`) is not just over 1/ under -1 (within some tolerance). Maybe we can reproduce it if we slightly perturb the vectors in the UT to trigger it (e.g. get the argument to be 1.0 + 1e-12)?

**Review by rfaasse — COMMENTED** [review]
No blocking comment, just a suggestion for reproducing one of the earlier things we encountered

File: applications/GeoMechanicsApplication/custom_utilities/stress_strain_utilities.cpp (hunk 1 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/custom_utilities/stress_strain_utilities.cpp:68]: The defaults that you are referring to are defined in `applications\GeoMechanicsApplication\tests\cpp_tests\test_utilities.h`. Since those are default tolerance values for tests, I'd rather not mix them with default tolerance values for production code. We could create a new file where we define application-wide tolerance values, and use that here. Let me know whether that is what you've intended to say. Thanks.

Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_utilities/stress_strain_utilities.cpp:68]: I do not want to cause scope creep of the PR. Leave as is.

File: applications/GeoMechanicsApplication/custom_utilities/stress_strain_utilities.cpp (hunk 3 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/custom_utilities/stress_strain_utilities.cpp]: Thank you very much for your suggestion. I have played a bit with finding the right perturbation, and when I found it I've added two regression tests for it. The value of the number passed to `std::asin` is now `std::clamp`ed to the domain [-1, +1].

**Review by WPK4FEM — APPROVED** [review]

File: applications/GeoMechanicsApplication/custom_utilities/stress_strain_utilities.cpp (hunk 3 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/custom_utilities/stress_strain_utilities.cpp]: Nice find! Thanks for processing this!

**Review by rfaasse — APPROVED** [review]
Thanks for processing the review comments, in my opinion this is ready to go!
