### PR TITLE
[GeoMechanicsApplication] Base integration scheme on order of geometry ( i.s.o. number of node )

### LINKED ISSUE #13239: [GeoMechanicsApplication] Investigation on 3D tetrahedral element with 10 nodes gets wrong integration method
**Probably to be picked up in the first sprint of 2025.**

The integration method is checked based on the number of nodes, and not on the dimension, 
Tetrahedral element 10 noded gets the integration method of triangular 2D element of 10 nodes, which is Gauss_4 with 7 points.
However, it has to take Gauss_2

NB: it is also valid for 1D elements, get mixed with 2D way

This task starts with an investigation on how many times this is done, what is the impact, and how it can be limited. If we need certain functionality or that it has a big impact, we can then decide what we want to do with it.

### PR DESCRIPTION
**Pull request by WPK4FEM**
**📝 Description**
The quadritc tetrahedra UPw element got GI_GAUSS_4 i.s.o. GI_GAUSS_2 as it has 10 nodes like the TransientPwElement2D10N

**🆕 Changelog**
- Based the discrimination on the order of the geometry.
- Added unit test.

### CODE REVIEW

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_elements/test_u_pw_tetra_element_integration.cpp [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+KRATOS_TEST_CASE_IN_SUITE(UPwSmallStrainTetrahedra3D10ElementReturnsGI_GAUS_2, KratosGeoMechanicsFastSuiteWithoutKernel)
+{
+    // Arrange
+    const auto p_properties = std::make_shared<Properties>();
+    auto       process_info = ProcessInfo{};
+    Model      model;
+    auto       element = UPwSmallStrainElementWithUPwDofs(model, p_properties);
+
+    // Act & Assert
+    KRATOS_EXPECT_EQ(element.GetIntegrationMethod(), GeometryData::IntegrationMethod::GI_GAUSS_2);
```
Comment (rfaasse) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_elements/test_u_pw_tetra_element_integration.cpp]: Nice that you added this test case here. I think since we're changing the implementation, we should also have tests for the integration methods of the other configs (2D6, 2D10, 2D9, 2D3 etc) to confirm they keep working. I think it's quite doable to do that (maybe even with a parametrized test), maybe we can have a look together.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_elements/test_u_pw_tetra_element_integration.cpp [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+//
+//  License:         geo_mechanics_application/license.txt
+//
+//  Main authors:    Wijtze Pieter Kikstra
+//
+
+#include "custom_elements/U_Pw_small_strain_element.hpp"
+#include "custom_elements/three_dimensional_stress_state.h"
+#include "tests/cpp_tests/geo_mechanics_fast_suite.h"
+#include "tests/cpp_tests/test_utilities.h"
```
Comment (rfaasse) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_elements/test_u_pw_tetra_element_integration.cpp]: In the end I don't think you're using the test utilities, so we can remove the include again.

File: applications/GeoMechanicsApplication/custom_elements/U_Pw_base_element.cpp [hunk 3]
```diff
@@ -162,27 +162,21 @@ void UPwBaseElement::GetDofList(DofsVectorType& rElementalDofList, const Process
...
+        integration_method = GeometryData::IntegrationMethod::GI_GAUSS_5;
         break;
     default:
-        GI_GAUSS = GeometryData::IntegrationMethod::GI_GAUSS_2;
+        integration_method = GeometryData::IntegrationMethod::GI_GAUSS_2;
         break;
     }
 
-    return GI_GAUSS;
+    return integration_method;
```
Comment (rfaasse) [inline applications/GeoMechanicsApplication/custom_elements/U_Pw_base_element.cpp]: Very nice implementation using the GeometryOrder. I think we can write it even shorter like this:
```
    switch (this->GetGeometry().GetGeometryOrderType()) {
    case GeometryData::Kratos_Cubic_Order:
        return GeometryData::IntegrationMethod::GI_GAUSS_4;
    case GeometryData::Kratos_Quartic_Order:
        return GeometryData::IntegrationMethod::GI_GAUSS_5;
    default:
        return GeometryData::IntegrationMethod::GI_GAUSS_2;
    }
```

**Review by rfaasse — COMMENTED** [review]
Very nice fix using different geometry info! I do think we need to add a couple more tests to make sure the behavior for other configurations is also still fine (I don't see a reason why not, but I think it's nice to be sure).

File: applications/GeoMechanicsApplication/custom_elements/U_Pw_base_element.cpp [hunk 4]
```diff
@@ -162,27 +162,14 @@ void UPwBaseElement::GetDofList(DofsVectorType& rElementalDofList, const Process
...
+    switch (this->GetGeometry().GetGeometryOrderType()) {
+    case GeometryData::Kratos_Cubic_Order:
+        return GeometryData::IntegrationMethod::GI_GAUSS_4;
+    case GeometryData::Kratos_Quartic_Order:
+        return GeometryData::IntegrationMethod::GI_GAUSS_5;
     default:
-        GI_GAUSS = GeometryData::IntegrationMethod::GI_GAUSS_2;
-        break;
+        return GeometryData::IntegrationMethod::GI_GAUSS_2;
     }
```
Comment (mnabideltares) [inline applications/GeoMechanicsApplication/custom_elements/U_Pw_base_element.cpp:172]: I really like the current implementation, as it keeps the function concise and explicitly connects the Gauss method to the polynomial order.

However, there is an important point to consider: I expect this code to be part of a utility function that will be used by all elements. In line elements, such as Pw-line-elements and thermal (line)elements, the integration rule differs. For example, cubic-order line elements use GAUSS_3.

This leaves us with two options:

1. Modify the number of integration points in line elements to match 2D and 3D elements.

Pros: Consistent and compact code.
Cons: Slightly increased computational cost due to additional calculations.

2. Introduce exceptions for line elements in this function.

Pros: Preserves the standard integration rules for different element types.
Cons: Adds exceptions and extra coding, making the function less readable.

Each option has trade-offs, so this decision needs to be carefully considered. It may be in a different PR

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_elements/test_u_pw_tetra_element_integration.cpp [hunk 5]
```diff
@@ -0,0 +1,75 @@
...
+//
+
+#include "tests/cpp_tests/geo_mechanics_fast_suite.h"
+#include "tests/cpp_tests/test_utilities/model_setup_utilities.h"
+
+namespace Kratos::Testing
+{
+using namespace Kratos;
+
+KRATOS_TEST_CASE_IN_SUITE(UPwSmallStrainTetrahedra3D10ElementReturnsGI_GAUS_2, KratosGeoMechanicsFastSuiteWithoutKernel)
```
Comment (mnabideltares) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_elements/test_u_pw_tetra_element_integration.cpp]: Do you mean GI_GAUSS_2?

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_elements/test_u_pw_tetra_element_integration.cpp [hunk 6]
```diff
@@ -0,0 +1,75 @@
...
+    // Arrange
+    Model model;
+    const auto& r_model_part = ModelSetupUtilities::CreateModelPartWithASingle2D6NDiffOrderElement(model);
+    const auto& element = r_model_part.Elements().front();
+
+    // Act & Assert
+    KRATOS_EXPECT_EQ(element.GetIntegrationMethod(), GeometryData::IntegrationMethod::GI_GAUSS_2);
+}
+
+KRATOS_TEST_CASE_IN_SUITE(UPwSmallStrainTriangle2D10ElementReturnsGI_GAUS_4, KratosGeoMechanicsFastSuiteWithoutKernel)
```
Comment (mnabideltares) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_elements/test_u_pw_tetra_element_integration.cpp]: GI_GAUSS_4?

**Review by mnabideltares — COMMENTED** [review]
@WPK4FEM 
Thank you for this nice work and making the integration such clear, avoiding the confusion which comes by the number of nodes for each element. I have few comments which I addressed here.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_elements/test_u_pw_tetra_element_integration.cpp (hunk 5 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_elements/test_u_pw_tetra_element_integration.cpp]: Indeed, corrected.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_elements/test_u_pw_tetra_element_integration.cpp (hunk 6 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_elements/test_u_pw_tetra_element_integration.cpp]: Indeed, corrected.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_elements/test_u_pw_tetra_element_integration.cpp (hunk 1 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_elements/test_u_pw_tetra_element_integration.cpp]: Had a look together and created more tests to cover all branches of the case statement.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_elements/test_u_pw_tetra_element_integration.cpp (hunk 2 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_elements/test_u_pw_tetra_element_integration.cpp]: Cleaned up during our refactoring together.

File: applications/GeoMechanicsApplication/custom_elements/U_Pw_base_element.cpp (hunk 4 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_elements/U_Pw_base_element.cpp:172]: This PR only aims at fixing the confusion between the integration schemes for the 10 node triangles and tetrahedra that both derive from U_Pw_base_element. I agree with striving for consistency and using the same mechanism in the T and Pw line elements, but indeed in a separate PR as then we are potentially changing more functionality then only fixing the issue for the quadratic tetrahedron.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_elements/test_u_pw_element_integration.cpp [hunk 7]
```diff
@@ -0,0 +1,75 @@
...
+    // Arrange
+    Model       model;
+    const auto& r_model_part = ModelSetupUtilities::CreateModelPartWithASingle2D15NElement(model);
+    const auto& element      = r_model_part.Elements().front();
+
+    // Act & Assert
+    KRATOS_EXPECT_EQ(element.GetIntegrationMethod(), GeometryData::IntegrationMethod::GI_GAUSS_5);
+}
+
+} // namespace Kratos::Testing
```
Comment (mnabideltares) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_elements/test_u_pw_element_integration.cpp:75]: Nice tests, and they cover a large part. For completeness, maybe a good idea to add tests fot the quadrilateral elements too. We have three quadrilateral elements: 2D4N, 2D8N, and 2D9N.
As far as I remember, 2D8N has Quadratic_Order. Then it leads to GAUSS_5, while previously GAUSS_2 was implemented.

**Review by rfaasse — APPROVED** [review]
Looks good to me!

**Review by mnabideltares — COMMENTED** [review]
@WPK4FEM 
Thank you for adressing the review comments. I have only one issue yet.  Please see the below:

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_elements/test_u_pw_element_integration.cpp (hunk 7 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_elements/test_u_pw_element_integration.cpp:75]: For quadratic elements like quadratic quadrilateral 2D8N the integration schema was and still is GAUSS_2, please explain why this would have changed. As for the tests, they cover all branches within GetIntegrationMethod, as first, second, third and fourth order elements are in the tests. Whether the element shapes are triangular, quadrilateral, tetrahedral, hexagonal, pyramid or wedge is not relevant here, so that will not add to the coverage on GetIntegrationMethod of the u_pw_base_element.
