### PR TITLE
 [GeoMechanicsApplication] Fix the return mapping in Mohr-Coulomb tension cutoff

### LINKED ISSUE #14155: [GeoMechanicsApplication] Fix the return mapping in Mohr-Coulomb tension cutoff
### Description

There is inconsistency found in the return mapping for tension-cutoff return zone, and the tension-cutoff corner point zone.

The principal stress components sigma1 and sigma3 are mapped back, while sigma2 is kept constant. However, sigma2 needs to be mapped back for tension-cutoff. 
This issue was found because the code gives different results than Plaxis.

1. Fix the return mapping of sigma2, for tension-cutoff
2. Add unit test(s)
3. Update the documentation

### PR DESCRIPTION
**Pull request by mnabideltares**
**📝 Description**
There is inconsistency found in the return mapping for tension-cutoff return zone, and the tension-cutoff corner point zone.

The principal stress components sigma1 and sigma3 are mapped back, while sigma2 is kept constant. However, sigma2 needs to be mapped back for tension-cutoff.
This issue was found because the code gives different results than Plaxis.

Fix the return mapping of sigma2, for tension-cutoff
Add unit test(s)
Update the documentation

**🆕 Changelog**
- Added elastix matrix to the formulations
- Added functions related to principal stresses
- Added averaging for drivative of flow function, related to tension cut-off
- Fixed the unit tests
- Modified documentation

### CODE REVIEW

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp [hunk 1]
```diff
@@ -183,15 +202,28 @@ void CoulombYieldSurface::InitializeKappaDependentFunctions()
...
-    const auto sin_phi   = std::sin(GetFrictionAngleInRadians());
-    const auto numerator = sin_phi * rDerivativeOfFlowFunction[0] + rDerivativeOfFlowFunction[1];
-    return (GetCohesion() * std::cos(GetFrictionAngleInRadians()) - rSigmaTau.Sigma() * sin_phi -
-            rSigmaTau.Tau()) /
-           numerator;
+    const auto sin_phi = std::sin(GetFrictionAngleInRadians());
+    const auto numerator =
+        sin_phi * rDerivativeOfFlowFunction[0] * mMaterialProperties[INTERFACE_NORMAL_STIFFNESS] +
+        rDerivativeOfFlowFunction[1] * mMaterialProperties[INTERFACE_SHEAR_STIFFNESS];
+    return -YieldFunctionValue(rSigmaTau) / numerator;
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp]: Please do not reconstruct the elastic constitutive tensor here from the material parameters, but compute and pass it in the same way that is done for other functions.

If we write sigmamapped = sigma^trial^+ lambda * sigma^correction, where sigma^correction =  C * dG / dsigma, the components of sigma^correction can be used in the numerator. Then the numerator is correct for any constitutive tensor.

A better name for the argument rSigmaTau may be rTrialSigmaTau

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp [hunk 2]
```diff
@@ -183,15 +202,28 @@ void CoulombYieldSurface::InitializeKappaDependentFunctions()
...
+}
+
+double CoulombYieldSurface::CalculatePlasticMultiplier(const Geo::PrincipalStresses& rPrincipalStresses,
+                                                       const Vector& rDerivativeOfFlowFunction) const
+{
+    const auto sin_phi = std::sin(GetFrictionAngleInRadians());
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp]: Please also use the mechanism sketched in the previous comment for this override.

A better name for the argument rPincipalStresses may be rPrincipalTrialStresses

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp [hunk 3]
```diff
@@ -205,6 +237,19 @@ double CoulombYieldSurface::CalculateEquivalentPlasticStrainIncrement(const Geo:
            CalculatePlasticMultiplier(rSigmaTau, DerivativeOfFlowFunction(rSigmaTau, AveragingType));
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp]:
```suggestion
           CalculatePlasticMultiplier(rTrialSigmaTau, DerivativeOfFlowFunction(rTrialSigmaTau, AveragingType));
```

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp [hunk 4]
```diff
@@ -205,6 +237,19 @@ double CoulombYieldSurface::CalculateEquivalentPlasticStrainIncrement(const Geo:
...
 }
 
+double CoulombYieldSurface::CalculateEquivalentPlasticStrainIncrement(const Geo::PrincipalStresses& rPrincipalStresses,
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp]:
```suggestion
double CoulombYieldSurface::CalculateEquivalentPlasticStrainIncrement(const Geo::PrincipalStresses& rPrincipalTrialStresses,
```

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp [hunk 5]
```diff
@@ -205,6 +237,19 @@ double CoulombYieldSurface::CalculateEquivalentPlasticStrainIncrement(const Geo:
...
+                                                                      YieldSurfaceAveragingType AveragingType) const
+{
+    const auto derivative = DerivativeOfFlowFunction(rPrincipalStresses, AveragingType);
+    const auto mean       = std::accumulate(derivative.begin(), derivative.end(), 0.0) /
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp]: This I do not understand, what would a mean derivative be used for here. I guess this is computes a mean principal stress

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp [hunk 6]
```diff
@@ -205,6 +237,19 @@ double CoulombYieldSurface::CalculateEquivalentPlasticStrainIncrement(const Geo:
            CalculatePlasticMultiplier(rSigmaTau, DerivativeOfFlowFunction(rSigmaTau, AveragingType));
 }
 
+double CoulombYieldSurface::CalculateEquivalentPlasticStrainIncrement(const Geo::PrincipalStresses& rPrincipalStresses,
+                                                                      YieldSurfaceAveragingType AveragingType) const
+{
+    const auto derivative = DerivativeOfFlowFunction(rPrincipalStresses, AveragingType);
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp]:
```suggestion
    const auto derivative_of_G_to_sigma = DerivativeOfFlowFunction(rPrincipalTrialStresses, AveragingType);
```

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp [hunk 7]
```diff
@@ -183,15 +202,28 @@ void CoulombYieldSurface::InitializeKappaDependentFunctions()
...
+                     rDerivativeOfFlowFunction[2]) *
+                    sin_phi / 2.0;
+    return -YieldFunctionValue(rPrincipalStresses) / (c1 + c2);
 }
 
 double CoulombYieldSurface::CalculateEquivalentPlasticStrainIncrement(const Geo::SigmaTau& rSigmaTau,
-                                                                      CoulombAveragingType AveragingType) const
+                                                                      YieldSurfaceAveragingType AveragingType) const
 {
     const auto derivative              = DerivativeOfFlowFunction(rSigmaTau, AveragingType);
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp]:
```suggestion
    const auto derivative_of_G_to_sigma_tau              = DerivativeOfFlowFunction(rTrialSigmaTau, AveragingType);
```

File: applications/GeoMechanicsApplication/custom_constitutive/interface_coulomb_with_tension_cut_off.cpp [hunk 8]
```diff
@@ -182,6 +183,14 @@ Matrix& InterfaceCoulombWithTensionCutOff::CalculateValue(Parameters& rConstitut
...
 }
 
+Matrix InterfaceCoulombWithTensionCutOff::CalculateElasticContitativeMatrix(const Properties& rMaterialProperties) const
+{
+    Matrix result = ZeroMatrix(2, 2);
+    result(0, 0)  = rMaterialProperties[INTERFACE_NORMAL_STIFFNESS];
+    result(1, 1)  = rMaterialProperties[INTERFACE_SHEAR_STIFFNESS];
+    return result;
+}
+
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/custom_constitutive/interface_coulomb_with_tension_cut_off.cpp]: This should be a function for an interface stress_state, similar to the one for plane_strain stress state and three_dimensional stress state

File: applications/GeoMechanicsApplication/custom_constitutive/interface_coulomb_with_tension_cut_off.h [hunk 9]
```diff
@@ -58,6 +58,7 @@ class KRATOS_API(GEO_MECHANICS_APPLICATION) InterfaceCoulombWithTensionCutOff :
     [[nodiscard]] Geo::SigmaTau CalculateTrialTractionVector(const Vector& rRelativeDisplacementVector,
                                                              double NormalStiffness,
                                                              double ShearStiffness) const;
+    [[nodiscard]] Matrix CalculateElasticContitativeMatrix(const Properties& rMaterialProperties) const;
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/custom_constitutive/interface_coulomb_with_tension_cut_off.h]:
```suggestion
    [[nodiscard]] Matrix CalculateElasticConstitutiveMatrix(const Properties& rMaterialProperties) const;
```

But is should be located elsewhere

File: applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp [hunk 10]
```diff
@@ -204,17 +204,22 @@ void MohrCoulombWithTensionCutOff::CalculateMaterialResponseCauchy(ConstitutiveL
     } else {
         mCoulombWithTensionCutOffImpl.SaveKappaOfCoulombYieldSurface();
 
+        const auto c0 = r_properties[YOUNG_MODULUS] /
+                        ((1.0 + r_properties[POISSON_RATIO]) * (1.0 - 2.0 * r_properties[POISSON_RATIO]));
+        auto elastic_matrix = mpConstitutiveDimension->CalculateElasticMatrix(r_properties);
+        elastic_matrix /= c0;
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp]: I would prefer to use the elastic matrix as is and not spread its formation to more places. The constitutive matrix can be a result of nonlinear elasticity. That you do not want to know about here.

File: applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp [hunk 11]
```diff
@@ -239,6 +244,17 @@ void MohrCoulombWithTensionCutOff::FinalizeMaterialResponseCauchy(ConstitutiveLa
...
+{
+    const auto youngs_modulus = rMaterialProperties[YOUNG_MODULUS];
+    const auto poissons_ratio = rMaterialProperties[POISSON_RATIO];
+    const auto c0     = youngs_modulus / ((1.0 + poissons_ratio) * (1.0 - 2.0 * poissons_ratio));
+    Matrix     result = ZeroMatrix(3, 3);
+    result(0, 0) = result(1, 1) = result(2, 2) = c0 * (1.0 - poissons_ratio);
+    result(0, 1) = result(0, 2) = result(1, 0) = result(1, 2) = result(2, 0) = result(2, 1) = c0 * poissons_ratio;
+    return result;
+}
+
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp]: This is a repetition of the implementation that is in the stress state. Please use the one from the stress state.

File: applications/GeoMechanicsApplication/custom_constitutive/README.md [hunk 12]
```diff
@@ -279,9 +279,39 @@ We move perpendicular to the tension cutoff yield surface by using the derivativ
...
+                    0
+    \end{bmatrix}
+```
+```math
+    C = 
+    \begin{bmatrix} 1 - \nu &     \nu & \nu     \\
+                        \nu & 1 - \nu & \nu     \\
+                        \nu &     \nu & 1 - \nu
+    \end{bmatrix}
+```
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/custom_constitutive/README.md]: This is part of the formulation of a linear elastic constitutive tensor, but incomplete. For the return mapping it's contents may vary with what elasticity was chosen. I think it can be left out here.

File: applications/GeoMechanicsApplication/custom_constitutive/README.md [hunk 13]
```diff
@@ -279,9 +279,39 @@ We move perpendicular to the tension cutoff yield surface by using the derivativ
     \end{bmatrix}
 ```
 ```math
-    \sigma^{map} = \sigma^{trial} + \dot{\lambda} \frac{\partial G_{tc}}{\partial \sigma}
+    C = 
+    \begin{bmatrix} C_{xx} & 0     \\
+                    0      & C_{yy}
+    \end{bmatrix}
+```
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/custom_constitutive/README.md]: I think that the fill in of C can be skipped here. The important notice is that C * dG/dsigma is used

File: applications/GeoMechanicsApplication/custom_constitutive/README.md [hunk 14]
```diff
@@ -383,7 +413,21 @@ At yield function,
...
+    \begin{bmatrix}
+    \frac{1}{2} (\sin{\psi} + 1) \\
+    0                            \\
+    \frac{1}{2} (\sin{\psi} - 1)
+    \end{bmatrix}
+```
+
+```math
+    \dot{\lambda} = -2 \frac{\tau^{trial} + \sigma^{trial} \sin{\phi} - c \cos{\phi}}{(\frac{\partial G_{MC}}{\partial \sigma_1} - \frac{\partial G_{MC}}{\partial \sigma_3})(1 - 2 \nu) + (\frac{\partial G_{MC}}{\partial \sigma_1} + 2 \nu \frac{\partial G_{MC}}{\partial \sigma_2} + \frac{\partial G_{MC}}{\partial \sigma_3}) \sin{\phi}}
 ```
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/custom_constitutive/README.md:420]: if we write sigma^m = C * dG / dsigma, the specific form of the elastic matrix can be left out of the equation.

File: applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp [hunk 15]
```diff
@@ -15,15 +15,22 @@
...
 #include "custom_utilities/stress_strain_utilities.h"
+#include "geo_mechanics_application_variables.h"
 #include "includes/serializer.h"
 
 #include <boost/numeric/ublas/assignment.hpp>
 
 namespace Kratos
 {
-TensionCutoff::TensionCutoff(double TensileStrength) : mTensileStrength{TensileStrength} {}
+TensionCutoff::TensionCutoff(const Properties& rMaterialProperties)
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp]: Is passing all of the material properties still necessary is we use the elastic constitutive tensor from the stress state?

File: applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp [hunk 16]
```diff
@@ -33,38 +40,87 @@ double TensionCutoff::YieldFunctionValue(const Vector& rSigmaTau) const
...
+    return DerivativeOfFlowFunction(unused_sigma_tau, YieldSurfaceAveragingType::NO_AVERAGING);
+}
+
+Vector TensionCutoff::DerivativeOfFlowFunction(const Geo::SigmaTau&, YieldSurfaceAveragingType AveragingType) const
+{
+    Vector result(2);
+    switch (AveragingType) {
+        using enum YieldSurfaceAveragingType;
+    case LOWEST_PRINCIPAL_STRESSES:
+        result <<= 0.5, 0.5;
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp]: This is a use of ublas_assignment for which we have an issue to remove it. Lets not introduce more of them.
```suggestion
        return CreateVector({0.5, 0.5});
```
and for the other branches similar.

File: applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp [hunk 17]
```diff
@@ -33,38 +40,87 @@ double TensionCutoff::YieldFunctionValue(const Vector& rSigmaTau) const
...
 
-Vector TensionCutoff::DerivativeOfFlowFunction(const Geo::SigmaTau&) const
+double TensionCutoff::CalculatePlasticMultiplier(const Geo::PrincipalStresses& rPrincipalStresses,
+                                                 const Vector& rDerivativeOfFlowFunction) const
 {
-    return Vector{ScalarVector{2, 1.0}};
+    const auto poisson = mMaterialProperties[POISSON_RATIO];
+    const auto numerator =
+        rDerivativeOfFlowFunction[0] * (1.0 - poisson) + rDerivativeOfFlowFunction[1] * poisson;
+    return -YieldFunctionValue(rPrincipalStresses) / numerator;
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp]: Please use the elastic constitutive tensor from the stress state.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_interface_coulomb_with_tension_cut_off.cpp [hunk 18]
```diff
@@ -156,6 +156,8 @@ KRATOS_TEST_CASE_IN_SUITE(InterfaceCoulombWithTensionCutOff_CalculateMaterialRes
     properties.SetValue(GEO_COHESION, 10.0);
     properties.SetValue(GEO_DILATANCY_ANGLE, 20.0);
     properties.SetValue(GEO_TENSILE_STRENGTH, 10.0);
+    properties.SetValue(INTERFACE_NORMAL_STIFFNESS, 1.0);
+    properties.SetValue(INTERFACE_SHEAR_STIFFNESS, 1.0);
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_interface_coulomb_with_tension_cut_off.cpp]: maybe use more discriminating values like 25.0, 12.5

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_interface_coulomb_with_tension_cut_off.cpp [hunk 19]
```diff
@@ -230,6 +232,8 @@ KRATOS_TEST_CASE_IN_SUITE(InterfaceCoulombWithTensionCutOff_CalculateMaterialRes
     properties.SetValue(GEO_COHESION, 10.0);
     properties.SetValue(GEO_DILATANCY_ANGLE, 0.0);
     properties.SetValue(GEO_TENSILE_STRENGTH, 10.0);
+    properties.SetValue(INTERFACE_NORMAL_STIFFNESS, 1.0);
+    properties.SetValue(INTERFACE_SHEAR_STIFFNESS, 1.0);
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_interface_coulomb_with_tension_cut_off.cpp]: See remark about discriminating values.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp [hunk 20]
```diff
@@ -222,6 +224,7 @@ KRATOS_TEST_CASE_IN_SUITE(MohrCoulombWithTensionCutOff_CalculateMaterialResponse
     properties.SetValue(GEO_COHESION, 10.0);
     properties.SetValue(GEO_DILATANCY_ANGLE, 20.0);
     properties.SetValue(GEO_TENSILE_STRENGTH, 10.0);
+    properties.SetValue(YOUNG_MODULUS, 1.0e6);
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp:229]: does it assume a Poisson's value here?

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp [hunk 21]
```diff
@@ -258,6 +261,7 @@ KRATOS_TEST_CASE_IN_SUITE(MohrCoulombWithTensionCutOff_CalculateMaterialResponse
...
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp:267]: does it assume a Poisson's value here?

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp [hunk 22]
```diff
@@ -615,8 +622,11 @@ KRATOS_TEST_CASE_IN_SUITE(MohrCoulombWithTensionCutOff_CalculateMaterialResponse
     properties.SetValue(GEO_COHESION, 10.0);
     properties.SetValue(GEO_DILATANCY_ANGLE, 0.0);
     properties.SetValue(GEO_TENSILE_STRENGTH, 10.0);
+    properties.SetValue(YOUNG_MODULUS, 1.0e6);
+    properties.SetValue(POISSON_RATIO, 0.0);
+    properties.SetValue(GEO_MAX_PLASTIC_ITERATIONS, 100);
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp:632]: Out of curiosity, how many does it really use now after the corrections?

**Review by WPK4FEM — COMMENTED** [review]
Hi Mohamed,
Thank you for the inclusion of the elastic constitutive tensor. As indicated in the remarks, there may still be some work to do to generalize it. You could also contact Gennady to see if he can repeat the comparison between you current branch and the reference for the slope analysis.
Regards,
Wijtze Pieter

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp [hunk 23]
```diff
@@ -179,39 +182,51 @@ Geo::PrincipalStresses CoulombWithTensionCutOffImpl::ReturnStressAtTensionApexRe
...
-        ReturnStressAtTensionCutoffReturnZone(
-            StressStrainUtilities::TransformPrincipalStressesToSigmaTau(rPrincipalStresses)),
-        rPrincipalStresses);
+    const auto derivative_of_flow_function =
+        mTensionCutOff.DerivativeOfFlowFunction(rPrincipalStresses, AveragingType);
+    const auto lambda =
+        mTensionCutOff.CalculatePlasticMultiplier(rPrincipalStresses, derivative_of_flow_function);
+    const Matrix elastic_matrix = boost::numeric::ublas::subrange(rElasticMatrix, 0, 3, 0, 3);
+    return Geo::PrincipalStresses{rPrincipalStresses.Values() +
+                                  lambda * prod(elastic_matrix, derivative_of_flow_function)};
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp]: This is a suggestion that you shouldn't address in this PR, I just write it down so we won't forget about it. Like for class `SigmaTau`, we can define addition operations (i.e. `operator+=` and `operator+`) for class `PrincipalStresses`. In that way, we can rewrite this statement in a slightly more intuitive way.

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.h [hunk 24]
```diff
@@ -40,9 +40,11 @@ class CoulombWithTensionCutOffImpl
     [[nodiscard]] bool IsAdmissibleStressState(const Geo::PrincipalStresses& rTrialPrincipalStresses) const;
 
     [[nodiscard]] Geo::SigmaTau DoReturnMapping(const Geo::SigmaTau& rTrialTraction,
-                                                CoulombYieldSurface::CoulombAveragingType AveragingType);
+                                                YieldSurface::YieldSurfaceAveragingType AveragingType,
+                                                Matrix& rElasticMatrix);
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.h]: As was also found by SonarQube, please make `rElasticMatrix` a reference-to-const:

```suggestion
                                                const Matrix& rElasticMatrix);
```

This suggestion also applies to the other member function where you've added a function parameter to pass the elastic matrix.

File: applications/GeoMechanicsApplication/custom_constitutive/yield_surface.h [hunk 25]
```diff
@@ -23,6 +23,12 @@ class Serializer;
 class YieldSurface
 {
 public:
+    enum class YieldSurfaceAveragingType {
+        NO_AVERAGING,
+        LOWEST_PRINCIPAL_STRESSES,
+        HIGHEST_PRINCIPAL_STRESSES
+    };
+
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/yield_surface.h]: When I look at the enumerator names, I feel that `PrincipalStressesAveragingType` might be a better name:

```suggestion
    enum class PrincipalStressesAveragingType{
        NO_AVERAGING,
        LOWEST_PRINCIPAL_STRESSES,
        HIGHEST_PRINCIPAL_STRESSES
    };

```

Furthermore, since we plan to remove the `YieldSurface` class in the near future, I think it's wiser to put the `enum class` elsewhere. What about putting it next to the new `PrincipalStresses` class?

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp [hunk 26]
```diff
@@ -179,39 +182,51 @@ Geo::PrincipalStresses CoulombWithTensionCutOffImpl::ReturnStressAtTensionApexRe
...
+Geo::SigmaTau CoulombWithTensionCutOffImpl::ReturnStressAtTensionCutoffReturnZone(
+    const Geo::SigmaTau& rTraction, YieldSurface::YieldSurfaceAveragingType AveragingType, Matrix& rElasticMatrix) const
 {
-    const auto derivative_of_flow_function = mTensionCutOff.DerivativeOfFlowFunction(rTraction);
-    const auto lambda_tc = (mTensionCutOff.GetTensileStrength() - rTraction.Sigma() - rTraction.Tau()) /
-                           (derivative_of_flow_function[0] + derivative_of_flow_function[1]);
-    return rTraction + Geo::SigmaTau{lambda_tc * derivative_of_flow_function};
+    const auto derivative_of_flow_function = mTensionCutOff.DerivativeOfFlowFunction(rTraction, AveragingType);
+    const auto lambda = mTensionCutOff.CalculatePlasticMultiplier(rTraction, derivative_of_flow_function);
+    ;
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp]: As was also found by SonarQube, there's an empty statement here. Can you please remove it?

```suggestion
```

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp [hunk 27]
```diff
@@ -179,39 +182,51 @@ Geo::PrincipalStresses CoulombWithTensionCutOffImpl::ReturnStressAtTensionApexRe
...
-Geo::SigmaTau CoulombWithTensionCutOffImpl::ReturnStressAtTensionCutoffReturnZone(const Geo::SigmaTau& rTraction) const
+Geo::SigmaTau CoulombWithTensionCutOffImpl::ReturnStressAtTensionCutoffReturnZone(
+    const Geo::SigmaTau& rTraction, YieldSurface::YieldSurfaceAveragingType AveragingType, Matrix& rElasticMatrix) const
 {
-    const auto derivative_of_flow_function = mTensionCutOff.DerivativeOfFlowFunction(rTraction);
-    const auto lambda_tc = (mTensionCutOff.GetTensileStrength() - rTraction.Sigma() - rTraction.Tau()) /
-                           (derivative_of_flow_function[0] + derivative_of_flow_function[1]);
-    return rTraction + Geo::SigmaTau{lambda_tc * derivative_of_flow_function};
+    const auto derivative_of_flow_function = mTensionCutOff.DerivativeOfFlowFunction(rTraction, AveragingType);
+    const auto lambda = mTensionCutOff.CalculatePlasticMultiplier(rTraction, derivative_of_flow_function);
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp]: How nice that the tension cut-off can now calculate the plastic multiplier by itself 👍

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp (hunk 23 above)
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp]: The namespace qualifiers are redundant here. Also, I'm wondering whether we really need to introduce an intermediate variable, or that a temporary will do. For instance:
```suggestion
    return Geo::PrincipalStresses{rPrincipalStresses.Values() +
                                  lambda * prod(subrange(rElasticMatrix, 0, 3, 0, 3), derivative_of_flow_function)};
```

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp [hunk 28]
```diff
@@ -179,39 +182,51 @@ Geo::PrincipalStresses CoulombWithTensionCutOffImpl::ReturnStressAtTensionApexRe
...
-        ReturnStressAtRegularFailureZone(
-            StressStrainUtilities::TransformPrincipalStressesToSigmaTau(rPrincipalStresses), AveragingType),
-        rPrincipalStresses);
+    const auto derivative_of_flow_function =
+        mCoulombYieldSurface.DerivativeOfFlowFunction(rPrincipalStresses, AveragingType);
+    const auto lambda =
+        mCoulombYieldSurface.CalculatePlasticMultiplier(rPrincipalStresses, derivative_of_flow_function);
+    const Matrix elastic_matrix = boost::numeric::ublas::subrange(rElasticMatrix, 0, 3, 0, 3);
+    return Geo::PrincipalStresses{rPrincipalStresses.Values() +
+                                  lambda * prod(elastic_matrix, derivative_of_flow_function)};
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp]: Same thing here:
```suggestion
    return Geo::PrincipalStresses{rPrincipalStresses.Values() +
                                  lambda * prod(subrange(rElasticMatrix, 0, 3, 0, 3), derivative_of_flow_function)};
```

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.h [hunk 29]
```diff
@@ -57,14 +51,21 @@ class KRATOS_API(GEO_MECHANICS_APPLICATION) CoulombYieldSurface : public YieldSu
     [[nodiscard]] double YieldFunctionValue(const Geo::PrincipalStresses& rPrincipalStresses) const;
 
     [[nodiscard]] Vector DerivativeOfFlowFunction(const Vector&) const override;
-    [[nodiscard]] Vector DerivativeOfFlowFunction(const Geo::SigmaTau&,
-                                                  CoulombAveragingType AveragingType = CoulombAveragingType::NO_AVERAGING) const;
+    [[nodiscard]] Vector DerivativeOfFlowFunction(
+        const Geo::SigmaTau&,
+        YieldSurfaceAveragingType AveragingType = YieldSurfaceAveragingType::NO_AVERAGING) const;
+    [[nodiscard]] Vector DerivativeOfFlowFunction(const Geo::PrincipalStresses&,
+                                                  YieldSurfaceAveragingType AveragingType) const;
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.h]: Since the previous overload (which receives a `Geo::SigmaTau` object) has a default value for the averaging type, I was wondering whether we would like to apply the same default value here, too?

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp (hunk 5 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp]: I have the same question. As it is written now, it will compute the mean value of the derivative. I mean not sure whether that's what you meant...?

File: applications/GeoMechanicsApplication/custom_constitutive/interface_coulomb_with_tension_cut_off.h (hunk 9 above)
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/interface_coulomb_with_tension_cut_off.h]: Please, reuse what we already have. In other words, please remove this local re-implementation. As suggested before, please add a constitutive dimension as data member to this class, and then ask it to calculate the constitutive matrix.

```cpp
// This is identical to what we have in class `MohrCoulombWithTensionCutOff`
std::unique_ptr<ConstitutiveLawDimension> mpConstitutiveDimension;
```

Just like we did for class `MohrCoulombWithTensionCutOff`, I would suggest to pass the constitutive law dimension to be used to the constructor of class `InterfaceCoulombWithTensionCutOff` (see `geo_mechanics_application.h`, lines 981 to 984). Since so far we're using this constitutive law in the context of plane strain models only, pass it `std::make_unique<InterfacePlaneStrain>`.

File: applications/GeoMechanicsApplication/custom_constitutive/interface_coulomb_with_tension_cut_off.cpp [hunk 30]
```diff
@@ -139,8 +139,9 @@ void InterfaceCoulombWithTensionCutOff::CalculateMaterialResponseCauchy(Paramete
     trial_sigma_tau.Tau() = std::abs(trial_sigma_tau.Tau());
 
     if (!mCoulombWithTensionCutOffImpl.IsAdmissibleStressState(trial_sigma_tau)) {
-        mapped_sigma_tau = mCoulombWithTensionCutOffImpl.DoReturnMapping(
-            trial_sigma_tau, CoulombYieldSurface::CoulombAveragingType::NO_AVERAGING);
+        auto elastic_matrix = CalculateElasticContitativeMatrix(r_properties);
+        mapped_sigma_tau    = mCoulombWithTensionCutOffImpl.DoReturnMapping(
+            trial_sigma_tau, YieldSurface::YieldSurfaceAveragingType::NO_AVERAGING, elastic_matrix);
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/interface_coulomb_with_tension_cut_off.cpp]: Here, ask the constitutive law dimension to calculate the elastic matrix:

```suggestion
        mapped_sigma_tau    = mCoulombWithTensionCutOffImpl.DoReturnMapping(
            trial_sigma_tau, YieldSurface::YieldSurfaceAveragingType::NO_AVERAGING, mpConstitutiveDimension->CalculateElasticMatrix());
```

Note that this will only work **after** you've changed the function parameter `rElasticMatrix` of the various overloads from `Matrix&` to `const Matrix&` (see one of my previous suggestions).

File: applications/GeoMechanicsApplication/custom_constitutive/interface_coulomb_with_tension_cut_off.cpp (hunk 8 above)
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/interface_coulomb_with_tension_cut_off.cpp]: This new member function should be removed after you've implemented my previous suggestion (it's no longer needed, since it duplicates the calculation of the elastic matrix).

File: applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.h [hunk 31]
```diff
@@ -69,6 +69,7 @@ class KRATOS_API(GEO_MECHANICS_APPLICATION) MohrCoulombWithTensionCutOff : publi
     bool                                      mIsModelInitialized = false;
 
     [[nodiscard]] Vector CalculateTrialStressVector(const Vector& rStrainVector, const Properties& rProperties) const;
+    [[nodiscard]] Matrix CalculateElasticConstitutiveMatrix(const Properties& rMaterialProperties) const;
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.h]: The same thing here: we should ask the constitutive law dimension to calculate the elastic matrix for us, rather than repeating the implementation here. In this case, you have less work to do, since class `MohrCoulombWithTensionCutOff` already has a constitutive law dimension member (i.e. `mpConstitutiveDimension`).

File: applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp (hunk 10 above)
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp]: Please, don't manipulate the elastic matrix, just use it "as-is". What adds to the confusion is that you have introduced a new member function `CalculateElasticConstitutiveMatrix`, but you're also using the elastic matrix calculated by the constitutive law dimension. Let's keep it as simple as possible: when you need the elastic matrix, ask the constitutive law dimension to calculate it for you. Nothing more and nothing less.

File: applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp [hunk 32]
```diff
@@ -204,17 +204,22 @@ void MohrCoulombWithTensionCutOff::CalculateMaterialResponseCauchy(ConstitutiveL
...
         mCoulombWithTensionCutOffImpl.SaveKappaOfCoulombYieldSurface();
 
+        const auto c0 = r_properties[YOUNG_MODULUS] /
+                        ((1.0 + r_properties[POISSON_RATIO]) * (1.0 - 2.0 * r_properties[POISSON_RATIO]));
+        auto elastic_matrix = mpConstitutiveDimension->CalculateElasticMatrix(r_properties);
+        elastic_matrix /= c0;
+
         auto mapped_principal_stresses = mCoulombWithTensionCutOffImpl.DoReturnMapping(
-            trial_principal_stresses, CoulombYieldSurface::CoulombAveragingType::NO_AVERAGING);
+            trial_principal_stresses, YieldSurface::YieldSurfaceAveragingType::NO_AVERAGING, elastic_matrix);
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp]: Here, I had expected the constitutive law to provide us with the elastic matrix:

```suggestion
            trial_principal_stresses, YieldSurface::YieldSurfaceAveragingType::NO_AVERAGING, mpConstitutiveDimension->CalculateElasticMatrix(r_properties));
```

File: applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp [hunk 33]
```diff
@@ -204,17 +204,22 @@ void MohrCoulombWithTensionCutOff::CalculateMaterialResponseCauchy(ConstitutiveL
...
         // For interchanging principal stresses, retry mapping with averaged principal stresses.
         if (const auto averaging_type = FindAveragingType(mapped_principal_stresses);
-            averaging_type != CoulombYieldSurface::CoulombAveragingType::NO_AVERAGING) {
+            averaging_type != YieldSurface::YieldSurfaceAveragingType::NO_AVERAGING) {
             const auto averaged_principal_trial_stress_vector =
                 AveragePrincipalStressComponents(trial_principal_stresses, averaging_type);
             mCoulombWithTensionCutOffImpl.RestoreKappaOfCoulombYieldSurface();
             mapped_principal_stresses = mCoulombWithTensionCutOffImpl.DoReturnMapping(
-                averaged_principal_trial_stress_vector, averaging_type);
+                averaged_principal_trial_stress_vector, averaging_type, elastic_matrix);
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp]: And also here:

```suggestion
                averaged_principal_trial_stress_vector, averaging_type, mpConstitutiveDimension->CalculateElasticMatrix(r_properties));
```

Note: if we find (through measurements) that this has a measurable impact on performance, we can calculate the elastic matrix just once and assign it to a local variable, to avoid re-calculation here.

File: applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp (hunk 11 above)
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp]: I would expect that the elastic matrix which can be calculated by the constitutive law dimension will do. Therefore, no need to repeat that calculation here.

File: applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.h [hunk 34]
```diff
@@ -32,22 +33,30 @@ class KRATOS_API(GEO_MECHANICS_APPLICATION) TensionCutoff : public YieldSurface
 
     TensionCutoff() = default;
 
-    explicit TensionCutoff(double TensileStrength);
+    explicit TensionCutoff(const Properties& rMaterialProperties);
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.h]: I don't understand why we now need to have access to more material properties.

File: applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.h [hunk 35]
```diff
@@ -32,22 +33,30 @@ class KRATOS_API(GEO_MECHANICS_APPLICATION) TensionCutoff : public YieldSurface
...
 
     [[nodiscard]] double YieldFunctionValue(const Vector& rSigmaTau) const override;
     [[nodiscard]] double YieldFunctionValue(const Geo::SigmaTau& rSigmaTau) const;
     [[nodiscard]] double YieldFunctionValue(const Geo::PrincipalStresses& rPrincipalStresses) const;
     [[nodiscard]] Vector DerivativeOfFlowFunction(const Vector&) const override;
-    [[nodiscard]] Vector DerivativeOfFlowFunction(const Geo::SigmaTau&) const;
+    [[nodiscard]] Vector DerivativeOfFlowFunction(const Geo::SigmaTau&,
+                                                  YieldSurfaceAveragingType AveragingType) const;
+    [[nodiscard]] Vector DerivativeOfFlowFunction(const Geo::PrincipalStresses&,
+                                                  YieldSurfaceAveragingType AveragingType) const;
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.h]: I'm wondering whether we would like to have a default value for the averaging type, just like we did for the Coulomb yield surface? If yes, then perhaps "no averaging" is a good choice?

File: applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.h [hunk 36]
```diff
@@ -32,22 +33,30 @@ class KRATOS_API(GEO_MECHANICS_APPLICATION) TensionCutoff : public YieldSurface
...
+    [[nodiscard]] double CalculatePlasticMultiplier(const Geo::PrincipalStresses& rPrincipalStresses,
+                                                    const Vector& rDerivativeOfFlowFunction) const;
 
 private:
     friend class Serializer;
     void save(Serializer& rSerializer) const override;
     void load(Serializer& rSerializer) override;
 
-    double mTensileStrength = 0.0;
+    Properties mMaterialProperties;
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.h]: Again, is this change really needed now?

File: applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp [hunk 37]
```diff
@@ -33,38 +40,87 @@ double TensionCutoff::YieldFunctionValue(const Vector& rSigmaTau) const
 
 double TensionCutoff::YieldFunctionValue(const Geo::SigmaTau& rSigmaTau) const
 {
-    // Note that we attempt to calculate the principal stress vector (which consists of three values) from the given
-    // sigma and tau (two values). As a result, the second principal stress cannot be uniquely determined.
-    const auto principal_stress_vector = Geo::PrincipalStresses{};
-    return YieldFunctionValue(StressStrainUtilities::TransformSigmaTauToPrincipalStresses(
-        rSigmaTau, principal_stress_vector));
+    return rSigmaTau.Sigma() + rSigmaTau.Tau() - mMaterialProperties[GEO_TENSILE_STRENGTH];
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp]: If we change this line as follows, no further changes are needed when we will add tension-softening:

```suggestion
    return rSigmaTau.Sigma() + rSigmaTau.Tau() - GetTensileStrength();
```

File: applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp [hunk 38]
```diff
@@ -33,38 +40,87 @@ double TensionCutoff::YieldFunctionValue(const Vector& rSigmaTau) const
...
 }
 
 double TensionCutoff::YieldFunctionValue(const Geo::PrincipalStresses& rPrincipalStresses) const
 {
-    return rPrincipalStresses.Values()[0] - mTensileStrength;
+    return rPrincipalStresses.Values()[0] - mMaterialProperties[GEO_TENSILE_STRENGTH];
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp]:
```suggestion
    return rPrincipalStresses.Values()[0] - GetTensileStrength();
```

File: applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp (hunk 16 above)
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp]: As we agreed as a team, we no longer want to use `operator<<=`, but use `UblasUtilities::CreateVector` to construct the vector:

```suggestion
        return UblasUtilities::CreateVector({0.5, 0.5});
```

This suggestion also applies to the other places where you've used `operator<<=` to fill a pre-constructed vector.

File: applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp [hunk 39]
```diff
@@ -33,38 +40,87 @@ double TensionCutoff::YieldFunctionValue(const Vector& rSigmaTau) const
...
+    }
+    return result;
+}
+
+double TensionCutoff::CalculatePlasticMultiplier(const Geo::SigmaTau& rSigmaTau,
+                                                 const Vector& rDerivativeOfFlowFunction) const
+{
+    const auto numerator = mMaterialProperties[INTERFACE_NORMAL_STIFFNESS] * rDerivativeOfFlowFunction[0] +
+                           mMaterialProperties[INTERFACE_SHEAR_STIFFNESS] * rDerivativeOfFlowFunction[1];
+    return -YieldFunctionValue(rSigmaTau) / numerator;
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp]: I'm wondering whether it wouldn't make more sense to pass the elastic matrix and express this calculation in terms of that?

This question also applies to the next overload.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_interface_coulomb_with_tension_cut_off.cpp
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_interface_coulomb_with_tension_cut_off.cpp:1]: The thing that surprised me a bit (but probably that's just me) is that we need interface stiffness values for the case where we map the trial traction to the tension cut-off as well as the "regular" failure zone, but not for the intersection point of these two yield surfaces. How should I understand that?

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp [hunk 40]
```diff
@@ -144,6 +144,8 @@ KRATOS_TEST_CASE_IN_SUITE(MohrCoulombWithTensionCutOff_CalculateMaterialResponse
     properties.SetValue(GEO_COHESION, 10.0);
     properties.SetValue(GEO_DILATANCY_ANGLE, 0.0);
     properties.SetValue(GEO_TENSILE_STRENGTH, 10.0);
+    properties.SetValue(YOUNG_MODULUS, 1.0e6);
+    properties.SetValue(POISSON_RATIO, 0.0);
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp]: Don't we want a test case where $`\nu \ne 0`$?

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp (hunk 20 above)
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp:229]: Why do we only provide a value for $`E`$, but none for $`\nu`$?

I have the same question for some of the other test cases.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp [hunk 41]
```diff
@@ -615,8 +622,11 @@ KRATOS_TEST_CASE_IN_SUITE(MohrCoulombWithTensionCutOff_CalculateMaterialResponse
...
+    properties.SetValue(GEO_MAX_PLASTIC_ITERATIONS, 100);
     properties.SetValue(GEO_FRICTION_ANGLE_FUNCTION_COEFFICIENTS, UblasUtilities::CreateVector({0.0}));
-    properties.SetValue(GEO_COHESION_FUNCTION_COEFFICIENTS, UblasUtilities::CreateVector({1.53589838486}));
+    properties.SetValue(GEO_COHESION_FUNCTION_COEFFICIENTS, UblasUtilities::CreateVector({0.7679491924311227}));
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp]: Was this change expected? And do you have any suggestions for me to check that the new value is correct?

**Review by avdg81 — COMMENTED** [review]
Hi Mohamed,

Thanks a lot for fixing the return mapping for the Coulomb model with a tension cut-off. I have several questions and suggestions. Some are quite straightforward, others may need a bit more thinking/rework. I noticed that @WPK4FEM also has several suggestions, which made me think that perhaps it's more efficient when we sit together and work out some of the suggestions together. What do you think?

My suggestion would be to start processing the easy and straightforward suggestions and leave the more difficult ones for the time when we get together.

One final remark: we need to think about a few more unit tests that cover the fix that you've made, because I'm not sure whether the existing ones actually provide that cover.

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp (hunk 26 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp]: Done

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp (hunk 23 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp]: Done

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp (hunk 28 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp]: Done

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.h (hunk 24 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.h]: Done

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.h (hunk 29 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.h]: Done

File: applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp (hunk 10 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp]: Changed to include the components of rElasticMatrix, replacing of material properties

Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp]: CalculateElasticConstitutiveMatrix is removed.

File: applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp (hunk 32 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp]: Actually here, we don't pass the full form of the elastic matrix. We pass:
ElasticMatrix / [E/(1+nu)(1-2v)].

        const auto c0 = r_properties[YOUNG_MODULUS] /
                        ((1.0 + r_properties[POISSON_RATIO]) * (1.0 - 2.0 * r_properties[POISSON_RATIO]));
        auto elastic_matrix = mpConstitutiveDimension->CalculateElasticMatrix(r_properties);
        elastic_matrix /= c0;

It is the reason, this matrix is calculated in advance, then sent to DoReturnMapping.

File: applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp (hunk 33 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp]: We don't send the complete form of elastic matrix. Please see the comment before.

File: applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp (hunk 11 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp]: This function is removed.

Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp]: Removed

File: applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.h (hunk 31 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.h]: Already removed.

File: applications/GeoMechanicsApplication/custom_constitutive/README.md (hunk 13 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/README.md]: The filling of C is removed

File: applications/GeoMechanicsApplication/custom_constitutive/README.md (hunk 12 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/README.md]: Removed

File: applications/GeoMechanicsApplication/custom_constitutive/README.md (hunk 14 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/README.md:420]: Wrote based on C in a new form. Please see this form in the doc.

File: applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp (hunk 16 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp]: Done

File: applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp (hunk 15 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp]: Fixed.
It was changed, because more material properties was needed (E and nu). However, after passing the elastic matrix, those properties are not required anymore.

File: applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.h (hunk 34 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.h]: It is changed, because more material properties was needed (E and nu). However, after passing the elastic matrix, those properties are not required anymore.
So, this one is reverted to its original form

File: applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.h (hunk 35 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.h]: Done

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp (hunk 20 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp:229]: Yes, when it is not given, it assumes it as zero. However for clearity, poisson ratio is added.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp (hunk 21 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp:267]: added poisson as zero

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp (hunk 2 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp]: Done, 
rTrialPrincipalStress is used.

File: applications/GeoMechanicsApplication/custom_constitutive/yield_surface.h (hunk 25 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/yield_surface.h]: Moved the enum to PrincipalStresses class, and changed the name to PrincipalStressesAveragingType.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_interface_coulomb_with_tension_cut_off.cpp (hunk 18 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_interface_coulomb_with_tension_cut_off.cpp]: I set them to 1.0 before, to avoid breaking the test case, because we modified the formulation for the return mapping, and we get the same results only if k_n=k_t=1. However, here I changed those values as suggested (25 and 12.5) and modified the expected results.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_interface_coulomb_with_tension_cut_off.cpp (hunk 19 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_interface_coulomb_with_tension_cut_off.cpp]: Done. The results are not changed for this test case. It is because this test case is for return mapping at Coulomb yield surface.

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp (hunk 6 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp]: Done

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp (hunk 4 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp]: Done

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp (hunk 3 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp]: Done

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp (hunk 7 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp]: Done

File: applications/GeoMechanicsApplication/custom_constitutive/interface_coulomb_with_tension_cut_off.h (hunk 9 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/interface_coulomb_with_tension_cut_off.h]: This function is removed.

File: applications/GeoMechanicsApplication/custom_constitutive/interface_coulomb_with_tension_cut_off.cpp (hunk 8 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/interface_coulomb_with_tension_cut_off.cpp]: This function is redundant and it is removed

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp (hunk 22 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp:632]: I didn't get your point. Do you mean, how the results change if we set Poisson > 0 ?

File: applications/GeoMechanicsApplication/custom_constitutive/interface_coulomb_with_tension_cut_off.h (hunk 9 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/interface_coulomb_with_tension_cut_off.h]: The local implementation is removed.

File: applications/GeoMechanicsApplication/custom_constitutive/interface_coulomb_with_tension_cut_off.cpp (hunk 30 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/interface_coulomb_with_tension_cut_off.cpp]: Done

File: applications/GeoMechanicsApplication/custom_constitutive/interface_coulomb_with_tension_cut_off.cpp (hunk 8 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/interface_coulomb_with_tension_cut_off.cpp]: Removed

File: applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp (hunk 37 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp]: Reverted,

File: applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp (hunk 38 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp]: Done

File: applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp (hunk 16 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp]: changed to UblasUtilities form

File: applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp (hunk 39 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp]: Alrady the elastic matrix is passed

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp (hunk 20 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp:229]: We pass E and nu for the elastic matrix for continum. However here, interface, we don't need those values as we handle with k_n and k_t. Maybe @WPK4FEM can help explaining it?

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp (hunk 41 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp]: Yes, it is expected, because we fixed the return mapping.
Analytical solution supports this change, and actually this value was extracted from the analytical solution.

**Review by mnabideltares — COMMENTED** [review]
@WPK4FEM @avdg81 
Thank you for the review. I tried to answer them, however, please let me know if I missed some.

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp [hunk 42]
```diff
@@ -48,19 +48,21 @@ bool CoulombWithTensionCutOffImpl::IsAdmissibleStressState(const Geo::PrincipalS
 }
 
 Geo::SigmaTau CoulombWithTensionCutOffImpl::DoReturnMapping(const Geo::SigmaTau& rTrialTraction,
-                                                            CoulombYieldSurface::CoulombAveragingType AveragingType)
+                                                            Geo::PrincipalStresses::PrincipalStressesAveragingType AveragingType,
+                                                            const Matrix& rElasticMatrix)
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp]:
```suggestion
                                                            const Matrix& rElasticConstitutiveTensor)
```
I think we should use the mathematical meaning in the naming, not the C++ type. That repeats through the entire PR. Further, I wonder whether the order of the arguments is a natural one. maybe I would expect the elastic constitutive tensor before the averaging type throughout most of this PR

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp [hunk 43]
```diff
@@ -179,39 +182,53 @@ Geo::PrincipalStresses CoulombWithTensionCutOffImpl::ReturnStressAtTensionApexRe
...
-    return StressStrainUtilities::TransformSigmaTauToPrincipalStresses(
-        ReturnStressAtTensionCutoffReturnZone(
-            StressStrainUtilities::TransformPrincipalStressesToSigmaTau(rPrincipalStresses)),
-        rPrincipalStresses);
+    const auto derivative_of_flow_function =
+        mTensionCutOff.DerivativeOfFlowFunction(rPrincipalStresses, AveragingType);
+    const auto lambda = mTensionCutOff.CalculatePlasticMultiplier(
+        rPrincipalStresses, derivative_of_flow_function, rElasticMatrix);
+    return Geo::PrincipalStresses{rPrincipalStresses.Values() +
+                                  lambda * prod(subrange(rElasticMatrix, 0, 3, 0, 3), derivative_of_flow_function)};
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp:206]: for the subrange 0, 3, 0, 3 indicates begin, end, begin, end. I'm not good in reading the cpp reference, but wonder whether end lies at the last element or beyond the last element. Maybe Anne can shed some light on this.

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp [hunk 44]
```diff
@@ -180,29 +200,61 @@ void CoulombYieldSurface::InitializeKappaDependentFunctions()
...
+                                                       const Vector& rDerivativeOfFlowFunction,
+                                                       const Matrix& rElasticMatrix) const
 {
     const auto sin_phi   = std::sin(GetFrictionAngleInRadians());
-    const auto numerator = sin_phi * rDerivativeOfFlowFunction[0] + rDerivativeOfFlowFunction[1];
-    return (GetCohesion() * std::cos(GetFrictionAngleInRadians()) - rSigmaTau.Sigma() * sin_phi -
-            rSigmaTau.Tau()) /
-           numerator;
+    const auto numerator = rElasticMatrix(0, 0) * rDerivativeOfFlowFunction[0] * sin_phi +
+                           rElasticMatrix(1, 1) * rDerivativeOfFlowFunction[1];
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp]: I would prefer to do a complete matrix vector product first and then use the components of the resulting stress correction direction in the computation of the numerator.

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp [hunk 45]
```diff
@@ -180,29 +200,61 @@ void CoulombYieldSurface::InitializeKappaDependentFunctions()
...
-    const auto principal_stress_vector = UblasUtilities::CreateVector(
-        {(derivative[0] + derivative[1]) / 2.0, 0.0, (derivative[0] - derivative[1]) / 2.0});
+    const auto sin_phi        = std::sin(GetFrictionAngleInRadians());
+    const auto elastic_matrix = subrange(rElasticMatrix, 0, 3, 0, 3);
+    const auto c1             = (inner_prod(row(elastic_matrix, 0), rDerivativeOfFlowFunction) -
+                     inner_prod(row(elastic_matrix, 2), rDerivativeOfFlowFunction)) /
+                    2.0;
+    const auto c2 = (inner_prod(row(elastic_matrix, 0), rDerivativeOfFlowFunction) +
+                     inner_prod(row(elastic_matrix, 2), rDerivativeOfFlowFunction)) *
+                    sin_phi / 2.0;
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp]: Also here, I would prefer the full computation of the stress correction direction first and then using its components for the computation of the denominator.
The separate inner products of rows with dG/dsigma apparently aims at avoiding some computational cost, I'd prefer the clearest implementation first.

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp [hunk 46]
```diff
@@ -180,29 +200,61 @@ void CoulombYieldSurface::InitializeKappaDependentFunctions()
...
+                                                                      const Matrix& rElasticMatrix) const
+{
+    const auto derivative_of_G_to_sigma = DerivativeOfFlowFunction(rTrialPrincipalStresses, AveragingType);
+    const auto mean = std::accumulate(derivative_of_G_to_sigma.begin(), derivative_of_G_to_sigma.end(), 0.0) /
+                      static_cast<double>(derivative_of_G_to_sigma.size());
+    auto deviatoric_principle_stress_vector = Vector{3};
+    std::ranges::transform(derivative_of_G_to_sigma, deviatoric_principle_stress_vector.begin(),
+                           [mean](auto sigma) { return sigma - mean; });
+    return -std::sqrt(2.0 / 3.0) * MathUtils<>::Norm(deviatoric_principle_stress_vector) *
+           CalculatePlasticMultiplier(rTrialPrincipalStresses, derivative_of_G_to_sigma, rElasticMatrix);
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp:242]: This function confuses me because of the mixing of stress and strain.

According to the name it should compute an EquivalentPlasticStrainIncrement. To do so it should use an equivalent deviatoric strain and a plastic multiplier lambda.

For the computation of the plastic multipliers lambda the principal stress is correctly used.
For the computation of the deviatoric strain, correctly dG/dsigma is used, but the result is named deviatoric_principle_stress_vector and in the expression the stress symbol sigma appears. I expect something like deviatoric strain

File: applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp [hunk 47]
```diff
@@ -204,17 +204,23 @@ void MohrCoulombWithTensionCutOff::CalculateMaterialResponseCauchy(ConstitutiveL
     } else {
         mCoulombWithTensionCutOffImpl.SaveKappaOfCoulombYieldSurface();
 
+        const auto c0 = r_properties[YOUNG_MODULUS] /
+                        ((1.0 + r_properties[POISSON_RATIO]) * (1.0 - 2.0 * r_properties[POISSON_RATIO]));
+        auto elastic_matrix = mpConstitutiveDimension->CalculateElasticMatrix(r_properties);
+        elastic_matrix /= c0;
+
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp]: Modification of the elastic constitutive tensor by using Young's modulus and Poisson's ratio prevents use of any other form of elasticity. Please do not do it this way.

File: applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp [hunk 48]
```diff
@@ -49,12 +46,58 @@ double TensionCutoff::YieldFunctionValue(const Geo::PrincipalStresses& rPrincipa
...
+        KRATOS_ERROR << "Unsupported Averaging Type: " << static_cast<std::size_t>(AveragingType) << "\n";
+    }
+}
+
+double TensionCutoff::CalculatePlasticMultiplier(const Geo::SigmaTau& rTrialSigmaTau,
+                                                 const Vector&        rDerivativeOfFlowFunction,
+                                                 const Matrix&        rElasticMatrix) const
+{
+    const auto numerator = rElasticMatrix(0, 0) * rDerivativeOfFlowFunction[0] +
+                           rElasticMatrix(1, 1) * rDerivativeOfFlowFunction[1];
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp]: Please use the result of the stress correction direction full matrix vector product i.s.o. doing it component by component as here.

File: applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp [hunk 49]
```diff
@@ -49,12 +46,58 @@ double TensionCutoff::YieldFunctionValue(const Geo::PrincipalStresses& rPrincipa
...
+    return -YieldFunctionValue(rTrialSigmaTau) / numerator;
+}
+
+double TensionCutoff::CalculatePlasticMultiplier(const Geo::PrincipalStresses& rTrialPrincipalStresses,
+                                                 const Vector& rDerivativeOfFlowFunction,
+                                                 const Matrix& rElasticMatrix) const
+{
+    const auto elastic_matrix = subrange(rElasticMatrix, 0, 3, 0, 3);
+    const auto numerator      = inner_prod(row(elastic_matrix, 0), rDerivativeOfFlowFunction);
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp]: please do the full matrix vector product to get a stress correction direction and then use its component.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_interface_coulomb_with_tension_cut_off.cpp [hunk 50]
```diff
@@ -179,7 +182,7 @@ KRATOS_TEST_CASE_IN_SUITE(InterfaceCoulombWithTensionCutOff_CalculateMaterialRes
 
     // Assert
     Vector expected_cauchy_stress_vector(2);
-    expected_cauchy_stress_vector <<= 8.0, 2.0;
+    expected_cauchy_stress_vector <<= 7.3333333333333333, 2.6666666666666667;
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_interface_coulomb_with_tension_cut_off.cpp]: Please avoid the use of ublas assignment and replace by ublas utilities CreateVector.
If this is an analytically computed result, we probably can avoid introduction of further rounding by writing something like 22.0/3.0 and 8.0/3.0 and let the precision depend on the computer accuracy.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp [hunk 51]
```diff
@@ -538,6 +548,7 @@ KRATOS_TEST_CASE_IN_SUITE(MohrCoulombWithTensionCutOff_CalculateMaterialResponse
     properties.SetValue(GEO_COHESION, 10.0);
     properties.SetValue(GEO_DILATANCY_ANGLE, 20.0);
     properties.SetValue(GEO_TENSILE_STRENGTH, 10.0);
+    properties.SetValue(YOUNG_MODULUS, 1.0e6);
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp:551]: Then explicitely write Poisson's ratio here too.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp [hunk 52]
```diff
@@ -641,7 +655,7 @@ KRATOS_TEST_CASE_IN_SUITE(MohrCoulombWithTensionCutOff_CalculateMaterialResponse
     // Act and Assert
     cauchy_stress_vector = UblasUtilities::CreateVector({10.0, 0.0, -40.0, 0.0});
     expected_cauchy_stress_vector =
-        UblasUtilities::CreateVector({3.0004227197012, 0.0, -33.0004227197012, 0.0});
+        UblasUtilities::CreateVector({2.780289249892, 2.780289249892, -35.5605784998, 0});
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp]: If these are the result of an analytical computation, please write in terms of the analytics and don't truncate. Otherwise mark it as regression values.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp [hunk 53]
```diff
@@ -615,8 +626,11 @@ KRATOS_TEST_CASE_IN_SUITE(MohrCoulombWithTensionCutOff_CalculateMaterialResponse
     properties.SetValue(GEO_COHESION, 10.0);
     properties.SetValue(GEO_DILATANCY_ANGLE, 0.0);
     properties.SetValue(GEO_TENSILE_STRENGTH, 10.0);
+    properties.SetValue(YOUNG_MODULUS, 1.0e6);
+    properties.SetValue(POISSON_RATIO, 0.0);
+    properties.SetValue(GEO_MAX_PLASTIC_ITERATIONS, 100);
     properties.SetValue(GEO_FRICTION_ANGLE_FUNCTION_COEFFICIENTS, UblasUtilities::CreateVector({0.0}));
-    properties.SetValue(GEO_COHESION_FUNCTION_COEFFICIENTS, UblasUtilities::CreateVector({1.53589838486}));
+    properties.SetValue(GEO_COHESION_FUNCTION_COEFFICIENTS, UblasUtilities::CreateVector({0.7679491924311227}));
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp]: If this is the result of an analytical computation, please write in terms of the analytics and don't truncate. Otherwise mark it as a regression value.

**Review by WPK4FEM — COMMENTED** [review]
Hi Mohamed,
Thank you for including the constitutive dimension and getting the elastic constitutive tensor from there. I have some more remarks that hopefully make its use more general and easier to read.
Regards, Wijtze Pieter

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp (hunk 22 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp:632]: How many iterations does the return mapping take now, after the correction of including the elastic constitutive tensor.

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp (hunk 42 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp]: @WPK4FEM
Thank you for the review. 
Do you have any suggestion for the mathematical naming?
The order of variables for the elastic matrix is changed. They are set before the averaging type.

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp (hunk 44 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp]: Done

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp (hunk 45 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp]: Done

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp (hunk 46 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp:242]: The namings are changed

File: applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp (hunk 47 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp]: Do you have any suggestion in how to do it in a different way?

File: applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp (hunk 48 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp]: Done

File: applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp (hunk 49 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp]: Done

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_interface_coulomb_with_tension_cut_off.cpp (hunk 50 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_interface_coulomb_with_tension_cut_off.cpp]: Done

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp (hunk 51 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp:551]: POISSON_RATIO = 0 is added

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp (hunk 52 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp]: regression values. A short comment is added after the values

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp (hunk 53 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp]: Analytical. It is written in exact form (2.5 - sqrt(3))

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp [hunk 54]
```diff
@@ -179,39 +182,53 @@ Geo::PrincipalStresses CoulombWithTensionCutOffImpl::ReturnStressAtTensionApexRe
...
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp]: I will soon add addition operations (i.e. `operator+=` and `operator+`) to class `PrincipalStresses`, just so we can make this return statement more similar to what you wrote for the overload with `SigmaTau`. Perhaps, at some point we can extract a private member function template that can be called from both overloads, since conceptually we're doing the same thing using different stress states. At present, no further action from your side is required.

**Edit:** In fact, we might even be able to take this one step further, since I see a similar pattern for the return mapping code that targets the Coulomb yield surface. Basically, you could say that if we have a template member function that receives a trial stress state, a yield surface, an elastic matrix and an averaging type, we should be able to express the return mapping in a very generic way consisting of the following steps:
1. Request the given yield surface to calculate the derivative of the flow function by passing it the trial stress state and the averaging type.
2. Request the given yield surface to calculate the plastic multiplier by passing it the trial stress state, the derivative of the flow function and the elastic matrix.
3. Calculate the mapped stress state by returning the sum of the trial stress state and the product of the plastic multiplier, the elastic matrix and the derivative of the flow function.

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.h [hunk 55]
```diff
@@ -59,24 +61,34 @@ class CoulombWithTensionCutOffImpl
...
     [[nodiscard]] Geo::SigmaTau ReturnStressAtTensionApexReturnZone(const Geo::SigmaTau&) const;
     [[nodiscard]] Geo::PrincipalStresses ReturnStressAtTensionApexReturnZone(const Geo::PrincipalStresses& rPrincipalStresses) const;
-    [[nodiscard]] Geo::SigmaTau ReturnStressAtTensionCutoffReturnZone(const Geo::SigmaTau& rTraction) const;
-    [[nodiscard]] Geo::PrincipalStresses ReturnStressAtTensionCutoffReturnZone(const Geo::PrincipalStresses& rPrincipalStresses) const;
-    [[nodiscard]] Geo::SigmaTau ReturnStressAtRegularFailureZone(const Geo::SigmaTau& rTraction,
-                                                                 CoulombYieldSurface::CoulombAveragingType AveragingType) const;
+    [[nodiscard]] Geo::SigmaTau ReturnStressAtTensionCutoffReturnZone(
+        const Geo::SigmaTau&                                   rTraction,
+        const Matrix&                                          rElasticMatrix,
+        Geo::PrincipalStresses::PrincipalStressesAveragingType AveragingType) const;
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.h]: I feel it would be a bit clearer if we let the names of the input stress states (i.e. the first parameter of each `Return...` member function) start with `rTrial` to emphasize that the return mapping starts from the trial stress states.

File: applications/GeoMechanicsApplication/custom_constitutive/yield_surface.h (hunk 25 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/custom_constitutive/yield_surface.h]: Now that the `enum class` is a member of class `PrincipalStresses` we can reduce its name to just `AveragingType` to avoid repetition of "principal stresses".

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.h
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.h:1]: Can you please remove the forward declaration of class `PrincipalStresses` (line 29), since you need to include it now? Also, please add an `#include` here for class `PrincipalStresses` (since you need it for the definition of `PrincipalStressesAveragingType`). Thanks.

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.h
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.h:1]: Can you also remove the forward declaration of class `PrincipalStresses` here (line 32), since you now include the header file that contains the definition of this class.

File: applications/GeoMechanicsApplication/custom_constitutive/interface_coulomb_with_tension_cut_off.cpp [hunk 56]
```diff
@@ -140,7 +149,8 @@ void InterfaceCoulombWithTensionCutOff::CalculateMaterialResponseCauchy(Paramete
 
     if (!mCoulombWithTensionCutOffImpl.IsAdmissibleStressState(trial_sigma_tau)) {
         mapped_sigma_tau = mCoulombWithTensionCutOffImpl.DoReturnMapping(
-            trial_sigma_tau, CoulombYieldSurface::CoulombAveragingType::NO_AVERAGING);
+            trial_sigma_tau, mpConstitutiveDimension->CalculateElasticMatrix(r_properties),
+            Geo::PrincipalStresses::PrincipalStressesAveragingType::NO_AVERAGING);
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/interface_coulomb_with_tension_cut_off.cpp]: Not for now, but maybe later: we may consider to make the averaging type here optional, by giving it a default value of "no averaging". What do you think?

File: applications/GeoMechanicsApplication/custom_constitutive/interface_coulomb_with_tension_cut_off.cpp
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/interface_coulomb_with_tension_cut_off.cpp:1]: Can you please add serialization of member `mpConstitutiveDimension` to the member functions `save` and `load`?

File: applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp (hunk 10 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp]: Thanks for removing `CalculateElasticConstitutiveMatrix`. Yet, you're still manipulating the given elastic matrix. I think that @WPK4FEM meant to just use it "as-is", without calculating a "derived" elastic matrix. This may still require a few changes in the code.

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp [hunk 57]
```diff
@@ -180,29 +200,59 @@ void CoulombYieldSurface::InitializeKappaDependentFunctions()
...
+    Geo::PrincipalStresses::PrincipalStressesAveragingType AveragingType) const
 {
-    const auto derivative              = DerivativeOfFlowFunction(rSigmaTau, AveragingType);
-    const auto principal_stress_vector = UblasUtilities::CreateVector(
-        {(derivative[0] + derivative[1]) / 2.0, 0.0, (derivative[0] - derivative[1]) / 2.0});
-    const auto mean = std::accumulate(principal_stress_vector.begin(), principal_stress_vector.end(), 0.0) /
-                      static_cast<double>(principal_stress_vector.size());
+    const auto derivative_of_G_to_sigma = DerivativeOfFlowFunction(rTrialPrincipalStresses, AveragingType);
+    const auto mean = std::accumulate(derivative_of_G_to_sigma.begin(), derivative_of_G_to_sigma.end(), 0.0) /
+                      static_cast<double>(derivative_of_G_to_sigma.size());
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp]: I'm still very hesitant about this statement. You are aware that you're calculating the average of the components of the derivative of G w.r.t. sigma here. In the other overload (see above), you're applying this operation to the principal strain (??) vector. Can you please revisit this part of the code once more to double-check that this is what you meant?

File: applications/GeoMechanicsApplication/custom_constitutive/principal_stresses.hpp [hunk 58]
```diff
@@ -25,6 +25,12 @@ namespace Kratos::Geo
 class KRATOS_API(GEO_MECHANICS_APPLICATION) PrincipalStresses
 {
 public:
+    enum class PrincipalStressesAveragingType {
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/principal_stresses.hpp]: Since this `enum class` is now part of class `PrincipalStresses`, I don't think we need to repeat that part here:

```suggestion
    enum class AveragingType {
```

File: applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp [hunk 59]
```diff
@@ -49,12 +46,57 @@ double TensionCutoff::YieldFunctionValue(const Geo::PrincipalStresses& rPrincipa
 Vector TensionCutoff::DerivativeOfFlowFunction(const Vector&) const
 {
     const auto unused_sigma_tau = Geo::SigmaTau{};
-    return DerivativeOfFlowFunction(unused_sigma_tau);
+    return DerivativeOfFlowFunction(
+        unused_sigma_tau, Geo::PrincipalStresses::PrincipalStressesAveragingType::NO_AVERAGING);
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp]: No need to repeat the default averaging type:

```suggestion
        unused_sigma_tau);
```

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_yield_surface.cpp [hunk 60]
```diff
@@ -126,10 +126,11 @@ TEST_P(ParametrizedDerivativeOfFlowFunctionOfTensionCutOff, TensionCutOff_Deriva
     constexpr auto tensile_strength = 2.0;
     const auto     tension_cut_off  = TensionCutoff{tensile_strength};
     const auto&    sigma_tau        = GetParam();
+    const auto averaging_type = Geo::PrincipalStresses::PrincipalStressesAveragingType::NO_AVERAGING;
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_yield_surface.cpp]: But this is the default value of the averaging type that `DerivativeOfFlowFunction` receives. I don't understand why we define it here when the default value is just what we need...?

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_yield_surface.cpp [hunk 61]
```diff
@@ -147,6 +148,7 @@ KRATOS_TEST_CASE_IN_SUITE(TensionCutOff_CanBeSavedAndLoaded, KratosGeoMechanicsF
     constexpr auto tensile_strength = 2.0;
     const auto     tension_cut_off  = TensionCutoff{tensile_strength};
     auto           serializer       = StreamSerializer{};
+    const auto averaging_type = Geo::PrincipalStresses::PrincipalStressesAveragingType::NO_AVERAGING;
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_yield_surface.cpp]: Same question here.

**Review by avdg81 — COMMENTED** [review]
Hi Mohamed,
Thanks a lot for processing the review suggestions. I feel that we're moving in the right direction. Still, I think there is some work left to be done. I've tried to explain it as clearly as possible in a set of new suggestions. But in case anything is unclear, please don't hesitate to ask me. Thanks.

File: applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp (hunk 32 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp]: I'm sorry, I don't understand what you're doing exactly. And perhaps I misunderstand, but I think that changing the elastic matrix that is returned by the constitutive law dimension is not in line with what @WPK4FEM suggested either. I feel we need to discuss about this with the three of us.

File: applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp (hunk 33 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp]: Again, I don't think this is what @WPK4FEM meant. Let's discuss this later with the three of us and modify the code on the spot.

File: applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp (hunk 37 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp]: This is not what I meant. Please replace `mTensileStrength` in the subtraction to `GetTensileStrength()`. In this way, when we later add tension-softening, this subtraction doesn't need to be changed anymore.

File: applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp (hunk 38 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp]: Also here, please replace `mTensileStrength` by `GetTensileStrength()` as suggested before.

File: applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp (hunk 16 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp]: Please, remove the now redundant `#include <boost/numeric/ublas/assignment.hpp>`. Thanks.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp (hunk 20 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp:229]: But these are the unit tests for continuum constitutive law, right? So then, we do need $`E`$ and $`\nu`$, I think.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_yield_surface.cpp (hunk 61 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_yield_surface.cpp]: Removed

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_yield_surface.cpp (hunk 60 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_yield_surface.cpp]: Removed

File: applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp (hunk 59 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/tension_cutoff.cpp]: Removed

File: applications/GeoMechanicsApplication/custom_constitutive/principal_stresses.hpp (hunk 58 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/principal_stresses.hpp]: Changed to AveragingType

File: applications/GeoMechanicsApplication/custom_constitutive/interface_coulomb_with_tension_cut_off.cpp
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/interface_coulomb_with_tension_cut_off.cpp:1]: Added

File: applications/GeoMechanicsApplication/custom_constitutive/interface_coulomb_with_tension_cut_off.cpp (hunk 56 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/interface_coulomb_with_tension_cut_off.cpp]: I find it a good idea, but I think it needs to have low piority

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.h
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.h:1]: Done

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.h
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.h:1]: Done

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.h (hunk 55 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.h]: tTialTractions and rTrialPrincipalStresses are implemented

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp (hunk 57 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_constitutive/coulomb_yield_surface.cpp]: The namings are modified.

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp (hunk 43 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp:206]: As far as I know and understand from the Boost code, the second index should point to one-past-the-last element. For the code that is written here, that means the sub-matrix will be 3x3.

**Review by avdg81 — APPROVED** [review]
Hi Mohamed,
Thanks a lot for all the hard work and taking care of the review suggestions. I feel this PR is good to go.

**Review by WPK4FEM — APPROVED** [review]
Hi Mohamed,
Lets bring this back to master.  I have some future suggestions for variable name changes and a suggestion for a not using components of C in the documentation, but we can do that in a next pull request as we still will work on the corner return.
Regards, Wijtze Pieter
