### PR TITLE
[MeshMoving] Explicit FM-ALE fix iterator (reference instead of copy)

### LINKED ISSUE #2950: [MeshMoving] explicit-mesh-moving test fails after 2740
see #2740 
The test still uses `Element`, I think it should now use `MeshElement`
I tried it but it seems like the `MeshElement` is not registered
@loumalouomega

### PR DESCRIPTION
**Pull request by rubenzorrilla**
The new MeshElement raised this potential source of errors. @philbucher and @loumalouomega thanks again!

(this fixes #2950)

### CODE REVIEW

**Review by loumalouomega — APPROVED** [review]
OK

File: applications/MeshMovingApplication/custom_utilities/explicit_mesh_moving_utilities.cpp [hunk 1]
```diff
@@ -66,7 +66,7 @@ namespace Kratos
 
         // Copy the origin model part elements
         auto &r_elems = rOriginModelPart.Elements();
-        for(auto elem : r_elems){
+        for(auto &elem : r_elems){
```
Comment (philbucher) [inline applications/MeshMovingApplication/custom_utilities/explicit_mesh_moving_utilities.cpp:69]: so here you were silently creating new elements?


@msandre could such things be avoided with #2527 ?

Comment (rubenzorrilla) [reply applications/MeshMovingApplication/custom_utilities/explicit_mesh_moving_utilities.cpp:69]: Actually, I need to create new elements. If I'm not wrong, I was iterating with a copy of the elements (no ampersand). So when creating the copy iterator, the base element copy constructor was called instead of the MeshElement one (don't ask me why).

Comment (msandre) [reply applications/MeshMovingApplication/custom_utilities/explicit_mesh_moving_utilities.cpp:69]: @philbucher I don't think so. Explicit is not used for copy constructors.
