### PR TITLE
[Core] In `SparseMatrixMultiplicationUtility` some modernization + plus `SortRows` minor optimization + replace `omp` simple loops with `IndexPartition<IndexType>`

### LINKED ISSUE #12138: [Core] Matrix Product Performance
## Symptoms

I noticed that moderately increasing the number of MPCs in a given system (while not changing anything else) significantly increased assembly duration, to the point that it became an order of magnitude more expensive than solving the resulting linear system.

## Traceback

1) `ResidualBasedBlockBuilderAndSolver::ApplyConstraints`
2) `SparseMatrixMultiplicationUtility::MatrixMultiplication`
3) `SparseMatrixMultiplicationUtility::MatrixMultiplicationSaad`
4) `SparseMatrixMultiplicationUtility::SortRows`

Surprisingly, `SortRows` is to blame.

## Issue

This is an issue of complexity and bad parallelization. `SortRows` loops over the rows of the sparse matrix and **naively** sorts the entries (values and column indices) within it, meaning that each row has quadratic complexity.

```cpp
template <typename TSize, typename Col, typename TIndexType, typename ValueType>
    static inline void SortRows(
        const TIndexType* CPtr,
        const TSize NRows,
        const TSize NCols,
        Col* Columns,
        ValueType* Values
        )
    {
        #pragma omp parallel
        {
            #pragma omp for
            for (int i_row=0; i_row<static_cast<int>(NRows); i_row++) {
                const TIndexType row_begin = CPtr[i_row];
                const TIndexType row_end = CPtr[i_row + 1];

                for(IndexType j = 1; j < row_end - row_begin; ++j) {
                    const IndexType i_column = Columns[j + row_begin];
                    const double value = Values[j + row_begin];

                    SignedIndexType i = j - 1;

                    while(i >= 0 && Columns[i + row_begin] > i_column) {
                        Columns[i + 1 + row_begin] = Columns[i + row_begin];
                        Values[i + 1 + row_begin] = Values[i + row_begin];
                        i--;
                    }

                    Columns[i + 1 + row_begin] = i_column;
                    Values[i + 1 + row_begin] = value;
                }
            }
        }
    }
```

As a result, the whole function has `O(number_of_rows * number_of_nonzero_columns²)` complexity that will be somewhere between quadratic and cubic complexity.  This is especially bad for MPCs that relate many masters to a single slave, as this results in a few dense rows. Since parallelization is done trivially on rows (each core gets some rows to sort) instead of parallelizing the sorting algorithm, this leads to serialization on dense rows and terrible performance.

## Discussion

As I see it, there are three possible ways of going about solving this issue:
- keep the current parallelization (rows assigned to cores) and change the sorting from naive to `std::sort`. This somewhat addresses complexity issues but will still lead to serialization if there's at least one dense row in the matrix.
- serially loop through rows and parallelize the sorting algorithm. I imagine we'd take a performance hit for usual cases (every row is sparse) but at least we'd never get serialized on dense rows.
- keep looping through rows in parallel, but also parallelize sorting dense rows. This would be the ideal solution, but it'll be tricky to implement because there are several things we need to ensure:
   - instead of directly assigning rows to cores, make sorting a row a task
   - decide whether parallelizing a row makes sense (requires some heuristics similar to what we're already doing in matrix multiplication)
   - if parallelizing a row is necessary, break up the sorting algorithm into tasks and assign them to cores. We need a parallel sorting algorithm for this

Any comments or other ideas?

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Fixes https://github.com/KratosMultiphysics/Kratos/issues/12138.

This PR refactors the `sparse_matrix_multiplication_utility.h`. The changes involve reorganizing the code, updating comments, and improving readability, some minor optimization and use the moder `parallel_utilities.h`:
- Reformatting license information and author details.
- Fixing `typedef` declarations with using.
- Optimizing loops and variable declarations.
- Updating comments for clarity.
- Cleaning up unused code and redundant comments.
- Ensuring proper indentation and formatting throughout the file.
- `SortRows` minor optimization using `std::sort` instead of  naive sort, STL uses quicksort algorithm which is *n log n* complexity instead of n^2 complexity.
- Reorganized and optimized loops using OpenMP directives for parallel execution.

**🆕 Changelog**

- [Some modernization + plus `SortRows` minor optimization](https://github.com/KratosMultiphysics/Kratos/commit/6fb8efd504e39affbaf57ac9e74344e50196ed99)
- [Replace `omp` simple loops with `IndexPartition<IndexType>`](https://github.com/KratosMultiphysics/Kratos/commit/f91598bfeb7b357a690e0ef5e8ca7a4253d55b85)

### CODE REVIEW

File: kratos/utilities/sparse_matrix_multiplication_utility.h [hunk 1]
```diff
@@ -659,31 +654,28 @@ class SparseMatrixMultiplicationUtility
...
-                    const double v = Values[j + row_beg];
-
-                    SignedIndexType i = j - 1;
+        IndexPartition<TSize>(NRows).for_each([&](TSize i_row) {
+            const TIndexType row_begin = CPtr[i_row];
+            const TIndexType row_end = CPtr[i_row + 1];
+            TSize length = row_end - row_begin;
+
+            // Use vectors to facilitate sorting
+            std::vector<std::pair<Col, ValueType>> row_data(length);
```
Comment (matekelemen) [inline kratos/utilities/sparse_matrix_multiplication_utility.h:621]: I'd rather do the sorting in-place and avoid copying two full arrays twice. It needs a custom iterator definition but that shouldn't be so bad; I'll open an example PR tomorrow.

**Comment by matekelemen** [comment]
Here's a [link](https://gigamove.rwth-aachen.de/en/download/83f1a71d7e37f64f7b8442bf343c576a) to two matrices whose product highlights the issue

and an example program to read the files and carry out the matrix product:
```cpp
// --- Core Includes ---
#include "spaces/ublas_space.h"
#include "utilities/sparse_matrix_multiplication_utility.h"

// --- STL Includes ---
#include <filesystem>
#include <sstream>
#include <chrono>
#include <ctime>


namespace Kratos {


using Space = TUblasSparseSpace<double>;


void read(const std::filesystem::path& rPath,
          Space::MatrixType& rTargetMatrix)
{
    std::ifstream file(rPath);
    std::string line;

    // Expect exactly 1 comment line ==> ignore it
    std::getline(file, line);

    // Expect size line ==> parse it
    std::size_t row_count=0ul, column_count=0ul, nonzero_count=0ul;
    std::getline(file, line);
    {
        std::istringstream stream(line);
        if (!(stream >> row_count >> column_count >> nonzero_count)) throw 1;
    }

    rTargetMatrix.resize(row_count, column_count, /*preserve=*/false);

    while (std::getline(file, line)) {
        // Ignore empty lines
        if (line.empty()) continue;

        std::istringstream stream(line);
        std::size_t i_row = 0ul, i_column = 0ul;
        double value;
        if (!(stream >> i_row >> i_column >> value)) throw 1;

        // Matrix market works with 1-based indices
        --i_row;
        --i_column;

        rTargetMatrix.insert_element(i_row, i_column, value);
    }

    rTargetMatrix.complete_index1_data();
}


int main()
{
    Space::MatrixType left, right;

    try {read("left.mm", left);} catch (...) {return 1;}
    try {read("right.mm", right);} catch (...) {return 2;}

    Space::MatrixType result;

    std::cout << "Begin matrix product\n";
    const auto begin = std::chrono::system_clock::now();
    SparseMatrixMultiplicationUtility::MatrixMultiplication(left, right, result);
    KRATOS_INFO("Matrix product duration")
        << std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now() - begin).count() << " ms"
        << (result.nnz() == 0 ? " " : "\n"); // <== dummy line to use the result

    return 0;
}


} // namespace Kratos


int main(int argc, const char** const argv)
{
    return Kratos::main();
}

```

File: kratos/utilities/sparse_matrix_multiplication_utility.h (hunk 1 above)
Comment (loumalouomega) [reply kratos/utilities/sparse_matrix_multiplication_utility.h:621]: Okay

**Comment by loumalouomega** [comment]
> Here's a [link](https://gigamove.rwth-aachen.de/en/download/83f1a71d7e37f64f7b8442bf343c576a) to two matrices whose product highlights the issue
> 	
> left 	right
> left operand 	right operand
> 
> and an example program to read the files and carry out the matrix product:
> 
> ```c++
> // --- Core Includes ---
> #include "spaces/ublas_space.h"
> #include "utilities/sparse_matrix_multiplication_utility.h"
> 
> // --- STL Includes ---
> #include <filesystem>
> #include <sstream>
> #include <chrono>
> #include <ctime>
> 
> 
> namespace Kratos {
> 
> 
> using Space = TUblasSparseSpace<double>;
> 
> 
> void read(const std::filesystem::path& rPath,
>           Space::MatrixType& rTargetMatrix)
> {
>     std::ifstream file(rPath);
>     std::string line;
> 
>     // Expect exactly 1 comment line ==> ignore it
>     std::getline(file, line);
> 
>     // Expect size line ==> parse it
>     std::size_t row_count=0ul, column_count=0ul, nonzero_count=0ul;
>     std::getline(file, line);
>     {
>         std::istringstream stream(line);
>         if (!(stream >> row_count >> column_count >> nonzero_count)) throw 1;
>     }
> 
>     rTargetMatrix.resize(row_count, column_count, /*preserve=*/false);
> 
>     while (std::getline(file, line)) {
>         // Ignore empty lines
>         if (line.empty()) continue;
> 
>         std::istringstream stream(line);
>         std::size_t i_row = 0ul, i_column = 0ul;
>         double value;
>         if (!(stream >> i_row >> i_column >> value)) throw 1;
> 
>         // Matrix market works with 1-based indices
>         --i_row;
>         --i_column;
> 
>         rTargetMatrix.insert_element(i_row, i_column, value);
>     }
> 
>     rTargetMatrix.complete_index1_data();
> }
> 
> 
> int main()
> {
>     Space::MatrixType left, right;
> 
>     try {read("left.mm", left);} catch (...) {return 1;}
>     try {read("right.mm", right);} catch (...) {return 2;}
> 
>     Space::MatrixType result;
> 
>     std::cout << "Begin matrix product\n";
>     const auto begin = std::chrono::system_clock::now();
>     SparseMatrixMultiplicationUtility::MatrixMultiplication(left, right, result);
>     KRATOS_INFO("Matrix product duration")
>         << std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now() - begin).count() << " ms"
>         << (result.nnz() == 0 ? " " : "\n"); // <== dummy line to use the result
> 
>     return 0;
> }
> 
> 
> } // namespace Kratos
> 
> 
> int main(int argc, const char** const argv)
> {
>     return Kratos::main();
> }
> ```

To avoid compile a binary you can use python directly:

~~~py
import KratosMultiphysics

import os
import time

def GetFilePath(fileName):
    return os.path.join(os.path.dirname(os.path.realpath(__file__)), fileName)

if __name__ == '__main__':
    space = KratosMultiphysics.UblasSparseSpace()

    #read the matrices
    A = KratosMultiphysics.CompressedMatrix()
    file_read = KratosMultiphysics.ReadMatrixMarketMatrix(GetFilePath("left"),A)

    B = KratosMultiphysics.CompressedMatrix()
    file_read = KratosMultiphysics.ReadMatrixMarketMatrix(GetFilePath("right"),B)

    # Multiply matrices
    AB = KratosMultiphysics.CompressedMatrix()

    start_time = time.time()
    KratosMultiphysics.SparseMatrixMultiplicationUtility.MatrixMultiplication(A, B, AB)
    end_time = time.time()

    execution_time = end_time - start_time
    print("Matrix multiplication execution time: ", execution_time, " seconds")
~~~

I am on it!

**Comment by loumalouomega** [comment]
> > Here's a [link](https://gigamove.rwth-aachen.de/en/download/83f1a71d7e37f64f7b8442bf343c576a) to two matrices whose product highlights the issue
> > left 	right
> > left operand 	right operand
> > and an example program to read the files and carry out the matrix product:
> > ```c++
> > // --- Core Includes ---
> > #include "spaces/ublas_space.h"
> > #include "utilities/sparse_matrix_multiplication_utility.h"
> > 
> > // --- STL Includes ---
> > #include <filesystem>
> > #include <sstream>
> > #include <chrono>
> > #include <ctime>
> > 
> > 
> > namespace Kratos {
> > 
> > 
> > using Space = TUblasSparseSpace<double>;
> > 
> > 
> > void read(const std::filesystem::path& rPath,
> >           Space::MatrixType& rTargetMatrix)
> > {
> >     std::ifstream file(rPath);
> >     std::string line;
> > 
> >     // Expect exactly 1 comment line ==> ignore it
> >     std::getline(file, line);
> > 
> >     // Expect size line ==> parse it
> >     std::size_t row_count=0ul, column_count=0ul, nonzero_count=0ul;
> >     std::getline(file, line);
> >     {
> >         std::istringstream stream(line);
> >         if (!(stream >> row_count >> column_count >> nonzero_count)) throw 1;
> >     }
> > 
> >     rTargetMatrix.resize(row_count, column_count, /*preserve=*/false);
> > 
> >     while (std::getline(file, line)) {
> >         // Ignore empty lines
> >         if (line.empty()) continue;
> > 
> >         std::istringstream stream(line);
> >         std::size_t i_row = 0ul, i_column = 0ul;
> >         double value;
> >         if (!(stream >> i_row >> i_column >> value)) throw 1;
> > 
> >         // Matrix market works with 1-based indices
> >         --i_row;
> >         --i_column;
> > 
> >         rTargetMatrix.insert_element(i_row, i_column, value);
> >     }
> > 
> >     rTargetMatrix.complete_index1_data();
> > }
> > 
> > 
> > int main()
> > {
> >     Space::MatrixType left, right;
> > 
> >     try {read("left.mm", left);} catch (...) {return 1;}
> >     try {read("right.mm", right);} catch (...) {return 2;}
> > 
> >     Space::MatrixType result;
> > 
> >     std::cout << "Begin matrix product\n";
> >     const auto begin = std::chrono::system_clock::now();
> >     SparseMatrixMultiplicationUtility::MatrixMultiplication(left, right, result);
> >     KRATOS_INFO("Matrix product duration")
> >         << std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now() - begin).count() << " ms"
> >         << (result.nnz() == 0 ? " " : "\n"); // <== dummy line to use the result
> > 
> >     return 0;
> > }
> > 
> > 
> > } // namespace Kratos
> > 
> > 
> > int main(int argc, const char** const argv)
> > {
> >     return Kratos::main();
> > }
> > ```
> 
> To avoid compile a binary you can use python directly:
> 
> ```python
> import KratosMultiphysics
> 
> import os
> import time
> 
> def GetFilePath(fileName):
>     return os.path.join(os.path.dirname(os.path.realpath(__file__)), fileName)
> 
> if __name__ == '__main__':
>     space = KratosMultiphysics.UblasSparseSpace()
> 
>     #read the matrices
>     A = KratosMultiphysics.CompressedMatrix()
>     file_read = KratosMultiphysics.ReadMatrixMarketMatrix(GetFilePath("left"),A)
> 
>     B = KratosMultiphysics.CompressedMatrix()
>     file_read = KratosMultiphysics.ReadMatrixMarketMatrix(GetFilePath("right"),B)
> 
>     # Multiply matrices
>     AB = KratosMultiphysics.CompressedMatrix()
> 
>     start_time = time.time()
>     KratosMultiphysics.SparseMatrixMultiplicationUtility.MatrixMultiplication(A, B, AB)
>     end_time = time.time()
> 
>     execution_time = end_time - start_time
>     print("Matrix multiplication execution time: ", execution_time, " seconds")
> ```
> 
> I am on it!

Proposed change:
~~~sh
 |  /           |                  
 ' /   __| _` | __|  _ \   __|    
 . \  |   (   | |   (   |\__ \  
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 9.4."3"-core/improve-f91598bfeb-Release-x86_64
           Compiled for GNU/Linux and Python3.10 with GCC-11.4
Compiled with threading and MPI support.
Maximum number of threads: 16.
Running without MPI.
Matrix reading execution time:  65.3339204788208  seconds
Matrix multiplication execution time:  4.3560473918914795  seconds
 *  Las tareas reutilizarán el terminal, presione cualquier tecla para cerrarlo. 
 ~~~

Current one:
~~~sh
  |  /           |                  
 ' /   __| _` | __|  _ \   __|    
 . \  |   (   | |   (   |\__ \  
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 9.4."3"-master-4c902f1c49-Release-x86_64
           Compiled for GNU/Linux and Python3.10 with GCC-11.4
Compiled with threading and MPI support.
Maximum number of threads: 16.
Running without MPI.
Matrix reading execution time:  66.79455351829529  seconds
Matrix multiplication execution time:  15.352271556854248  seconds
 *  Las tareas reutilizarán el terminal, presione cualquier tecla para cerrarlo. 
~~~

**Comment by loumalouomega** [comment]
> > > Here's a [link](https://gigamove.rwth-aachen.de/en/download/83f1a71d7e37f64f7b8442bf343c576a) to two matrices whose product highlights the issue
> > > left 	right
> > > left operand 	right operand
> > > and an example program to read the files and carry out the matrix product:
> > > ```c++
> > > // --- Core Includes ---
> > > #include "spaces/ublas_space.h"
> > > #include "utilities/sparse_matrix_multiplication_utility.h"
> > > 
> > > // --- STL Includes ---
> > > #include <filesystem>
> > > #include <sstream>
> > > #include <chrono>
> > > #include <ctime>
> > > 
> > > 
> > > namespace Kratos {
> > > 
> > > 
> > > using Space = TUblasSparseSpace<double>;
> > > 
> > > 
> > > void read(const std::filesystem::path& rPath,
> > >           Space::MatrixType& rTargetMatrix)
> > > {
> > >     std::ifstream file(rPath);
> > >     std::string line;
> > > 
> > >     // Expect exactly 1 comment line ==> ignore it
> > >     std::getline(file, line);
> > > 
> > >     // Expect size line ==> parse it
> > >     std::size_t row_count=0ul, column_count=0ul, nonzero_count=0ul;
> > >     std::getline(file, line);
> > >     {
> > >         std::istringstream stream(line);
> > >         if (!(stream >> row_count >> column_count >> nonzero_count)) throw 1;
> > >     }
> > > 
> > >     rTargetMatrix.resize(row_count, column_count, /*preserve=*/false);
> > > 
> > >     while (std::getline(file, line)) {
> > >         // Ignore empty lines
> > >         if (line.empty()) continue;
> > > 
> > >         std::istringstream stream(line);
> > >         std::size_t i_row = 0ul, i_column = 0ul;
> > >         double value;
> > >         if (!(stream >> i_row >> i_column >> value)) throw 1;
> > > 
> > >         // Matrix market works with 1-based indices
> > >         --i_row;
> > >         --i_column;
> > > 
> > >         rTargetMatrix.insert_element(i_row, i_column, value);
> > >     }
> > > 
> > >     rTargetMatrix.complete_index1_data();
> > > }
> > > 
> > > 
> > > int main()
> > > {
> > >     Space::MatrixType left, right;
> > > 
> > >     try {read("left.mm", left);} catch (...) {return 1;}
> > >     try {read("right.mm", right);} catch (...) {return 2;}
> > > 
> > >     Space::MatrixType result;
> > > 
> > >     std::cout << "Begin matrix product\n";
> > >     const auto begin = std::chrono::system_clock::now();
> > >     SparseMatrixMultiplicationUtility::MatrixMultiplication(left, right, result);
> > >     KRATOS_INFO("Matrix product duration")
> > >         << std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now() - begin).count() << " ms"
> > >         << (result.nnz() == 0 ? " " : "\n"); // <== dummy line to use the result
> > > 
> > >     return 0;
> > > }
> > > 
> > > 
> > > } // namespace Kratos
> > > 
> > > 
> > > int main(int argc, const char** const argv)
> > > {
> > >     return Kratos::main();
> > > }
> > > ```
> > 
> > 
> > To avoid compile a binary you can use python directly:
> > ```python
> > import KratosMultiphysics
> > 
> > import os
> > import time
> > 
> > def GetFilePath(fileName):
> >     return os.path.join(os.path.dirname(os.path.realpath(__file__)), fileName)
> > 
> > if __name__ == '__main__':
> >     space = KratosMultiphysics.UblasSparseSpace()
> > 
> >     #read the matrices
> >     A = KratosMultiphysics.CompressedMatrix()
> >     file_read = KratosMultiphysics.ReadMatrixMarketMatrix(GetFilePath("left"),A)
> > 
> >     B = KratosMultiphysics.CompressedMatrix()
> >     file_read = KratosMultiphysics.ReadMatrixMarketMatrix(GetFilePath("right"),B)
> > 
> >     # Multiply matrices
> >     AB = KratosMultiphysics.CompressedMatrix()
> > 
> >     start_time = time.time()
> >     KratosMultiphysics.SparseMatrixMultiplicationUtility.MatrixMultiplication(A, B, AB)
> >     end_time = time.time()
> > 
> >     execution_time = end_time - start_time
> >     print("Matrix multiplication execution time: ", execution_time, " seconds")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am on it!
> 
> Proposed change:
> 
> ```shell
>  |  /           |                  
>  ' /   __| _` | __|  _ \   __|    
>  . \  |   (   | |   (   |\__ \  
> _|\_\_|  \__,_|\__|\___/ ____/
>            Multi-Physics 9.4."3"-core/improve-f91598bfeb-Release-x86_64
>            Compiled for GNU/Linux and Python3.10 with GCC-11.4
> Compiled with threading and MPI support.
> Maximum number of threads: 16.
> Running without MPI.
> Matrix reading execution time:  65.3339204788208  seconds
> Matrix multiplication execution time:  4.3560473918914795  seconds
>  *  Las tareas reutilizarán el terminal, presione cualquier tecla para cerrarlo. 
> ```
> 
> Current one:
> 
> ```shell
>   |  /           |                  
>  ' /   __| _` | __|  _ \   __|    
>  . \  |   (   | |   (   |\__ \  
> _|\_\_|  \__,_|\__|\___/ ____/
>            Multi-Physics 9.4."3"-master-4c902f1c49-Release-x86_64
>            Compiled for GNU/Linux and Python3.10 with GCC-11.4
> Compiled with threading and MPI support.
> Maximum number of threads: 16.
> Running without MPI.
> Matrix reading execution time:  66.79455351829529  seconds
> Matrix multiplication execution time:  15.352271556854248  seconds
>  *  Las tareas reutilizarán el terminal, presione cualquier tecla para cerrarlo. 
> ```

Is more than 3x faster!

I will try to improve with you comments anyway.

**Comment by loumalouomega** [comment]
@matekelemen looks like segmentation fault

**Comment by loumalouomega** [comment]
IMO opinion we should merge this as it is already a great improvement, and then point #12153 to master once is fixed the memory error (I have tried to fix it but no idea why it fails).

**Comment by matekelemen** [comment]
I agree that it's an improvement, but let me check what the problem is. I don't change this thing twice (though ideally we should change the parallelization as well at some point).

**Comment by loumalouomega** [comment]
@matekelemen if you agree we can proceed with this

File: kratos/utilities/sparse_matrix_multiplication_utility.h [hunk 2]
```diff
@@ -68,26 +65,26 @@ class SparseMatrixMultiplicationUtility
...
-    typedef DenseVector<SignedIndexType> SignedIndexVectorType;
+    using SignedIndexVectorType = DenseVector<SignedIndexType>;
 
     ///@}
     ///@name Life Cycle
     ///@{
 
     /// Default constructor
-    SparseMatrixMultiplicationUtility(){};
+    SparseMatrixMultiplicationUtility() = default;
```
Comment (matekelemen) [inline kratos/utilities/sparse_matrix_multiplication_utility.h]: very minor nitpicking: do we ever actually instantiate this class? If not, why not make it unambiguous and explicitly delete all constructors and destructors?

File: kratos/utilities/sparse_matrix_multiplication_utility.h [hunk 3]
```diff
@@ -103,7 +100,7 @@ class SparseMatrixMultiplicationUtility
     /// Metafunction that returns value type of a matrix or a vector type.
     template <class T, class Enable = void>
     struct value_type {
-        typedef typename T::value_type type;
+        using type = typename T::value_type;
     };
```
Comment (matekelemen) [inline kratos/utilities/sparse_matrix_multiplication_utility.h]: I don't get what this nested `value_type` does that `typename T::value_type` cannot. Is it possible that this is just some leftover that's no longer necessary? Can you please try replacing it?

File: kratos/utilities/sparse_matrix_multiplication_utility.h [hunk 4]
```diff
@@ -147,9 +144,9 @@ class SparseMatrixMultiplicationUtility
         CMatrix& C
         )
     {
-        typedef typename value_type<CMatrix>::type ValueType;
+        using ValueType = typename value_type<CMatrix>::type;
```
Comment (matekelemen) [inline kratos/utilities/sparse_matrix_multiplication_utility.h]: > Can you please try replacing it?

for example here:

```suggestion
        using ValueType = typename CMatrix::type;
```

File: kratos/utilities/sparse_matrix_multiplication_utility.h [hunk 5]
```diff
@@ -168,78 +165,74 @@ class SparseMatrixMultiplicationUtility
...
-            for (int i_fill = 0; i_fill < static_cast<int>(ncols); ++i_fill)
-                marker[i_fill] = -1;
+        // Definition of marker TLS
+        struct TLS {
+            TLS(const SizeType NumberOfColumns)
+                : marker(NumberOfColumns)
+            {
+                for (IndexType i_fill = 0; i_fill < NumberOfColumns; ++i_fill) {
+                    marker[i_fill] = -1;
+                }
```
Comment (matekelemen) [inline kratos/utilities/sparse_matrix_multiplication_utility.h]:
```suggestion
                std::fill(marker.begin(), marker.end(), -1);
```

File: kratos/utilities/sparse_matrix_multiplication_utility.h [hunk 6]
```diff
@@ -287,6 +280,7 @@ class SparseMatrixMultiplicationUtility
 
         IndexType max_row_width = 0;
 
+        // TODO: Replace with block_for_each. Difficult due to critical section
```
Comment (matekelemen) [inline kratos/utilities/sparse_matrix_multiplication_utility.h]: you can use [`MaxReduction`](https://github.com/KratosMultiphysics/Kratos/blob/3aacd9741d3ec20c68a5700d43ebdda0be2ad20e/kratos/utilities/reduction_utilities.h#L126-L152) with an [overload of `IndexPartition::for_each`](https://github.com/KratosMultiphysics/Kratos/blob/3aacd9741d3ec20c68a5700d43ebdda0be2ad20e/kratos/utilities/parallel_utilities.h#L194-L214) that takes a reduction.

File: kratos/utilities/sparse_matrix_multiplication_utility.h [hunk 7]
```diff
@@ -326,6 +320,7 @@ class SparseMatrixMultiplicationUtility
         IndexType* c_ptr = new IndexType[nrows + 1];
         c_ptr[0] = 0;
 
+        // TODO: Replace with block_for_each
```
Comment (matekelemen) [inline kratos/utilities/sparse_matrix_multiplication_utility.h]: a while ago, I mentioned prolonging the lifetime of TLS so that the main thread can access the results and do some fancy complex reduction on them. That would be perfect here.

**Review by matekelemen — COMMENTED** [review]
> @matekelemen if you agree we can proceed with this

fine by me, but I believe we need a proper review from the @KratosMultiphysics/technical-committee for this one.

File: kratos/utilities/sparse_matrix_multiplication_utility.h (hunk 4 above)
Comment (loumalouomega) [reply kratos/utilities/sparse_matrix_multiplication_utility.h]: Okay

File: kratos/utilities/sparse_matrix_multiplication_utility.h (hunk 5 above)
Comment (loumalouomega) [reply kratos/utilities/sparse_matrix_multiplication_utility.h:175]: Does this work in paralllel?

File: kratos/utilities/sparse_matrix_multiplication_utility.h (hunk 6 above)
Comment (loumalouomega) [reply kratos/utilities/sparse_matrix_multiplication_utility.h]: LEts see

**Comment by loumalouomega** [comment]
@matekelemen should be Okay now

**Comment by loumalouomega** [comment]
Okay, I fixed it

**Comment by loumalouomega** [comment]
> Okay, I fixed it

This is an improvement, can anyone at @KratosMultiphysics/technical-committee  approve?

**Comment by loumalouomega** [comment]
> > Okay, I fixed it
> 
> This is an improvement, can anyone at @KratosMultiphysics/technical-committee approve?

@RiccardoRossi

File: kratos/utilities/sparse_matrix_multiplication_utility.h [hunk 8]
```diff
@@ -120,11 +118,10 @@ class SparseMatrixMultiplicationUtility
         CMatrix& rC
         )
     {
-    #ifdef _OPENMP
-        const int nt = omp_get_max_threads();
-    #else
-        const int nt = 1;
-    #endif
+        int nt = 1;
+        if constexpr(UsesOpenMP) {
```
Comment (RiccardoRossi) [inline kratos/utilities/sparse_matrix_multiplication_utility.h]: there is a function in the parallel_utils doing exactly this. The bad thing of your approach is that nt is not constant

Comment (RiccardoRossi) [reply kratos/utilities/sparse_matrix_multiplication_utility.h]: https://github.com/KratosMultiphysics/Kratos/blob/a988fb6b70451e6d55604212a3098223dc947065/kratos/utilities/parallel_utilities.cpp#L34

File: kratos/utilities/sparse_matrix_multiplication_utility.h [hunk 9]
```diff
@@ -285,92 +276,75 @@ class SparseMatrixMultiplicationUtility
...
+                row_width += index1_b[a_col + 1] - index1_b[a_col];
             }
+            rTLS.my_max = std::max(rTLS.my_max, row_width);
+            return rTLS.my_max;
+        });
 
-            #pragma omp critical
-            max_row_width = std::max(max_row_width, my_max);
+        int nthreads = 1;
+        if constexpr(UsesOpenMP) {
```
Comment (RiccardoRossi) [inline kratos/utilities/sparse_matrix_multiplication_utility.h]: https://github.com/KratosMultiphysics/Kratos/blob/a988fb6b70451e6d55604212a3098223dc947065/kratos/utilities/parallel_utilities.cpp#L34

File: kratos/utilities/sparse_matrix_multiplication_utility.h [hunk 10]
```diff
@@ -285,92 +276,75 @@ class SparseMatrixMultiplicationUtility
...
-            const int tid = omp_get_thread_num();
-        #else
-            const int tid = 0;
-        #endif
+        IndexPartition<IndexType>(nrows).for_each([&](IndexType i) {
+            const IndexType row_beg = index1_a[i];
+            const IndexType row_end = index1_a[i+1];
 
+            int tid = 0;
+            if constexpr(UsesOpenMP) {
```
Comment (RiccardoRossi) [inline kratos/utilities/sparse_matrix_multiplication_utility.h]: this is a "forbidden function", is there any way to avoid using this?

File: kratos/utilities/sparse_matrix_multiplication_utility.h [hunk 11]
```diff
@@ -285,92 +276,75 @@ class SparseMatrixMultiplicationUtility
...
-            const int tid = omp_get_thread_num();
-        #else
-            const int tid = 0;
-        #endif
+        IndexPartition<IndexType>(nrows).for_each([&](IndexType i) {
+            const IndexType row_beg = index1_a[i];
+            const IndexType row_end = index1_a[i+1];
+
+            int tid = 0;
+            if constexpr(UsesOpenMP) {
```
Comment (RiccardoRossi) [inline kratos/utilities/sparse_matrix_multiplication_utility.h]: same

File: kratos/utilities/sparse_matrix_multiplication_utility.h (hunk 1 above)
Comment (RiccardoRossi) [reply kratos/utilities/sparse_matrix_multiplication_utility.h:621]: mate's comment is relevant ... you decided not to?

> Openend and discussed here: https://github.com/KratosMultiphysics/Kratos/pull/12153

File: kratos/utilities/sparse_matrix_multiplication_utility.h (hunk 8 above)
Comment (loumalouomega) [reply kratos/utilities/sparse_matrix_multiplication_utility.h]: Okay

File: kratos/utilities/sparse_matrix_multiplication_utility.h (hunk 11 above)
Comment (loumalouomega) [reply kratos/utilities/sparse_matrix_multiplication_utility.h]: It is already used in the current code, just refactoring

File: kratos/utilities/sparse_matrix_multiplication_utility.h (hunk 10 above)
Comment (loumalouomega) [reply kratos/utilities/sparse_matrix_multiplication_utility.h]: This function was already used, this is just a refactor

File: kratos/utilities/sparse_matrix_multiplication_utility.h (hunk 1 above)
Comment (RiccardoRossi) [reply kratos/utilities/sparse_matrix_multiplication_utility.h:621]: this code, taken from:
https://codereview.stackexchange.com/questions/231352/c17-zip-iterator-compatible-with-stdsort

would most probably do what you need without copies. Having said this, admittedly i am not sure wheter it is faster or not, but i would expect that allocation of a lot of pairs is not for free. 
(the main is at the end of the post ... everything at the beginning are the helper functions)

~~~cpp
#include <cstdint>
#include <algorithm>
#include <functional>
#include <tuple>
#include <utility>

template <typename ...T>
class ZipRef {
    std::tuple<T*...> ptr;
public:
    ZipRef() = delete;
    ZipRef(const ZipRef& z) = default;
    ZipRef(ZipRef&& z) = default;
    ZipRef(T* const... p): ptr(p...) {}

    ZipRef& operator=(const ZipRef& z)             { return copy_assign(z); }
    ZipRef& operator=(const std::tuple<T...>& val) { return val_assign(val); }

    template <std::size_t I = 0>
    ZipRef& copy_assign(const ZipRef& z) {
        *(std::get<I>(ptr)) = *(std::get<I>(z.ptr));
        if constexpr(I+1 < sizeof...(T)) return copy_assign<I+1>(z);
        return *this;
    }
    template <std::size_t I = 0>
    ZipRef& val_assign(const std::tuple<T...>& t) {
        *(std::get<I>(ptr)) = std::get<I>(t);
        if constexpr(I+1 < sizeof...(T)) return val_assign<I+1>(t);
        return *this;
    }

    std::tuple<T...> val() const {return std::apply([](auto&&...args) { return std::tuple((*args)...); }, ptr);}
    operator std::tuple<T...>() const { return val(); }

    void swap(const ZipRef& o) const {
        swap_impl<sizeof...(T)-1>(o);
    }

private:
    template <std::size_t I>
    void swap_impl(const ZipRef& o) const {
        using std::swap;
        swap(*std::get<I>(ptr), *std::get<I>(o.ptr));
        if constexpr(I) swap_impl<I-1>(o);
    }

public:
#define OPERATOR(OP)                                                    \
    bool operator OP(const ZipRef & o) const { return val() OP o.val(); } \
    inline friend bool operator OP(const ZipRef& r, const std::tuple<T...>& t) { return r.val() OP t; } \
    inline friend bool operator OP(const std::tuple<T...>& t, const ZipRef& r) { return t OP r.val(); }

    OPERATOR(==) OPERATOR(<=) OPERATOR(>=)
    OPERATOR(!=) OPERATOR(<)  OPERATOR(>)
#undef OPERATOR

};

template<typename ...IT>
class ZipIter {
    std::tuple<IT...> it;

    template<int N, typename... T> using NthTypeOf =
        typename std::tuple_element<N, std::tuple<T...>>::type;
    template<typename... T> using FirstTypeOf = NthTypeOf<0, T...>;

public:
    using iterator_category = typename std::iterator_traits<FirstTypeOf<IT...>>::iterator_category;
    using difference_type   = typename std::iterator_traits<FirstTypeOf<IT...>>::difference_type;
    using value_type        = std::tuple<typename std::iterator_traits<IT>::value_type ...>;
    using pointer           = std::tuple<typename std::iterator_traits<IT>::pointer ...>;
    using reference         = ZipRef<typename std::iterator_traits<IT>::value_type ...>;

    ZipIter() = default;
    ZipIter(const ZipIter &rhs) = default;
    ZipIter(ZipIter&& rhs) = default;
    ZipIter(IT... rhs): it(std::move(rhs)...) {}

    ZipIter& operator=(const ZipIter& rhs) = default;
    ZipIter& operator=(ZipIter&& rhs) = default;

    ZipIter& operator+=(const difference_type d) {
        std::apply([&d](auto&&...args) {((std::advance(args,d)),...);}, it); return *this;
    }
    ZipIter& operator-=(const difference_type d) { return operator+=(-d); }

    reference operator* () const {return std::apply([](auto&&...args) {return reference(&(*(args))...);}, it);}
    pointer   operator->() const {return std::apply([](auto&&...args) {return pointer(&(*(args))...);}, it);}
    reference operator[](difference_type rhs) const {return *(operator+(rhs));}

    ZipIter& operator++() { return operator+=(1); }
    ZipIter& operator--() { return operator+=(-1); }
    ZipIter operator++(int) {ZipIter tmp(*this); operator++(); return tmp;}
    ZipIter operator--(int) {ZipIter tmp(*this); operator--(); return tmp;}

    difference_type operator-(const ZipIter& rhs) const {return std::get<0>(it)-std::get<0>(rhs.it);}
    ZipIter operator+(const difference_type d) const {ZipIter tmp(*this); tmp += d; return tmp;}
    ZipIter operator-(const difference_type d) const {ZipIter tmp(*this); tmp -= d; return tmp;}
    inline friend ZipIter operator+(const difference_type d, const ZipIter& z) {return z+d;}
    inline friend ZipIter operator-(const difference_type d, const ZipIter& z) {return z-d;}

#define OPERATOR(OP)                                                    \
    bool operator OP(const ZipIter& rhs) const {return it OP rhs.it;}
    OPERATOR(==) OPERATOR(<=) OPERATOR(>=)
    OPERATOR(!=) OPERATOR(<)  OPERATOR(>)
#undef OPERATOR
};

template<typename ...Container>
class Zip {
    std::tuple<Container&...> zip;

public:
    Zip() = delete;
    Zip(const Zip& z) = default;
    Zip(Zip&& z) = default;
    Zip(Container&... z)
        : zip {z...}
    {
        auto const len = {(z.size())...,};
        // if (std::adjacent_find(len.begin(), len.end(), std::not_equal_to()) != len.end())
        //     throw std::error("array lengths differ");
    }

#define HELPER(OP)                                                      \
    auto OP() {return std::apply([](auto&&... args) { return ZipIter((args.OP())...);}, zip);}
    HELPER(begin) HELPER(end)
    HELPER(rbegin) HELPER(rend)
#undef HELPER

#define HELPER(OP)                                                      \
    auto OP() const {return std::apply([](auto&&... args) { return ZipIter((args.OP())...);}, zip);}
    HELPER(begin) HELPER(end)
    HELPER(rbegin) HELPER(rend)
    HELPER(cbegin) HELPER(cend)
    HELPER(crbegin) HELPER(crend)
#undef HELPER
};

#include <utility>
using std::swap;
template<typename ...T> void swap(const ZipRef<T...>& a, const ZipRef<T...>& b) { a.swap(b); }

#include <sstream>
template< class Ch, class Tr, class...IT, typename std::enable_if<(sizeof...(IT)>0), int>::type = 0>
auto& operator<<(std::basic_ostream<Ch, Tr>& os, const ZipRef<IT...>& t) {
    std::basic_stringstream<Ch, Tr> ss;
    ss << "[ ";
    std::apply([&ss](auto&&... args) {((ss << args << ", "), ...);}, t.val());
    ss.seekp(-2, ss.cur);
    ss << " ]";
    return os << ss.str();
}


#include <vector>
#include <string>
#include <algorithm>
#include <iostream>

int main() {
    std::vector<int> a {3,1,4,2};
    //std::vector<std::string> b {"Alice","Bob","Charles","David"};
    std::vector<double> b {3000,1000,4000,2000};

    auto const zip = Zip(a,b);

    for (const auto & z: zip) std::cout << z << std::endl;

    std::cout << std::endl;
    std::sort(zip.begin(), zip.end());
    for (const auto & z: zip) std::cout << z << std::endl;
}
~~~

alternatively also boost has a zip_iterator which probably would allow us doing the same

Comment (loumalouomega) [reply kratos/utilities/sparse_matrix_multiplication_utility.h:621]: Can we move this disccussion to the othe PR?, @matekelemen deciced to merge the current PR as it is and fix the issue in the other one. But it is not trivial because memory is not threated consistently in the STL library as @matekelemen discovered.

Comment (matekelemen) [reply kratos/utilities/sparse_matrix_multiplication_utility.h:621]: @RiccardoRossi I tried an implementation with a custom iterator that sorts the two arrays in-place #12153 , but it adds a lot of code and I didn't measure an increase in performance on my machine for this test case.

@loumalouomega there's nothing wrong with the STL's memory management, but std::sort is more complex than I initially thought, so I had to extend the iterator a bit.

**Comment by loumalouomega** [comment]
@RiccardoRossi It would be interesting to merge this as already it is s an important speed up in relation with current solution. We can test new alternatives in future PR.

**Review by RiccardoRossi — APPROVED** [review]
ok, 
      i do not see anything wrong with the proposed implementation so if you tell it is faster i'll accept it. Still @matekelemen  i am surprised that the pair version can be faster than the one in place

**Comment by RiccardoRossi** [comment]
still i would propose to open an issue to keep track of the possibility to use inplace sorting

(and also let me pig for information @ddemidov since this comment about sorting may also ber relevant to him)
