### PR TITLE
[Core] Fix failing test with empty partitions MPI discontinuous distance

### LINKED ISSUE #8859: [Core, MPI] testDiscontinuousDistanceProcess fails with 8 cores.
testDiscontinuousDistanceProcessCutOnEdge2D and testDiscontinuousDistanceProcessCutThroughNode2D  from test_mpi_processes are failing when running with 8 cores (segmentation fault). It is not shown in ci as we only use 4,3 and 2 cores.

GDB seems to complain about this line.
https://github.com/KratosMultiphysics/Kratos/blob/efb3ea461e6119ca1427a6b3ba98a1711e98fd2b/kratos/processes/find_intersected_geometrical_objects_process.cpp#L284

I guess the problem is that some partitions might be empty so when trying to access NodesBegin you get the segmentation fault. This is what I found so far @uksajja 

Just pinging some people that might be related to this problem. @loumalouomega @marcnunezc @rubenzorrilla

### PR DESCRIPTION
**Pull request by marcnunezc**
**Description**
Closes #8859. 

Skips the generation of the octree if there are no nodes in the partition.   Maybe the check should be placed elsewhere.

~~Also took the chance to remove a duplicated Initialize call, keeping the "ExecuteInitialize()" version.~~ done in #8864 

Also, with empty partitions the characteristic length computation was giving a Inf value, so a synchronisation is added. This was previously computing a different characteristic length at every partition. Was this intended @rubenzorrilla ?

**Changelog**
Please summarize the changes in one list to generate the changelog:
E.g.
- Skip initialize in find intersected objects with no nodes in the mesh
- ~~Removed duplicated Initialize() call.~~
- Added mpi synchronisation in the characteristic length domain computation.

### CODE REVIEW

**Comment by ddiezrod** [comment]
Tests are passing now fine on my machine. Thanks very much @marcnunezc for the quick fix!, I leave the approval for @rubenzorrilla

File: kratos/processes/find_intersected_geometrical_objects_process.h [hunk 1]
```diff
@@ -401,12 +401,6 @@ class KRATOS_API(KRATOS_CORE) FindIntersectedGeometricalObjectsProcess
     ///@name Operations
     ///@{
 
-    /**
-     * @brief This function is designed for being called at the beginning of the computations right after reading the model and the groups
-     * @todo This should be moved to ExecuteInitialize (base class of Process)
-     */
-    virtual void Initialize();
-
```
Comment (rubenzorrilla) [inline kratos/processes/find_intersected_geometrical_objects_process.h]: I'd leave this API breaker change for a standalone PR. Note that you're silently breaking the compatibility with everything not covered by the CI.

File: kratos/processes/find_intersected_geometrical_objects_process.cpp [hunk 2]
```diff
@@ -212,7 +204,9 @@ void FindIntersectedGeometricalObjectsProcess::Execute()
 
 void FindIntersectedGeometricalObjectsProcess::ExecuteInitialize()
 {
-    GenerateOctree();
+    if (mrModelPartIntersected.NumberOfNodes() > 0) {
```
Comment (rubenzorrilla) [inline kratos/processes/find_intersected_geometrical_objects_process.cpp:217]: Although so far we assume that we have the complete skin model part in each node, I'd check the global number of nodes in here.

File: kratos/processes/apply_ray_casting_process.cpp [hunk 3]
```diff
@@ -65,7 +65,7 @@ namespace Kratos
 	void ApplyRayCastingProcess<TDim>::Execute()
 	{
         if(mIsSearchStructureAllocated) // we have not initialized it yet
-            mpFindIntersectedObjectsProcess->Initialize();
+            mpFindIntersectedObjectsProcess->ExecuteInitialize();
```
Comment (rubenzorrilla) [inline kratos/processes/apply_ray_casting_process.cpp]: `Initialize` and `ExecuteInitialize` have exactly the same behavior right?

File: kratos/processes/find_intersected_geometrical_objects_process.h (hunk 1 above)
Comment (rubenzorrilla) [reply kratos/processes/find_intersected_geometrical_objects_process.h]: Indeed, I'd first deprecate the method (both in compilation and usage) for a while to then remove it.

**Review by rubenzorrilla — COMMENTED** [review]
Comments on the `Initialize` removal. Aside of these, MPI fixes are OK to me.

File: kratos/processes/find_intersected_geometrical_objects_process.cpp (hunk 2 above)
Comment (marcnunezc) [reply kratos/processes/find_intersected_geometrical_objects_process.cpp:217]: You mean checking if GlobalNumberOfNodes > 0?. 

Note that his would make every partition (even the empty partitions) enter in GenerateOctree() which would lead to the error reported initially

Sorry if I misunderstood you

File: kratos/processes/apply_ray_casting_process.cpp (hunk 3 above)
Comment (marcnunezc) [reply kratos/processes/apply_ray_casting_process.cpp]: Yes

File: kratos/processes/find_intersected_geometrical_objects_process.h (hunk 1 above)
Comment (marcnunezc) [reply kratos/processes/find_intersected_geometrical_objects_process.h]: Ok, will do. I will revert these changes here so the fix can go fast and keep the Initialize changes in another PR.

File: kratos/processes/find_intersected_geometrical_objects_process.cpp (hunk 2 above)
Comment (rubenzorrilla) [reply kratos/processes/find_intersected_geometrical_objects_process.cpp:217]: My bad, I thought you were checking the skin model part nodes. This is OK. Forget about my comment.

**Review by rubenzorrilla — APPROVED** [review]
