### PR TITLE
Mpi/communicator update

### LINKED ISSUE #4358: Possible bugs in MPICommunicator
I ran a static analysis while looking at #1277. It flagged some suspicious lines which might be bugs. I didn't want to comment in #1277 since these lines are not part of the PR.

https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/mpi/includes/mpi_communicator.h#L352
https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/mpi/includes/mpi_communicator.h#L367
> Casting from double* to integer* is not portable due to different binary data representations on different platforms.

https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/mpi/includes/mpi_communicator.h#L196
https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/mpi/includes/mpi_communicator.h#L223
> Member variable 'MPICommunicator::mpVariables_list' is not initialized in the constructor

Can you take a look?

### LINKED ISSUE #4453: MPI Synchronization of dynamic Matrix and Vector type variables?
I am currently writing tests in preparation to update the MPICommunicator for the MPI Core. I have encountered an issue where trying to Assemble a `Variable<Vector>` produces a segfault and I was wondering if anyone has experience with it.

In any case, is Assembly of dynamic vectors and matrices something that is well defined? Should it even be supported? Right now we are not even checking that the vectors have the same sizes on the different ranks before communicating...

@KratosMultiphysics/technical-committee

### PR DESCRIPTION
**Pull request by jcotela**
Major refactoring of MPI Communicator. The original idea was to give an internal `DataCommunicator` to the Communicator class and use it instead of the hardcoded `MPI_COMM_WORLD` calls in order to support different communicators in the future.

Since the class contained an unacceptable amount of duplicated code, I undertook a major refactoring. There are now essentially only two communication functions, a synchronous one (`TransferDistributedValues`) and the existing asynchronous one (with only minor modifications, since it was already cleanly templated and the DataCommunicator does not support asynchronous communication at the moment anyway).

For the synchronous case, the specifics of the access to the different nodal or elemental databases is based on templating, while the selection of the data reduction operation (replace existing values, assemble, bitwise and/or of existing and received data) and the direction of communication (local to ghost or ghost to local) are both dispatched at compile time using an `Int2Type` trick (see A. Alexandrescu, Modern C++ Design).

This PR requires #4743 and #4744. It closes #4453 and closes #4358.

~It also opens a way for an alternative solution to #4571, but I did not implement it on this already quite big PR because it requires some extra changes in `DataCommunicator`.~

Bool communication was added to the PR in the end.

### CODE REVIEW

File: kratos/includes/communicator.h [hunk 1]
```diff
@@ -193,59 +211,51 @@ class Communicator
...
         , mInterfaceMeshes(rOther.mInterfaceMeshes)
+        , mrDataCommunicator(rOther.mrDataCommunicator)
     {
     }
 
-    virtual Communicator::Pointer Create()
+    virtual Communicator::Pointer Create(const DataCommunicator& rDataCommunicator) const
     {
-        KRATOS_TRY
+        KRATOS_TRY;
```
Comment (pooyan-dadvand) [inline kratos/includes/communicator.h]: Does not cause a warning?

File: kratos/includes/communicator.h [hunk 2]
```diff
@@ -193,59 +211,51 @@ class Communicator
...
-        mpInterfaceMesh = rOther.mpInterfaceMesh;
-        mLocalMeshes = rOther.mLocalMeshes;
-        mGhostMeshes = rOther.mGhostMeshes;
-        mInterfaceMeshes = rOther.mInterfaceMeshes;
-
-        return *this;
-    }
-
-
+    Communicator & operator=(Communicator const& rOther) = delete;
```
Comment (pooyan-dadvand) [inline kratos/includes/communicator.h:240]: Not a bad idea, but does it work everywhere? Good that we don't have any copy!

File: kratos/mpi/includes/mpi_communicator.h [hunk 3]
```diff
@@ -74,673 +67,978 @@ namespace Kratos
...
-    typedef MeshType::ElementConstantIterator ElementConstantIterator;
+template<class TValue> struct SendTools;
 
-    /// Condintions container. A vector set of Conditions with their Id's as key.
-    typedef MeshType::ConditionsContainerType ConditionsContainerType;
+template<> struct SendTools<int>
+{
+    typedef int SendType;
+    constexpr static bool IsFixedSize = true;
+    constexpr static std::size_t MessageSize = 1;
```
Comment (pooyan-dadvand) [inline kratos/mpi/includes/mpi_communicator.h]: What is the block size? A comment would be appreciated. Or another constexpr.

File: kratos/mpi/includes/mpi_communicator.h [hunk 4]
```diff
@@ -74,673 +67,978 @@ namespace Kratos
...
+}
+
+/// MPICommunicator manages the transfer of ModelPart data in MPI distributed memory environment.
+class MPICommunicator : public Communicator
+{
+
+enum class DistributedType {
+    Local,
+    Ghost
+};
```
Comment (pooyan-dadvand) [inline kratos/mpi/includes/mpi_communicator.h:543]: and Interface?

**Review by pooyan-dadvand — COMMENTED** [review]
Great improvement respect to the previous version! Meanwhile some comments:

* There are many variants of SendTo which are direct copy and other group which are memberwise. I would specialized for these two types (please check the serializer for this) and then I would put the typedef traits in a separate class to reduce the amount of duplicated code.

* The accessors can be simplified if we add a `template<TEntityType> GetEntitities()` to model part

* Why the SyncronizeVariable methods are always returning true? They shouldn't return the result state of the transfer?

File: kratos/includes/communicator.h (hunk 2 above)
Comment (jcotela) [reply kratos/includes/communicator.h:240]: What do you mean everywhere?

File: kratos/mpi/includes/mpi_communicator.h (hunk 4 above)
Comment (jcotela) [reply kratos/mpi/includes/mpi_communicator.h:543]: I did not add it because there is no function using the entire interface currently, so I had no test for it.

**Comment by jcotela** [comment]
One thing I forgot to add: `SynchronizeNodalSolutionStepsData` fails both in the existing implementation and in the one proposed in this PR if the variables list contains dynamic size variables (Vector, Matrix,...). I believe the correct way to synchronize in that case is to use serialization, but I did not implement it since I guess it would have some overhead over the current approach (and I would say it is quite rare to add this kind of variable size Variables to SolutionStepData in practice). What should we do in that case? Should I open a separate issue for that?

File: kratos/mpi/includes/mpi_communicator.h (hunk 3 above)
Comment (jcotela) [reply kratos/mpi/includes/mpi_communicator.h]: I believe it is the `MessageSize`? It is intended to be the size of a single send, measured in `SendType` (formally, `sizeof(ValueType)/sizeof(SendType)`). If so, I can just rename it to be clearer, since I do not particularly like the current name anyway....

**Comment by jcotela** [comment]
I tried to reduce the duplicated code in the SendTools (defining proper SendTraits) and in the nodal/elemental access (by introducing a common base class with the Mesh access methods).

Regarding the return value, it was already working like that. We could probably just remove it, since we usually raise an Exception if the function throws an error.

File: kratos/includes/communicator.h (hunk 2 above)
Comment (pooyan-dadvand) [reply kratos/includes/communicator.h:240]: Means that we never have assigned a Communicator in our applications?

**Comment by pooyan-dadvand** [comment]
> One thing I forgot to add: `SynchronizeNodalSolutionStepsData` fails both in the existing implementation and in the one proposed in this PR if the variables list contains dynamic size variables (Vector, Matrix,...). I believe the correct way to synchronize in that case is to use serialization, but I did not implement it since I guess it would have some overhead over the current approach (and I would say it is quite rare to add this kind of variable size Variables to SolutionStepData in practice). What should we do in that case? Should I open a separate issue for that?

I would use serializer for that case and if you see it more appropriate in another PR I won't object

File: kratos/includes/communicator.h (hunk 2 above)
Comment (jcotela) [reply kratos/includes/communicator.h:240]: I would say no. We normally use the SetCommunicator method of the ModelPart, which takes a pointer, so the Communicator object is never directly held.

**Comment by jcotela** [comment]
I will look into using the serializer for SolutionStepData synchonization. There is partial support for it thanks to @RiccardoRossi. If I can make it work with what is already there I will include it in this PR, otherwise I will postpone it to a separate PR with the appropriate changes in DataCommunicator.

**Comment by jcotela** [comment]
Update: SolutionStepData synchronization based on the serializer seems to work well with what is already there, also for dynamic-size types.

**Comment by jcotela** [comment]
One last question: some of the methods in Communicator are not directly related to the ModelPart or the coloring and only execute standard MPI calls (see `SumAll`, `MinAll` or `Barrier` in `communicator.h`). Since this is now the task of the `DataCommunicator`, we were discussing with @philbucher that they could possibly be deprecated to reduce duplicate code. The equivalent call `my_communicator.GetDataCommunicator().Barrier()` (or whatever) can be used instead.

Does this make sense? If so, I would add the deprecation warnings as part of this PR.

**Comment by philbucher** [comment]
> One last question: some of the methods in Communicator are not directly related to the ModelPart or the coloring and only execute standard MPI calls (see `SumAll`, `MinAll` or `Barrier` in `communicator.h`). Since this is now the task of the `DataCommunicator`, we were discussing with @philbucher that they could possibly be deprecated to reduce duplicate code. The equivalent call `my_communicator.GetDataCommunicator().Barrier()` (or whatever) can be used instead.
> 
> Does this make sense? If so, I would add the deprecation warnings as part of this PR.

To me this makes sense. It will require some minor refactoring but I think it is worth it since we are anyway cleaning up the MPI stuff

File: kratos/sources/kratos_application.cpp [hunk 5]
```diff
@@ -322,6 +322,10 @@ void KratosApplication::RegisterKratosCore() {
     KRATOS_REGISTER_FLAG(MARKER);
     KRATOS_REGISTER_FLAG(PERIODIC);
 
+    // Note: using internal macro for these two because they do not have a NOT_ version
+    KRATOS_ADD_FLAG_TO_KRATOS_COMPONENTS(ALL_DEFINED);
+    KRATOS_ADD_FLAG_TO_KRATOS_COMPONENTS(ALL_TRUE);
```
Comment (philbucher) [inline kratos/sources/kratos_application.cpp]: wasn't this part of a different PR?

Comment (jcotela) [reply kratos/sources/kratos_application.cpp]: That PR was a cherry-pick from this branch. It should go away once we merge master (will do later with some of the more "cosmetic" changes suggested).

**Comment by jcotela** [comment]
Unless we want to add the templated modelpart methods in this PR, this is ready to re-review. The decision on whether to deprecate the non-modelpart-related methods remains, but it can easily be addressed on a separate PR.

File: kratos/sources/kratos_application.cpp (hunk 5 above)
Comment (jcotela) [reply kratos/sources/kratos_application.cpp]: The alredy-merged changes should be gone now.

**Comment by philbucher** [comment]
I would leave this PR as is and add the deprecation stuff in the next PR
This one is already large enough :)

**Review by philbucher — COMMENTED** [review]
to me this looks ok but I am probably not the most suitable to review this
@pooyan-dadvand @roigcarlo @RiccardoRossi 

Nice refactor :+1:

File: kratos/mpi/includes/mpi_communicator.h [hunk 6]
```diff
@@ -74,12 +67,502 @@ namespace Kratos
...
+
+enum class OperationType {
+    Replace,
+    SumValues,
+    MinValues,
+    OrMaskedFlags,
+    AndMaskedFlags,
+    ReplaceMaskedFlags
+};
```
Comment (pooyan-dadvand) [inline kratos/mpi/includes/mpi_communicator.h:558]: Just a minor comment, Defined wouldn't be more descriptive than Masked?

**Comment by pooyan-dadvand** [comment]
I agree with using directly the DataCommunicator methods and deprecating the current ones in a separate PR.

File: kratos/mpi/includes/mpi_communicator.h (hunk 6 above)
Comment (jcotela) [reply kratos/mpi/includes/mpi_communicator.h:558]: I don't love either name: the idea is that this "operation" works only on the flags passed as argument to the AccessType:
```
UpdateValues(..., NodalFlagAccess(BOUNDARY), OrMaskedFlags);
```
Modifies only the `BOUNDARY` flag, regardless of which nodal flags are defined. Personally, if it was called "defined", I would understand it to affect all defined flags in the node.

Comment (jcotela) [reply kratos/mpi/includes/mpi_communicator.h:558]: Maybe `OrSelectedFlags`? Suggestions are welcome...

Comment (pooyan-dadvand) [reply kratos/mpi/includes/mpi_communicator.h:558]: Now I see the meaning, saying that the name was not descriptive! 

I like `OrSelectedFlags` more.

Comment (pooyan-dadvand) [reply kratos/mpi/includes/mpi_communicator.h:558]: `OrGivenFlags`?

Comment (jcotela) [reply kratos/mpi/includes/mpi_communicator.h:558]: I went ahead with `OrAccessedFlags` to try to convey that it affects the flags given by the "Access" object:
```
constexpr MeshAccess<DistributedType::Local> local_meshes;
constexpr MeshAccess<DistributedType::Ghost> ghost_meshes;
MPIInternals::NodalFlagsAccess nodal_flag_access(TheFlags);
constexpr Operation<OperationType::OrAccessedFlags> or_accessed;
constexpr Operation<OperationType::ReplaceAccessedFlags> replace_accessed;

TransferDistributedValues(ghost_meshes, local_meshes, nodal_flag_access, or_accessed);
```
I'm open to change if someone has a better name.

Comment (pooyan-dadvand) [reply kratos/mpi/includes/mpi_communicator.h:558]: :+1:

**Review by pooyan-dadvand — APPROVED** [review]
I like the AccessedFlag
