### PR TITLE
[GeoMechanicsApplication] Fix Zero-Diagonal error in the a thermal case

### LINKED ISSUE #14342: [GeoMechanicsApplication] Fix Zero-Diagonal error in the a thermal case
The user has issue with a thermal case. 
Makes the mesh by Gmsh. For a mesh, it works fine, but changing the mesh, it leads to Zero Diagonal error. 

[Success.zip](https://github.com/user-attachments/files/26379818/Success.zip)
[Fail.zip](https://github.com/user-attachments/files/26379820/Fail.zip)

### PR DESCRIPTION
**Pull request by mnabideltares**
## **📝 Description**
An error handeling is needed if the input material properties (heat capacity, and thermal conductivities) are all set to zer. It leads to zero-diagonal matrix.

## **🆕 Changelog**
1. Error handeling is added
2. Unit test is added

### CODE REVIEW

File: applications/GeoMechanicsApplication/custom_elements/transient_thermal_element.cpp [hunk 1]
```diff
@@ -165,8 +169,26 @@ int TransientThermalElement<TDim, TNumNodes>::Check(const ProcessInfo& rCurrentP
...
+        r_properties[SPECIFIC_HEAT_CAPACITY_WATER],  r_properties[SPECIFIC_HEAT_CAPACITY_SOLID],
+        r_properties[THERMAL_CONDUCTIVITY_WATER],    r_properties[THERMAL_CONDUCTIVITY_SOLID_XX],
+        r_properties[THERMAL_CONDUCTIVITY_SOLID_YY], r_properties[THERMAL_CONDUCTIVITY_SOLID_XY]};
+    if constexpr (TDim == 3) {
+        values.insert(values.end(), {r_properties[THERMAL_CONDUCTIVITY_SOLID_ZZ],
+                                     r_properties[THERMAL_CONDUCTIVITY_SOLID_YZ],
+                                     r_properties[THERMAL_CONDUCTIVITY_SOLID_XZ]});
+    }
+    const auto areAllValuesZero = std::all_of(values.begin(), values.end(), [&](double value) {
+        return std::abs(value) <= 1.0e-12 || std::abs(value) <= std::numeric_limits<double>::epsilon();
```
Comment (markelov208) [inline applications/GeoMechanicsApplication/custom_elements/transient_thermal_element.cpp]: you may remove std::numeric_limits<double>::epsilon(), which is 2.e-16 and does not work due to other check.

File: applications/GeoMechanicsApplication/custom_elements/transient_thermal_element.cpp [hunk 2]
```diff
@@ -165,8 +169,26 @@ int TransientThermalElement<TDim, TNumNodes>::Check(const ProcessInfo& rCurrentP
...
+    std::vector<double> values{
+        r_properties[SPECIFIC_HEAT_CAPACITY_WATER],  r_properties[SPECIFIC_HEAT_CAPACITY_SOLID],
+        r_properties[THERMAL_CONDUCTIVITY_WATER],    r_properties[THERMAL_CONDUCTIVITY_SOLID_XX],
+        r_properties[THERMAL_CONDUCTIVITY_SOLID_YY], r_properties[THERMAL_CONDUCTIVITY_SOLID_XY]};
+    if constexpr (TDim == 3) {
+        values.insert(values.end(), {r_properties[THERMAL_CONDUCTIVITY_SOLID_ZZ],
+                                     r_properties[THERMAL_CONDUCTIVITY_SOLID_YZ],
+                                     r_properties[THERMAL_CONDUCTIVITY_SOLID_XZ]});
+    }
+    const auto areAllValuesZero = std::all_of(values.begin(), values.end(), [&](double value) {
```
Comment (markelov208) [inline applications/GeoMechanicsApplication/custom_elements/transient_thermal_element.cpp]: you may use `ranges`: std::ranges::all_of(values,[&](double value). Hope there is no need in `&` here.

File: applications/GeoMechanicsApplication/custom_elements/transient_thermal_element.cpp [hunk 3]
```diff
@@ -165,8 +169,26 @@ int TransientThermalElement<TDim, TNumNodes>::Check(const ProcessInfo& rCurrentP
     if constexpr (TDim == 2) CheckUtilities::CheckForNonZeroZCoordinateIn2D(GetGeometry());
 
     check_properties.CheckAvailabilityAndEquality(RETENTION_LAW, "SaturatedLaw");
-    return RetentionLawFactory::Clone(r_properties)->Check(r_properties, rCurrentProcessInfo);
 
+    std::vector<double> values{
```
Comment (markelov208) [inline applications/GeoMechanicsApplication/custom_elements/transient_thermal_element.cpp]: perhaps, rename  `values ` as `property_values`

**Review by markelov208 — COMMENTED** [review]
Hi Mohamed, thank you for adding this check and unit test. I suggest small corrections. In addition, you may get read of repeating `r_properties `with the following

    std::vector<const Variable<double>*> properties_list{
        &SPECIFIC_HEAT_CAPACITY_WATER,  &SPECIFIC_HEAT_CAPACITY_SOLID,
        &THERMAL_CONDUCTIVITY_WATER,    &THERMAL_CONDUCTIVITY_SOLID_XX,
        &THERMAL_CONDUCTIVITY_SOLID_YY, &THERMAL_CONDUCTIVITY_SOLID_XY};
    if constexpr (TDim == 3) {
        properties_list.insert(properties_list.end(), {&THERMAL_CONDUCTIVITY_SOLID_ZZ, &THERMAL_CONDUCTIVITY_SOLID_YZ,
                                                       &THERMAL_CONDUCTIVITY_SOLID_XZ});
    }
    const auto areAllValuesZero =
        std::ranges::all_of(properties_list, [&r_properties](const Variable<double>* pVariable) {
        return std::abs(r_properties[*pVariable]) <= 1.0e-12;
    });

**Review by markelov208 — DISMISSED** [review]
Hi Mohamed, thank you for processing the review comments. I think our colleagues shall be informed about this check.

File: applications/GeoMechanicsApplication/custom_elements/transient_thermal_element.cpp [hunk 4]
```diff
@@ -165,8 +169,26 @@ int TransientThermalElement<TDim, TNumNodes>::Check(const ProcessInfo& rCurrentP
...
-    return RetentionLawFactory::Clone(r_properties)->Check(r_properties, rCurrentProcessInfo);
 
+    std::vector<const Variable<double>*> properties_list{
+        &SPECIFIC_HEAT_CAPACITY_WATER,  &SPECIFIC_HEAT_CAPACITY_SOLID,
+        &THERMAL_CONDUCTIVITY_WATER,    &THERMAL_CONDUCTIVITY_SOLID_XX,
+        &THERMAL_CONDUCTIVITY_SOLID_YY, &THERMAL_CONDUCTIVITY_SOLID_XY};
+    if constexpr (TDim == 3) {
+        properties_list.insert(properties_list.end(), {&THERMAL_CONDUCTIVITY_SOLID_ZZ, &THERMAL_CONDUCTIVITY_SOLID_YZ,
+                                                       &THERMAL_CONDUCTIVITY_SOLID_XZ});
+    }
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_elements/transient_thermal_element.cpp:180]: My understanding is that heat capacity values are actually allowed to be equal to zero. This also applies to the conductivity cross terms (i.e. `THERMAL_CONDUCTIVITY_SOLID_XY`, `THERMAL_CONDUCTIVITY_SOLID_YZ` and `THERMAL_CONDUCTIVITY_SOLID_XZ`), since they don't appear on the matrix diagonal. In that case, the list becomes shorter:

```suggestion
    std::vector<const Variable<double>*> properties_list{
        &THERMAL_CONDUCTIVITY_WATER,    &THERMAL_CONDUCTIVITY_SOLID_XX,
        &THERMAL_CONDUCTIVITY_SOLID_YY};
    if constexpr (TDim == 3) {
        properties_list.push_back(&THERMAL_CONDUCTIVITY_SOLID_ZZ);
    }
```

File: applications/GeoMechanicsApplication/custom_elements/transient_thermal_element.cpp [hunk 5]
```diff
@@ -165,8 +169,26 @@ int TransientThermalElement<TDim, TNumNodes>::Check(const ProcessInfo& rCurrentP
...
+    const auto areAllValuesZero =
+        std::ranges::all_of(properties_list, [&r_properties](const Variable<double>* pVariable) {
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_elements/transient_thermal_element.cpp:182]: I think that Wijtze Pieter had indicated before that if **any** of the listed conductivity values (i.e. `THERMAL_CONDUCTIVITY_WATER`, `THERMAL_CONDUCTIVITY_SOLID_XX`, `THERMAL_CONDUCTIVITY_SOLID_YY`, `THERMAL_CONDUCTIVITY_SOLID_ZZ`) equals zero, we can expect zero values to appear on the matrix diagonal. In other words, we shouldn't check whether **all** values are equal to zero, but if **any** value equals zero.

```suggestion
        std::ranges::any_of(properties_list, [&r_properties](const Variable<double>* pVariable) {
```

File: applications/GeoMechanicsApplication/custom_elements/transient_thermal_element.cpp [hunk 6]
```diff
@@ -165,8 +169,26 @@ int TransientThermalElement<TDim, TNumNodes>::Check(const ProcessInfo& rCurrentP
...
+        return std::abs(r_properties[*pVariable]) <= 1.0e-12;
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_elements/transient_thermal_element.cpp:183]: I honestly don't know whether 1.0e-12 is a good choice for the tolerance value. Perhaps it is, perhaps it isn't. I think the answer to this question depends on the chosen units. What matters in the end is whether the resultant matrix becomes singular.

File: applications/GeoMechanicsApplication/custom_elements/transient_thermal_element.cpp [hunk 7]
```diff
@@ -165,8 +169,26 @@ int TransientThermalElement<TDim, TNumNodes>::Check(const ProcessInfo& rCurrentP
...
+    });
+    if (areAllValuesZero) {
+        KRATOS_ERROR << "The input is invalid: capacity and thermal conductivity parameters "
+                        "cannot all be zero."
+                     << std::endl;
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_elements/transient_thermal_element.cpp:188]: This error message can be made a bit more specific. In particular, I'm missing a property ID, since that will help the user to identify the faulty material. Wijtze Pieter has suggested to use an adapted version of `CheckProperties::CheckPermeabilityProperties` (i.e. something like `CheckProperties::CheckConductivityProperties`).

**Review by avdg81 — COMMENTED** [review]
Hi Mohamed,
Thanks for preparing the additional checks. I'm doubting whether the checks are actually correct, so I have written down my thoughts. Hope this helps.

File: applications/GeoMechanicsApplication/custom_elements/transient_thermal_element.cpp (hunk 4 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_elements/transient_thermal_element.cpp]: @avdg81 Thank you for the review.

The thermal conductivity tensor does not go alone into the conductivity matrix. The conductivity matrix is defined by $\nabla N^T  \lambda  \nabla N$. Suppose that the diagonal to be entirely zero. Any non-zero component off-diagonal can still fill the matrix entirely with not-zero components.

Moreover, the final matrix takes the superposition of the storivity and conduction. Heat capacity fills the storivity matrix, and thermal conductivity fills the conduction matrix. If one of those are non-zero, then the sum of them, which goes into the final matrix, will be non-zero

File: applications/GeoMechanicsApplication/custom_elements/transient_thermal_element.cpp (hunk 5 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_elements/transient_thermal_element.cpp]: As mentioned in the previous comment, I think any value which is larger than zero, it leads to matrix with non-zero diagonal. Please correct me if I am wrong.

File: applications/GeoMechanicsApplication/custom_elements/transient_thermal_element.cpp (hunk 6 above)
Comment (mnabideltares) [reply applications/GeoMechanicsApplication/custom_elements/transient_thermal_element.cpp]: I could set it as absolute zero. However, we may risk that truncation error takes effect. I know that setting absolute zero, stays as it is in the memory as long as there is no calculation. However, for safety I tried to set a small value. i think those properties are never smaller than that value regardless of the unit system.

**Review by markelov208 — APPROVED** [review]
Hi Wijtze Piter, thank you for this fix. I think the PR is ready to be merged.
