### PR TITLE
[Structural] copy-paste bugfix in ConvCrit

### LINKED ISSUE #4479: Failing Example in release
Dear @KlausBSautter @philbucher @loumalouomega , it is Riccardo here writing on behalf of Agustina.

we have a test which is still failing with the beam. It sort of works for the small displacmeent beam, however it fails immediately as soon as we switch to the large displacement one.

https://www.dropbox.com/s/t05ixe69v2jtpq5/Test-beam-metro.gid.zip?dl=0

the test represents a small portion of a stent, with realistic data for the properties of the beams.
Data are in mm.

essentially the boundary conditions pull the "tube" in the direction y and fix the displacement of  the basis. The interest is essentially in measuring the change of diameter as a function of the relative displacement in y direction.

With the small deformation beam we get a result however the structure becomes bigger in all directions instead of showing a reduction in diameter as we increase the pull.
the large dispalcement case fails invariably, even if we use smaller steps.
We have been taking some good care in the BCs and we are convinced that they are ok, so in our opinion (Riccardo's in particular :-p) the error should not be in he BCs but rather somewhere in the solution process. 

any hint would be very welcome

### PR DESCRIPTION
**Pull request by philbucher**
Fixing a copy-paste error that leads to NEGLECTING the "other" Dof. For Structural Cases this means that it ALWAYS neglects how the rotations converge / convergence of rotations is not being checked!!!

This is the second time I fixed a MAYOR error in this criteria.
I have not checked the tests yet, no time right now

Since this is anyway 100% the same as the VelPr Criteria in the FluidDynamics I will refactor this and put it to the Core (and also make it compatible with Trilinos) FYI @sunethwarna @jcotela 

@KratosMultiphysics/structural-mechanics please check your cases with this

Edit after my findings I would say this should also solve #4479 (closes #4479)

### CODE REVIEW

File: applications/StructuralMechanicsApplication/custom_strategies/custom_convergencecriterias/displacement_and_other_dof_criteria.h [hunk 1]
```diff
@@ -420,7 +420,7 @@ class DisplacementAndOtherDoFCriteria : public ConvergenceCriteria< TSparseSpace
                 }
                 else
                 {
-                    mReferenceOtherDoFNorm += AuxValue*AuxValue;
+                    DeltaOtherDoFNorm += AuxValue*AuxValue;
```
Comment (loumalouomega) [inline applications/StructuralMechanicsApplication/custom_strategies/custom_convergencecriterias/displacement_and_other_dof_criteria.h:423]: Uff, that it is my fault

**Review by loumalouomega — APPROVED** [review]
OK

File: applications/StructuralMechanicsApplication/custom_strategies/custom_convergencecriterias/displacement_and_other_dof_criteria.h (hunk 1 above)
Comment (philbucher) [reply applications/StructuralMechanicsApplication/custom_strategies/custom_convergencecriterias/displacement_and_other_dof_criteria.h:423]: no worries
I was always curious why it always said that the rotations converge instant, but never checked in detail why

**Comment by philbucher** [comment]
@KratosMultiphysics/structural-mechanics this seems to be a game changer, the simulations that I struggle with for very very very long now converge like a charm!

@agiuliodori could you please try the cases that did not converge for you from #4479 with this branch?

**Comment by philbucher** [comment]
I ran the tests now, they work fine, hence I will merge this

@loumalouomega @AlejandroCornejo the following test fails (has nothing to do with this PR):
~~~
======================================================================
FAIL: test_execution (structural_mechanics_test_factory.TensileTestStructuralTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philippb/software/Kratos_prod/applications/StructuralMechanicsApplication/tests/structural_mechanics_test_factory.py", line 55, in test_execution
    self.test.RunSolutionLoop()
  File "/home/philippb/software/Kratos_prod/kratos/python_scripts/analysis_stage.py", line 69, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/home/philippb/software/Kratos_prod/kratos/python_scripts/analysis_stage.py", line 144, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/home/philippb/software/Kratos_prod/kratos/python_scripts/from_json_check_result_process.py", line 173, in ExecuteFinalizeSolutionStep
    self.__check_values(elem.Id, "Element", value[gp], value_json, variable_name)
  File "/home/philippb/software/Kratos_prod/kratos/python_scripts/from_json_check_result_process.py", line 262, in __check_values
    self.assertTrue(isclosethis, msg=msg)
AssertionError: False is not true : Error checking Element #1221 for variable PLASTIC_DISSIPATION results:
0.38531 != 0.39531; rel_tol=0.0001, abs_tol=0.01

----------------------------------------------------------------------
~~~

**Comment by AlejandroCornejo** [comment]
> 
> 
> I ran the tests now, they work fine, hence I will merge this
> 
> @loumalouomega @AlejandroCornejo the following test fails (has nothing to do with this PR):
> 
> ```
> ======================================================================
> FAIL: test_execution (structural_mechanics_test_factory.TensileTestStructuralTest)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/philippb/software/Kratos_prod/applications/StructuralMechanicsApplication/tests/structural_mechanics_test_factory.py", line 55, in test_execution
>     self.test.RunSolutionLoop()
>   File "/home/philippb/software/Kratos_prod/kratos/python_scripts/analysis_stage.py", line 69, in RunSolutionLoop
>     self.FinalizeSolutionStep()
>   File "/home/philippb/software/Kratos_prod/kratos/python_scripts/analysis_stage.py", line 144, in FinalizeSolutionStep
>     process.ExecuteFinalizeSolutionStep()
>   File "/home/philippb/software/Kratos_prod/kratos/python_scripts/from_json_check_result_process.py", line 173, in ExecuteFinalizeSolutionStep
>     self.__check_values(elem.Id, "Element", value[gp], value_json, variable_name)
>   File "/home/philippb/software/Kratos_prod/kratos/python_scripts/from_json_check_result_process.py", line 262, in __check_values
>     self.assertTrue(isclosethis, msg=msg)
> AssertionError: False is not true : Error checking Element #1221 for variable PLASTIC_DISSIPATION results:
> 0.38531 != 0.39531; rel_tol=0.0001, abs_tol=0.01
> 
> ----------------------------------------------------------------------
> ```

Okkey thank you, since I want to change the characteristic length calculation, I'll check all the changes

**Comment by agiuliodori** [comment]
@philbucher  Hi Philipp, i tried the example again with the new branch but it still doesnt work for large displacement (it does work with small displacement beams). Here i attach the example:
https://www.dropbox.com/s/2i2np91zjj6ahdo/Test_viga_18_10_2.gid.rar?dl=0

**Comment by philbucher** [comment]
@agiuliodori I see that you set the number of non-lin iterations to 10, which in my experience is not enough for very non-lin problems. Did you try with a higher number? I suggest to try with up to 100. Usually it does not need this many but in some steps it might

Also did you try to play with the conv-crit tolerances?
Your setup seems to be the one written by default from gid

Last but not least did you play with the timestep?

What is the error you are getting? Does it not converge in some step or already not in the first one?

**Comment by agiuliodori** [comment]
@philbucher Thanks Philipp, i have already tried increasing the number of iterations and with different timestep values, but i did not try to play with tolerances yet. I will do it and tell you.
The simulation runs and finishes correctly but since the first time step the results make no sense (the displacement that i set is in the  order of 1e-2 and the displacement output is about 1e+38).

**Comment by agiuliodori** [comment]
@philbucher @RiccardoRossi Hi Philipp; i have run the test decreasing tolerances and the displacement field, and incresing the inertia values and it has already converged. Thanks!

**Comment by KlausBSautter** [comment]
@agiuliodori if you have further problems, could you check out this branch:
https://github.com/KratosMultiphysics/Kratos/tree/StructMech/beam_check

and use the `BeamElement3D2N` ? It works way better than the current beam. We might replace it in the future....  @philbucher
