### PR TITLE
[GeoMechanicsApplication] Add functionality of fixing water pressures above phreatic line to zero

### LINKED ISSUE #13453: [GeoMechanicsApplication] Bring prototype of fix_model_part_above_phreatic_line_process to master
Bring the prototype developed in branch:

geo/water-pressures-in-dry-zone

and produced in #13216 

to the master

### PR DESCRIPTION
**Pull request by rfaasse**
**📝 Description**
This PR creates a process (based on knowledge obtained by the creation of a prototype/proof of concept), which dynamically fixes the water pressures above the phreatic line (the dry zone) to zero. 

The process takes into account the current position of the nodes using the TOTAL_DISPLACEMENT (combined with the initial position of the nodes), such that it works the same for simulations with/without the move_mesh option enabled.

### CODE REVIEW

File: applications/GeoMechanicsApplication/custom_processes/fix_water_pressures_above_phreatic_line.h [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+//
+
+#pragma once
+
+#include "includes/table.h"
+#include "processes/process.h"
+
+namespace Kratos
+{
+///
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_processes/fix_water_pressures_above_phreatic_line.h:25]: For completeness (and making it less susceptible to changes in included headers), I would suggest to forward declare classes `ModelPart` and `Parameters`.

File: applications/GeoMechanicsApplication/custom_processes/fix_water_pressures_above_phreatic_line.cpp [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+//
+//  License:         geo_mechanics_application/license.txt
+//
+//  Main authors:    Richard Faasse
+//                   Jonathan Nuttall
+//
+
+#include "fix_water_pressures_above_phreatic_line.h"
+#include "geo_mechanics_application_variables.h"
+#include "includes/model_part.h"
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_processes/fix_water_pressures_above_phreatic_line.cpp:17]: Shouldn't we, for completeness, also include the header that contains the definition of class `Parameters`?

File: applications/GeoMechanicsApplication/custom_processes/fix_water_pressures_above_phreatic_line.cpp [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+    const auto x_coordinates = rSettings["x_coordinates"].GetVector();
+    const auto y_coordinates = rSettings["y_coordinates"].GetVector();
+
+    KRATOS_ERROR_IF(x_coordinates.empty() || y_coordinates.empty())
+        << "The x_coordinates and/or y_coordinates of the phreatic line must be "
+           "non-empty vectors.\n";
+
+    KRATOS_ERROR_IF(x_coordinates.size() != y_coordinates.size())
+        << "The lengths of the x_coordinates and y_coordinates of the phreatic line must be "
+           "equal.\n";
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_processes/fix_water_pressures_above_phreatic_line.cpp]: If we would swap these two checks, the now first check (for empty vectors) can be reduced to checking only one vector for being empty (since after swapping you already know that they must have the same size). That makes the code slightly easier.

File: applications/GeoMechanicsApplication/custom_processes/fix_water_pressures_above_phreatic_line.cpp [hunk 4]
```diff
@@ -0,0 +1,55 @@
...
+}
+
+void FixWaterPressuresAbovePhreaticLineProcess::ExecuteInitializeSolutionStep()
+{
+    block_for_each(mrModelPart.Nodes(), [this](Node& rNode) {
+        const auto current_coordinates =
+            rNode.GetInitialPosition() + rNode.FastGetSolutionStepValue(TOTAL_DISPLACEMENT);
+        if (current_coordinates[1] > mPhreaticLineTable(current_coordinates[0])) {
+            rNode.FastGetSolutionStepValue(WATER_PRESSURE) = 0.0;
+            rNode.Fix(WATER_PRESSURE);
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_processes/fix_water_pressures_above_phreatic_line.cpp]: For clarity, we may want to swap these two statements. First say that we're going to fix the water pressure, and only then at what value. That seems a more natural order to me.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp [hunk 5]
```diff
@@ -0,0 +1,245 @@
...
+
+namespace Kratos::Testing
+{
+
+KRATOS_TEST_CASE_IN_SUITE(TestFixWaterPressureAbovePhreaticLine_ThrowsUponConstructionWhenXOrYCoordinatesAreEmpty,
+                          KratosGeoMechanicsFastSuiteWithoutKernel)
+{
+    // Arrange
+    constexpr double y_node_1     = 0.0;
+    constexpr double y_node_2     = -2.0;
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp]: I generally prefer to use `auto` when the type can be deduced:
```suggestion
    constexpr auto y_node_1     = 0.0;
    constexpr auto y_node_2     = -2.0;
```

This suggestion also applies to the other test cases.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp [hunk 6]
```diff
@@ -0,0 +1,245 @@
...
+
+Parameters CreateParametersWithConstantPhreaticLineAtHeight(double height)
+{
+    return Parameters{R"(
+            {
+                "model_part_name": "foo",
+                "x_coordinates": [0.0],
+                "y_coordinates": [)" +
+                      std::to_string(height) + R"(],
+                "z_coordinates": [0.0]
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp]: I think this list is never used by the tested process, so perhaps we'd better not define it at all. What do you think?

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp [hunk 7]
```diff
@@ -0,0 +1,245 @@
...
+    constexpr double y_node_2     = -2.0;
+    auto             model        = Model{};
+    auto&            r_model_part = CreateModelPartWithTwoNodesAtHeights(model, y_node_1, y_node_2);
+
+    auto test_parameters = Parameters{R"(
+            {
+                "model_part_name": "foo",
+                "x_coordinates": [],
+                "y_coordinates": []
+            }  )"};
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp]: I believe we can make this variable `const`:
```suggestion
    const auto test_parameters = Parameters{R"(
            {
                "model_part_name": "foo",
                "x_coordinates": [],
                "y_coordinates": []
            }  )"};
```

This suggestion also applies to the test parameters of the following test cases.

File: applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/common/mesh.mdpa [hunk 8]
```diff
@@ -0,0 +1,240 @@
+Begin Table 3 TIME DISPLACEMENT_Y
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/common/mesh.mdpa]: Just out of curiosity: why start counting from 3?

File: applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/common/mesh.mdpa [hunk 9]
```diff
@@ -0,0 +1,240 @@
...
+  18  0  25 15 27 43 52 53
+  19  0  15 16 27 20 38 52
+  20  0  8 25 27 42 53 40
+End Elements
+
+Begin SubModelPart Soil
+  Begin SubModelPartTables
+    3
+  End SubModelPartTables
+  Begin SubModelPartNodes
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/common/mesh.mdpa]: Since the list of nodes is not sorted, it's difficult to check whether any nodes are missing.

File: applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/with_move_mesh/ProjectParameters.json [hunk 10]
```diff
@@ -0,0 +1,166 @@
...
+    "model_import_settings": {
+      "input_type": "mdpa",
+      "input_filename": "../common/mesh"
+    },
+    "material_import_settings": {
+      "materials_filename": "../common/MaterialParameters.json"
+    },
+    "time_stepping": {
+      "time_step": 3600.0,
+      "max_delta_time_factor": 8640000000.0
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/with_move_mesh/ProjectParameters.json]: I don't think we need this input parameter, since the `"increase_factor"` has been set to 1.0.

File: applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/with_move_mesh/ProjectParameters.json [hunk 11]
```diff
@@ -0,0 +1,166 @@
...
+                "GiDPostMode": "GiD_PostAscii",
+                "MultiFileFlag": "SingleFile"
+              },
+              "file_label": "step",
+              "output_control_type": "step",
+              "output_interval": 1,
+              "body_output": true,
+              "node_output": false,
+              "skin_output": false,
+              "plane_output": [],
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/with_move_mesh/ProjectParameters.json]: Perhaps we can remove this empty list? The same goes for `"point_data_configuration"`.

File: applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/with_move_mesh/ProjectParameters.json [hunk 12]
```diff
@@ -0,0 +1,166 @@
...
+        }
+      },{
+        "python_module": "apply_vector_constraint_table_process",
+        "kratos_module": "KratosMultiphysics.GeoMechanicsApplication",
+        "process_name": "ApplyVectorConstraintTableProcess",
+        "Parameters": {
+          "model_part_name": "PorousDomain.Soil",
+          "variable_name": "DISPLACEMENT",
+          "active": [true, true, true],
+          "is_fixed": [true, true, true],
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/with_move_mesh/ProjectParameters.json]: I'm just wondering: since this is a plane strain model, can't we make the z components inactive?
```suggestion
          "active": [true, true, false],
          "is_fixed": [true, true, false],
```

File: applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/with_move_mesh/ProjectParameters.json
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/with_move_mesh/ProjectParameters.json:1]: Just something to ponder about: it's a pity that we need to define the applicable phreatic line three times. Twice for the boundary conditions (along the top and bottom edges of the column), and once for the new process that fixes the water pressures above the phreatic line. It's easy to make mistakes here, but so far I don't have a better idea yet.

File: applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line.py [hunk 13]
```diff
@@ -0,0 +1,84 @@
...
+            5,
+        )
+        # When it's moving upwards again, we have another theoretical cross-over time at 151200 seconds. However,
+        # since the DoF is fixed based on the TOTAL_DISPLACEMENT (which is calculated at the end of the time step),
+        # the real cross-over happens one step later.
+        self.assertAlmostEqual(
+            reader.nodal_values_at_time("WATER_PRESSURE", 154800, output_data, [27])[0],
+            -3678.75,
+            5,
+        )
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line.py]: Despite the comment that tried to explain at which times the water pressure values are checked, I was still a bit confused. Perhaps we can try to make the comment even more explicit about how we arrive at the checked time steps?

Also, I failed to reproduce the water pressure value just before the cross-over (i.e. -3678.75). Since the water table falls with 1/12 m per hour, I would expect to see here a hydrostatic water pressure that corresponds to 1/12 m of water depth. But the expected value here is quite different, and I just don't understand why. Perhaps we can try to figure out what happens, and check whether that makes sense? Thanks.

**Review by avdg81 — COMMENTED** [review]
Hi @rfaasse,

Thanks a lot for making a clean and well-tested version of the process that was originally developed by @mcgicjn2. I feel that this PR is almost ready for being merged into `master`. I have several minor suggestions and also a few questions. Hope you'll find them useful.

File: applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line.py (hunk 13 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line.py]: The reason for this seems to be that although our new process is time dependent, the BCs for the top and bottom are not. Therefore, the -3678.75 value is the value node 27 would have had if it hadn't moved. We're now experimenting with making the BC 'time-dependent' by adding a table with a constant value, such that it is recalculated each time step

File: applications/GeoMechanicsApplication/custom_processes/fix_water_pressures_above_phreatic_line.cpp (hunk 2 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/custom_processes/fix_water_pressures_above_phreatic_line.cpp:17]: You're right, done

File: applications/GeoMechanicsApplication/custom_processes/fix_water_pressures_above_phreatic_line.h (hunk 1 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/custom_processes/fix_water_pressures_above_phreatic_line.h:25]: Done

File: applications/GeoMechanicsApplication/custom_processes/fix_water_pressures_above_phreatic_line.cpp (hunk 4 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/custom_processes/fix_water_pressures_above_phreatic_line.cpp]: I have no preference for the order, so applied your suggestion

File: applications/GeoMechanicsApplication/custom_processes/fix_water_pressures_above_phreatic_line.cpp (hunk 3 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/custom_processes/fix_water_pressures_above_phreatic_line.cpp]: Done

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp (hunk 6 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp]: Agreed, missed this one, removed

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp (hunk 5 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp]: Done

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp (hunk 7 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp]: Done

File: applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/common/mesh.mdpa (hunk 9 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/common/mesh.mdpa]: Sorted

File: applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/with_move_mesh/ProjectParameters.json
Comment (rfaasse) [reply applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/with_move_mesh/ProjectParameters.json:1]: Indeed, probably the possibility to enter multiple model parts for a process would help

File: applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/with_move_mesh/ProjectParameters.json (hunk 10 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/with_move_mesh/ProjectParameters.json]: Removed

File: applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/with_move_mesh/ProjectParameters.json (hunk 11 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/with_move_mesh/ProjectParameters.json]: Removed. The gauss_point_results are always expected (even though empty) in our DSettlement workflow. We could have a look at a later moment if we think that's necessary

**Review by rfaasse — COMMENTED** [review]
Processed review comments

File: applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line.py (hunk 13 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line.py]: At this point we're still confused about the precise values of the water pressures. However, all this process does is either fix a DoF to 0, or keep it free. Therefore, I'd propose to merge this PR and have a deeper dive into the phreatic multiline processes in general in a separate issue.

FYI @avdg81 @WPK4FEM @mcgicjn2

Comment (rfaasse) [reply applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line.py]: Just to add some more context. This is the water pressure profile through depth in the time step just before (red) and after (green) node the asserted node 27 is crossed by the phreatic line (by moving through it), the vertical lines depict the effective depth of the phreatic line at these moments in time:

image

Comment (rfaasse) [reply applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line.py]: @avdg81 @WPK4FEM @mcgicjn2 Please let me know whether you need more info, or if these results are not a blocker for the PR to be merged.

**Review by WPK4FEM — DISMISSED** [review]
With the 2 tests and their improved explanation on tables and values in tables, I think this is good to go.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp [hunk 14]
```diff
@@ -0,0 +1,244 @@
...
+    KRATOS_EXPECT_EXCEPTION_IS_THROWN(
+        FixWaterPressuresAbovePhreaticLineProcess(r_model_part, test_parameters), expected_error_message);
+}
+
+KRATOS_TEST_CASE_IN_SUITE(TestFixWaterPressureAbovePhreaticLine_ThrowsUponConstructionWhenXYCoordinatesAreNotEqualLength,
+                          KratosGeoMechanicsFastSuiteWithoutKernel)
+{
+    // Arrange
+    constexpr double y_node_1     = 0.0;
+    constexpr double y_node_2     = -2.0;
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp]: Nitpicking:
```suggestion
    constexpr auto y_node_1     = 0.0;
    constexpr auto y_node_2     = -2.0;
```

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp [hunk 15]
```diff
@@ -0,0 +1,244 @@
...
+    KRATOS_EXPECT_EXCEPTION_IS_THROWN(
+        FixWaterPressuresAbovePhreaticLineProcess(r_model_part, test_parameters), expected_error_message);
+}
+
+KRATOS_TEST_CASE_IN_SUITE(TestFixWaterPressureAbovePhreaticLine_FixesAllWaterPressuresToZeroWhenAllNodesAbovePhreaticLine,
+                          KratosGeoMechanicsFastSuiteWithoutKernel)
+{
+    // Arrange
+    constexpr double y_node_1     = 0.0;
+    constexpr double y_node_2     = -1.0;
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp]: More nitpicking:
```suggestion
    constexpr auto y_node_1     = 0.0;
    constexpr auto y_node_2     = -1.0;
```

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp [hunk 16]
```diff
@@ -0,0 +1,244 @@
...
+        EXPECT_TRUE(r_node.IsFixed(WATER_PRESSURE));
+    }
+}
+
+KRATOS_TEST_CASE_IN_SUITE(TestFixWaterPressureAbovePhreaticLine_DoesNothingWhenAllNodesBelowPhreaticLine,
+                          KratosGeoMechanicsFastSuiteWithoutKernel)
+{
+    // Arrange
+    constexpr double y_node_1     = 0.0;
+    constexpr double y_node_2     = -1.0;
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp]:
```suggestion
    constexpr auto y_node_1     = 0.0;
    constexpr auto y_node_2     = -1.0;
```

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp [hunk 17]
```diff
@@ -0,0 +1,244 @@
...
+    EXPECT_DOUBLE_EQ(r_model_part.GetNode(2).FastGetSolutionStepValue(WATER_PRESSURE), 2.0);
+    EXPECT_FALSE(r_model_part.GetNode(2).IsFixed(WATER_PRESSURE));
+}
+
+KRATOS_TEST_CASE_IN_SUITE(TestFixWaterPressureAbovePhreaticLine_OnlyFixesNodesAbovePhreaticLine,
+                          KratosGeoMechanicsFastSuiteWithoutKernel)
+{
+    // Arrange
+    constexpr double y_node_1     = 0.0;
+    constexpr double y_node_2     = -1.0;
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp]:
```suggestion
    constexpr auto y_node_1     = 0.0;
    constexpr auto y_node_2     = -1.0;
```

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp [hunk 18]
```diff
@@ -0,0 +1,244 @@
...
+    EXPECT_DOUBLE_EQ(r_model_part.GetNode(2).FastGetSolutionStepValue(WATER_PRESSURE), 2.0);
+    EXPECT_FALSE(r_model_part.GetNode(2).IsFixed(WATER_PRESSURE));
+}
+
+KRATOS_TEST_CASE_IN_SUITE(TestFixWaterPressureAbovePhreaticLine_FreesNodesWhenTheyGetBelowPhreaticLine_WithoutMoveMesh,
+                          KratosGeoMechanicsFastSuiteWithoutKernel)
+{
+    // Arrange
+    constexpr double y_node_1     = 0.0;
+    constexpr double y_node_2     = -2.0;
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp]:
```suggestion
    constexpr auto y_node_1     = 0.0;
    constexpr auto y_node_2     = -2.0;
```

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp [hunk 19]
```diff
@@ -0,0 +1,244 @@
...
+
+KRATOS_TEST_CASE_IN_SUITE(TestFixWaterPressureAbovePhreaticLine_FixesAllWaterPressuresToZeroWhenAllNodesAbovePhreaticLine,
+                          KratosGeoMechanicsFastSuiteWithoutKernel)
+{
+    // Arrange
+    constexpr double y_node_1     = 0.0;
+    constexpr double y_node_2     = -1.0;
+    auto             model        = Model{};
+    auto&            r_model_part = CreateModelPartWithTwoNodesAtHeights(model, y_node_1, y_node_2);
+    auto             test_parameters = CreateParametersWithConstantPhreaticLineAtHeight(-2.0);
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp]: Can we make this variable `const`?
```suggestion
    const auto       test_parameters = CreateParametersWithConstantPhreaticLineAtHeight(-2.0);
```

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp [hunk 20]
```diff
@@ -0,0 +1,244 @@
...
+{
+    // Arrange
+    constexpr double y_node_1     = 0.0;
+    constexpr double y_node_2     = -1.0;
+    auto             model        = Model{};
+    auto&            r_model_part = CreateModelPartWithTwoNodesAtHeights(model, y_node_1, y_node_2);
+    r_model_part.GetNode(1).FastGetSolutionStepValue(WATER_PRESSURE) = 1.0;
+    r_model_part.GetNode(2).FastGetSolutionStepValue(WATER_PRESSURE) = 2.0;
+
+    auto test_parameters = CreateParametersWithConstantPhreaticLineAtHeight(1.0);
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp]: Same question here: can we make this variable `const`?
```suggestion
    const auto test_parameters = CreateParametersWithConstantPhreaticLineAtHeight(1.0);
```

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp [hunk 21]
```diff
@@ -0,0 +1,244 @@
...
+    // Arrange
+    constexpr double y_node_1     = 0.0;
+    constexpr double y_node_2     = -1.0;
+    auto             model        = Model{};
+    auto&            r_model_part = CreateModelPartWithTwoNodesAtHeights(model, y_node_1, y_node_2);
+
+    r_model_part.GetNode(1).FastGetSolutionStepValue(WATER_PRESSURE) = 1.0;
+    r_model_part.GetNode(2).FastGetSolutionStepValue(WATER_PRESSURE) = 2.0;
+
+    auto test_parameters = CreateParametersWithConstantPhreaticLineAtHeight(-0.5);
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp]: And this one, can we make this variable `const`?
```suggestion
    const auto test_parameters = CreateParametersWithConstantPhreaticLineAtHeight(-0.5);
```

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp [hunk 22]
```diff
@@ -0,0 +1,244 @@
...
+    // Arrange
+    constexpr double y_node_1     = 0.0;
+    constexpr double y_node_2     = -2.0;
+    auto             model        = Model{};
+    auto&            r_model_part = CreateModelPartWithTwoNodesAtHeights(model, y_node_1, y_node_2);
+
+    r_model_part.GetNode(1).FastGetSolutionStepValue(WATER_PRESSURE) = 1.0;
+    r_model_part.GetNode(2).FastGetSolutionStepValue(WATER_PRESSURE) = 2.0;
+
+    auto test_parameters = CreateParametersWithConstantPhreaticLineAtHeight(-0.5);
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp]:
```suggestion
    const auto test_parameters = CreateParametersWithConstantPhreaticLineAtHeight(-0.5);
```
??

File: applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/README.md [hunk 23]
```diff
@@ -0,0 +1,41 @@
...
+seconds (or 42 hours). However, since the DoF are fixed/freed based on the `TOTAL_DISPLACEMENT` variable (which is
+calculated at the end of a time step), the crossover happens one time-step later. 
+
+The values of the water pressures when the DoF is free at node 27 is verified by visual inspection of the following depth profiles at different times:
+
+![pressure_depth_profiles.png](pressure_depth_profiles.png)
+
+The different lines represent the water pressure in the middle of the column at different times: just before the phreatic line crosses node 27 (red), just after the phreatic line crosses node 27 (green), the time just before the phreatic line crosses 0.5 m below the top of the column (olive/dark yellow) and the time when the phreatic line is at the top of the column (blue).
+
+The pressure are expected to have the same slope (determined by the specific weight). The reason the green line exhibits a different slope is because the column does not have any storage capacity, meaning a straight line is created between two prescribed pressures. Since the pressures can only be prescribed on the nodes, but not in between the nodes, the slope is not constant.
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/README.md]: More nitpicking: shouldn't it be plural?
```suggestion
The pressures are expected to have the same slope (determined by the specific weight). The reason the green line exhibits a different slope is because the column does not have any storage capacity, meaning a straight line is created between two prescribed pressures. Since the pressures can only be prescribed on the nodes, but not in between the nodes, the slope is not constant.
```

File: applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/with_move_mesh/mesh.mdpa [hunk 24]
```diff
@@ -0,0 +1,251 @@
...
+    18
+    19
+    20
+  End SubModelPartElements
+End SubModelPart 
+
+Begin SubModelPart SoilExcludingBoundary
+  Begin SubModelPartTables
+  End SubModelPartTables
+  Begin SubModelPartNodes
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/with_move_mesh/mesh.mdpa:178]: Nice to have: can we sort these node numbers, please?

File: applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/without_move_mesh/ProjectParameters.json [hunk 25]
```diff
@@ -0,0 +1,165 @@
...
+                "GiDPostMode": "GiD_PostAscii",
+                "MultiFileFlag": "SingleFile"
+              },
+              "file_label": "step",
+              "output_control_type": "step",
+              "output_interval": 1,
+              "body_output": true,
+              "node_output": false,
+              "skin_output": false,
+              "plane_output": [],
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/without_move_mesh/ProjectParameters.json]: Nitpicking: perhaps you've overlooked this empty list, which is redundant.

File: applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/without_move_mesh/ProjectParameters.json [hunk 26]
```diff
@@ -0,0 +1,165 @@
...
+              "nodal_results": ["WATER_PRESSURE", "TOTAL_DISPLACEMENT"],
+              "gauss_point_results": []
+            },
+            "point_data_configuration": []
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/without_move_mesh/ProjectParameters.json]: Same thing here.

File: applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/without_move_mesh/mesh.mdpa [hunk 27]
```diff
@@ -0,0 +1,252 @@
...
+    18
+    19
+    20
+  End SubModelPartElements
+End SubModelPart 
+
+Begin SubModelPart SoilExcludingBoundary
+  Begin SubModelPartTables
+  End SubModelPartTables
+  Begin SubModelPartNodes
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/without_move_mesh/mesh.mdpa:179]: Nice to have: can we sort these node numbers, please?

**Review by avdg81 — COMMENTED** [review]
Thank you very much for picking up most review suggestions. When going over the changes, I've noticed that perhaps you've missed a few instances where the suggestions were also supposed to be applied. But this is really nitpicking. Overall, this PR looks ready to go.

**Comment by avdg81** [comment]
One more thing: please rerun Clang-format before merging this branch to `master`. Thanks.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp (hunk 14 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp]: Done

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp (hunk 15 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp]: Done

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp (hunk 19 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp]: Done

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp (hunk 16 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp]: Done

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp (hunk 20 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp]: Done

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp (hunk 17 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp]: Done

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp (hunk 21 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp]: Done

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp (hunk 18 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp]: Done

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp (hunk 22 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_processes/test_fix_water_pressures_above_phreatic_line.cpp]: Done

File: applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/README.md (hunk 23 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/README.md]: Good catch, done!

File: applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/common/mesh.mdpa (hunk 8 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/common/mesh.mdpa]: No particular reason, it was in the model I started creating this test case from, changed now to make it more logical

File: applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/with_move_mesh/mesh.mdpa (hunk 24 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/with_move_mesh/mesh.mdpa:178]: Done

File: applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/without_move_mesh/mesh.mdpa (hunk 27 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/without_move_mesh/mesh.mdpa:179]: Done

File: applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/without_move_mesh/ProjectParameters.json (hunk 25 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/without_move_mesh/ProjectParameters.json]: Yes, I don't know how, my bad, removed

File: applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/without_move_mesh/ProjectParameters.json (hunk 26 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/without_move_mesh/ProjectParameters.json]: Removed

**Review by rfaasse — COMMENTED** [review]
I think I processed all review comments, thanks for the thorough re-review!

**Review by avdg81 — APPROVED** [review]
Thank you very much for taking care of the review suggestions. I feel this PR is ready to be merged.

File: applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/without_move_mesh/ProjectParameters.json [hunk 28]
```diff
@@ -0,0 +1,163 @@
...
+                "MultiFileFlag": "SingleFile"
+              },
+              "file_label": "step",
+              "output_control_type": "step",
+              "output_interval": 1,
+              "body_output": true,
+              "node_output": false,
+              "skin_output": false,
+              "nodal_results": ["WATER_PRESSURE", "TOTAL_DISPLACEMENT"],
+              "gauss_point_results": []
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/without_move_mesh/ProjectParameters.json:78]: The empty table could have been removed.

**Review by WPK4FEM — APPROVED** [review]
The only comment is really nitpicking, this can be merged.

File: applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/without_move_mesh/ProjectParameters.json (hunk 28 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/tests/moving_column_with_fixed_pressure_above_phreatic_line/without_move_mesh/ProjectParameters.json:78]: Unfortunately, our settlement workflow expects this parameter to always be there (even though it's empty), so I couldn't remove this one. I think it's a good idea to fix that, such that it's no longer necessary
