### PR TITLE
[FastPR][Fluid] Fix distance modification empty partition issue

### LINKED ISSUE #8921: Segmentation fault in DistanceModificationProcess in MPI
**Description**
When using `distance_modification_process` with an empty modelpart, a segmentation fault occurs. The most usual scenario for this to happen is when using MPI and the modelpart is small relative to the whole model.

This is because in [line 126](https://github.com/KratosMultiphysics/Kratos/blob/ff0492769ee978c50c7e9e2e8cfea34fb1689ce5/applications/FluidDynamicsApplication/custom_processes/distance_modification_process.cpp#L126), an iterator to end is dereferenced when the modelpart has no nodes:
```
const auto& r_node = *mrModelPart.NodesBegin();
```

**Scope**
FluidDynamicsApplication

**To Reproduce**
Attempt to use  `Kratos::DistanceModificationProcess::ExecuteInitialize` on either of these:
- An empty modelpart.
- With MPI, a small model that cannot be distributed amongst all partitions, hence some are empty.
- With MPI, a modelpart that takes up a small proportion of the model, so that some some partitions have no nodes from that modelpart.

**Expected behavior**
Since the modelpart has no nodes, nothing should happen.

**Environment**
Should not depend on environment, but here is my particular setup:
- OS: Centos8  (With WSL, running on Windows 10)
- Branch: master
- Python 3.7

### PR DESCRIPTION
**Pull request by rubenzorrilla**
**Description**
As reported in #8921 the `DistanceModificationProcess` segfaults in presence of empty partitions. This fixes the issue. Thanks for reporting @EduardGomezEscandell.

Fixes #8921

### CODE REVIEW

File: applications/FluidDynamicsApplication/custom_processes/distance_modification_process.cpp [hunk 1]
```diff
@@ -123,8 +123,10 @@ void DistanceModificationProcess::ExecuteInitialize()
 
     if (mContinuousDistance){
         // Continuous distance modification historical variables check
-        const auto& r_node = *mrModelPart.NodesBegin();
-        KRATOS_CHECK_VARIABLE_IN_NODAL_DATA(DISTANCE, r_node);
+        if (mrModelPart.GetCommunicator().LocalMesh().NumberOfNodes() != 0) {
+            const auto& r_node = *mrModelPart.NodesBegin();
+            KRATOS_CHECK_VARIABLE_IN_NODAL_DATA(DISTANCE, r_node);
+        }
```
Comment (sunethwarna) [inline applications/FluidDynamicsApplication/custom_processes/distance_modification_process.cpp]: May be we can check it in the model part if model part is accessible? 
```suggestion
        KRATOS_ERROR_IF_NOT(mrModelPart.HasNodalSolutionStepVariable(DISTANCE)) << "DISTANCE variable not found in solution step variables list in " << mrModelPart.FullName() << ".\n";
```

Comment (philbucher) [reply applications/FluidDynamicsApplication/custom_processes/distance_modification_process.cpp]: yep thats better :+1:

**Review by sunethwarna — APPROVED** [review]
I am fine with changes :)
