### PR TITLE
Replace "typedef" by "using"

### LINKED ISSUE #10897: [GeoMechanicsApplication] "using" should be preferred to "typedef" for type aliasing.
**Description**
This is code improvements based on C++ guidelines.
Replace "typedef" with "using"

**Scope**
GeoMechanicsApplication

**To Reproduce**
SonarCloud reported a list of suggestions.

**Expected behavior**
This issues to be resolved on SonarCloud. 

**Environment**
Windows, Linux

### PR DESCRIPTION
**Pull request by mnabideltares**
**📝 Description**
"using" is preffered on "typedef" based on C++ guidelines.
SonarCloud also suggests replacing "typedef" by "using".

**🆕 Changelog**
Changed for Pw_normal_flux_condition.hpp

### CODE REVIEW

File: applications/GeoMechanicsApplication/custom_conditions/Pw_normal_flux_condition.hpp [hunk 1]
```diff
@@ -37,13 +37,13 @@ class KRATOS_API(GEO_MECHANICS_APPLICATION) PwNormalFluxCondition : public PwCon
...
-    typedef Node <3> NodeType;
-    typedef Geometry<NodeType> GeometryType;
-    typedef Geometry<NodeType>::PointsArrayType NodesArrayType;
-    typedef Vector VectorType;
-    typedef Matrix MatrixType;
+    using IndexType = std::size_t;
+    using PropertiesType = Properties;
+    using NodeType = Node<3>;
+    using GeometryType = Geometry<NodeType>;
+    using NodesArrayType = Geometry<NodeType>::PointsArrayType;
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_conditions/Pw_normal_flux_condition.hpp]: You may be able to simplify this even further:
```suggestion
    using NodesArrayType = GeometryType::PointsArrayType;
```
But please, don't take my word for it. Test it first!

If you agree and assuming it works, don't forget to check the other files for the same thing. Thanks.

File: applications/GeoMechanicsApplication/custom_elements/U_Pw_small_strain_FIC_element.hpp [hunk 2]
```diff
@@ -37,13 +37,13 @@ class KRATOS_API(GEO_MECHANICS_APPLICATION) UPwSmallStrainFICElement :
...
-    typedef Node <3> NodeType;
-    typedef Geometry<NodeType> GeometryType;
-    typedef Geometry<NodeType>::PointsArrayType NodesArrayType;
-    typedef Vector VectorType;
-    typedef Matrix MatrixType;
+    using IndexType = std::size_t;
+    using PropertiesType = Properties;
+    using NodeType = Node<3>;
+    using GeometryType = Geometry<NodeType>;
+    using NodesArrayType = Geometry<NodeType>::PointsArrayType;
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_elements/U_Pw_small_strain_FIC_element.hpp]:
```suggestion
    using NodesArrayType = GeometryType::PointsArrayType;
```

File: applications/GeoMechanicsApplication/custom_elements/U_Pw_small_strain_axisymmetric_FIC_element.hpp [hunk 3]
```diff
@@ -34,15 +34,15 @@ class KRATOS_API(GEO_MECHANICS_APPLICATION) UPwSmallStrainAxisymmetricFICElement
...
-    typedef Node<3> NodeType;
-    typedef Geometry<NodeType> GeometryType;
-    typedef Geometry<NodeType>::PointsArrayType NodesArrayType;
-    typedef Vector VectorType;
-    typedef Matrix MatrixType;
+    using IndexType = std::size_t;
+    using PropertiesType = Properties;
+    using NodeType = Node<3>;
+    using  GeometryType = Geometry<NodeType>;
+    using NodesArrayType = Geometry<NodeType>::PointsArrayType;
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_elements/U_Pw_small_strain_axisymmetric_FIC_element.hpp]:
```suggestion
    using NodesArrayType = GeometryType::PointsArrayType;
```

File: applications/GeoMechanicsApplication/custom_elements/geo_linear_truss_element_base.hpp [hunk 4]
```diff
@@ -40,16 +40,16 @@ class KRATOS_API(GEO_MECHANICS_APPLICATION) GeoTrussElementLinearBase
...
+    using BaseType  = GeoTrussElementBase<TDim,TNumNodes> ;
+    using GeometryType  = Element::GeometryType ;
+    using NodesArrayType  = Element::NodesArrayType ;
+    using PropertiesType  = Element::PropertiesType ;
+    using IndexType  = Element::IndexType ;
+    using SizeType  = Element::SizeType ;
+    using MatrixType  = Element::MatrixType ;
+    using VectorType  = Element::VectorType ;
+    using FullDofMatrixType  = typename GeoTrussElementBase<TDim,TNumNodes>::FullDofMatrixType ;
+    using FullDofVectorType  = typename GeoTrussElementBase<TDim,TNumNodes>::FullDofVectorType ;
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_elements/geo_linear_truss_element_base.hpp]: Note that there are two spaces in front of `=`. You probably intended to only have one, I guess.

File: applications/GeoMechanicsApplication/custom_elements/geo_truss_element_base.hpp [hunk 5]
```diff
@@ -47,18 +47,18 @@ class KRATOS_API(GEO_MECHANICS_APPLICATION) GeoTrussElementBase : public Element
...
+    using NodesArrayType = BaseType::NodesArrayType;
+    using PropertiesType = BaseType::PropertiesType;
+    using IndexType = BaseType::IndexType;
+    using SizeType = BaseType::SizeType;
+    using MatrixType = BaseType::MatrixType;
+    using VectorType = BaseType::VectorType;
+    using EquationIdVectorType = BaseType::EquationIdVectorType;
+    using DofsVectorType = BaseType::DofsVectorType;
+    using FullDofMatrixType = BoundedMatrix<double, TDim* TNumNodes, TDim* TNumNodes>;
+    using FullDofVectorType = BoundedVector<double, TDim* TNumNodes>;
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_elements/geo_truss_element_base.hpp]: I would remove the added spaces, since that is more confusing here. `*` is here used to express multiplication, not a raw pointer. So either have spaces on both sides of `*` or none at all.

File: applications/GeoMechanicsApplication/custom_elements/transient_Pw_element.hpp [hunk 6]
```diff
@@ -34,26 +34,26 @@ class KRATOS_API(GEO_MECHANICS_APPLICATION) TransientPwElement :
...
+    using GeometryType = Geometry<NodeType>;
+    using NodesArrayType = Geometry<NodeType>::PointsArrayType;
+    using VectorType = Vector;
+    using MatrixType = Matrix;
+    using DofsVectorType = Element::DofsVectorType;
+    using EquationIdVectorType = Element::EquationIdVectorType;
 
     /// The definition of the sizetype
-    typedef std::size_t SizeType;
+    using SizeType  = std::size_t ;
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_elements/transient_Pw_element.hpp]: Two spaces in front of `=`, whereas you probably intended to have only one.

File: applications/GeoMechanicsApplication/custom_elements/U_Pw_small_strain_element.hpp [hunk 7]
```diff
@@ -35,15 +35,15 @@ class KRATOS_API(GEO_MECHANICS_APPLICATION) UPwSmallStrainElement :
...
-    typedef Node <3> NodeType;
-    typedef Geometry<NodeType> GeometryType;
-    typedef Geometry<NodeType>::PointsArrayType NodesArrayType;
-    typedef Vector VectorType;
-    typedef Matrix MatrixType;
+    using IndexType = std::size_t;
+    using PropertiesType = Properties;
+    using NodeType = Node<3>;
+    using GeometryType = Geometry<NodeType>;
+    using NodesArrayType = Geometry<NodeType>::PointsArrayType;
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_elements/U_Pw_small_strain_element.hpp]:
```suggestion
    using NodesArrayType = GeometryType::PointsArrayType;
```

**Review by avdg81 — APPROVED** [review]
Thanks for the hard work Mohamed!
