### PR TITLE
[Core] Fix `IntegrationValuesExtrapolationToNodesProcess` for 0D elements and fixing VTK for 0D elements

### LINKED ISSUE #12415: [Core][IO] wrong output in vtk files when Point3D elements are present in model
In case Point3D elements are present in my model, all values on all integration points are inf or Nan. 

My guess is that it happens because Point3D has zero integration points and in vtk_output.cpp in WriteIntegrationScalarContainerVariable(, there is a division by the number of integration points.

### PR DESCRIPTION
**Pull request by loumalouomega**
**📝 Description**

Fix `IntegrationValuesExtrapolationToNodesProcess` for 0D elements. Just checking that is 0D element and manually computing coefficients.

Fixes https://github.com/KratosMultiphysics/Kratos/issues/12415

**🆕 Changelog**

- [Fix IntegrationValuesExtrapolationToNodesProcess for 0D elements](https://github.com/KratosMultiphysics/Kratos/commit/1dd0b5ca13a81a39ab0afd642466a2a2509c7bc2)
- [Actually fix problem](https://github.com/KratosMultiphysics/Kratos/pull/12417/commits/cbe469a7300214e74b3ccc37014f0e1e016a9bf9)

### CODE REVIEW

**Comment by aronnoordam** [comment]
I dont think this will fix https://github.com/KratosMultiphysics/Kratos/issues/12415. ( but it might fix another problem)

As when i found the problem, im not using extrapolation from gauss to nodes. Im just using: "gauss_point_variables_in_elements"

**Comment by loumalouomega** [comment]
> I dont think this will fix #12415. ( but it might fix another problem)
> 
> As when i found the problem, im not using extrapolation from gauss to nodes. Im just using: "gauss_point_variables_in_elements"

Ah, Ok, I thought uou mean in the extrapolation

**Comment by aronnoordam** [comment]
no problem, I think the fix you've made is also important

**Comment by loumalouomega** [comment]
Some 
one from the @KratosMultiphysics/technical-committee agrees with the changes?

**Comment by loumalouomega** [comment]
What is the status of this?

**Comment by aronnoordam** [comment]
@KratosMultiphysics/technical-committee ping

**Comment by roigcarlo** [comment]
Not an expert tnh, @sunethwarna ?

**Comment by aronnoordam** [comment]
@KratosMultiphysics/technical-committee any update on this? Until this pr is merged, vtk files are not usable in case the output contains point-elements

File: kratos/input_output/vtk_output.cpp [hunk 1]
```diff
@@ -899,27 +899,33 @@ void VtkOutput::WriteIntegrationScalarContainerVariable(
...
 
-    double aux_value;
-    for (auto& r_entity : rContainer) { // TODO: CalculateOnIntegrationPoints should be const methods
-        aux_value = 0.0;
-        std::vector<TVarType> aux_result(integration_points_number);
-        r_entity.CalculateOnIntegrationPoints(rVariable, aux_result, r_process_info);
-        for (const double value : aux_result) {
-            aux_value += value;
+    // Just if number of GP is greater than 0
+    if (integration_points_number > 0) {
```
Comment (sunethwarna) [inline kratos/input_output/vtk_output.cpp:909]: Will there be a possiblity to this if block to be false? In `Element` and `Condition` classes, there should be atleast one GP ryt? If so, I would remove this complexity.

File: kratos/input_output/vtk_output.cpp [hunk 2]
```diff
@@ -899,27 +899,33 @@ void VtkOutput::WriteIntegrationScalarContainerVariable(
...
+                    << rContainer.size() << "  float\n";
+
+        double aux_value;
+        for (auto& r_entity : rContainer) { // TODO: CalculateOnIntegrationPoints should be const methods
+            aux_value = 0.0;
+            std::vector<TVarType> aux_result(integration_points_number);
+            r_entity.CalculateOnIntegrationPoints(rVariable, aux_result, r_process_info);
+            for (const double value : aux_result) {
+                aux_value += value;
+            }
```
Comment (sunethwarna) [inline kratos/input_output/vtk_output.cpp:924]: I am curious, will this work for `TVarType = array_1d<double, 3>` [i.e. `std::vector<array_1d<double, 3>> aux_result`]? Did you check it?

File: kratos/input_output/vtk_output.cpp [hunk 3]
```diff
@@ -899,27 +899,33 @@ void VtkOutput::WriteIntegrationScalarContainerVariable(
...
-        for (const double value : aux_result) {
-            aux_value += value;
+    // Just if number of GP is greater than 0
+    if (integration_points_number > 0) {
+        // Auxiliary values
+        const auto& r_process_info = mrModelPart.GetProcessInfo();
+
+        // Write first line
+        rFileStream << rVariable.Name() << " 1 "
+                    << rContainer.size() << "  float\n";
```
Comment (sunethwarna) [inline kratos/input_output/vtk_output.cpp:915]: This `1` is only valid for `double` variables ryt? Woudn't it be better to support at least `array_1d<double, 3>`?

**Review by sunethwarna — COMMENTED** [review]
Could you please add tests to reflect changes to both `vtk_output.cpp` and `ntegration_values_extrapolation_to_nodes_process.cpp`. Apart from that, I have some minor comments/questions.

File: kratos/input_output/vtk_output.cpp (hunk 1 above)
Comment (loumalouomega) [reply kratos/input_output/vtk_output.cpp:909]: This is the point of this PR, elements may not have GP, particularly in 0D. You need to check the number of GP more than the geometry itself.

File: kratos/input_output/vtk_output.cpp (hunk 2 above)
Comment (loumalouomega) [reply kratos/input_output/vtk_output.cpp:924]: The method is called `WriteIntegrationScalarContainerVariable`, it will only write scalars

File: kratos/input_output/vtk_output.cpp (hunk 3 above)
Comment (loumalouomega) [reply kratos/input_output/vtk_output.cpp:915]: The method is called `WriteIntegrationScalarContainerVariable`, only works in doubles

**Comment by loumalouomega** [comment]
> Could you please add tests to reflect changes to both `vtk_output.cpp` and `ntegration_values_extrapolation_to_nodes_process.cpp`. Apart from that, I have some minor comments/questions.

I added the test for `integration_values_extrapolation_to_nodes_process.cpp`. But for  `vtk_output.cpp` is a bit more problematic.

**Comment by aronnoordam** [comment]
Is there an update on this?

**Comment by loumalouomega** [comment]
> Is there an update on this?

Ping @KratosMultiphysics/technical-committee

**Review by rubenzorrilla — APPROVED** [review]
I think we can safely merge this. Thanks @loumalouomega .
