### PR TITLE
[GeoMechanicsApplication] Shorter domain of the phreatic line causes a crash

### LINKED ISSUE #12608: [GeoMechanicsApplication] Shorter domain of the phreatic line causes a crash
If the domain of the phreatic line is shorter than the model, then it crashes. It is assumed that it is an indexing problem. On line 245 the index should be changed to -2:

Image

**It needs to be corrected in both "constant" and also in "table".**

A test needs to be added for this.

### PR DESCRIPTION
**Pull request by markelov208**
**📝 Description**
A brief description of the PR.

- fixed a return of findIndex
- added a unit test

### CODE REVIEW

File: applications/GeoMechanicsApplication/tests/cpp_tests/test_apply_constant_phreatic_multi_line_pressure_process.cpp [hunk 1]
```diff
@@ -140,4 +142,45 @@ KRATOS_TEST_CASE_IN_SUITE(ApplyConstantPhreaticMultiLinePressureProcessDoesNotTh
...
+                "gravity_direction": 1,
+                "out_of_plane_direction": 2,
+                "is_seepage": true
+            }  )"};
+
+    ApplyConstantPhreaticMultiLinePressureProcess process{r_model_part, test_parameters};
+    process.ExecuteInitialize();
+
+    KRATOS_EXPECT_DOUBLE_EQ(r_model_part.Nodes()[7].FastGetSolutionStepValue(WATER_PRESSURE, 0), -10000.0);
+    KRATOS_EXPECT_DOUBLE_EQ(r_model_part.Nodes()[8].FastGetSolutionStepValue(WATER_PRESSURE, 0), -5000.0);
```
Comment (rfaasse) [inline applications/GeoMechanicsApplication/tests/cpp_tests/test_apply_constant_phreatic_multi_line_pressure_process.cpp]: Just for my info: how do we get these numbers? I don't see a parameter for the process so I don't see what the applied water pressure is. Is there a default parameter? If there is, it might be better to instead specify it in the test_parameters for clarity

File: applications/GeoMechanicsApplication/tests/cpp_tests/test_apply_constant_phreatic_multi_line_pressure_process.cpp [hunk 2]
```diff
@@ -140,4 +142,45 @@ KRATOS_TEST_CASE_IN_SUITE(ApplyConstantPhreaticMultiLinePressureProcessDoesNotTh
         r_model_part, test_parameters))
 }
 
+KRATOS_TEST_CASE_IN_SUITE(ApplyConstantPhreaticMultiLinePressureProcessForShortDomain,
```
Comment (rfaasse) [inline applications/GeoMechanicsApplication/tests/cpp_tests/test_apply_constant_phreatic_multi_line_pressure_process.cpp]: If I understand the issue correctly, it occurs when some nodes of the domain are beyond the phreatic line, i.e. the phreatic line is 'too short'. To me, the name of the test does not really describe that situation. 
Maybe something like 
`ApplyConstantPhreaticMultilinePressureProcess_AppliesCorrectPressure_WhenPhreaticLineDoesNotSpanEntireDomain` would be more descriptive (it's quite long though, so I leave it up to you)

File: applications/GeoMechanicsApplication/custom_processes/apply_constant_phreatic_multi_line_pressure_process.cpp [hunk 3]
```diff
@@ -249,7 +249,7 @@ int ApplyConstantPhreaticMultiLinePressureProcess::findIndex(const Node& rNode)
         }
     }
 
-    return number_of_coordinates - 1;
+    return number_of_coordinates - 2;
```
Comment (rfaasse) [inline applications/GeoMechanicsApplication/custom_processes/apply_constant_phreatic_multi_line_pressure_process.cpp:252]: Nice find that we need to return the index of the 'one-before-the-last' instead of for the last point!

**Review by rfaasse — COMMENTED** [review]
Nice find and a clean, well-tested fix! I have some (more conceptual) questions about the issue and the naming of certain elements, but other than that I'd say this is ready!

File: applications/GeoMechanicsApplication/tests/cpp_tests/test_apply_constant_phreatic_multi_line_pressure_process.cpp (hunk 1 above)
Comment (markelov208) [reply applications/GeoMechanicsApplication/tests/cpp_tests/test_apply_constant_phreatic_multi_line_pressure_process.cpp]: As far as I understand this process calculates hydrostatic water pressure for a specific coordinate based on the position of the phreatic line. @WPK4FEM , is it correct?

File: applications/GeoMechanicsApplication/custom_processes/apply_constant_phreatic_multi_line_pressure_process.cpp (hunk 3 above)
Comment (markelov208) [reply applications/GeoMechanicsApplication/custom_processes/apply_constant_phreatic_multi_line_pressure_process.cpp:252]: All credits to @avdg81 ! I've just made what is written if the issue description.

File: applications/GeoMechanicsApplication/tests/cpp_tests/test_apply_constant_phreatic_multi_line_pressure_process.cpp (hunk 2 above)
Comment (markelov208) [reply applications/GeoMechanicsApplication/tests/cpp_tests/test_apply_constant_phreatic_multi_line_pressure_process.cpp]: Thank you for the suggestion. The title is long ;) but very descriptive.

**Review by markelov208 — COMMENTED** [review]
Hi Richard, many thanks for the review. Sorry my contribution is only the unit test.

File: applications/GeoMechanicsApplication/tests/cpp_tests/test_apply_constant_phreatic_multi_line_pressure_process.cpp (hunk 1 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/tests/cpp_tests/test_apply_constant_phreatic_multi_line_pressure_process.cpp]: That is correct.
The phreatic line is given by the x_, y_ and z_coordinates. The distance from r_model_part.Nodes()[7] or 8 to this line is computed looking in gravity_direction. The computed distance is multiplied with specific_weight.

Here specific_weight is gotten from the defaults. It is clearer when it is explicitly stated in the variable test_parameters. On the other hand, I would leave out out_of_plane_direction and is_seepage from the given parameters.

is_seepage steers an undocumented, not understood and untested piece of code. It is better not to raise the impression that we are testing is_seepage as we intend to remove all of it in one go when Jonathan has decided.

**Comment by rfaasse** [comment]
@markelov208 I have one quick question: in the related issue, I see it mentioned that 'It needs to be corrected in both "constant" and also in "table".', did it turn out it wasn't necessary for the table version of this process, or is it still something to be looked into?

**Comment by markelov208** [comment]
> @markelov208 I have one quick question: in the related issue, I see it mentioned that 'It needs to be corrected in both "constant" and also in "table".', did it turn out it wasn't necessary for the table version of this process, or is it still something to be looked into?

@rfaasse Thank you for pointing. Frankly speaking, I do not know. @avdg81 , please could you clarify?

**Comment by WPK4FEM** [comment]
> > @markelov208 I have one quick question: in the related issue, I see it mentioned that 'It needs to be corrected in both "constant" and also in "table".', did it turn out it wasn't necessary for the table version of this process, or is it still something to be looked into?
> 
> @rfaasse Thank you for pointing. Frankly speaking, I do not know. @avdg81 , please could you clarify?

In apply_constant_pheatic_multi_line_pressure_proces.cpp, the fixed findIndex function is only used in CalculatePressure.
In its turn CalculatePressure is used in both ApplyConstantPhreaticMultiLinePressureProcess::ExecuteInitialize() and ApplyPhreaticMultiLinePressureTableProcess::ExecuteInitializeSolutionStep(). With that knowledge, my interpretation is that the ApplyPhreaticMultiLinePressureTableProcess is fixed with the fix in ApplyConstantPhreaticMultiLinePressureProcess.

File: applications/GeoMechanicsApplication/tests/cpp_tests/test_apply_constant_phreatic_multi_line_pressure_process.cpp (hunk 1 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/tests/cpp_tests/test_apply_constant_phreatic_multi_line_pressure_process.cpp]: I agree with @rfaasse that it is not obvious how the expected values have been calculated. I can imagine that we also assert the coordinates of nodes 7 and 8, because when the nodal positions change (e.g. due to changes in the mesh generator), this test may start to fail. Also, I would prefer to see how the expected water pressures are calculated. In other words, let's be explicit about the adopted density, gravity acceleration, and water depth.

**Review by avdg81 — COMMENTED** [review]
Thank you for fixing this issue and providing a test that shows the fix works. I have one minor remark that builds on the comment by @rfaasse.

**Comment by avdg81** [comment]
> > @markelov208 I have one quick question: in the related issue, I see it mentioned that 'It needs to be corrected in both "constant" and also in "table".', did it turn out it wasn't necessary for the table version of this process, or is it still something to be looked into?
> 
> @rfaasse Thank you for pointing. Frankly speaking, I do not know. @avdg81 , please could you clarify?

I couldn't find any other occurrences of `findIndex` in directory `custom_processes`. So perhaps this was all...? I don't recall exactly why that remark has been put there.

File: applications/GeoMechanicsApplication/tests/cpp_tests/test_apply_constant_phreatic_multi_line_pressure_process.cpp (hunk 1 above)
Comment (markelov208) [reply applications/GeoMechanicsApplication/tests/cpp_tests/test_apply_constant_phreatic_multi_line_pressure_process.cpp]: Thank you for the clarification and suggestion. `specific_weight` is added, other parameters are removed.

Comment (markelov208) [reply applications/GeoMechanicsApplication/tests/cpp_tests/test_apply_constant_phreatic_multi_line_pressure_process.cpp]: As well pressure is calculated for all nodes and tested.

**Review by WPK4FEM — APPROVED** [review]
Now it is clear where the values come from as their computation is also visible in the test. Thank you.
