### PR TITLE
[Core] Fix #3597. Initializing variables

### LINKED ISSUE #3597: cpp test failing in full debug and -D_GLIBCXX_DEBUG
i have a test failure at the line

https://github.com/KratosMultiphysics/Kratos/blame/master/kratos/tests/spatial_containers/test_bins_dynamic.cpp#L254

error message is 

'''
TestDynamicBinsExistPoint__LINE__ : 251
__LINE__ : 254
__LINE__ : 257
                                                OK.

/usr/include/c++/7/debug/safe_iterator.h:374:
Error: attempt to advance a singular iterator 0 steps, which falls outside 
its valid range.

Objects involved in the operation:
    iterator @ 0x0x7ffe50e01b40 {
      type = __gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<__gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >*, std::__cxx1998::vector<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > >, std::__debug::vector<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > >*, std::__cxx1998::vector<__gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >*, std::__cxx1998::vector<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > >, std::__debug::vector<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > >, std::allocator<__gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >*, std::__cxx1998::vector<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > >, std::__debug::vector<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > > > > >, std::__debug::vector<__gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >*, std::__cxx1998::vector<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > >, std::__debug::vector<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > >, std::allocator<__gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >*, std::__cxx1998::vector<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > >, std::__debug::vector<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > > > > > (mutable iterator);
      state = singular;
    }
Aborted (core dumped)
'''

### PR DESCRIPTION
**Pull request by loumalouomega**
Fixes #3597

When I run with FullDebug and -D_GLIBCXX_DEBUG I get an clean run. But this should fix the #3597 issue

### CODE REVIEW

File: kratos/processes/compute_nodal_gradient_process.cpp [hunk 1]
```diff
@@ -224,8 +261,15 @@ ComputeNodalGradientProcess<3, component_type, NonHistorical>::ComputeNodalGradi
     KRATOS_TRY
     
     VariableUtils().CheckVariableExists(rOriginVariable, mrModelPart.Nodes());
-    KRATOS_ERROR_IF_NOT(rModelPart.Nodes().begin()->Has( rGradientVariable )) << "Missing variable " << rGradientVariable << std::endl;
```
Comment (philbucher) [inline kratos/processes/compute_nodal_gradient_process.cpp:227]: shouldn't this still be checked depending on the template-arg?

Comment (philbucher) [reply kratos/processes/compute_nodal_gradient_process.cpp:227]: I mean in case you have it historical, then this should be checked
=> Maybe you can have a small aux-function (templated) and specialized with the stuff you are adding here

Comment (loumalouomega) [reply kratos/processes/compute_nodal_gradient_process.cpp:227]: The area variable is always non-historical

**Comment by RiccardoRossi** [comment]
you just changes this behaviour right? this breaks existing code, who approved it?

**Comment by RiccardoRossi** [comment]
howevever i cannot see how you could get a clean run. are u sure you are running the "run_cpp_tests"?

it should break not only on your tests also on the other ones i pointed you to

**Comment by loumalouomega** [comment]
> howevever i cannot see how you could get a clean run. are u sure you are running the "run_cpp_tests"?
> 
> it should break not only on your tests also on the other ones i pointed you to

@RiccardoRossi I run the cpp test, and Travis run them to in FullDebug. I am sorry for that, I checked where the nodal_gradient_proccess was used before proceed

**Comment by RiccardoRossi** [comment]
but are u adding the -D_GLIBCXX_DEBUG in your compilation?

**Comment by loumalouomega** [comment]
Yes, I said in the introduction of the PR

**Comment by RiccardoRossi** [comment]
are u running with clang? that would explain -D_GLIBCXX_DEBUG not doing anything in your case

**Comment by loumalouomega** [comment]
I compile both with clang and gcc

**Review by RiccardoRossi — APPROVED** [review]
i am approving since it fixes the bug.

i am not 100% sure we want to retain the NODAL_AREA as a non historical variable always, since this is a change in behaviour from the previous one. thoughts on this? @KratosMultiphysics/implementation-committee @KratosMultiphysics/design-committee ?

**Comment by loumalouomega** [comment]
@RiccardoRossi I did a blindfix because I couldn't replicate the error. In any case we can do the AREA_NORMAL historical when the input is historical

**Comment by pooyan-dadvand** [comment]
you should check if nodes is not empty then use the begin
