### PR TITLE
[Core] Block bs with mpc

### LINKED ISSUE #4146: MoveMesh not called in LinearStrategy Predict
title says it all: the move mesh function is not called in the predict of the linear strategy.

this is wrong (and inconsistent with the behaviour of the NR strategy)

### PR DESCRIPTION
**Pull request by RiccardoRossi**
This is a proposal for a proposal for a fix solution of the current problems of block_builder and solvers when Masterslave conditions with jump are active.

what i did here is to override the current implementation with one that uses global operations on sparse matrices to apply     Trans A T dx = Trans b

**This is not necessarily the way to go.** Actually the block_builder and solver with constraints is NOT derived from the base one, but is rather an implementation per-se.
My idea is to substitute the base one by this, since this has absolutely no overhead in the case of no constraints. I also take the time to polish the implementation including changes for which there are open (and accepted) PRs.
@adityaghantasala i am open to suggestions on how this should coexist with your implementation.

In order for this to work however i need to add a new function to the base builder and solver and to call it in the strategy predict. Here it is important that we should do scheme predict, then update the database and THEN update the time derivatives and the mesh position. BTW, i fix #4146 in this PR.
I am not 100% sure this is correct in the case of complex predictions.
(It does pass existing tests)

NOTE: the current master is broken. We need to decide how to fix that asap... be it with this PR or with alternative solutions

### CODE REVIEW

**Comment by adityaghantasala** [comment]
@RiccardoRossi  Thank you very much. I will definitely have a look at this today evening !

File: kratos/solving_strategies/strategies/residualbased_linear_strategy.h [hunk 1]
```diff
@@ -358,7 +358,12 @@ class ResidualBasedLinearStrategy
 
         this->GetScheme()->Predict(BaseType::GetModelPart(), r_dof_set, rA, rDx, rb);
```
Comment (loumalouomega) [inline kratos/solving_strategies/strategies/residualbased_linear_strategy.h:359]: @RiccardoRossi This conflicts with my current PR, how I am supposed to proceed?

File: kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver_with_constraints.h [hunk 2]
```diff
@@ -1,1105 +1,1575 @@
...
+     * @param rModelPart The model part of the problem to solve
+     * @param A The LHS matrix
+     * @param b The RHS vector
+     */
+    void Build(
+        typename TSchemeType::Pointer pScheme,
+        ModelPart& rModelPart,
+        TSystemMatrixType& A,
+        TSystemVectorType& b) override
+    {
```
Comment (loumalouomega) [inline kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver_with_constraints.h]: @RiccardoRossi the build with constraints should be done only in case of constraints, otherwise call the base class Build, otherwise the code is being duplicated

**Comment by loumalouomega** [comment]
First comment, the cpp tests are not working (the builder and solver ones), It tried the branch in my computer and this is the case

**Review by loumalouomega — CHANGES_REQUESTED** [review]
I block because I consider that needs more refinement, my main points after downloading the branch are:

- The cpp tests for builder and solvers are not working anymore
- This B&S changes drastically how this class works. I recommend to create a new B&S instead of replacing the current one. Maybe the current is not 100% functional, but it has it advantages, for few MPC doesn't require to assemble any global relation matrix so it is faster.
- Almost all the code is changed, but the style guide is not followed
- There is a lot of code copy/pasted code from the base B&S. I think is more intelligent and cleaner to call the base class instead
- The name of member variables are different with respect with the elimination B&S with constraints should be unified. Additionally the common operations should go in a independent utility in order to reduce code duplication
- There is a behaviour change in the strategies, this should go in a different PR and discussed independently, otherwise will provoke a conflict with the current changes in the other PR related with the elimination B&S with constraints

**Comment by philbucher** [comment]
some comments from my side without checking the code

> I block because I consider that needs more refinement, my main points after downloading the branch are:
> 
>     * The cpp tests for builder and solvers are not working anymore
> 
>     * This B&S changes drastically how this class works. I recommend to create a new B&S instead of replacing the current one. Maybe the current is not 100% functional, but it has it advantages, for few MPC doesn't require to assemble any global relation matrix so it is faster.
> 
>     * Almost all the code is changed, but the style guide is not followed

This is not good!

>     * There is a lot of code copy/pasted code from the base B&S. I think is more intelligent and cleaner to call the base class instead

@loumalouomega the proposed B&S does NOT derive from the block-version any more. As far as I understood it is the combination of the block-B&S with and without constraints, i.e. the final version of the BlockBuilderAndSolver 
> 
>     * The name of member variables are different with respect with the elimination B&S with constraints should be unified. Additionally the common operations should go in a independent utility in order to reduce code duplication

This is a must for such an important class! this also makes testing the individual components easier

> 
>     * There is a behaviour change in the strategies, this should go in a different PR and discussed independently, otherwise will provoke a conflict with the current changes in the other PR related with the elimination B&S with constraints

I agree that this should be done in a separate PR

**Comment by loumalouomega** [comment]
> some comments from my side without checking the code
> 
> > I block because I consider that needs more refinement, my main points after downloading the branch are:
> > ```
> > * The cpp tests for builder and solvers are not working anymore
> > 
> > * This B&S changes drastically how this class works. I recommend to create a new B&S instead of replacing the current one. Maybe the current is not 100% functional, but it has it advantages, for few MPC doesn't require to assemble any global relation matrix so it is faster.
> > 
> > * Almost all the code is changed, but the style guide is not followed
> > ```
> 
> This is not good!
> 
> > ```
> > * There is a lot of code copy/pasted code from the base B&S. I think is more intelligent and cleaner to call the base class instead
> > ```
> 
> @loumalouomega the proposed B&S does NOT derive from the block-version any more. As far as I understood it is the combination of the block-B&S with and without constraints, i.e. the final version of the BlockBuilderAndSolver
> 
> > ```
> > * The name of member variables are different with respect with the elimination B&S with constraints should be unified. Additionally the common operations should go in a independent utility in order to reduce code duplication
> > ```
> 
> This is a must for such an important class! this also makes testing the individual components easier
> 
> > ```
> > * There is a behaviour change in the strategies, this should go in a different PR and discussed independently, otherwise will provoke a conflict with the current changes in the other PR related with the elimination B&S with constraints
> > ```
> 
> I agree that this should be done in a separate PR

My question was in fact why not deriving from the base block builder and solver?, we should not duplicate code, if an error is found in the block B&S we should correct here too (if we remember that the code is the same...)

File: kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver_with_constraints.h (hunk 2 above)
Comment (RiccardoRossi) [reply kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver_with_constraints.h]: @loumalouomega 

could u tell me which test is failing? 'i'll check it out.

regarding your other comments, my big concern is that we are going into a major release with two versions of the builder and solver which are actually not working, at least in the case of a constraint which includes a constant.
Apparently we have a fix for the elimination builder and solver, however as i told you this gave me an unexpected bad alloc. when i have time i will try that again.
What is worst however is that the block builder and solver is not working properly, and that we are using as default in many of our testcases.

You are completely right that as of now the version of the B&S "with constraints" has duplicated code. Actually i directly copied the base class and i modified it, taking the occasion of cleaning it up.
My suggestion would be to **replace the base class** by this one, so to have one single block_builder and solver which CAN handle constraints instead of two different ones. 
This would allow to replace the base class optionally use the version of @adityaghantasala so that the work done is not lost.

On the other hand this is not really a "behaviour change" in the sense that the behaviour is identical from the user point of view. Even the user API is completely unmodified.

I do not see any of this changes been in conflict with your modification of the elimination builder and solver, that file is not included here. What is it in conflict?

Comment (RiccardoRossi) [reply kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver_with_constraints.h]: just to add that i am very convinced that without the modification of the predict, no version can work correctly.

please note that for a nonlinear problem if we have a relation of the type

     us = T * um + b

it is different to do

    Residual(um,us) = Residual(um,  us = T*um + b)

and

     Residual(um, us ) = Residual(um, us_old) - LHS*( 0  ,   T*dus)

**Comment by RiccardoRossi** [comment]
@loumalouomega why should we have two separate class one that handles the constraint and the other one that doesn't? 

we did it for debugging/testing, however if we can have a single one it is better (provided that it has no overhead)

**Comment by loumalouomega** [comment]
@RiccardoRossi I can accept your arguments, but precisely like this is a major release better to do the things right. Please we should take care of this properly and of course minimizing the code generated.

The tests failing are:

~~~
Ran 707 of 708 test cases in 2.51353s. 2 failed:
    TestBasicDisplacementBlockBuilderAndSolverWithConstraints Failed with message: 
        Error: Check failed because std::abs((rA(2,2) - 2069000000.0000000000000000)/rA(2,2)) is greater than tolerance
in kratos/tests/cpp_tests/strategies/builder_and_solvers/test_builder_and_solver.cpp:338:virtual void Testing::TestBasicDisplacementBlockBuilderAndSolverWithConstraints::TestFunction()

    TestExtendedDisplacementBlockBuilderAndSolverWithConstraints Failed with message: 
        Error: Check failed because std::abs((rA(1,1) - 1486220957.4536478519439697)/rA(1,1)) is greater than tolerance
in kratos/tests/cpp_tests/strategies/builder_and_solvers/test_builder_and_solver.cpp:565:virtual void Testing::TestExtendedDisplacementBlockBuilderAndSolverWithConstraints::TestFunction()

~~~

**Comment by adityaghantasala** [comment]
@RiccardoRossi  if it is intended to replace the main block b&s ... why not we replace the block builder&solver ? The behavior is not changed if the functions like `BuildWithConstraints` and `BuildWithOutConstraints` are used.

File: kratos/solving_strategies/strategies/residualbased_linear_strategy.h [hunk 3]
```diff
@@ -358,6 +358,15 @@ class ResidualBasedLinearStrategy
...
 
+        if(BaseType::GetModelPart().MasterSlaveConstraints().size() != 0)
+        {
+            TSparseSpace::SetToZero(rDx);
+            p_scheme->Update(BaseType::GetModelPart(), r_dof_set, rA, rDx, rb);
```
Comment (adityaghantasala) [inline kratos/solving_strategies/strategies/residualbased_linear_strategy.h]: shouldn't these two line here should be reversed .. first apply m-s constraints and then update ??

**Comment by RiccardoRossi** [comment]
Hi Aditya,

yes, my  idea  is to unify the versions with and without constraints.

in developing it i called  it "_with_constraints" so that it would work automatically without having to change the stage etc. 


my idea really would be to have 2   distinct block builder and solvers, both able to use constraints: "mine" (actually largely benefitting of the work of Vicente, which i should acknowledge in the author's list) and "yours" which works element by element

residualbased_block_builder_and_solver (the unified one)

block_builder_and_solver_elment_by_element(or whatever name we give) which would be your versions 

regarding the modification of the BuilderAndSolver API, i do not think it really makes sense to have it in a different PR, since the new function can only work if we provide an implementation... so
@loumalouomega  @philbucher (and  techical committee) please take a look at the proposal for API change in this PR (it is only 5 files, i really don't see needed further splitting it)

File: kratos/solving_strategies/strategies/residualbased_linear_strategy.h (hunk 3 above)
Comment (RiccardoRossi) [reply kratos/solving_strategies/strategies/residualbased_linear_strategy.h]: yes this should be reversed. I did correct this in the NR  but not here. Marking as todo for tomorrow.

**Comment by adityaghantasala** [comment]
@RiccardoRossi  Then we could do it like this .. 
we do not replace the existing `_with_constraints.h`. We can do either of the following : 
- we leave the existing` _with_constraints.h` and merge your implementation into the `block_builder_and_solver.h`
- We rename the existing `_with_constraints.h` to `_element_constraints.h` and your implementation to `_with_constraints.h` (which will go away later) !

**Comment by loumalouomega** [comment]
> Hi Aditya,
> 
> yes, my idea is to unify the versions with and without constraints.
> 
> in developing it i called it "_with_constraints" so that it would work automatically without having to change the stage etc.
> 
> my idea really would be to have 2 distinct block builder and solvers, both able to use constraints: "mine" (actually largely benefitting of the work of Vicente, which i should acknowledge in the author's list) and "yours" which works element by element
> 
> residualbased_block_builder_and_solver (the unified one)
> 
> block_builder_and_solver_elment_by_element(or whatever name we give) which would be your versions
> 
> regarding the modification of the BuilderAndSolver API, i do not think it really makes sense to have it in a different PR, since the new function can only work if we provide an implementation... so
> @loumalouomega @philbucher (and techical committee) please take a look at the proposal for API change in this PR (it is only 5 files, i really don't see needed further splitting it)

Understood, let me think about it

**Comment by philbucher** [comment]
Guys why all those different versions?

I thought in the long run we want to have one block and one elimination B&S (which can natively handle constraints)?

What is the differe btw the one of Aditya and the one of Riccardo? Cannot we remove one of them?

**Comment by RiccardoRossi** [comment]
@philbucher "my" builder and solver assembles a global, sparse T matrix and does

       Ttrans * A * T * dx =Ttrans * r ( um, us(um) )

by operating on sparse matrix (using SpMM method)

Aditya's technique does something equivalent but operating element-by-element.

**Comment by RiccardoRossi** [comment]
@loumalouomega i took a look into the failing test (sorry i didn't notice it yesterday)

the failure is not really meaningful, in the sense that the only thing you verify is that the matrix is the same...which is obviously not in this case. I mean, the test should check that the solution is correct, not that the matrix has a prescribed list of corefficients...

**Comment by philbucher** [comment]
Thanks for the clearification @RiccardoRossi 
Two more questions:
1. From what I understood the one of Aditya has a problem, whereas yours works for all cases right?
2. which approach (sparse T or element by element) is better suited to be implemented in MPI?

@adityaghantasala would the B&S of Riccardo also work for Chimera?

**Comment by adityaghantasala** [comment]
@philbucher  no the builder one with global T will not work for chimera. In any case, for Chimera we might need a different B&S  (based on my implementation)  as we have to do some special things inside.

**Comment by pooyan-dadvand** [comment]
@adityaghantasala why the new version won't work for chimera? I understand that the @RiccardoRossi one is a generalization of yours with more resource requirement. Isn't it?

**Comment by adityaghantasala** [comment]
@pooyan-dadvand  the modification for chimera is not exactly  `T' * K * T` and` T'*(RHS-K*g)` it involves a few more steps.

**Comment by RiccardoRossi** [comment]
@philbucher the current implementation does not work correctly when the constraint is in the form $y=T*x+b$. It is not a fundamental design problem but rather a bug which so far could not be found. @adityaghantasala i let you comment more on this.
EpetraEXT provides mpi SpMM implementation (@jcotela used it some years back) so it should not be difficult to extend my implementation to MPI. 
Also note that the SpMM is used once per linear solver iteration by the AMG solvers (both in MPI and in OpenMP).

@adityaghantasala i also don't see why this cannot be used as basis for Chimera. 

@pooyan-dadvand I do not think it needs more resources. My implementation allocates one extra sparse matrix T, which remains allocated through the entire solution. It does need extra allocations for the triple global product, nevertheless everything is deallocated prior to calling the solve. 
Note however that a data structure equivalent to T is also used in the "element by element" version

**Comment by adityaghantasala** [comment]
@RiccardoRossi  the implementation does work for `x = Ty+c` the periodic conditions work like that (the rotation disk one) !! what is the bug is that it is not working when the initial solution is already following `x = Ty+c`  (which is the case with the RVE). 

About the Chimera, I have feeling it needs this element by element formulation this is because as I mentioned it is not exactly doing T'*K*T, we can discuss the details later on. I will be happy to make it work with the global implementation !

**Comment by RiccardoRossi** [comment]
so, we reached a conclusion this morning in @KratosMultiphysics/technical-committee 

there is no good solution, since we are at 1day from release, nevertheless we will
1 - replace the base class block_builder and solver by the one i am proposing here (and eventually bugfix it in the release branch)
2 - rename Aditya's version to "elementwise"
3 - I will use Apply and ResetSlave methods in the strategy, so that no new method is needed in the BuilderAndSolver.

the bad news is that this needs to be done between today and tomorrow. I will do my best to comply with coding standards, nevertheless the priority is to have this in release.

**Comment by philbucher** [comment]
> 3 - I will use Apply and ResetSlave methods in the strategy, so that no new method is needed in the BuilderAndSolver.

is it possible to use the [ConstraintUtilities](https://github.com/KratosMultiphysics/Kratos/blob/077456640c6423c5439d665da9c559874785ef15/kratos/utilities/constraint_utilities.h) @loumalouomega is adding in #4159 for this?

**Comment by RiccardoRossi** [comment]
@philbucher it is possible, however as of now the code looks like this:

~~~cpp
            auto it_begin = BaseType::GetModelPart().MasterSlaveConstraints().begin;

            #pragma omp parallel for firstprivate(it_begin)
            for(int i=0; i<BaseType::GetModelPart().MasterSlaveConstraints().size(); ++i)
                (it_begin+i)->ResetSlaves();

            #pragma omp parallel for firstprivate(it_begin)
            for(int i=0; i<BaseType::GetModelPart().MasterSlaveConstraints().size(); ++i)
                 (it_begin+i)->Apply();
~~~

**Comment by RiccardoRossi** [comment]
@adityaghantasala could u rename your file and have it in a branch derived from this one?

@loumalouomega could you also open a branch derived from this one and add the fixes to the elimination builder and solver in there?

my idea is to merge
1 - the Apply/reset branch
2 - this branch
3 - the branch with your corrections. 

all of this between today and tomorrow!!! (so, let's be extra careful)

**Comment by adityaghantasala** [comment]
on it !

**Comment by adityaghantasala** [comment]
@RiccardoRossi  ... the branch is named `core/renaming_b_s_constraints`

File: applications/ContactStructuralMechanicsApplication/python_scripts/contact_structural_mechanics_implicit_dynamic_solver.py [hunk 4]
```diff
@@ -153,10 +153,7 @@ def _create_builder_and_solver(self):
         if self.contact_settings["mortar_type"].GetString() != "":
             linear_solver = self.get_linear_solver()
             if self.settings["block_builder"].GetBool():
-                if self.settings["multi_point_constraints_used"].GetBool():
-                    builder_and_solver = CSMA.ContactResidualBasedBlockBuilderAndSolverWithConstraints(linear_solver)
-                else:
-                    builder_and_solver = CSMA.ContactResidualBasedBlockBuilderAndSolver(linear_solver)
+                builder_and_solver = CSMA.ContactResidualBasedBlockBuilderAndSolver(linear_solver)
```
Comment (RiccardoRossi) [inline applications/ContactStructuralMechanicsApplication/python_scripts/contact_structural_mechanics_implicit_dynamic_solver.py:156]: @loumalouomega i am not sure if i did not screw up here. Could u take a look?

File: kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver_with_constraints.h [hunk 5]
```diff
@@ -358,18 +358,18 @@ class ResidualBasedBlockBuilderAndSolverWithConstraints
         KRATOS_INFO_IF("ResidualBasedBlockBuilderAndSolverWithConstraints", ( this->GetEchoLevel() > 2)) << "Initializing lock array" << std::endl;
 
 #ifdef _OPENMP
-        if (BaseType::mlock_array.size() != 0)
+        if (mlock_array.size() != 0)
```
Comment (RiccardoRossi) [inline kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver_with_constraints.h:361]: as a comment, this should be removed and substituted by @adityaghantasala 's file.

File: kratos/solving_strategies/strategies/residualbased_linear_strategy.h (hunk 1 above)
Comment (RiccardoRossi) [reply kratos/solving_strategies/strategies/residualbased_linear_strategy.h:359]: as i commented elsewhere rebase your pr on the top of this one

File: kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver.h [hunk 6]
```diff
@@ -508,49 +533,29 @@ class ResidualBasedBlockBuilderAndSolver
...
-#endif
-        }
+        set_type dof_global_set;
+        dof_global_set.reserve(nelements*20);  
 
         KRATOS_INFO_IF("ResidualBasedBlockBuilderAndSolver", ( this->GetEchoLevel() > 2)) << "Initializing element loop" << std::endl;
 
         #pragma omp parallel firstprivate(nelements, ElementalDofList)
         {
+            set_type dofs_tmp_set;
```
Comment (RiccardoRossi) [inline kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver.h:535]: @loumalouomega take a look at how I use this set here. I think you can do the same in the elimination

File: kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver.h [hunk 7]
```diff
@@ -969,16 +945,251 @@ class ResidualBasedBlockBuilderAndSolver
...
     ///@name Protected Operations
     ///@{
+    void ConstructMasterSlaveConstraintsStructure(ModelPart &rModelPart)
+    {
+        if (rModelPart.MasterSlaveConstraints().size() > 0)
+        {
+            ProcessInfo &r_current_process_info = rModelPart.GetProcessInfo();
+
+            // Constraint initial iterator
+            const auto const_begin = rModelPart.MasterSlaveConstraints().begin();
```
Comment (RiccardoRossi) [inline kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver.h:941]: @loumalouomega also take a look at this for the elimination

**Comment by adityaghantasala** [comment]
@RiccardoRossi  should I merge the name change branch into this branch ??

**Comment by RiccardoRossi** [comment]
@adityaghantasala first i'll merge this into master, then you'll merge the name change one

@loumalouomega please approve this so that it can make it to release. We will keep it open to fix the formatting and cleanup (which will go in after the release)

**Comment by adityaghantasala** [comment]
ok .. !

File: applications/ContactStructuralMechanicsApplication/python_scripts/contact_structural_mechanics_implicit_dynamic_solver.py (hunk 4 above)
Comment (loumalouomega) [reply applications/ContactStructuralMechanicsApplication/python_scripts/contact_structural_mechanics_implicit_dynamic_solver.py:156]: Did you compile my app and run the tests?

**Review by loumalouomega — APPROVED** [review]
Well, hope not broke anything (specially my app)

**Comment by philbucher** [comment]
2tqybf

**Comment by loumalouomega** [comment]
@RiccardoRossi I am compiling, I suspect that the Contact will not even compile with your changes. One sec

**Comment by loumalouomega** [comment]
OK, it works, go ahead

**Comment by loumalouomega** [comment]
@RiccardoRossi I don't see the use of the apply

**Comment by RiccardoRossi** [comment]
I wanted to leave open this branch to have the stylistic changes, but ok, it can go in as a different branch "after release"
