### PR TITLE
[Fluid] EmbeddedSkinVisualizationProcess MPI issues

### LINKED ISSUE #7878: [EmbeddedSkinVisualizationProcess] MPI PointOutputProcess of points in visualization model part called #cores times
**Description**
When running an embedded MPI simulation with a point output (or derived classes) of a point in the skin visualization model part, several things happen, that do not happen for a fluid_computational_model_part:

- if 28 cores/ processes are used, there are 27 warnings, that the point was not found
- if the output is supposed to be written to a directory, that does not exist before starting the simulation, there are error messages, because processes try to create that directory, although one process already created it
- the output file will be overwritten 27 times, so that there is an extremely high probability that the last process that writes is a process that could not find the element, so no useful output is created (element id -1 and values 0.0)

**Bypassing the problem**
--> the last problem can be eliminated by a simple change in the PointOutputProcess, so that a process doesn't write a file at all, when it hasn't found a matching element.
--> In case the directory is created in advance and the above change is done in point_output_process.py useful output is written.

**Scope**
- EmbeddedSkinVisualizationProcess
- PointOutputProcess

**To Reproduce**
- embedded simulation with MPI
- a EmbeddedSkinVisualizationProcess to create a visualization model part
- a PointOutputProcess of a point of the visualization model part
see [visOutputMPI.zip](https://github.com/KratosMultiphysics/Kratos/files/5599109/visOutputMPI.zip)

**Expected behavior**
No warnings and no need to prevent point output file of skin visualization model part from being overwritten and no need to create output directory in advance.

**Environment**
- OS: Linux Cluster
- Branch: master
- Python 3.6

### PR DESCRIPTION
**Pull request by rubenzorrilla**
**Description**
Fix several MPI-related issues in the `EmbeddedSkinVisualizationProcess`. So far we use to (politely speaking) "circumvent" the parallel issues in this process. After these changes the entities are assigned a `PARTITION_INDEX` and the communication plan is computed. About the `PARTITION_INDEX`:
- The copied nodes keep the `PARTITION_INDEX` of the origin mesh.
- The newly created nodes are assigned with the `PARTITION_INDEX` corresponding to the current rank, which is that one of the intersected element from which they are created.
- Note that there are no new ghost nodes as the newly created nodes are not "collapsed" between the intersected elements.

@KratosMultiphysics/mpi 
I'm not fully convinced about the need of setting up the communication plan each time the visualization mesh is updated. For the specific purpose of visualization, it shouldn't be required at all. However, this silently impedes an eventual alternative usage. I'm not aware about the computational cost of this operation, if it's reasonably small I'd keep it. If this is not the case, this could have an impact in moving interfaces simulation as these require the visualization mesh to be updated each time the solution is to be printed.

@frawahl this should solve the problems you reported :wink: 

Note that #8104 needs to be merged before this.

**Changelog**
- Making the `EmbeddedSkinVisualizationProcess` fully MPI-compatible.

closes #7878

### CODE REVIEW

**Comment by rubenzorrilla** [comment]
Now that #8104 is merged this is ready to be reviewed.

File: kratos/mpi/utilities/parallel_fill_communicator.cpp [hunk 1]
```diff
@@ -475,6 +475,9 @@ void ParallelFillCommunicator::GenerateMeshes(int NeighbourPID, int MyPID, unsig
     ModelPart::NodesContainerType& r_local_nodes =
         rModelPart.GetCommunicator().LocalMesh(Color).Nodes();
     r_local_nodes.clear();
+
+    KRATOS_WATCH(rModelPart)
```
Comment (roigcarlo) [inline kratos/mpi/utilities/parallel_fill_communicator.cpp]:
```suggestion
```

File: applications/FluidDynamicsApplication/custom_processes/embedded_skin_visualization_process.h [hunk 2]
```diff
@@ -513,6 +518,16 @@ class KRATOS_API(FLUID_DYNAMICS_APPLICATION) EmbeddedSkinVisualizationProcess :
      */
     void RemoveVisualizationProperties();
 
+    template<const bool IsParallel>
```
Comment (philbucher) [inline applications/FluidDynamicsApplication/custom_processes/embedded_skin_visualization_process.h]:
```suggestion
    template<const bool IsDistributed>
```

this is what we usually use, IsParallel is ambiguous

File: applications/FluidDynamicsApplication/custom_processes/embedded_skin_visualization_process.cpp [hunk 3]
```diff
@@ -89,6 +90,17 @@ ModelPart& EmbeddedSkinVisualizationProcess::CreateAndPrepareVisualizationModelP
...
     }
 
+    // Set the origin model part as temporary communicator
+    // This is required to perform all the IsDistributed checks that appear before creating the visualization mesh
+    // This will be updated by a proper one after the creation of the visualization entities
+    r_visualization_model_part.SetCommunicator(r_origin_model_part.pGetCommunicator());
+
+    // If MPI, add the PARTITION_INDEX variable to the visualization model part variables
+    // Note that check the IsDistributed with the default communicator as the visualization model part one is not set yet
+    if (ParallelEnvironment::GetDefaultDataCommunicator().IsDistributed()) {
```
Comment (philbucher) [inline applications/FluidDynamicsApplication/custom_processes/embedded_skin_visualization_process.cpp]: don't use this, this must come from the ModelPart!

Comment (rubenzorrilla) [reply applications/FluidDynamicsApplication/custom_processes/embedded_skin_visualization_process.cpp]: I can't. As the comment explains the `ModelPart` communicator is not set so the inner pointer points to the default serial one. 
Actually, I struggle with this for a while so I'm pretty convinced in this case :smile:

File: applications/FluidDynamicsApplication/custom_processes/embedded_skin_visualization_process.h (hunk 2 above)
Comment (rubenzorrilla) [reply applications/FluidDynamicsApplication/custom_processes/embedded_skin_visualization_process.h]: OK. Changing it.

File: applications/FluidDynamicsApplication/custom_processes/embedded_skin_visualization_process.cpp (hunk 3 above)
Comment (rubenzorrilla) [reply applications/FluidDynamicsApplication/custom_processes/embedded_skin_visualization_process.cpp]: Actually I think that the `SetCommunicator` above could be avoided as it is not used anymore... I'll check again.

Comment (philbucher) [reply applications/FluidDynamicsApplication/custom_processes/embedded_skin_visualization_process.cpp]: why is it not set yet?
This then seems like a bigger design issue to me
can you point me to the place where you call this ?

File: applications/FluidDynamicsApplication/custom_processes/embedded_skin_visualization_process.cpp [hunk 4]
```diff
@@ -19,6 +19,7 @@
 #include "containers/model.h"
 #include "includes/checks.h"
 #include "includes/model_part.h"
+#include "includes/parallel_environment.h"
```
Comment (philbucher) [inline applications/FluidDynamicsApplication/custom_processes/embedded_skin_visualization_process.cpp:22]:
```suggestion
```

File: applications/FluidDynamicsApplication/custom_processes/embedded_skin_visualization_process.cpp [hunk 5]
```diff
@@ -89,6 +90,17 @@ ModelPart& EmbeddedSkinVisualizationProcess::CreateAndPrepareVisualizationModelP
...
     }
 
+    // Set the origin model part as temporary communicator
+    // This is required to perform all the IsDistributed checks that appear before creating the visualization mesh
+    // Note that these checks might be required outside this process (i.e. in the creation of the visualization mesh output)
+    // This will be updated by a proper one by the ParallelFillCommunicator after the creation of the visualization entities
+    r_visualization_model_part.SetCommunicator(r_origin_model_part.pGetCommunicator());
+
+    // If MPI, add the PARTITION_INDEX variable to the visualization model part variables
+    if (r_visualization_model_part.GetCommunicator().IsDistributed()) {
```
Comment (philbucher) [inline applications/FluidDynamicsApplication/custom_processes/embedded_skin_visualization_process.cpp]:
```suggestion
    if (r_visualization_model_part.IsDistributed()) {
```

File: applications/FluidDynamicsApplication/custom_processes/embedded_skin_visualization_process.cpp (hunk 3 above)
Comment (rubenzorrilla) [reply applications/FluidDynamicsApplication/custom_processes/embedded_skin_visualization_process.cpp]: (forget about the previous comment; the communicator needs to be set to perform the `IsDistributed` checks outside this process)

It is not set because the visualization model part is created in here and cannot be created at the solver level. As the visualization mesh contains different entities than that ones of the parent model part, the communicator should be different. However the communication plan cannot be established until we create such new entities (even though there are no ghost nodes so far). Until these new entities are created we need a "fake" communicator in order to do the `IsDistributed` checks (these are for instance required in order to create the output processes of the visualization mesh).

File: applications/FluidDynamicsApplication/custom_processes/embedded_skin_visualization_process.cpp (hunk 5 above)
Comment (rubenzorrilla) [reply applications/FluidDynamicsApplication/custom_processes/embedded_skin_visualization_process.cpp]: I wasn't aware of this one. Thanks!

File: applications/FluidDynamicsApplication/custom_processes/embedded_skin_visualization_process.cpp (hunk 4 above)
Comment (rubenzorrilla) [reply applications/FluidDynamicsApplication/custom_processes/embedded_skin_visualization_process.cpp:22]: This is required in order to call the factory of the `ParallelFillCommunicator`.

Comment (philbucher) [reply applications/FluidDynamicsApplication/custom_processes/embedded_skin_visualization_process.cpp:22]: ups :)

**Comment by philbucher** [comment]
looks good to me, thx!

**Review by philbucher — APPROVED** [review]
