### PR TITLE
[FastPR][Structural] Skip test and verbosity in structural mechanics application tests

### LINKED ISSUE #12160: [StructuralMechanics] Tests Requiring ConstitutiveLawsApp
The [TotalLagrangianMixedVolumetricStrainElementBonetPatch](https://github.com/KratosMultiphysics/Kratos/blob/5c47d94ef271aad3ce998a8ed5f6f6accf1c2d92/applications/StructuralMechanicsApplication/tests/cpp_tests/test_total_lagrangian_mixed_volumetric_strain_element.cpp#L178) test segfaults if `ConstitutiveLawsApplication` is not available. @rubenzorrilla can you please fix it and check the rest of the tests in `StructuralMechanicsApplication` as well?

### PR DESCRIPTION
**Pull request by rubenzorrilla**
**📝 Description**
This fixes #12160. Besides, I took the chance to clean the terminal output as some of the tests were way too verbose. In order to get the clean output,  #12161 must be merged first.

Closes #12160.

### CODE REVIEW

**Review by loumalouomega — DISMISSED** [review]

File: applications/StructuralMechanicsApplication/tests/cpp_tests/test_total_lagrangian_mixed_volumetric_strain_element.cpp [hunk 1]
```diff
@@ -144,6 +144,11 @@ namespace Kratos::Testing
      */
     KRATOS_TEST_CASE_IN_SUITE(TotalLagrangianMixedVolumetricStrainElementBonetPatch, KratosStructuralMechanicsFastSuite)
     {
+        // Skip the test if the constitutive law is not available (i.e. the ConstitutiveLawsApplication is not compiled)
+        if (!KratosComponents<ConstitutiveLaw>::Has("HyperElasticPlaneStrain2DLaw")) {
```
Comment (philbucher) [inline applications/StructuralMechanicsApplication/tests/cpp_tests/test_total_lagrangian_mixed_volumetric_strain_element.cpp]: perhaps use a variable for the name of the law, just in case it changes in the future

Comment (rubenzorrilla) [reply applications/StructuralMechanicsApplication/tests/cpp_tests/test_total_lagrangian_mixed_volumetric_strain_element.cpp]: Done.

**Review by philbucher — APPROVED** [review]
