### PR TITLE
Fix warnings about initialization of member variables.

### LINKED ISSUE #10857: [GeoMechanicsApplication] Fix warnings about initialization of member variables

### PR DESCRIPTION
**Pull request by huhaas**
**📝 Description**
Fix warnings and simplify retention law parameter logic.

**🆕 Changelog**
- Fix warnings and simplify retention law parameter logic.

### CODE REVIEW

File: applications/GeoMechanicsApplication/custom_retention/retention_law.h [hunk 1]
```diff
@@ -68,80 +68,61 @@ class KRATOS_API(GEO_MECHANICS_APPLICATION) RetentionLaw
...
 
         * PROCESS PROPERTIES:
-        * @param mpCurrentProcessInfo pointer to current ProcessInfo instance (input data)
+        * @param mrCurrentProcessInfo reference to current ProcessInfo instance (input data)
 
         */
 
     private:
         /*** NOTE: Member Pointers are used only to point to a certain variable, 
          * no "new" or "malloc" can be used for this Parameters ***/
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_retention/retention_law.h]: I believe this comment no longer applies here, so please remove it. Thanks.

File: applications/GeoMechanicsApplication/custom_strategies/schemes/newmark_quasistatic_U_Pw_scheme.hpp [hunk 2]
```diff
@@ -519,15 +520,15 @@ class NewmarkQuasistaticUPwScheme : public Scheme<TSparseSpace,TDenseSpace>
...
-    double mDeltaTime;
+    double mDeltaTime = 0.0;
 
 //----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-    NewmarkQuasistaticUPwScheme() : Scheme<TSparseSpace,TDenseSpace>()
+    NewmarkQuasistaticUPwScheme()
+        : Scheme<TSparseSpace,TDenseSpace>()
+        , mBeta(0.25)
+        , mGamma(0.5)
+        , mTheta(0.5)
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_strategies/schemes/newmark_quasistatic_U_Pw_scheme.hpp]: What about moving these default values to the declaration of the class (just like you did for `mDeltaTime`)? In that way we ensure that the data members are always initialized properly (including any future constructors). As a bonus, it also puts all default values in a single location, which makes looking them up easy. If you do that, you probably also don't need to explicitly define the default constructor (the compiler can generate it for you).

**Review by avdg81 — DISMISSED** [review]
Nice cleanup Hugo. Just two minor remarks from my side. Please merge when you're done.

File: applications/GeoMechanicsApplication/custom_strategies/schemes/newmark_quasistatic_U_Pw_scheme.hpp [hunk 3]
```diff
@@ -514,21 +512,10 @@ class NewmarkQuasistaticUPwScheme : public Scheme<TSparseSpace,TDenseSpace>
 
 protected:
 
-    /// Member Variables
-
     double mBeta;
     double mGamma;
     double mTheta;
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_strategies/schemes/newmark_quasistatic_U_Pw_scheme.hpp]: I would prefer to give these default values (based on what used to be set in the default constructor), just so we can't forget to initialize them (in particular when new constructors are added).

**Review by avdg81 — DISMISSED** [review]

**Review by avdg81 — APPROVED** [review]
