### PR TITLE
Fixing tests

### LINKED ISSUE #6998: Error in MPI-Core test TestPointerCommunicatorIndexConsistence
maybe related to #6979?

~~~
#0  0x00007ffff014bc84 in __gnu_cxx::__normal_iterator<std::pair<Kratos::VariableData const*, void*>*, std::vector<std::pair<Kratos::VariableData const*, void*>, std::allocator<std::pair<Kratos::VariableData const*, void*> > > >::__normal_iterator (this=0x7fffffff8c28, 
    __i=<error reading variable>)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/stl_iterator.h:783
No locals.
#1  0x00007ffff014bb5c in std::vector<std::pair<Kratos::VariableData const*, void*>, std::allocator<std::pair<Kratos::VariableData const*, void*> > >::begin (this=0x88)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/stl_vector.h:564
No locals.

#2  0x00007ffff01ab881 in Kratos::DataValueContainer::GetValue<int> (this=0x80, rThisVariable=
    ...)
    at /home/philipp/software/Kratos_MasterBranch/kratos/containers/data_value_container.h:214
        i = non-dereferenceable iterator for std::vector
        p_source_variable = 0x7fffffff8d30
#3  0x00007fffefbd10e6 in Kratos::Node<3ul, Kratos::Dof<double> >::GetValue<Kratos::Variable<int> > (this=0x0, rThisVariable=...)
    at /home/philipp/software/Kratos_MasterBranch/kratos/includes/node.h:592
No locals.
#4  0x00007fffefd3b428 in Kratos::Testing::TestPointerCommunicatorIndexConsistence::TestFunction()::$_10::operator()(Kratos::GlobalPointer<Kratos::Node<3ul, Kratos::Dof<double> > >&) const
    (this=0x7fffffff9450, gp=...)
    at /home/philipp/software/Kratos_MasterBranch/kratos/mpi/tests/sources/test_pointer_communicator.cpp:126
No locals.
#5  0x00007fffefd3b1b5 in Kratos::GlobalPointerCommunicator<Kratos::Node<3ul, Kratos::Dof<double> > >::Update<Kratos::Testing::TestPointerCommunicatorIndexConsistence::TestFunction()::$_10>(Kratos::Testing::TestPointerCommunicatorIndexConsistence::TestFunction()::$_10&, Kratos::GlobalPointersUnorderedMap<Kratos::Node<3ul, Kratos::Dof<double> >, Kratos::ResultsProxy<Kratos::Node<3ul, Kratos::Dof<double> >, Kratos::Testing::TestPointerCommunicatorIndexConsistence::TestFunction()::$_10>::TSendType>&) (this=0x7fffffff94c8, rUserFunctor=..., rNonLocalData=warning: RTTI symbol not found for class 'Kratos::GlobalPointersUnorderedMap<Kratos::Node<3ul, Kratos::Dof<double> >, double>'
...)
    at /home/philipp/software/Kratos_MasterBranch/kratos/utilities/pointer_communicator.h:236
        gp = @0x13bb380: {mDataPointer = 0x0, mRank = 0}
        __range5 = std::vector of length 2, capacity 2 = {{mDataPointer = 0x0, mRank = 0}, {
            mDataPointer = 0x13b5340, mRank = 0}}
        __begin0 = {mDataPointer = 0x0, mRank = 0}
        __end0 = {mDataPointer = 0x100000000, mRank = 529}
        gps_to_be_sent = warning: RTTI symbol not found for class 'Kratos::GlobalPointersVector<Kratos::Node<3ul, Kratos::Dof<double> > >'
~~~

### PR DESCRIPTION
**Pull request by roigcarlo**
Fixes #6998. Was not related to #6979, it had several problems that did not appear because I forgot to run in mpi when I did the test sorry :S

### CODE REVIEW

File: kratos/mpi/tests/sources/test_pointer_communicator.cpp [hunk 1]
```diff
@@ -123,7 +123,7 @@ KRATOS_TEST_CASE_IN_SUITE(PointerCommunicatorIndexConsistence, KratosMPICoreFast
 
     auto double_proxy = pointer_comm.Apply(
         [](GlobalPointer< Node<3> >& gp)->double {
-            return gp->GetValue(PARTITION_INDEX);
```
Comment (philbucher) [inline kratos/mpi/tests/sources/test_pointer_communicator.cpp:126]: :D

Comment (roigcarlo) [reply kratos/mpi/tests/sources/test_pointer_communicator.cpp:126]: Those dangerous copy pastes...
</img>

**Review by philbucher — APPROVED** [review]
perfect thx
