### PR TITLE
Fix triangle aabb intersection

### LINKED ISSUE #2840: Kratos ParticleMechanics fails when running large problems
I recently run my test examples for large static cantilevers and found them failing -  it should not fail since I didn't touch the corresponding constitutive law nor any related conditions within the last two months. After some checks, I found out that it only fails for large problems with relatively more elements, i.e. when I run problems with fewer meshes, it works! Since they are static problems, the time discretization issue is not present. Also, I checked that the same problems occur when OpenMP is deactivated. Therefore, it is not an issue of parallelism.

The same test cases used to work before, e.g. once I validated PR #2387. With the recent code, the nonlinear iteration of that example does not converge and the obtained ratio and absolute norm grow excessively. Please find **problem_1.gid** attached.
[problem_1.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/2366982/problem_1.gid.zip)

Please also find **problem_2_fine.gid** and **problem_2_coarse.gid** attached to see that the finer problem is not working while the coarser one is okay.
[problem_2_coarse.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/2366986/problem_2_coarse.gid.zip)
[problem_2_fine.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/2366988/problem_2_fine.gid.zip)

I am guessing that the problem might be either in BuilderandSolver, ConvergenceCriteria or LinearSolver. I asked @loumalouomega and @roigcarlo about this issue and they suggested me to tag @RiccardoRossi and @adityaghantasala in case they can help me with this. 

Thank you very much in advance! I would appreciate if anyone can give me any suggestions.

### PR DESCRIPTION
**Pull request by roigcarlo**
I still want to make some more tests, but this should fix #2840

Also there were tests that were testing if there was NO intersection, but non to check a normal intersection. I added those.

### CODE REVIEW

**Comment by bodhinandach** [comment]
Thanks a lot, @roigcarlo for the help. If you want, I can try to run some local tests of particlemechanics to see the improvements made in general.

File: kratos/geometries/triangle_3d_3.h [hunk 1]
```diff
@@ -2210,11 +2210,11 @@ template<class TPointType> class Triangle3D3
         if(min_max.first>rBoxHalfSize[0] || min_max.second<-rBoxHalfSize[0]) return false;
 
         // test in Y-direction
-        min_max = std::minmax({vert0[0], vert1[0], vert2[0]});
+        min_max = std::minmax({vert0[1], vert1[1], vert2[1]});
```
Comment (miguelmaso) [inline kratos/geometries/triangle_3d_3.h:2213]: Does triangle2D3 needs the same change?

File: kratos/geometries/hexahedra_3d_8.h [hunk 2]
```diff
@@ -609,17 +609,17 @@ template<class TPointType> class Hexahedra3D8 : public Geometry<TPointType>
...
         // Check if faces have intersection
-        if(Quadrilateral3D4Type(this->pGetPoint(0),this->pGetPoint(1), this->pGetPoint(2), this->pGetPoint(3)).HasIntersection(rLowPoint, rHighPoint))
-            return true;
-        if(Quadrilateral3D4Type(this->pGetPoint(4),this->pGetPoint(5), this->pGetPoint(6), this->pGetPoint(7)).HasIntersection(rLowPoint, rHighPoint))
+        if(Quadrilateral3D4Type(this->pGetPoint(3),this->pGetPoint(2), this->pGetPoint(1), this->pGetPoint(0)).HasIntersection(rLowPoint, rHighPoint))
             return true;
         if(Quadrilateral3D4Type(this->pGetPoint(0),this->pGetPoint(1), this->pGetPoint(5), this->pGetPoint(4)).HasIntersection(rLowPoint, rHighPoint))
             return true;
-        if(Quadrilateral3D4Type(this->pGetPoint(3),this->pGetPoint(2), this->pGetPoint(6), this->pGetPoint(7)).HasIntersection(rLowPoint, rHighPoint))
+        if(Quadrilateral3D4Type(this->pGetPoint(2),this->pGetPoint(6), this->pGetPoint(5), this->pGetPoint(1)).HasIntersection(rLowPoint, rHighPoint))
```
Comment (loumalouomega) [inline kratos/geometries/hexahedra_3d_8.h:616]: I assumed you checked, but the thing of reconstruct face geometries scares me. Take into account that depending of the application some people expect inside normals and others outside normals

File: kratos/tests/geometries/test_triangle_3d_3.cpp [hunk 3]
```diff
@@ -502,6 +502,126 @@ namespace Testing
...
+     * Test an overlaping non-cubic box and triangle (intersects a triangle edge) HasIntersection
+     */
+    KRATOS_TEST_CASE_IN_SUITE(Triangle3D3AABoxIntersectionNonEquilaterElongXPlaneX, KratosCoreGeometriesFastSuite) {
+		Triangle3D3<Point > triangle_1(
+			GeneratePoint<Node<3> >(0.55, -0.25, 0.25),
+			GeneratePoint<Node<3> >(0.50, -0.25, 0.75),
+			GeneratePoint<Node<3> >(0.50,  0.25, 0.25)
+		);
+        
+        auto aabb_min = GeneratePoint<Node<3>>(0.0, 0.0, 0.0);
```
Comment (loumalouomega) [inline kratos/tests/geometries/test_triangle_3d_3.cpp]:
```suggestion
                auto aabb_min = GeneratePoint<Node<3>>(0.0, 0.0, 0.0);
```

File: kratos/tests/geometries/test_triangle_3d_3.cpp [hunk 4]
```diff
@@ -502,6 +502,126 @@ namespace Testing
...
+        auto aabb_max = GeneratePoint<Node<3>>(2.0, 1.0, 1.0);
```
Comment (loumalouomega) [inline kratos/tests/geometries/test_triangle_3d_3.cpp]:
```suggestion
                auto aabb_max = GeneratePoint<Node<3>>(2.0, 1.0, 1.0);
```

Tabs

File: kratos/geometries/triangle_3d_3.h (hunk 1 above)
Comment (miguelmaso) [reply kratos/geometries/triangle_3d_3.h:2213]: I see, triangle2D3 seems to be ok

File: kratos/tests/geometries/test_triangle_3d_3.cpp [hunk 5]
```diff
@@ -502,6 +502,126 @@ namespace Testing
...
+    }
+    
+    KRATOS_TEST_CASE_IN_SUITE(Triangle3D3AABoxIntersectionNonEquilaterElongXPlaneY, KratosCoreGeometriesFastSuite) {
+		Triangle3D3<Point > triangle_1(
+			GeneratePoint<Node<3> >(-0.25, 0.50, 0.25),
+			GeneratePoint<Node<3> >(-0.25, 0.55, 0.75),
+			GeneratePoint<Node<3> >( 0.25, 0.50, 0.25)
+		);
+        
+        auto aabb_min = GeneratePoint<Node<3>>(0.0, 0.0, 0.0);
```
Comment (loumalouomega) [inline kratos/tests/geometries/test_triangle_3d_3.cpp]:
```suggestion
                auto aabb_min = GeneratePoint<Node<3>>(0.0, 0.0, 0.0);
```

**Review by miguelmaso — DISMISSED** [review]
Thank you

File: kratos/tests/geometries/test_triangle_3d_3.cpp [hunk 6]
```diff
@@ -502,6 +502,126 @@ namespace Testing
...
+        auto aabb_max = GeneratePoint<Node<3>>(2.0, 1.0, 1.0);
```
Comment (loumalouomega) [inline kratos/tests/geometries/test_triangle_3d_3.cpp]:
```suggestion
                auto aabb_max = GeneratePoint<Node<3>>(2.0, 1.0, 1.0);
```

File: kratos/tests/geometries/test_triangle_3d_3.cpp [hunk 7]
```diff
@@ -502,6 +502,126 @@ namespace Testing
...
+    }
+    
+    KRATOS_TEST_CASE_IN_SUITE(Triangle3D3AABoxIntersectionNonEquilaterElongXPlaneZ, KratosCoreGeometriesFastSuite) {
+		Triangle3D3<Point > triangle_1(
+			GeneratePoint<Node<3> >(-0.25, 0.25, 0.50),
+			GeneratePoint<Node<3> >(-0.25, 0.75, 0.50),
+			GeneratePoint<Node<3> >( 0.25, 0.25, 0.55)
+		);
+        
+        auto aabb_min = GeneratePoint<Node<3>>(0.0, 0.0, 0.0);
```
Comment (loumalouomega) [inline kratos/tests/geometries/test_triangle_3d_3.cpp]:
```suggestion
                auto aabb_min = GeneratePoint<Node<3>>(0.0, 0.0, 0.0);
```

File: kratos/tests/geometries/test_triangle_3d_3.cpp [hunk 8]
```diff
@@ -502,6 +502,126 @@ namespace Testing
...
+        auto aabb_max = GeneratePoint<Node<3>>(2.0, 1.0, 1.0);
```
Comment (loumalouomega) [inline kratos/tests/geometries/test_triangle_3d_3.cpp]:
```suggestion
                auto aabb_max = GeneratePoint<Node<3>>(2.0, 1.0, 1.0);
```

File: kratos/tests/geometries/test_triangle_3d_3.cpp [hunk 9]
```diff
@@ -502,6 +502,126 @@ namespace Testing
...
+    }
+
+    KRATOS_TEST_CASE_IN_SUITE(Triangle3D3AABoxIntersectionNonEquilaterElongYPlaneX, KratosCoreGeometriesFastSuite) {
+		Triangle3D3<Point > triangle_1(
+			GeneratePoint<Node<3> >(0.55, -0.25, 0.25),
+			GeneratePoint<Node<3> >(0.50, -0.25, 0.75),
+			GeneratePoint<Node<3> >(0.50,  0.25, 0.25)
+		);
+        
+        auto aabb_min = GeneratePoint<Node<3>>(0.0, 0.0, 0.0);
```
Comment (loumalouomega) [inline kratos/tests/geometries/test_triangle_3d_3.cpp]:
```suggestion
                auto aabb_min = GeneratePoint<Node<3>>(0.0, 0.0, 0.0);
```

File: kratos/tests/geometries/test_triangle_3d_3.cpp [hunk 10]
```diff
@@ -502,6 +502,126 @@ namespace Testing
...
+        auto aabb_max = GeneratePoint<Node<3>>(1.0, 2.0, 1.0);
```
Comment (loumalouomega) [inline kratos/tests/geometries/test_triangle_3d_3.cpp]:
```suggestion
                auto aabb_max = GeneratePoint<Node<3>>(1.0, 2.0, 1.0);
```

**Review by bodhinandach — APPROVED** [review]
I am good with this! Many thanks @roigcarlo

File: kratos/geometries/hexahedra_3d_8.h (hunk 2 above)
Comment (roigcarlo) [reply kratos/geometries/hexahedra_3d_8.h:616]: Well that's one of the changes I wanted to discuss. This is only used when calculating the intersection, and the code that actually give access to the normal returns always the faces pointing in the right direction. So I assumes it was ok to change it here as it does not affect the results of the TriBoxOverlap function down into the triangle3d3

Comment (RiccardoRossi) [reply kratos/geometries/hexahedra_3d_8.h:616]: uff, you sure of this change?

Comment (roigcarlo) [reply kratos/geometries/hexahedra_3d_8.h:616]: It can be reverted as it does not affect the result at all. Its only "cosmetic", see the getFaces function.

Comment (roigcarlo) [reply kratos/geometries/hexahedra_3d_8.h:616]: Also It is a little bit more efficient as it does not need to hold the array of faces, just the one which is being tested.

**Comment by roigcarlo** [comment]
Merging, thx @loumalouomega for the cosmetics!

**Comment by AndreasWinterstein** [comment]
@pooyan-dadvand our cluster is running again. I will check if this fixes the problem with the ML solver (#2829). This will take some days, since the cluster is quite full at the moment and this means I will have to wait a few days till my job runs.
