### PR TITLE
[GeoMechanicsApplication] Fix DGeoFlow logging

### LINKED ISSUE #13077: [GeoMechanicsApplication] Fix missing log output in DGeoFlow
It was found that DGeoFlow did not log anything at all when running an analysis, despite passing a valid logging callback.

### PR DESCRIPTION
**Pull request by avdg81**
**📝 Description**

DGeoFlow did not log anything, since a newly constructed stream object was used when flushing the output. We now use the log buffer that is being filled throughout the analysis run. This required some changes to the signatures of a few member functions (to pass on the intended buffer).

### CODE REVIEW

File: applications/GeoMechanicsApplication/custom_constitutive/incremental_linear_elastic_law.cpp [hunk 1]
```diff
@@ -10,8 +10,8 @@
 //  Main authors:    Wijtze Pieter Kikstra
 //                   Richard Faasse
 
-#include "constitutive_law_dimension.h"
 #include "custom_constitutive/incremental_linear_elastic_law.h"
+#include "constitutive_law_dimension.h"
```
Comment (rfaasse) [inline applications/GeoMechanicsApplication/custom_constitutive/incremental_linear_elastic_law.cpp:14]: Did kp format do this? I would expect alphabetical ordering

File: applications/GeoMechanicsApplication/custom_workflows/dgeoflow.cpp [hunk 2]
```diff
@@ -307,7 +307,7 @@ int KratosExecute::ExecuteFlowAnalysis(std::string_view         WorkingDirectory
         bool has_piping = rCriticalHeadInfo.stepCriticalHead != 0;
 
         if (rCallBackFunctions.ShouldCancel()) {
-            HandleCleanUp(rCallBackFunctions, pOutput);
+            HandleCleanUp(rCallBackFunctions, pOutput, kratos_log_buffer);
```
Comment (rfaasse) [inline applications/GeoMechanicsApplication/custom_workflows/dgeoflow.cpp:310]: Do you think it would be preferable to make the buffer a member such that we can just access it where needed?

**Review by rfaasse — APPROVED** [review]
Nice catch and clear fix! No blockers from my side, just a suggestion, but I leave it up to you to use it, or leave it 👍

File: applications/GeoMechanicsApplication/custom_constitutive/incremental_linear_elastic_law.cpp (hunk 1 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/custom_constitutive/incremental_linear_elastic_law.cpp:14]: Yes, this is produced by Clang-format 19.1.0 (which is being used by `kp format`). Perhaps this will be fixed in a newer release. I won't change it, since each run of Clang-format will revert that manual change.

File: applications/GeoMechanicsApplication/custom_workflows/dgeoflow.cpp (hunk 2 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/custom_workflows/dgeoflow.cpp:310]: Let's consider this option when we work out a more elegant way of handling the logging in DGeoFlow.
