### PR TITLE
[GeoMechanicsApplication] Fix corner return mapping

### LINKED ISSUE #14155: [GeoMechanicsApplication] Fix the return mapping in Mohr-Coulomb tension cutoff
### Description

There is inconsistency found in the return mapping for tension-cutoff return zone, and the tension-cutoff corner point zone.

The principal stress components sigma1 and sigma3 are mapped back, while sigma2 is kept constant. However, sigma2 needs to be mapped back for tension-cutoff. 
This issue was found because the code gives different results than Plaxis.

1. Fix the return mapping of sigma2, for tension-cutoff
2. Add unit test(s)
3. Update the documentation

### PR DESCRIPTION
**Pull request by avdg81**
**📝 Description**
Fixed the corner return mapping.

**🆕 Changelog**
- Fixed the intermediate principal stress for corner return mapping.
- Fixed the averaging procedure by applying the mean value to two consecutive elements rather than a single one.
- Added a unit test to cover the case where the trial stress is on the degenerated tensile cut-off return zone.
- Corrected the unit tests for the corner return mapping.
- Renamed several member function parameters from `rElasticMatrix` to `rElasticConstitutiveTensor`.

### CODE REVIEW

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp [hunk 1]
```diff
@@ -791,7 +828,7 @@ KRATOS_TEST_CASE_IN_SUITE(MohrCoulombWithTensionCutOff_CalculateMaterialResponse
         cohesion, friction_angle, strain_vector_finalized, stress_vector_finalized, strain_vector);
     // Assert
     const auto expected_cauchy_stress_vector = UblasUtilities::CreateVector(
-        {9.9999999660952608e+02, -2.5265113546536796e+02, 3.4117047235541349e+01, 6.5169629648695174e-02});
+        {999.999996609523, -252.651135465368, -252.651138855841, 0.065169629648695});
```
Comment (markelov208) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp:815]: A perfect match with the example64 solution.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp [hunk 2]
```diff
@@ -770,7 +807,7 @@ KRATOS_TEST_CASE_IN_SUITE(MohrCoulombWithTensionCutOff_CalculateMaterialResponse
         cohesion, friction_angle, strain_vector_finalized, stress_vector_finalized, strain_vector);
     // Assert
     const auto expected_cauchy_stress_vector = UblasUtilities::CreateVector(
-        {9.9999999981240751e+02, -2.5265113866824933e+02, 3.4252114252393994e+01, 1.5329308790913803e-02});
+        {999.999999812408, -252.651138668248, -252.65113885584, 0.0153293087909138});
```
Comment (markelov208) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp:794]: A perfect match with the example64 solution.

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp [hunk 3]
```diff
@@ -184,49 +180,112 @@ Geo::PrincipalStresses CoulombWithTensionCutOffImpl::ReturnStressAtTensionApexRe
...
+    if (const auto apex = mCoulombYieldSurface.CalculateApex(); mTensionCutOff.GetTensileStrength() > apex)
+        return StressStrainUtilities::TransformSigmaTauToPrincipalStresses(Geo::SigmaTau{apex, 0.0},
+                                                                           rTrialPrincipalStresses);
+
+    const auto dG_dSigma_Coulomb =
+        mCoulombYieldSurface.DerivativeOfFlowFunction(rTrialPrincipalStresses, AveragingType);
+    const auto principal_stress_correction_Coulomb =
+        Geo::PrincipalStresses{prod(subrange(rElasticConstitutiveTensor, 0, 3, 0, 3), dG_dSigma_Coulomb)};
+    const auto traction_correction_Coulomb =
+        StressStrainUtilities::TransformPrincipalStressesToSigmaTau(principal_stress_correction_Coulomb);
```
Comment (markelov208) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp]: I think these lines can be a free/lambda function and it can be applied to lines 252-257.

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp [hunk 4]
```diff
@@ -184,49 +180,112 @@ Geo::PrincipalStresses CoulombWithTensionCutOffImpl::ReturnStressAtTensionApexRe
...
+        mTensionCutOff.DerivativeOfFlowFunction(rTrialPrincipalStresses, AveragingType);
+    const auto principal_stress_correction_tension_cut_off = Geo::PrincipalStresses{
+        prod(subrange(rElasticConstitutiveTensor, 0, 3, 0, 3), dG_dSigma_tension_cut_off)};
+    const auto traction_correction_tension_cut_off =
+        StressStrainUtilities::TransformPrincipalStressesToSigmaTau(principal_stress_correction_tension_cut_off);
+
+    const auto v = std::array{std::sin(mCoulombYieldSurface.GetFrictionAngleInRadians()), 1.0};
+    const auto A = UblasUtilities::CreateMatrix(
+        {{std::inner_product(traction_correction_Coulomb.Values().begin(),
+                             traction_correction_Coulomb.Values().end(), v.begin(), 0.0),
```
Comment (markelov208) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp]: I think these two lines can be a lambda function to simplify reading.

File: applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp [hunk 5]
```diff
@@ -48,11 +48,11 @@ Geo::PrincipalStresses AveragePrincipalStressComponents(const Geo::PrincipalStre
     switch (AveragingType) {
         using enum Geo::PrincipalStresses::AveragingType;
     case LOWEST_PRINCIPAL_STRESSES:
-        std::fill(result.Values().begin(), result.Values().begin() + 1,
+        std::fill(result.Values().begin(), result.Values().begin() + std::ptrdiff_t{2},
                   (rPrincipalStressVector.Values()[0] + rPrincipalStressVector.Values()[1]) * 0.5);
         break;
     case HIGHEST_PRINCIPAL_STRESSES:
-        std::fill(result.Values().begin() + 1, result.Values().begin() + 2,
+        std::fill(result.Values().end() - std::ptrdiff_t{2}, result.Values().end(),
```
Comment (markelov208) [inline applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp:55]: I think it is very difficult to catch it using FORTRAN mind. ;) rPrincipalStressVector has a size of 3. Would it be easier to use `std::fill(result.Values().begin() + 1, result.Values().end()`?

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp [hunk 6]
```diff
@@ -197,23 +197,26 @@ KRATOS_TEST_CASE_IN_SUITE(MohrCoulombWithTensionCutOff_CalculateMaterialResponse
...
-    Vector cauchy_stress_vector(4);
-    cauchy_stress_vector <<= 18.0, 8.0, -2.0, 0.0;
-    Vector expected_cauchy_stress_vector(4);
-    expected_cauchy_stress_vector <<= 10.0, 8.0, -1.5179192179966735, 0.0;
-    KRATOS_EXPECT_VECTOR_NEAR(CalculateMappedStressVector(cauchy_stress_vector, parameters, law),
-                              expected_cauchy_stress_vector, Defaults::absolute_tolerance);
-
-    cauchy_stress_vector <<= 24.0, 8.0, -8.0, 0.0;
-    expected_cauchy_stress_vector <<= 10.0, 8.0, -1.5179192179966735, 0.0;
+    // The following stress vector will exercise the "no averaging" type
```
Comment (markelov208) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp:198]: That is really useful comment. Others as well.

**Review by markelov208 — DISMISSED** [review]
Hi Anne, thank you very much for implementing the corner point stress. I have non-blocking comments on `ReturnStressAtCornerPoint`. Hope it can be changed to reduce the duplication and simplify reading.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp (hunk 1 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp:815]: That's great to hear, thanks.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp (hunk 2 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp:794]: That's great to hear, thanks.

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp (hunk 4 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp]: I have replaced these two lines by a call to `MathUtils<>::Dot`, which indeed makes it easier to read 👍 . Thanks for your suggestion.

File: applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp (hunk 5 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/custom_constitutive/mohr_coulomb_with_tension_cutoff.cpp:55]: Thanks for sharing your point of view. What we are trying to express here is to copy the averaged value to either the first two elements of the vector or the last two elements, depending on the averaging type. I can understand that with a Fortran background the solution that we've implemented is perhaps not the first one that comes to mind. However, I still feel that the way it is expressed now more clearly shows this symmetry, especially since this is C++ rather than Fortran ;-)

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp [hunk 7]
```diff
@@ -173,7 +173,7 @@ KRATOS_TEST_CASE_IN_SUITE(MohrCoulombWithTensionCutOff_CalculateMaterialResponse
 
     // HIGHEST_PRINCIPAL_STRESSES as averaging type
     cauchy_stress_vector <<= 12.0, -12.0, -16.0, 0.0;
-    expected_cauchy_stress_vector <<= 6.78245195822, -13.3912259791, -13.3912259791, 0.0;
+    expected_cauchy_stress_vector <<= 7.259759295835, -11.6298796479175, -11.6298796479175, 0.0;
```
Comment (mnabideltares) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp]: Please change it to Ublas::CreateVector

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp (hunk 3 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp]: I have moved the code of the first two statements to a local helper function (`CalculatePrincipalStressCorrection`). I deliberately left out the third statement, since I need `principal_stress_correction_Coulomb` as well as `traction_correction_Coulomb` further down in the function body. Do these changes sufficiently account for your suggestion?

**Comment by avdg81** [comment]
> Hi Anne, thank you very much for implementing the corner point stress. I have non-blocking comments on `ReturnStressAtCornerPoint`. Hope it can be changed to reduce the duplication and simplify reading.

Hi Gennady,
Thanks a lot for your suggestions and comparing the updated results with other results. I'd like to share the credits that you gave with Wijtze Pieter, since we've worked on this PR together. 😄

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp [hunk 8]
```diff
@@ -184,49 +181,110 @@ Geo::PrincipalStresses CoulombWithTensionCutOffImpl::ReturnStressAtTensionApexRe
...
+                                  lambda * prod(subrange(rElasticConstitutiveTensor, 0, 3, 0, 3),
+                                                derivative_of_flow_function)};
+}
+
+Geo::PrincipalStresses CoulombWithTensionCutOffImpl::ReturnStressAtCornerPoint(
+    const Geo::PrincipalStresses&         rTrialPrincipalStresses,
+    const Matrix&                         rElasticConstitutiveTensor,
+    Geo::PrincipalStresses::AveragingType AveragingType) const
+{
+    if (const auto apex = mCoulombYieldSurface.CalculateApex(); mTensionCutOff.GetTensileStrength() > apex)
```
Comment (mnabideltares) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp]: Here, CalculateApex returns "double", which is the sigma component of the coordinate, while tau = 0.
Although it is a taste design choice, but I think it is more suitable to return everything which gets out of sigma-tau diagram, in Geo::SigmaTau form. This is also valid for PrinsipalStresses, and PQ diagrams.

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp (hunk 3 above)
Comment (markelov208) [reply applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp]: Thank you for this change.

**Review by markelov208 — DISMISSED** [review]
Hi Anne and Wijtze Pieter, thank you very much for the quick fix.

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp [hunk 9]
```diff
@@ -184,49 +181,110 @@ Geo::PrincipalStresses CoulombWithTensionCutOffImpl::ReturnStressAtTensionApexRe
...
+        prod(subrange(rElasticConstitutiveTensor, 0, 3, 0, 3), dG_dSigma_tension_cut_off)};
+    const auto traction_correction_tension_cut_off =
+        StressStrainUtilities::TransformPrincipalStressesToSigmaTau(principal_stress_correction_tension_cut_off);
+
+    const auto v = std::array{std::sin(mCoulombYieldSurface.GetFrictionAngleInRadians()), 1.0};
+    const auto A =
+        UblasUtilities::CreateMatrix({{MathUtils<>::Dot(traction_correction_Coulomb.Values(), v),
+                                       MathUtils<>::Dot(traction_correction_tension_cut_off.Values(), v)},
+                                      {principal_stress_correction_Coulomb.Values()[0],
+                                       principal_stress_correction_tension_cut_off.Values()[0]}});
```
Comment (mnabideltares) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp:278]: The naming does not follow the guidline and it is not clear enough. Maybe change it to matrix_A?

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp [hunk 10]
```diff
@@ -184,49 +181,110 @@ Geo::PrincipalStresses CoulombWithTensionCutOffImpl::ReturnStressAtTensionApexRe
...
+
+    auto A_inverse   = Matrix(2, 2);
+    auto determinant = 0.0;
```
Comment (mnabideltares) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp:281]: inverse_matrix_A ?

**Review by markelov208 — DISMISSED** [review]

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp [hunk 11]
```diff
@@ -184,49 +181,110 @@ Geo::PrincipalStresses CoulombWithTensionCutOffImpl::ReturnStressAtTensionApexRe
...
+    MathUtils<>::InvertMatrix2(A, A_inverse, determinant);
+
+    const auto b = UblasUtilities::CreateVector(
+        {-1.0 * mCoulombYieldSurface.YieldFunctionValue(rTrialPrincipalStresses),
+         -1.0 * mTensionCutOff.YieldFunctionValue(rTrialPrincipalStresses)});
```
Comment (mnabideltares) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp:286]: const auto b = UblasUtilities::CreateVector(
        {- mCoulombYieldSurface.YieldFunctionValue(rTrialPrincipalStresses),
         - mTensionCutOff.YieldFunctionValue(rTrialPrincipalStresses)});

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp [hunk 12]
```diff
@@ -184,49 +181,110 @@ Geo::PrincipalStresses CoulombWithTensionCutOffImpl::ReturnStressAtTensionApexRe
...
+    const auto plastic_multipliers = Vector{prod(A_inverse, b)};
+
+    return Geo::PrincipalStresses{
+        rTrialPrincipalStresses.Values() +
+        plastic_multipliers[0] * principal_stress_correction_Coulomb.Values() +
+        plastic_multipliers[1] * principal_stress_correction_tension_cut_off.Values()};
```
Comment (mnabideltares) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp]: As we already have operator "+" for PrincipalStresses, this can be written as:

return rTrialPrincipalStresses + Geo::PrincipalStresses{plastic_multipliers[0] * principal_stress_correction_Coulomb.Values() +
        plastic_multipliers[1] * principal_stress_correction_tension_cut_off.Values()};

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp [hunk 13]
```diff
@@ -184,49 +181,110 @@ Geo::PrincipalStresses CoulombWithTensionCutOffImpl::ReturnStressAtTensionApexRe
...
+}
+
+Geo::SigmaTau CoulombWithTensionCutOffImpl::ReturnStressAtCornerPoint(
+    const Geo::SigmaTau&, const Matrix&, Geo::PrincipalStresses::AveragingType AveragingType) const
+{
+    KRATOS_DEBUG_ERROR_IF(AveragingType != Geo::PrincipalStresses::AveragingType::NO_AVERAGING) << "When returning the traction to the corner point, averaging of principal stresses is not supported\n";
```
Comment (mnabideltares) [inline applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp:298]: Just for my curiosity: Will it be supported later?

**Review by mnabideltares — COMMENTED** [review]
@avdg81 
Thank you for this nice work.
I have some minor comments.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp (hunk 7 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/tests/cpp_tests/custom_constitutive/test_mohr_coulomb_with_tension_cutoff.cpp]: I suspect that you've been looking at an older version of this branch, since the current version of this file contains no more occurrences of operator `<<=`. Can you please double-check that you've looked at the current version of the branch? Thanks.

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp (hunk 8 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp]: Thanks for your suggestion. Yes, we may consider to do that, I agree. But I won't make it part of this PR then.

**Edit:** now that I'm making other changes too, let me take care of this suggestion right away.

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp (hunk 11 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp:286]: We've discussed about this before. Again, we feel that just `-` is easily overlooked. Since `-1.0 *` stands out much more, we've decided to use that notation. I cannot imagine this will result in a performance penalty, so in that case we should definitely choose the clearest notation.

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp (hunk 12 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp]: Good catch. Now that we have `operator+` at our disposal, we should use it. Changed this occurrence as well as two other occurrences. 👍

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp (hunk 13 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp:298]: I'm not sure actually. Perhaps @WPK4FEM has an idea about this?

Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp:298]: Averaging is typical for the principal stress approach. In the SigmaTau route that we have for interface stress state, it should never be used.

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp (hunk 9 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp:278]: You're right about this name not following the Kratos Style Guide. However, if we would change this to a lower case 'a', no one would recognize it as a name for a matrix, since the common convention is to use uppercase letters for them. I disagree with adding the prefix `matrix_`, since that's just adding type info to a variable name. Also, how this variable is being initialized (using `UblasUtilities::CreateMatrix`) gives a very clear hint that `A` will be a matrix.

If you can think of a better name that describes the meaning of this matrix, I'm happy to hear about it. 👍

File: applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp (hunk 10 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/custom_constitutive/coulomb_with_tension_cut_off_impl.cpp:281]: Here I have the same reasoning as for the case of matrix `A`.

**Comment by avdg81** [comment]
> @avdg81 Thank you for this nice work. I have some minor comments.

Hi Mohamed,
Thanks a lot for your suggestions. Now that they have been processed, can you please let me know whether you're satisfied with the changes? Thanks.

**Review by mnabideltares — APPROVED** [review]
Ok to me
