### PR TITLE
[Core] Adding normal computation in Triangle2D3

### LINKED ISSUE #5945: [MappingApplication] Is it possible to map variables of two modelparts with different types of elements?
Hi,

I am opening this issue since I would like to use the MappingApplication to project values from a 2-D triangular mesh, to a 2-D linear mesh (map the values on the nodes of the triangles to the nodes of the lines). 

So far I have been using a custom process, but before opening a PR to merge it I would like to see if I can use what is already there in the MappingApplication. The function I am using is this one (not in the master):
https://github.com/KratosMultiphysics/Kratos/blob/cps/adding-embedded-adjoint/applications/CompressiblePotentialFlowApplication/custom_processes/project_sensitivity_to_skin_process.cpp
This projects the NORMAL_SENSITIVITY values on a triangular mesh to a 2-d linear mesh. This process direclty multiplies these scalar values to the normals of the skin, to finally write the SHAPE_SENSITIVITY on the skin. Here are some pictures to clarify:
image
These are the scalar values (on a triangular mesh), which are projected to the skin (on a linear mesh, directly computed as vectors using the skin normal).
image

I have tried using the MappingApplication with `nearest_element_mapper`  and I get the following error:

running:
```
mapping_parameters = KratosMultiphysics.Parameters("""{
	"mapper_type": "nearest_element",
	"interface_submodel_part_origin": "Parts_Parts_Auto1",
	"echo_level" : 4
	}""")
mapper = KratosMultiphysics.MappingApplication.MapperFactory.CreateMapper(model_part,skin_model_part,mapping_parameters)
mapper.Map(KratosMultiphysics.NORMAL_SENSITIVITY,KratosMultiphysics.NORMAL_SENSITIVITY)
```

```
RuntimeError: Error: Remember the normal can be computed just in geometries with a local dimension: 2smaller than the spatial dimension: 2

in kratos/geometries/geometry.h:982:array_1d<double, 3> Geometry<TPointType>::Normal(const CoordinatesArrayType&) const [with TPointType = Node<3>; Geometry<TPointType>::CoordinatesArrayType = array_1d<double, 3>]
```
Which makes me think that maybe the triangle-line combination is not supported?

Using the `nearest_neighbor_mapper ` works, but as you know it does not interpolate the values. 

Is it possible to do this operation in the MappingApplication or should I stick with the custom process?

Thanks!

### PR DESCRIPTION
**Pull request by marcnunezc**
Adding the computation of the triangle 2d3 normal (same implementation as triangle3d3) and a test. This addresses #5945

closes #5945

### CODE REVIEW

**Review by philbucher — DISMISSED** [review]
looks good to me, thx
does #5945 work with this?

**Comment by loumalouomega** [comment]
> 
> 
> Adding the computation of the triangle 2d3 normal (same implementation as triangle3d3) and a test. This addresses #5945
> 
> closes #5945

I don't understand, what means the normal in 2D for a 2D geometry?, is in order to check thsat is correctly oriented?

File: kratos/tests/cpp_tests/geometries/test_triangle_2d_3.cpp [hunk 1]
```diff
@@ -574,5 +574,38 @@ namespace Testing {
...
+        auto geom = GeneratePointsRightTriangle2D3();
+        Point::CoordinatesArrayType LocalCoord;
+        LocalCoord.clear();
+        auto normal = geom->Normal(LocalCoord);
+
+        KRATOS_CHECK_NEAR(normal[0], 0.0, TOLERANCE);
+        KRATOS_CHECK_NEAR(normal[1], 0.0, TOLERANCE);
+        KRATOS_CHECK_NEAR(normal[2], 0.5, TOLERANCE);
+
+        array_1d<double, 3> cross_norm(3, 0.0);
```
Comment (loumalouomega) [inline kratos/tests/cpp_tests/geometries/test_triangle_2d_3.cpp]: This constructor will be removed with AMatrix

**Review by loumalouomega — COMMENTED** [review]
Look my comment

**Comment by marcnunezc** [comment]
> Look my comment

I have updated both 2d and 3d tests to avoid using that constructor. 

> > Adding the computation of the triangle 2d3 normal (same implementation as triangle3d3) and a test. This addresses #5945
> > closes #5945
> 
> I don't understand, what means the normal in 2D for a 2D geometry?, is in order to check thsat is correctly oriented?

It is the same normal as in 3D, so it gives the normal of the 2D plane. 
I think @philbucher can give a more detailed answer, but the MappingApplication is expecting the triangle2d3 geometry to have the normal implementation to do the mapping.

**Comment by philbucher** [comment]
its the out-of-plane vector you can use to project

**Review by philbucher — APPROVED** [review]
