### PR TITLE
[GeoMechanicsApplication] Fix bug in time step mechanism C++ workflow

### LINKED ISSUE #14153: [GeoMechanicsApplication] Bug in time step mechanism C++ workflow
Given the attached project in the following comment, I expected a single linear calculation to take place it is a K0 step. 

The output confirms that it has converged at the end time step, i.e. -0.2

Image

However the stage fails with the following error:

_KratosGeoSettlement: Error: Delta time (2.77556e-17) is smaller than default minimum allowable value 1e-05_

It should also be noted that the input start time contains a rounding error: thus startTime = -0.30000000000000004.

### PR DESCRIPTION
**Pull request by rfaasse**
**📝 Description**
In the time stepping scheme in the C++ workflow, avoiding a small step was not done for the very first time-step, which resulted in an error for cases where the first increment of a stage would result in a very small subsequent step to get to the end-time.

This PR adds the same upscaling functionality that was there for subsequent steps also in the constructor, to check the very first step of a stage.

Changelog:
- The first time step is now checked for avoiding a small last step
- An integration test for the C++ workflow is added
- Unit tests are added

### CODE REVIEW

File: applications/GeoMechanicsApplication/custom_workflows/adaptive_time_incrementor.cpp [hunk 1]
```diff
@@ -37,7 +37,7 @@ AdaptiveTimeIncrementor::AdaptiveTimeIncrementor(double                StartTime
       mMaxNumOfCycles(MaxNumOfCycles),
       mReductionFactor(ReductionFactor),
       mIncreaseFactor(IncreaseFactor),
-      mUserMinDeltaTime(std::move(UserMinDeltaTime)),
+      mUserMinDeltaTime(UserMinDeltaTime),
```
Comment (rfaasse) [inline applications/GeoMechanicsApplication/custom_workflows/adaptive_time_incrementor.cpp:40]: Clang-tidy mentioned the move of a std::optional<double> was not necessary

File: applications/GeoMechanicsApplication/custom_workflows/adaptive_time_incrementor.cpp [hunk 2]
```diff
@@ -57,6 +57,9 @@ AdaptiveTimeIncrementor::AdaptiveTimeIncrementor(double                StartTime
         << "Increase factor must be greater than or equal to 1, but got " << mIncreaseFactor;
     KRATOS_ERROR_IF(MaxTimeStepFactor < 1.0)
         << "Max_delta_time_factor must be greater than or equal to 1, but got " << MaxTimeStepFactor;
+
+    CorrectDeltaTimeToEndTime(StartTime);
```
Comment (rfaasse) [inline applications/GeoMechanicsApplication/custom_workflows/adaptive_time_incrementor.cpp]: This is the actual fix, we need to check at construction to make sure the first increment is correct

File: applications/GeoMechanicsApplication/custom_workflows/adaptive_time_incrementor.cpp [hunk 3]
```diff
@@ -77,33 +80,46 @@ double AdaptiveTimeIncrementor::GetIncrement() const { return mDeltaTime; }
...
+
+double AdaptiveTimeIncrementor::GetMinimumDeltaTime() const
+{
+    constexpr auto delta_time_as_fraction_of_time_span = 0.0001;
+    const auto     default_min_delta_time =
+        std::min(mInitialDeltaTime, delta_time_as_fraction_of_time_span * mTimeSpan);
+    return mUserMinDeltaTime.value_or(default_min_delta_time);
+}
+
+void AdaptiveTimeIncrementor::CorrectDeltaTimeToEndTime(double StartOfIncrement)
```
Comment (rfaasse) [inline applications/GeoMechanicsApplication/custom_workflows/adaptive_time_incrementor.cpp]: I'm struggling with the name of this function. What it does is if the deltatime would result in either a very small next step (difference smaller than min delta time) or if it would result in going beyond the end time, it corrects it to be the end time. If you have any suggestions for a better name, let me know

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_workflows/test_time_incrementor.cpp [hunk 4]
```diff
@@ -422,32 +421,49 @@ KRATOS_TEST_CASE_IN_SUITE(ScaleIncrementToAvoidExtraSmallTimeStep, KratosGeoMech
 {
     AdaptiveTimeIncrementorSettings settings; // with EndTime = 8.0
     settings.StartIncrement          = 7.9999;
+    settings.UserMinDeltaTime        = 0.01;
     auto time_incrementor            = MakeAdaptiveTimeIncrementor(settings);
     auto previous_state              = TimeStepEndState{};
     previous_state.convergence_state = TimeStepEndState::ConvergenceState::converged;
 
-    time_incrementor.PostTimeStepExecution(previous_state);
```
Comment (rfaasse) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_workflows/test_time_incrementor.cpp:429]: Removing this line makes sure we don't do the correction that's in PostTimeStepExecution, to make sure a first step is also corrected

File: applications/GeoMechanicsApplication/custom_workflows/adaptive_time_incrementor.cpp (hunk 3 above)
Comment (WPK4FEM) [reply applications/GeoMechanicsApplication/custom_workflows/adaptive_time_incrementor.cpp]: CorrectDeltaTimeToReachEndTime or AdaptDeltaTimeToAvoidSmallNextIncrement

File: applications/GeoMechanicsApplication/tests/test_GeoMechanicsApplication.py [hunk 5]
```diff
@@ -125,7 +125,8 @@ def AssembleTestSuites():
                         KratosGeoMechanicsHydraulicHeads,
                         KratosGeoMechanicsSetMovingLoadProcessTests,
                         KratosGeoMechanicsSurfaceInterfaceElementTests,
-                        KratosGeoMechanicsAvoidSmallEndStepTests,
+                        KratosGeoMechanicsAvoidSmallTimeStepPythonRoute,
+                        KratosGeoMechanicsAvoidSmallTimeStepCppRoute,
```
Comment (WPK4FEM) [inline applications/GeoMechanicsApplication/tests/test_GeoMechanicsApplication.py]: I find the SmallEndStep more descriptive than SmallTimeStep

File: applications/GeoMechanicsApplication/custom_workflows/adaptive_time_incrementor.cpp (hunk 3 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/custom_workflows/adaptive_time_incrementor.cpp]: These are both better than the current name, but they don't capture the 'preventing overshooting the end time' part of the function, so I'm still wondering if there's an even better name somewhere

File: applications/GeoMechanicsApplication/custom_workflows/adaptive_time_incrementor.cpp [hunk 6]
```diff
@@ -77,33 +80,46 @@ double AdaptiveTimeIncrementor::GetIncrement() const { return mDeltaTime; }
...
     }
 
-    KRATOS_ERROR_IF(mDeltaTime < mUserMinDeltaTime.value_or(default_min_delta_time))
-        << "Delta time (" << mDeltaTime << ") is smaller than "
-        << (mUserMinDeltaTime ? "given" : "default") << " minimum allowable value "
-        << mUserMinDeltaTime.value_or(default_min_delta_time) << std::endl;
+    CheckMinimumDeltaTime(mDeltaTime);
+}
+
+void AdaptiveTimeIncrementor::CheckMinimumDeltaTime(double DeltaTime) const
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_workflows/adaptive_time_incrementor.cpp]: As far as I can see, this member function is always called given the data member `mDeltaTime`. Since it has access to this data directly, we don't really need to pass it through the argument list. Since it's a `private` member function, client code won't be able to call it directly. Would it be cleaner to have an empty argument list and fetch the required data directly inside the function body?

File: applications/GeoMechanicsApplication/custom_workflows/adaptive_time_incrementor.cpp (hunk 3 above)
Comment (avdg81) [reply applications/GeoMechanicsApplication/custom_workflows/adaptive_time_incrementor.cpp]: I agree that it's very hard to put the exact checks in words without ending up with extremely long function names. What about `AdaptDeltaTimeIfNeeded`? It doesn't spell out when it's needed, just that the time increment may or may not be modified after doing some checks.

File: applications/GeoMechanicsApplication/tests/cpp_tests/custom_workflows/test_time_incrementor.cpp [hunk 7]
```diff
@@ -457,7 +471,7 @@ KRATOS_TEST_CASE_IN_SUITE(HalfTimeStepAtNonConverged, KratosGeoMechanicsFastSuit
     auto time_incrementor            = MakeAdaptiveTimeIncrementor(settings);
     auto previous_state              = TimeStepEndState{};
     previous_state.convergence_state = TimeStepEndState::ConvergenceState::non_converged;
-    previous_state.time              = 8.0;
+    previous_state.time              = 0.0;
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/tests/cpp_tests/custom_workflows/test_time_incrementor.cpp:474]: Good catch!

**Review by avdg81 — COMMENTED** [review]
Dear @rfaasse and @WPK4FEM,
Thanks a lot for preparing this bug fix. The changes were clear, and are well-covered by the new unit tests and integration test. I only have a few minor comments, none of them being blocking. I feel this PR is almost ready to go 👍

File: applications/GeoMechanicsApplication/custom_workflows/adaptive_time_incrementor.cpp (hunk 6 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/custom_workflows/adaptive_time_incrementor.cpp]: Agreed, done!

File: applications/GeoMechanicsApplication/custom_workflows/adaptive_time_incrementor.cpp (hunk 3 above)
Comment (rfaasse) [reply applications/GeoMechanicsApplication/custom_workflows/adaptive_time_incrementor.cpp]: I think that's a good idea (since I don't see a way to capture both reasons in the function name). I did add a comment within the function to explain what it's doing. Hope that helps

File: applications/GeoMechanicsApplication/custom_workflows/adaptive_time_incrementor.cpp [hunk 8]
```diff
@@ -115,8 +116,12 @@ double AdaptiveTimeIncrementor::GetMinimumDeltaTime() const
     return mUserMinDeltaTime.value_or(default_min_delta_time);
 }
 
-void AdaptiveTimeIncrementor::CorrectDeltaTimeToEndTime(double StartOfIncrement)
+void AdaptiveTimeIncrementor::AdaptDeltaTimeIfNeeded(double StartOfIncrement)
 {
+    // If the delta time would result in
+    //  a. the next step exceeding the end time or
+    //  b. having too small a remaining time step
+    // then the delta time is chosen such that the next step ends exactly at the end time.
```
Comment (avdg81) [inline applications/GeoMechanicsApplication/custom_workflows/adaptive_time_incrementor.cpp:124]: Very clear, thank you.

**Review by avdg81 — APPROVED** [review]
Thanks a lot for processing the review suggestions. To me, this PR looks good to go.

**Review by markelov208 — COMMENTED** [review]
Hi Richard, thank you for fixing this bug and adding unit and integration tests. The PR looks very good for me.
