### PR TITLE
[Core] Fix Average Element size calculator for 2D9N

### LINKED ISSUE #12300: Element size for quadratic elements
**Description**
I saw that the way of calculating the `AverageSizeCalculator` has been changed in line 866 of `element_size_calculator.cpp`. I remember that I modified it in past because Kratos assigned for biquadratic elements half of the size that bilinear ones (you can try with a regular structured mesh). Have you checked that the method `rGeometry.Length()` still corrects the underestimation of element size?

**Scope**
KratosCore

### PR DESCRIPTION
**Pull request by sunethwarna**
**📝 Description**
As mentioned in the title, this corrects the average length calculation of the `Quad2D9N` to be consistent with the linear computation.

closes #12300 

**🆕 Changelog**
- Fixes average legth computation of `Quad2D9N`

### CODE REVIEW

**Comment by jgonzalezusua** [comment]
Thanks for the fix @sunethwarna. After passing the checks I will approve it.

File: kratos/utilities/element_size_calculator.cpp [hunk 1]
```diff
@@ -867,7 +867,7 @@ double ElementSizeCalculator<2,4>::AverageElementSizeDerivative(
 template<>
 double ElementSizeCalculator<2,9>::AverageElementSize(const Geometry<Node >& rGeometry)
 {
-    return rGeometry.Length();
+    return rGeometry.Length() * 2.0;
```
Comment (philbucher) [inline kratos/utilities/element_size_calculator.cpp:871]: hm so thats a hack for the hack?
Can you add a comment? :D

**Review by philbucher — COMMENTED** [review]
also if this passes, it is missing a test

given that this is a bit hackish, can you please add a test?

**Comment by sunethwarna** [comment]
I am planning to add tests for all the geometries :)

**Comment by jgonzalezusua** [comment]
Will you add the tests in this PR or in future?

**Comment by sunethwarna** [comment]
I will do it with the same PR, but not today. Would you be able to wait until this Friday?

**Comment by jgonzalezusua** [comment]
Sure, we can wait.

File: kratos/utilities/element_size_calculator.cpp (hunk 1 above)
Comment (sunethwarna) [reply kratos/utilities/element_size_calculator.cpp:871]: done :)

**Comment by sunethwarna** [comment]
Ok I have added the tests. @philbucher @jgonzalezusua :)

**Review by philbucher — APPROVED** [review]

**Review by jgonzalezusua — APPROVED** [review]
