### PR TITLE
[Core] Initialize RHS and Dx before solution

### LINKED ISSUE #6773: Unititialize variable in BlockBuilderAndSolver
@RiccardoRossi as I mentioned in our meeting. here is the valgrind error:

~~~valgrind
==28838== Thread 15:
==28838== Conditional jump or move depends on uninitialised value(s)
==28838==    at 0x164AF052: Kratos::ResidualBasedBlockBuilderAndSolver<Kratos::UblasSpace<double, boost::numeric::ublas::compressed_matrix<double, boost::numeric::ublas::basic_row_major<unsigned long, long>, 0ul, boost::numeric::ublas::unbounded_array<unsigned long, std::allocator<unsigned long> >, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > >, boost::numeric::ublas::vector<double, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > > >, Kratos::UblasSpace<double, boost::numeric::ublas::matrix<double, boost::numeric::ublas::basic_row_major<unsigned long, long>, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > >, boost::numeric::ublas::vector<double, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > > >, Kratos::LinearSolver<Kratos::UblasSpace<double, boost::numeric::ublas::compressed_matrix<double, boost::numeric::ublas::basic_row_major<unsigned long, long>, 0ul, boost::numeric::ublas::unbounded_array<unsigned long, std::allocator<unsigned long> >, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > >, boost::numeric::ublas::vector<double, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > > >, Kratos::UblasSpace<double, boost::numeric::ublas::matrix<double, boost::numeric::ublas::basic_row_major<unsigned long, long>, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > >, boost::numeric::ublas::vector<double, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > > >, Kratos::Reorderer<Kratos::UblasSpace<double, boost::numeric::ublas::compressed_matrix<double, boost::numeric::ublas::basic_row_major<unsigned long, long>, 0ul, boost::numeric::ublas::unbounded_array<unsigned long, std::allocator<unsigned long> >, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > >, boost::numeric::ublas::vector<double, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > > >, Kratos::UblasSpace<double, boost::numeric::ublas::matrix<double, boost::numeric::ublas::basic_row_major<unsigned long, long>, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > >, boost::numeric::ublas::vector<double, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > > > > > >::Assemble(boost::numeric::ublas::compressed_matrix<double, boost::numeric::ublas::basic_row_major<unsigned long, long>, 0ul, boost::numeric::ublas::unbounded_array<unsigned long, std::allocator<unsigned long> >, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > >&, boost::numeric::ublas::vector<double, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > >&, boost::numeric::ublas::matrix<double, boost::numeric::ublas::basic_row_major<unsigned long, long>, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > > const&, boost::numeric::ublas::vector<double, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > > const&, std::vector<unsigned long, std::allocator<unsigned long> >&) (residualbased_block_builder_and_solver.h:1495)
==28838==    by 0x164C00AE: Kratos::ResidualBasedBlockBuilderAndSolver<Kratos::UblasSpace<double, boost::numeric::ublas::compressed_matrix<double, boost::numeric::ublas::basic_row_major<unsigned long, long>, 0ul, boost::numeric::ublas::unbounded_array<unsigned long, std::allocator<unsigned long> >, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > >, boost::numeric::ublas::vector<double, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > > >, Kratos::UblasSpace<double, boost::numeric::ublas::matrix<double, boost::numeric::ublas::basic_row_major<unsigned long, long>, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > >, boost::numeric::ublas::vector<double, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > > >, Kratos::LinearSolver<Kratos::UblasSpace<double, boost::numeric::ublas::compressed_matrix<double, boost::numeric::ublas::basic_row_major<unsigned long, long>, 0ul, boost::numeric::ublas::unbounded_array<unsigned long, std::allocator<unsigned long> >, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > >, boost::numeric::ublas::vector<double, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > > >, Kratos::UblasSpace<double, boost::numeric::ublas::matrix<double, boost::numeric::ublas::basic_row_major<unsigned long, long>, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > >, boost::numeric::ublas::vector<double, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > > >, Kratos::Reorderer<Kratos::UblasSpace<double, boost::numeric::ublas::compressed_matrix<double, boost::numeric::ublas::basic_row_major<unsigned long, long>, 0ul, boost::numeric::ublas::unbounded_array<unsigned long, std::allocator<unsigned long> >, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > >, boost::numeric::ublas::vector<double, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > > >, Kratos::UblasSpace<double, boost::numeric::ublas::matrix<double, boost::numeric::ublas::basic_row_major<unsigned long, long>, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > >, boost::numeric::ublas::vector<double, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > > > > > >::Build(std::shared_ptr<Kratos::Scheme<Kratos::UblasSpace<double, boost::numeric::ublas::compressed_matrix<double, boost::numeric::ublas::basic_row_major<unsigned long, long>, 0ul, boost::numeric::ublas::unbounded_array<unsigned long, std::allocator<unsigned long> >, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > >, boost::numeric::ublas::vector<double, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > > >, Kratos::UblasSpace<double, boost::numeric::ublas::matrix<double, boost::numeric::ublas::basic_row_major<unsigned long, long>, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > >, boost::numeric::ublas::vector<double, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > > > > >, Kratos::ModelPart&, boost::numeric::ublas::compressed_matrix<double, boost::numeric::ublas::basic_row_major<unsigned long, long>, 0ul, boost::numeric::ublas::unbounded_array<unsigned long, std::allocator<unsigned long> >, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > >&, boost::numeric::ublas::vector<double, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > >&) [clone ._omp_fn.0] (residualbased_block_builder_and_solver.h:251)
==28838==    by 0x1791993D: ??? (in /usr/lib64/libgomp.so.1.0.0)
==28838==    by 0x4D7A4BF: start_thread (in /usr/lib64/libpthread-2.29.so)
==28838==    by 0x495E552: clone (in /usr/lib64/libc-2.29.so)
==28838== 
~~~

### PR DESCRIPTION
**Pull request by loumalouomega**
Fixes #6773 ?

The error of #6773 is because the RHS is not initialized, this tries to fix that

### CODE REVIEW

**Comment by pablobecker** [comment]
how was this working?

**Comment by adityaghantasala** [comment]
The point is they are set to zero from the strategy ... 
https://github.com/KratosMultiphysics/Kratos/blob/5aac6c75ba18849a338bf5b36d0ba705c19cffb3/kratos/solving_strategies/strategies/adaptive_residualbased_newton_raphson_strategy.h#L434

**Comment by philbucher** [comment]
are all strategies doing this?
I am not sure if the one you are refereing to is the reference :D

**Comment by pablobecker** [comment]
mm, what is the norm? where should this be done?

**Comment by adityaghantasala** [comment]
The newton raphson one is ... always before calling BuildAndSolve.

**Comment by pablobecker** [comment]
how does this solve the issue? the vectors already had the right size, so memory was allocated. having crap in that vectors should not make it crash that way. or am i mssing something?

**Comment by loumalouomega** [comment]
Resize does not mean to be zero, only means that is allocated.

**Comment by pablobecker** [comment]
Yes, that's why i don't understand why this should fix this. the error is "Conditional jump or move depends on uninitialised value(s)". The rhs and x vectors only contain values, so if they start with crap, you should get a crappy result /nan, but never a segfault

**Comment by loumalouomega** [comment]
> Yes, that's why i don't understand why this should fix this. the error is "Conditional jump or move depends on uninitialised value(s)". The rhs and x vectors only contain values, so if they start with crap, you should get a crappy result /nan, but never a segfault

but apparently it works (and it is a very minor change, not harmful at all)

**Comment by GuillermoCasas** [comment]
> Yes, that's why i don't understand why this should fix this. the error is "Conditional jump or move depends on uninitialised value(s)". The rhs and x vectors only contain values, so if they start with crap, you should get a crappy result /nan, but never a segfault

That error is only saying that the values have not been initialized. Which is True. I think the change is reasonable: It should not depend on external objects to initialize the value.

File: kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver.h [hunk 1]
```diff
@@ -766,8 +766,11 @@ class ResidualBasedBlockBuilderAndSolver
         }
         if (Dx.size() != BaseType::mEquationSystemSize)
             Dx.resize(BaseType::mEquationSystemSize, false);
-        if (b.size() != BaseType::mEquationSystemSize)
+        TSparseSpace::SetToZero(Dx);
```
Comment (RiccardoRossi) [inline kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver.h:857]: this should be 

if(...){
   resize
   SetToZero
}

other than that i agree (same for the b)

Comment (loumalouomega) [reply kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver.h:857]: IMO may be initialized but filled of values different of zero, therefore may be set to zero always

Comment (RiccardoRossi) [reply kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver.h:857]: ok

Comment (pablobecker) [reply kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver.h:857]: I agree with Vicente, even if it has the right size, it might still be uninit

**Comment by AlejandroCornejo** [comment]
On  behalf of @KratosMultiphysics/implementation-committee. We agree that this is correct. But we also think that this initialization should be done in the rest of the similar objects, for consistency.

**Comment by loumalouomega** [comment]
> 
> 
> On behalf of @KratosMultiphysics/implementation-committee. We agree that this is correct. But we also think that this initialization should be done in the rest of the similar objects, for consistency.

I think it is already consistent, what does it lack?

**Comment by GuillermoCasas** [comment]
> > On behalf of @KratosMultiphysics/implementation-committee. We agree that this is correct. But we also think that this initialization should be done in the rest of the similar objects, for consistency.
> 
> I think it is already consistent, what does it lack?

Other builder and solvers do not initialize the vector like that. Either all do or none does.

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee delegates the followup and approval of this PR to @KratosMultiphysics/implementation-committee

**Comment by loumalouomega** [comment]
@KratosMultiphysics/implementation-committee ?

**Comment by AlejandroCornejo** [comment]
On behalf of @KratosMultiphysics/implementation-committee Thank you for your implementation and taking into account our comments @loumalouomega. We agree to merge

**Review by AlejandroCornejo — APPROVED** [review]
