### PR TITLE
[ShapeOpt] Introducing omp parallelize to speedup matrix free vertex morphing mapper

### LINKED ISSUE #4308: [ShapeOpt] Many tests fail if StructuralMechanics is not compiled
Seems like you are missing some skiptests

### PR DESCRIPTION
**Pull request by dbaumgaertner**
Adjusted test towards cleaner imports and also addressed #4308

closes #4308

### CODE REVIEW

File: applications/ShapeOptimizationApplication/custom_utilities/mapping/mapper_vertex_morphing_matrix_free.h [hunk 1]
```diff
@@ -142,42 +142,53 @@ class MapperVertexMorphingMatrixFree : public Mapper
         mValuesDestination[2].clear();
 
         // Perform mapping
-        for(auto& node_i : mrDestinationModelPart.Nodes())
+        const auto destination_nodes_begin = mrDestinationModelPart.NodesBegin();
+
+        #pragma omp parallel for firstprivate(destination_nodes_begin)
+        for(IndexType node_itr=0; node_itr<mrDestinationModelPart.NumberOfNodes(); node_itr++)
```
Comment (philbucher) [inline applications/ShapeOptimizationApplication/custom_utilities/mapping/mapper_vertex_morphing_matrix_free.h]: without looking into it, this won't compile in Win => omp-loops only work with integers
I will review after this is changed

Comment (armingeiser) [reply applications/ShapeOptimizationApplication/custom_utilities/mapping/mapper_vertex_morphing_matrix_free.h]: :+1:

File: applications/ShapeOptimizationApplication/custom_utilities/mapping/mapper_vertex_morphing_matrix_free.h [hunk 2]
```diff
@@ -142,42 +142,53 @@ class MapperVertexMorphingMatrixFree : public Mapper
         mValuesDestination[2].clear();
 
         // Perform mapping
-        for(auto& node_i : mrDestinationModelPart.Nodes())
+        const auto destination_nodes_begin = mrDestinationModelPart.NodesBegin();
+
+        #pragma omp parallel for firstprivate(destination_nodes_begin)
```
Comment (armingeiser) [inline applications/ShapeOptimizationApplication/custom_utilities/mapping/mapper_vertex_morphing_matrix_free.h]: I am not sure about the `firstprivate(destination_nodes_begin)`. As far as i understand the definition of it, it is not necessary here.

File: applications/ShapeOptimizationApplication/custom_utilities/mapping/mapper_vertex_morphing_matrix_free.h [hunk 3]
```diff
@@ -142,42 +142,53 @@ class MapperVertexMorphingMatrixFree : public Mapper
...
+        for(IndexType node_itr=0; node_itr<mrDestinationModelPart.NumberOfNodes(); node_itr++)
         {
+            auto node_i = destination_nodes_begin + node_itr;
```
Comment (armingeiser) [inline applications/ShapeOptimizationApplication/custom_utilities/mapping/mapper_vertex_morphing_matrix_free.h]: if you try to obtain a reference here, you don't need to change the rest of the code

File: applications/ShapeOptimizationApplication/tests/test_ShapeOptimizationApplication.py [hunk 4]
```diff
@@ -67,20 +70,27 @@ def AssembleTestSuites():
 
     # Adding small tests (tests that take < 1s)
     smallSuite = suites['small']
+    smallSuite.addTest(mapper_test('test_execution'))
     smallSuite.addTest(opt_process_vertex_morphing_test('test_execution'))
-    smallSuite.addTest(opt_process_shell_test('test_execution'))
+    if not is_csm_app_missing:
```
Comment (armingeiser) [inline applications/ShapeOptimizationApplication/tests/test_ShapeOptimizationApplication.py]: it would be even nicer to use a 
```python
@KratosUnittest.skipUnless(has_eigensolvers_application,"Missing required application: MeshMovingApplication")
class XYTest():
```
in every individual test. Like this we can see how many tests are skipped, when the tests run.

**Review by armingeiser — CHANGES_REQUESTED** [review]
Some minor comments.

**Comment by dbaumgaertner** [comment]
@philbucher @armingeiser I addressed your comments. Thanks that hints!

File: applications/ShapeOptimizationApplication/custom_utilities/mapping/mapper_vertex_morphing_matrix_free.h [hunk 5]
```diff
@@ -142,42 +142,51 @@ class MapperVertexMorphingMatrixFree : public Mapper
         mValuesDestination[2].clear();
 
         // Perform mapping
-        for(auto& node_i : mrDestinationModelPart.Nodes())
+        #pragma omp parallel for
+        for(int node_itr=0; node_itr < static_cast<int>(mrDestinationModelPart.NumberOfNodes()); node_itr++)
         {
+            auto node_i = mrDestinationModelPart.NodesBegin() + node_itr;
```
Comment (armingeiser) [inline applications/ShapeOptimizationApplication/custom_utilities/mapping/mapper_vertex_morphing_matrix_free.h]: Doesn't it work to get `node_i` as a reference?

**Review by armingeiser — CHANGES_REQUESTED** [review]

File: applications/ShapeOptimizationApplication/tests/shape_optimization_test_factory.py [hunk 6]
```diff
@@ -7,6 +7,12 @@
 # Other imports
 import os
 
+# Check if external Apps are available
+has_eigen_app =  kratos_utilities.CheckIfApplicationsAvailable("EigenSolversApplication")
+has_csm_app = kratos_utilities.CheckIfApplicationsAvailable("StructuralMechanicsApplication")
+has_mesh_moving_app = kratos_utilities.CheckIfApplicationsAvailable("MeshMovingApplication")
+
+# Define controlled execution scope
 class controlledExecutionScope:
```
Comment (philbucher) [inline applications/ShapeOptimizationApplication/tests/shape_optimization_test_factory.py]: can you please use the class from KratosUnittest here?

File: applications/ShapeOptimizationApplication/tests/test_ShapeOptimizationApplication.py [hunk 7]
```diff
@@ -5,26 +5,10 @@
...
-else:
-    print("WARNING: EigenSolversApplication is not available, skipping related tests!")
-    is_eigen_app_missing = True
-
-if CheckIfApplicationsAvailable("MeshMovingApplication"):
-    is_mesh_moving_app_missing = False
-else:
-    print("WARNING: MeshMovingApplication is not available, skipping related tests!")
-    is_mesh_moving_app_missing = True
+import KratosMultiphysics.kratos_utilities as kratos_utilities
```
Comment (philbucher) [inline applications/ShapeOptimizationApplication/tests/test_ShapeOptimizationApplication.py]: is this still needed here?

File: applications/ShapeOptimizationApplication/tests/mapper_test/run_test.py [hunk 8]
```diff
@@ -1,8 +1,9 @@
 # Import Kratos core and apps
-from KratosMultiphysics import *
-from KratosMultiphysics.ShapeOptimizationApplication import *
+import KratosMultiphysics as KM
+import KratosMultiphysics.ShapeOptimizationApplication as KS
```
Comment (philbucher) [inline applications/ShapeOptimizationApplication/tests/mapper_test/run_test.py]: SUGGESTION:
```suggestion
import KratosMultiphysics.ShapeOptimizationApplication as KSO
```

File: applications/ShapeOptimizationApplication/custom_utilities/mapping/mapper_vertex_morphing_matrix_free.h (hunk 5 above)
Comment (philbucher) [inline applications/ShapeOptimizationApplication/custom_utilities/mapping/mapper_vertex_morphing_matrix_free.h]:
```suggestion
            auto node_i = *(mrDestinationModelPart.NodesBegin() + node_itr);
```

Comment (philbucher) [reply applications/ShapeOptimizationApplication/custom_utilities/mapping/mapper_vertex_morphing_matrix_free.h]: Btw I would do the following:
~~~c++
const auto nodes_begin = mrDestinationModelPart.NodesBegin();

for ...
~~~

File: applications/ShapeOptimizationApplication/custom_utilities/mapping/mapper_vertex_morphing_matrix_free.h [hunk 9]
```diff
@@ -142,42 +142,51 @@ class MapperVertexMorphingMatrixFree : public Mapper
...
 
                 ModelPart::NodeType& node_j = *neighbor_nodes[neighbor_itr];
                 array_3d& nodal_variable = node_j.FastGetSolutionStepValue(rOriginVariable);
 
+                #pragma omp atomic
                 mValuesDestination[0][node_i_mapping_id] += weight*nodal_variable[0];
+                #pragma omp atomic
                 mValuesDestination[1][node_i_mapping_id] += weight*nodal_variable[1];
+                #pragma omp atomic
                 mValuesDestination[2][node_i_mapping_id] += weight*nodal_variable[2];
```
Comment (philbucher) [inline applications/ShapeOptimizationApplication/custom_utilities/mapping/mapper_vertex_morphing_matrix_free.h:179]: can you reformulate those statements to only have one atomic?

File: applications/ShapeOptimizationApplication/tests/mapper_test/run_test.py (hunk 8 above)
Comment (armingeiser) [reply applications/ShapeOptimizationApplication/tests/mapper_test/run_test.py]: :+1: makes it more precise

File: applications/ShapeOptimizationApplication/custom_utilities/mapping/mapper_vertex_morphing_matrix_free.h (hunk 5 above)
Comment (dbaumgaertner) [reply applications/ShapeOptimizationApplication/custom_utilities/mapping/mapper_vertex_morphing_matrix_free.h]: node_i here is an iterator. So there is no overhead and you simply use its pointer. Why would you go for a reference here?

Comment (armingeiser) [reply applications/ShapeOptimizationApplication/custom_utilities/mapping/mapper_vertex_morphing_matrix_free.h]: Three functions that are using it below need a reference. Also the existing code was using references and it just reduces the changes in this PR.

File: applications/ShapeOptimizationApplication/custom_utilities/mapping/mapper_vertex_morphing_matrix_free.h [hunk 10]
```diff
@@ -142,42 +142,51 @@ class MapperVertexMorphingMatrixFree : public Mapper
...
-        for(auto& node_i : mrDestinationModelPart.Nodes())
+        #pragma omp parallel for
+        for(int node_itr=0; node_itr < static_cast<int>(mrDestinationModelPart.NumberOfNodes()); node_itr++)
         {
+            auto node_i = mrDestinationModelPart.NodesBegin() + node_itr;
+
             NodeVector neighbor_nodes(mMaxNumberOfNeighbors);
             std::vector<double> resulting_squared_distances(mMaxNumberOfNeighbors);
-            unsigned int number_of_neighbors = mpSearchTree->SearchInRadius( node_i,
+            unsigned int number_of_neighbors = mpSearchTree->SearchInRadius( *node_i,
```
Comment (armingeiser) [inline applications/ShapeOptimizationApplication/custom_utilities/mapping/mapper_vertex_morphing_matrix_free.h]: here

File: applications/ShapeOptimizationApplication/custom_utilities/mapping/mapper_vertex_morphing_matrix_free.h [hunk 11]
```diff
@@ -142,42 +142,51 @@ class MapperVertexMorphingMatrixFree : public Mapper
...
                                                                              mFilterRadius,
                                                                              neighbor_nodes.begin(),
                                                                              resulting_squared_distances.begin(),
                                                                              mMaxNumberOfNeighbors );
 
-            ThrowWarningIfNumberOfNeighborsExceedsLimit(node_i, number_of_neighbors);
+            ThrowWarningIfNumberOfNeighborsExceedsLimit(*node_i, number_of_neighbors);
```
Comment (armingeiser) [inline applications/ShapeOptimizationApplication/custom_utilities/mapping/mapper_vertex_morphing_matrix_free.h]: here

File: applications/ShapeOptimizationApplication/custom_utilities/mapping/mapper_vertex_morphing_matrix_free.h [hunk 12]
```diff
@@ -142,42 +142,51 @@ class MapperVertexMorphingMatrixFree : public Mapper
...
 
             std::vector<double> list_of_weights( number_of_neighbors, 0.0 );
             double sum_of_weights = 0.0;
-            ComputeWeightForAllNeighbors( node_i, neighbor_nodes, number_of_neighbors, list_of_weights, sum_of_weights );
+            ComputeWeightForAllNeighbors( *node_i, neighbor_nodes, number_of_neighbors, list_of_weights, sum_of_weights );
```
Comment (armingeiser) [inline applications/ShapeOptimizationApplication/custom_utilities/mapping/mapper_vertex_morphing_matrix_free.h]: here

File: applications/ShapeOptimizationApplication/tests/shape_optimization_test_factory.py (hunk 6 above)
Comment (dbaumgaertner) [reply applications/ShapeOptimizationApplication/tests/shape_optimization_test_factory.py]: which one?

File: applications/ShapeOptimizationApplication/custom_utilities/mapping/mapper_vertex_morphing_matrix_free.h (hunk 9 above)
Comment (dbaumgaertner) [reply applications/ShapeOptimizationApplication/custom_utilities/mapping/mapper_vertex_morphing_matrix_free.h:179]: Why? The only option I see here is to have a for loop with 3 iterations and the atomic command inside the loop. But I suppose this is not much faster, is it? Or is there a way to apply the atomic keyword to a whole block?

**Comment by dbaumgaertner** [comment]
@philbucher @armingeiser I addressed all your comments. So ready to be reviewed again.

**Comment by dbaumgaertner** [comment]
@armingeiser I removed the firstprivate setting

**Review by armingeiser — DISMISSED** [review]
Fine for me, thanks.

File: applications/ShapeOptimizationApplication/tests/mapper_test/run_test.py [hunk 13]
```diff
@@ -1,8 +1,9 @@
 # Import Kratos core and apps
-from KratosMultiphysics import *
-from KratosMultiphysics.ShapeOptimizationApplication import *
+import KratosMultiphysics as km
```
Comment (philbucher) [inline applications/ShapeOptimizationApplication/tests/mapper_test/run_test.py:2]: usually we use this:

```suggestion
import KratosMultiphysics as KM
```

File: applications/ShapeOptimizationApplication/custom_utilities/mapping/mapper_vertex_morphing_matrix_free.h (hunk 9 above)
Comment (philbucher) [reply applications/ShapeOptimizationApplication/custom_utilities/mapping/mapper_vertex_morphing_matrix_free.h:179]: I think it would be more efficient to have a "vector" version that does it all at once, but I am not sure if it is possible in your case

You can also leave it as is

**Comment by philbucher** [comment]
I have some minor comments, otherwise fine for me

BTW are all the tests running with the latest master? I think there was an error in the nightly build

**Comment by dbaumgaertner** [comment]
@philbucher all tests are running. This error will be fixed with this PR. I left the modules in small letters just for convenience and following standard python imports like you often see it with numpy etc. Other than that it should be fine now.

**Review by armingeiser — APPROVED** [review]

**Comment by philbucher** [comment]
fine for me 👍 

Usually I would vote for consistence in Kratos but its your app
