### PR TITLE
Structural/fix eigenfrequency sensitivities shells

### LINKED ISSUE #2556: Verification of semi-analytic sensitivities in eigenfrequency analysis of shells fails
Performing a verification of the semi-analytic eigenfrequency sensitivities against finite differencing, I noticed, that there is a significant deviation between the two results(several orders). By contrast, the same verification process applied to a solid beam example with a regular hex-mesh and a hook example with unstructured tet-elements shows a good agreement. 

Important to mention is that the optimization of a shell for eigenfrequency works. So it seems the direction of the sensitivities is correct, but some factor is hidden.

@armingeiser, @MFusseder This is supposed to be a reminder to further investigate on this.

### PR DESCRIPTION
**Pull request by armingeiser**
Fixes the eigenfrequency sensitivities for shells: Previously, the DOF ordering was not considered when creating an "eigenvector of elements size" from the nodal value `EIGENVECTOR_MATRIX`. 

A test is added.

closes #2556

### CODE REVIEW

File: applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h [hunk 1]
```diff
@@ -314,33 +315,44 @@ class EigenfrequencyResponseFunctionUtility
...
+        {
+            const ModelPart::NodeType::DofsContainerType& r_node_dofs = r_node_i.GetDofs();
 
-            for (std::size_t dof_index = 0; dof_index < num_node_dofs; dof_index++)
-                rEigenvectorOfElement(dof_index+num_node_dofs*node_index) = rNodeEigenvectors((eigenfrequency_id-1),dof_index);
+            const Matrix& rNodeEigenvectors = r_node_i.GetValue(EIGENVECTOR_MATRIX);
+            for (std::size_t dof_index = 0; dof_index < r_node_dofs.size(); dof_index++)
+            {
+                auto it_dof = std::begin(r_node_dofs) + dof_index;
+                const std::size_t elem_dof_index = std::distance(eq_ids.begin(), std::find(eq_ids.begin(), eq_ids.end(), it_dof->EquationId()));
```
Comment (armingeiser) [inline applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h]: I don't really like this line, but the only alternative i could come up with is to create an intermediate map to do the search, and that seems to be slower.

File: applications/StructuralMechanicsApplication/tests/structural_response_function_test_factory.py [hunk 2]
```diff
@@ -149,6 +155,19 @@ def test_execution(self):
         self.assertAlmostEqual(self.gradient[nodeId][1],  0.0017745756664132117, 9)
         self.assertAlmostEqual(self.gradient[nodeId][2], -1.5466215093998671e-07, 9)
 
+@KratosUnittest.skipUnless(has_eigensolvers_application,"Missing required application: EigenSolversApplication")
+class TestAdjointEigenfrequencyResponseFunction(StructuralResponseFunctionTestFactory):
+    file_name = "eigenfrequency_response"
```
Comment (MFusseder) [inline applications/StructuralMechanicsApplication/tests/structural_response_function_test_factory.py]: I am not happy with the name of the class, since eigenfrequency sensitivity analysis includes no adjoint problem.

Comment (MFusseder) [reply applications/StructuralMechanicsApplication/tests/structural_response_function_test_factory.py]: the class name also don't fit to the import in ```test_StructuralMechanicsApplication.py```.

File: applications/StructuralMechanicsApplication/tests/test_StructuralMechanicsApplication.py [hunk 3]
```diff
@@ -183,6 +183,7 @@
 from structural_response_function_test_factory import TestAdjointStressResponseFunction as TTestAdjointStressResponseFunction
 from structural_response_function_test_factory import TestMassResponseFunction as TTestMassResponseFunction
 from structural_response_function_test_factory import TestStrainEnergyResponseFunction as TTestStrainEnergyResponseFunction
+from structural_response_function_test_factory import TestEigenfrequencyResponseFunction as TTestEigenfrequencyResponseFunction
```
Comment (MFusseder) [inline applications/StructuralMechanicsApplication/tests/test_StructuralMechanicsApplication.py:186]: This will not work. See comment above.

File: applications/StructuralMechanicsApplication/tests/structural_response_function_test_factory.py (hunk 2 above)
Comment (armingeiser) [reply applications/StructuralMechanicsApplication/tests/structural_response_function_test_factory.py]: fixed it

File: applications/StructuralMechanicsApplication/tests/test_StructuralMechanicsApplication.py (hunk 3 above)
Comment (armingeiser) [reply applications/StructuralMechanicsApplication/tests/test_StructuralMechanicsApplication.py:186]: fixed

**Comment by MFusseder** [comment]
I am now satisfied with your implementation. Let's see what the others say.

File: applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h [hunk 4]
```diff
@@ -314,33 +315,42 @@ class EigenfrequencyResponseFunctionUtility
...
+        if (rEigenvectorOfElement.size() != eq_ids.size())
+        {
+            rEigenvectorOfElement.resize(eq_ids.size(), false);
+        }
 
-        for (std::size_t node_index=0; node_index<num_nodes; node_index++)
+        for (auto& r_node_i : rElement.GetGeometry())
         {
-            Matrix& rNodeEigenvectors = traced_element.GetGeometry()[node_index].GetValue(EIGENVECTOR_MATRIX);
+            const ModelPart::NodeType::DofsContainerType& r_node_dofs = r_node_i.GetDofs();
```
Comment (philbucher) [inline applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h]: this would be an optimal place to use `auto`

File: applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h [hunk 5]
```diff
@@ -314,33 +315,42 @@ class EigenfrequencyResponseFunctionUtility
                         gradient_contribution[coord_dir_i] += gradient_prefactors[i] * inner_prod(eigenvectors_of_element[i] , aux_vector) * mWeightingFactors[i];
                     }
 
-                   node_i.GetInitialPosition()[coord_dir_i] -= mDelta;
+                    node_i.GetInitialPosition()[coord_dir_i] -= mDelta;
```
Comment (philbucher) [inline applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h:318]: noalias

File: applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h [hunk 6]
```diff
@@ -314,33 +315,42 @@ class EigenfrequencyResponseFunctionUtility
...
+                    node_i.Coordinates()[coord_dir_i] -= mDelta;
                 }
                 noalias(node_i.FastGetSolutionStepValue(SHAPE_SENSITIVITY)) += gradient_contribution;
             }
         }
     }
 
     // --------------------------------------------------------------------------
-    double GetEigenvalue(int eigenfrequency_id)
+    double GetEigenvalue(const int& eigenfrequency_id)
```
Comment (philbucher) [inline applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h]: why by reference?

File: applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h [hunk 7]
```diff
@@ -314,33 +315,42 @@ class EigenfrequencyResponseFunctionUtility
...
     {
         return (mrModelPart.GetProcessInfo()[EIGENVALUE_VECTOR])[eigenfrequency_id-1];
     }
 
     // --------------------------------------------------------------------------
-    void DetermineEigenvectorOfElement(ModelPart::ElementType& traced_element, int eigenfrequency_id, int size_of_eigenvector, Vector& rEigenvectorOfElement)
+    void DetermineEigenvectorOfElement(ModelPart::ElementType& rElement, const int& eigenfrequency_id, Vector& rEigenvectorOfElement, ProcessInfo& CurrentProcessInfo)
```
Comment (philbucher) [inline applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h]: idem

File: applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h (hunk 1 above)
Comment (philbucher) [reply applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h]: I don't fully understand what you are doing here, can you explain a bit pls?

File: applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h [hunk 8]
```diff
@@ -314,33 +315,42 @@ class EigenfrequencyResponseFunctionUtility
...
 
-        const std::size_t num_nodes = traced_element.GetGeometry().size();
-        const std::size_t num_node_dofs = size_of_eigenvector/num_nodes;
+        if (rEigenvectorOfElement.size() != eq_ids.size())
+        {
+            rEigenvectorOfElement.resize(eq_ids.size(), false);
+        }
 
-        for (std::size_t node_index=0; node_index<num_nodes; node_index++)
+        for (auto& r_node_i : rElement.GetGeometry())
```
Comment (philbucher) [inline applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h]: const?

File: applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h [hunk 9]
```diff
@@ -314,33 +315,42 @@ class EigenfrequencyResponseFunctionUtility
...
         {
-            Matrix& rNodeEigenvectors = traced_element.GetGeometry()[node_index].GetValue(EIGENVECTOR_MATRIX);
+            const ModelPart::NodeType::DofsContainerType& r_node_dofs = r_node_i.GetDofs();
 
-            for (std::size_t dof_index = 0; dof_index < num_node_dofs; dof_index++)
-                rEigenvectorOfElement(dof_index+num_node_dofs*node_index) = rNodeEigenvectors((eigenfrequency_id-1),dof_index);
+            const Matrix& rNodeEigenvectors = r_node_i.GetValue(EIGENVECTOR_MATRIX);
+            for (std::size_t dof_index = 0; dof_index < r_node_dofs.size(); dof_index++)
+            {
+                auto it_dof = std::begin(r_node_dofs) + dof_index;
```
Comment (philbucher) [inline applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h]: const?

File: applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h (hunk 6 above)
Comment (armingeiser) [reply applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h]: Thought it makes sense to pass by reference if possible to avoid the copy. No other reason

File: applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h (hunk 1 above)
Comment (armingeiser) [reply applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h]: The eigenvectors are stored at the nodes in the `EIGENVECTOR_MATRIX`.
I need the part of the full eigenvector, that belongs to a specific element, in the order of the element dofs (because i multiply with the elemental stiffness matrix...)

The components of the `EIGENVECTOR_MATRIX` are ordered according to the Dof list of the node. The ordering of the dofs at the element and may not be the same. This is why i need to compare the equation ids of the dof lists coming from the node and the element.

e.g. for shells:

* dofs at node: [Rotation, Displacement]
* dofs at element (for each node): [Displacement, Rotation]

File: applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h (hunk 5 above)
Comment (armingeiser) [reply applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h:318]: Why do i need the noalias if i assign a value inside the vector?
I thought its only necessary for matrix/vector operations..

Comment (armingeiser) [reply applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h]: Ok found it on google: Apparently passing by reference does not give a benefit for types like int (maybe even produces overhead).

File: applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h (hunk 6 above)
Comment (armingeiser) [reply applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h]: Ok found it on google: Apparently passing by reference does not give a benefit for types like int (maybe even produces overhead).

File: applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h (hunk 8 above)
Comment (armingeiser) [reply applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h]: No, the `GetDofs()` function does not have the const version.

File: applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h (hunk 5 above)
Comment (philbucher) [reply applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h:318]: the InitialCoordinates are an array3, there you could/should also use it

File: applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h (hunk 6 above)
Comment (philbucher) [reply applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h]: Yep
We usually use it only when it is actually needed
I.e. if you pas an int by reference, then others will assume that sth happens to this int

Other types you should in most cases pass by (const) reference

File: applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h (hunk 1 above)
Comment (philbucher) [reply applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/eigenfrequency_response_function_utility.h]: hm ok, this i a bit over my head, maybe @msandre knows a better solution...?

**Comment by philbucher** [comment]
no more comments from my side :+1:

**Review by dbaumgaertner — APPROVED** [review]
Tests are running on my machine (also Windows). Since the others are also fine with the changes, I am approving the PR.
