### PR TITLE
[Core][Geometry] ShapeFunctionsIntegrationPointsGradients improvements

### LINKED ISSUE #9144: Line2D2 Check failed in Fulldebug
**Description**
The method ShapeFunctionsIntegrationPointsGradients for Line2D2 in FullDebug raises an error. See #9143 . Here is my console output:

```
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import KratosMultiphysics as KM
 |  /           |
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 9.0."Dev"-af095d68cb-FullDebug
Compiled with threading support.
Maximum number of threads: 4.
Process Id: 28352 
>>> KM.Tester.RunTestSuite("KratosCoreGeometriesFastSuite")
Check failed in file /usr/include/boost/numeric/ublas/detail/matrix_assign.hpp at line 585:
size1 == size2
Ran 286 of 988 test cases in 0.0406257s. 1 failed:
    TestLine2D2ShapeFunctionsGradients Failed with message: 
        Error: bad argument
in kratos/tests/cpp_tests/sources/test_shape_function_derivatives.cpp:103:void Testing::TestShapeFunctionsGradients(const Geometry<Node<3> >&)

1
```

**Scope**
- KratosCore
- Testing

**To Reproduce**
See #9143

### PR DESCRIPTION
**Pull request by rubenzorrilla**
**📝 Description**
This aims to completely fix the issue raised in #9144 according to the @KratosMultiphysics/technical-committee conclusions reported in #9242.

**Done**
- [x] Error thrown in base `Geometry` class.
- [x] Line geometries error thrown
- [x] 3D triangles error thrown
- [x] 3D quads error thrown

**To discuss**

- I think we should remove the next `ShapeFunctionsIntegrationPointsGradients` signature
```c++
    virtual ShapeFunctionsGradientsType& ShapeFunctionsIntegrationPointsGradients(
        ShapeFunctionsGradientsType& rResult,
        Vector& rDeterminantsOfJacobian,
        IntegrationMethod ThisMethod,
        Matrix& ShapeFunctionsIntegrationPointsValues) const
```
- I think we should remove the return the legacy `ShapeFunctionsGradientsType&` return type from the signature. I don't think it would be hard to do it at once as we will incur in a compilation error.

closes #9144

### CODE REVIEW

File: kratos/geometries/line_gauss_lobatto_3d_2.h [hunk 1]
```diff
@@ -645,13 +645,32 @@ class LineGaussLobatto3D2 : public Geometry<TPointType>
         return( rResult );
```
Comment (loumalouomega) [inline kratos/geometries/line_gauss_lobatto_3d_2.h:645]: Just mention I think we should remove this geometry if it is a copy-paste of the other lines with just different GP

Comment (rubenzorrilla) [reply kratos/geometries/line_gauss_lobatto_3d_2.h:645]: OK. Maybe we should have a look to it. Thanks for pointing it out!

**Review by roigcarlo — APPROVED** [review]
